묵찌빠 [STEP 1] Roks, Rarla
tasty-code/ios-rock-scissor-paper pull request #13
Opened 2023-09-06 07:39 UTC by rarlala

## 코드를 적성 시 고민되었던 점
1. readline()으로 받아오는 userSelect 값이 String? 타입이라 이를 Int로 변환해 computerSelect 비교할지, 1부터 3까지 랜덤하게 생성되어 Int 타입의 값인 computerSelect를 String으로 비교할지

2

## 해결이 되지 않은점
- 

## 조언을 얻고 싶은 부분
@rarla
- readline()으로 사용자 값을 얻고 이를 Int로 변환하고자 하는 경우 실무에서 가장 많이 사용되는 방식이 궁금합니다!

2023-09-06 14:52 UTC, zdodev requested changes
안녕하세요. @KimRoks , @rarlala !
 
 첫 프로젝트 첫 PR 축하합니다!🎉
 Step 1 요구사항에 맞게 잘 구현해보셨네요.👍
 
 먼저 질문에 대한 제 생각을 적어보았습니다.
 1. 현재 요구사항에서는 지금과 같은 방법도 좋은 방법이라고 생각합니다. 이후 여기에서 더 개선한다면 가위, 바위, 보를 단순히 1, 2, 3 과 같은 정수형으로 표현하기 보다는 보다 명확한 값(타입)으로 표현하면 가독성이 더 좋아질 것 같습니다!
 2. 순서도에 코드(Swift 문법)를 그대로 작성하기 보다는 행위와 조건으로 단순화해서 표현하는 것도 좋은 방법일 것 같습니다!
 
 그리고 몇 가지 궁금증을 남겨보았습니다!
 궁금증에 대해 코멘트를 남겨주셔도 좋습니다!

2023-09-06 14:52 UTC, zdodev commented on RockPaperScissors/RockPaperScissors/main.swift
> +while isRunning {
모든 로직이 `while` 문 안에 작성되어 있습니다. 간단한 프로그램이라 이렇게 작성할 수 있지만, 역할을 나눌 수 있는 부분은 메서드로 구현하여 호출하는 방식으로 개선해 보는 것은 어떨까요? 
어떤 부분을 메서드로 만들어보면 좋을까요? 간단한 역할(기능) 한, 두 가지라도 좋습니다!

2023-09-06 14:52 UTC, zdodev commented on RockPaperScissors/RockPaperScissors/main.swift
> +    guard let select = readLine() else { break }
`guard let` 을 사용하여 안전하게 언래핑 해보셨네요.👍
`select` 는 어떤 select 인지 의미가 좀 불분명해보입니다. 조금 더 구체적인 이름을 지어볼 수 있을까요?

2023-09-06 14:52 UTC, zdodev commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let computerSelect = String(Int.random(in: 1...3))
`Int.random` 메서드를 사용해서 컴퓨터의 패를 생성해보셨네요.👍

2023-09-06 14:52 UTC, zdodev commented on RockPaperScissors/RockPaperScissors/main.swift
> +            break
`break` 키워드는 어떤 의미로 사용했는지 궁금합니다!

2023-09-06 14:52 UTC, zdodev commented on RockPaperScissors/RockPaperScissors/main.swift
> +        break
`break` 키워드는 어떤 의미로 사용했는지 궁금합니다!

2023-09-07 00:50 UTC, rarlala commented on RockPaperScissors/RockPaperScissors/main.swift
> +            break
[d187dab](https://github.com/tasty-code/ios-rock-scissor-paper/pull/13/commits/d187dabc81b87118e897ad02e00055ce1064b53f) 불필요한 입력이었네요! 말씀해주셔서 인지 후 삭제했습니다 :)

2023-09-07 00:50 UTC, rarlala commented on RockPaperScissors/RockPaperScissors/main.swift
> +        break
[d187dab](https://github.com/tasty-code/ios-rock-scissor-paper/pull/13/commits/d187dabc81b87118e897ad02e00055ce1064b53f) 불필요한 입력이었네요! 말씀해주셔서 인지 후 삭제했습니다 :)

2023-09-07 00:51 UTC, rarlala commented on RockPaperScissors/RockPaperScissors/main.swift
> +    guard let select = readLine() else { break }
[d187dab](https://github.com/tasty-code/ios-rock-scissor-paper/pull/13/commits/d187dabc81b87118e897ad02e00055ce1064b53f) 전역 변수로 선언했을때는 조금 더 명확한 userSelect라는 변수명을 사용했었는데, 저희가 리팩토링하는 과정에서 select로 바뀐 부분을 인지하지 못했었네요! 다시 userSelect로 변경하였습니다!

2023-09-07 01:24 UTC, rarlala commented on RockPaperScissors/RockPaperScissors/main.swift
> +while isRunning {
조언 감사합니다!
[62aec61](https://github.com/tasty-code/ios-rock-scissor-paper/pull/13/commits/62aec619714bebe364a58ff76432e8e82ed5549c) 에서 수정해보았습니다!

아래 두가지 부분을 모듈화하여 가독성과 재사용성을 높이고자 했습니다.
1. 랜덤 넘버 생성 로직 분리
2. 가위, 바위, 보 결과 로직 분리

해당 작업 중 궁금한 점이 있어 문의드립니다.
어느 단위까지 함수를 쪼개는 것이 적절한지에 대한 의문이 생겼습니다.
1. switch 문 전체를 분리하는 것
2. switch 문 내 가위바위보 결과 로직만을 분리하는 것
3. 1, 2 둘 다 수행하는 것
이 중 어떤 것이 가독성을 높이는데 더 좋을지 고민하게 되었습니다.

저희의 생각으로는 switch 문 전체를 모듈화 하는 것 보다 2번만 수행하는 것이 while 문 내 진행 흐름을 더 잘 파악할 수 있을 것이라고 판단되어 해당과 같이 진행했습니다.

소대의 의견 부탁드립니다~!

2023-09-07 01:28 UTC, KimRoks commented on RockPaperScissors/RockPaperScissors/main.swift
> +            break
모듈화 작업중에 비슷한 고민이 생겼습니다.
swift 에서 상황에 따라 switch문에서의 break 생략 가능한 부분처럼
함수내에 return 키워드의 생략 또한 가능하다고 알고있는데
어떤 상황에 사용하는것이 적절할지 의견을 듣고 싶습니다

2023-09-07 01:58 UTC, rarlala commented
> 

[bdcef23](https://github.com/tasty-code/ios-rock-scissor-paper/pull/13/commits/bdcef23fe8917bc9510a6bfeda9fb9b009480c9c)에 조언해주신대로 가위바위보를 더 명확히 표현하고 가독성과 유지보수성을 높이기 위해 enum으로 옵션을 정의해 사용하도록 수정했습니다.

정의하면서 추가적으로 궁금한 부분이 있어 질문 드립니다.
```RPSOption.rock.rawValue``` 라고 정의하는 것보다는 변수로 해당 값을 ```let rock = RPSOption.rock.rawValue```로 정의 후 사용하는 방식으로 진행했습니다.

2023-09-07 02:09 UTC, KimRoks commented
> 안녕하세요. @KimRoks , @rarlala !
> 
> 첫 프로젝트 첫 PR 축하합니다!🎉 Step 1 요구사항에 맞게 잘 구현해보셨네요.👍
> 
> 먼저 질문에 대한 제 생각을 적어보았습니다.
> 
> 1. 현재 요구사항에서는 지금과 같은 방법도 좋은 방법이라고 생각합니다. 이후 여기에서 더 개선한다면 가위, 바위, 보를 단순히 1, 2, 3 과 같은 정수형으로 표현하기 보다는 보다 명확한 값(타입)으로 표현하면 가독성이 더 좋아질 것 같습니다!
> 2. 순서도에 코드(Swift 문법)를 그대로 작성하기 보다는 행위와 조건으로 단순화해서 표현하는 것도 좋은 방법일 것 같습니다!
> 
> 그리고 몇 가지 궁금증을 남겨보았습니다! 궁금증에 대해 코멘트를 남겨주셔도 좋습니다!




<img width="618" alt="스크린샷 2023-09-07 오전 9 41 51" src="https://github.com/tasty-code/ios-rock-scissor-paper/assets/113083860/d9301634-190d-4ebf-87c6-1c2009fb81b8">

순서도에 관한 언급을 해주셔서 추가 문의드립니다. PR 내 순서도를 작성하기 전 행위와 조건으로 단순화해서 위와 같은 순서도 또한 작성했었습니다. 혹시 위와 같이 작성한 순서도를 말씀하시는게 맞을지 궁금해 순서도를 첨부했습니다.

2023-09-07 13:31 UTC, zdodev commented on RockPaperScissors/RockPaperScissors/main.swift
> +while isRunning {
말씀해주신 3가지 케이스 다 함수를 나눌 수 있는 방법이 될 것 같습니다. 지금처럼 분리하신 것도 잘 작성해주셨습니다.👍
이후에 함수를 나눌 때 자신만의 근거과 기준을 가지고 한 가지의 일만 하도록 연습을 해보면 더욱 좋을 것 같습니다!

2023-09-07 13:33 UTC, zdodev commented on RockPaperScissors/RockPaperScissors/main.swift
> +            break
`return` 키워드를 생략하는 것이 좋다. 작성하는 것이 좋다. 라는 부분은 개인의 성향이나 조직의 코딩 스타일에 따라 달라질 것 같습니다.
개인적으로 생략할 수 있는 키워드는 보통 생략하는 편입니다!

2023-09-07 13:40 UTC, zdodev approved these changes
안녕하세요. @rarlala , @KimRoks !

리뷰에 대한 코멘트(의견이나 생각)을 잘 정리해주셨습니다👍
궁금증에 대해서 좋은 이유와 고민을 가지고 의견을 전달해주신 점도 좋았습니다!👍

Step 1 진행하시느라 고생하셨습니다!
몇 가지 코멘트만 확인해보면 될 것 같습니다.
여기서 마무리하도록 하겠습니다!🎉

2023-09-07 13:40 UTC, zdodev commented on RockPaperScissors/RockPaperScissors/RPS.swift
> +}
가위, 바위, 보를 나타내는 `enum` 타입을 구현해보셨네요.👍

2023-09-07 13:40 UTC, zdodev commented on RockPaperScissors/RockPaperScissors/RPS.swift
> +let paper = RPSOption.paper.rawValue
`rawValue` 를 명시하여 사용하기 보다는 `enum` 타입 그대로 사용하는 것을 (개인적으로)선호합니다. `rawValue` 를 사용하여 더 가독성이 좋아진다면 `rawValue` 를 사용해도 무방합니다!
사용자의 입력 값과 컴퓨터의 값을 `enum` 타입으로 변환하는 것도 생각해볼 수 있을 것 같습니다!

2023-09-07 13:40 UTC, zdodev commented on RockPaperScissors/RockPaperScissors/Utillity.swift
> +}
랜덤한 숫자를 생성하는 함수를 구현해보셨네요.👍

2023-09-07 13:40 UTC, zdodev commented on RockPaperScissors/RockPaperScissors/Utillity.swift
> +}
게임을 진행하는 로직을 함수로 구현해보셨네요.👍

2023-09-07 13:40 UTC, zdodev commented on RockPaperScissors/RockPaperScissors/main.swift
> +    guard let userSelcet = readLine() else { break }
좋습니다.👍

2023-09-07 13:40 UTC, merged