[STEP 1] janine, dora
tasty-code/ios-rock-scissor-paper pull request #15
Opened 2023-09-06 08:45 UTC by janine-kang

> 리뷰어: @corykim0829
버드: @janine-kang @KSK9820

## 구현 기능
- 프로그램 실행 시 사용자 입력값 받기 기능
- 묵찌빠 게임 룰에 따른 로직 구현
- 정해진 값이 아닌 경우 예외 처리 구현

## 상세 설명
- 사용자 입력값을 받는 로직을 함수로 분리하여 판별하였습니다. 해당 함수 내에서 주어진 범위를 벗어난 입력값에 대해 `-1`을 반환합니다.
- `guard let` 을 이용하여 사용자 입력값이 0인 경우부터 빠른 종료를 구현했습니다.
- 사용자의 입력값을 숫자로 변환하여, 난수화된 컴퓨터의 입력값과 대소값을 비교하는 방법으로 묵찌빠 로직을 구현했습니다. 이 경우, 대소관계로 해결되지 않는 경우를 먼저 선별하여 `guard let` 구문으로 처리했습니다.
- `if문` 을 이용해 이긴 경우 또는 진 경우, 결과 출력과 함께 while문 flag값인 `isRunning`을 false로 바꿔 while문을 탈출합니다. 나머지의 경우 while문을 탈출하지 않아야 하기 때문에 결과만 출력합니다.

## 고민되었던 점
- 하나의 기능을 하는 함수로만 만들어야하는 점은 인지하고 있는데, 어느 기능 단위로 나눠야 할지 고민이 되었습니다.

## 해결되지 않은 점
- 예외처리의 방법을 임의 값 `-1` 을 반환하여 처리하는 방법을 택했는데, 이 방법 외에 어떤 방법이 있는지 좀 더 찾아봐야 할 것 같습니다.
- 또한 임의 값 -1을 받을 때 최상단에서 처리하고 싶습니다. 그러기 위해서 guard let을 사용해야하고 또한 종료 명령문(`break` `return` `continue`)을 사용해야 하는데, 종료 명령문을 바로 쓰게 되면 while문 자체가 종료되는 이슈가 있어 부득이하게 최하단에서 처리하게 되었습니다. 이 부분을 아직 처리하지 못했습니다.

## 조언 얻고 싶은 점
- 임의값을 지정하지 않으면서 예외처리 하는 방법을 알고싶습니다.
- 처리하고자 하는 로직을 따로 타입으로 감싸지 않고 main함수에서 곧바로 while문을 돌리는 구조가 best practice인지 아닌지 궁금합니다.

2023-09-06 13:41 UTC, corykim0829 requested changes
수고하셨습니다!

다음에 PR을 올려주실 때에는 결과 화면도 캡쳐해서 올려주시면 좋을 것 같습니다!

고민되었던 점, 해결되지 않은 점, 조언 얻고 싶은 점이 전체적으로 비슷하여 한번에 답해드리려고 합니다.

1. 함수를 조금 더 활용해서 묶으면 좋겠습니다. while문 부분이 함수로 묶이면 좋겠네요!

2. `-1` 반환에 고민하신 부분이나 while 안에서 guard let 처리 부분은 제가 코드에 피드백해드린 부분을 참고해서 바꿔보시면 좋을 것 같습니다!

수고하셨습니다!

4.

2023-09-06 13:41 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +enum  Alert: String {
공백 정리 부탁드립니다! 😀

2023-09-06 13:41 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +func userInput() -> Int {
`임의값을 지정하지 않으면서 예외처리 하는 방법을 알고싶습니다.`

라고 조언을 구하신 부분과 연결지어서 피드백을 드리자면 여기서 반환값을 optional로 바꾸는건 어떨까요?

2023-09-08 01:03 UTC, janine-kang commented on RockPaperScissors/RockPaperScissors/main.swift
> +enum  Alert: String {
해당 부분 확인하여 반영하였습니다!

2023-09-08 01:26 UTC, janine-kang commented on RockPaperScissors/RockPaperScissors/main.swift
> +func userInput() -> Int {
이 리뷰에 관련하여, 논의 끝에 기존 구조에서 Struct 타입을 채택하는 방향으로 변경하게 되었습니다.

## 고려한 점
변경된 구조는 `while문 부분이 함수로 묶이면 좋겠네요`라는 리뷰에 따라 고려하게 되었으며, 
Struct 구조 내 여러 메서드와 프로퍼티를 통해 하나의 묶음으로 처리할 수 있다는 이점을 이용하고자 하였습니다.

## 기능 구현
- 기존 코드에서 발생하였던 여러 함수 간 의존성을 낮추기 위해, 리턴값이 아닌 프로퍼티를 이용한 의사소통 방법을 채택했습니다.
- `userInput()` 함수의 경우, 코리께서 말씀해주신 것 처럼 반환값을 Optional타입으로 변경하였고 이후 함수들을 Struct 타입으로 옮기는 과정에서 `userInput` 옵셔널 타입의 프로퍼티를 선언하여 값을 저장하는 방식을 적용하였습니다.
- 모든 프로퍼티는 은닉을 위해 Private으로 선언되었습니다.

## 궁금한 점
- 이번 프로젝트를 만들면서 하나의 Struct에서 모든 기능을 처리하게 되었는데, **각각의 메서드가 불필요하게 모든 프로퍼티에 접근**할 수 있다는 생각이 듭니다. 이런 경우에 이보다 `더 세분화하여 Struct를 만들어내는게 좋을까요`?
- Struct가 좀 더 가볍게 구동될 수 있다는 이점으로 채택하게 되었는데, 구현을 하다보니 **모든 메서드에 `mutating `키워드를 붙이게** 되었습니다. 만일 Struct의 메모리 효율성이 Class를 사용하는 것 보다 이점이 있는 경우에, 이번 처럼 모든 메서드에 mutating 키워드를 붙이게 된다는 점을 감안하고 사용하나요? 아니면, `이런 경우에는 Class로 선언하는게 더 이득이 되는 걸까요?`

2023-09-08 01:28 UTC, KSK9820 commented on RockPaperScissors/RockPaperScissors/main.swift
> +func userInput() -> Int {
Optional 로 리턴하는 방법은 그날 배운 개념인데 적용까지는 생각을 못 했습니다. 알려주셔서 감사합니다!

2023-09-08 15:14 UTC, corykim0829 approved these changes
> 이번 프로젝트를 만들면서 하나의 Struct에서 모든 기능을 처리하게 되었는데, 각각의 메서드가 불필요하게 모든 프로퍼티에 접근할 수 있다는 생각이 듭니다. 이런 경우에 이보다 더 세분화하여 Struct를 만들어내는게 좋을까요?
Struct가 좀 더 가볍게 구동될 수 있다는 이점으로 채택하게 되었는데, 구현을 하다보니 모든 메서드에 mutating 키워드를 붙이게 되었습니다. 만일 Struct의 메모리 효율성이 Class를 사용하는 것 보다 이점이 있는 경우에, 이번 처럼 모든 메서드에 mutating 키워드를 붙이게 된다는 점을 감안하고 사용하나요? 아니면, 이런 경우에는 Class로 선언하는게 더 이득이 되는 걸까요?

여기서 더 세분화될 필요는 없을 것 같아요. 두번째 질문에 있어서는 struct와 class의 차이점을 공부해보고 두 분이서 이야기해보면 좋을 것 같네요!! ☺️

다시 한번 피드백을 해드리자면, 구현되어있는 매직넘버, 즉 숫자들이 어떤 걸 의미하는지 코드만 봐서는 명확하게 알 수 없기 때문에 좋은 코드라고 보기 어려운 것 같습니다.

해당 부분을 다음 스텝에 같이 수정하셔도 되고, 다시 한번 수정하고 다음 스텝으로 넘어가도 됩니다!

의논해보시고 저에게 DM주세요!

2023-09-08 15:14 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/main.swift
> +game.run()
main 부분이 깔끔해서 가독성이 좋네요 👍

2023-09-08 15:14 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/RspService.swift
> +struct RspService {
RspService 파일 구조체를 구현했으니 이 파일에는 RspService 구조체만 구현하면 좋을 것 같습니다. 다른 요소가 들어가면 유지보수에 불리합니다 참고하세요!

2023-09-08 15:14 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/RspService.swift
> +enum  Progress: String {
아래에서 언급한 대로 하나의 객체가 하나의 파일을 가져가는게 좋습니다. 또한 공백도 정리해주세요!

2023-09-08 15:14 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/RspService.swift
> +    private var userInput: Int? = -1
초기값 -1은 어떤 의미를 가지고 있나요?

2023-09-08 15:14 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/RspService.swift
> +    private var computerValue: Int = 0
여기 코드만 보면 0이 어떤의미를 하는 지 유추하기가 어렵네요.
value라는 프로퍼티명은 추상적이여서 어떤 값이든 될 수가 있기 때문에 Int면 더 값을 유추하기 어려운 것 같아요.
이 부분은 조금 더 고민해보면 좋을 것 같아요!

2023-09-08 15:14 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/RspService.swift
> +    private var step1Result: GameResult = .draw
결과값 초기값이 .draw인 이유가 있나요?

2023-09-11 09:03 UTC, janine-kang commented on RockPaperScissors/RockPaperScissors/RspService.swift
> +    private var step1Result: GameResult = .draw
승패를 결정짓지 않은 초기 상태이기 때문에 서로 비긴 값으로부터 시작하는 것이 유의미하다고 생각했습니다.
이런 경우 옵셔널 값으로 지정하면 초기값을 설정하지 않아도 되는 이점이 있지만, 모든 옵셔널값을 unwrapping해야 하는 번거로움이 생길 수 있다고 생각하여 승패에 영향을 미치지 않으면서도 nil값이 아닌 .draw를 선택하여 초기값에 넣어주게 되었습니다.

혹시 이런 경우, 어떤 점들로 인해 문제가 될 수 있을까요?

2023-09-11 09:19 UTC, janine-kang commented on RockPaperScissors/RockPaperScissors/RspService.swift
> +    private var computerValue: Int = 0
computerValue가 사용되는 시점은 사용자 입력값의 유효성검사가 모두 완료된 후입니다. 따라서, computerValue값은 무조건적으로 1~3 중 하나의 값만을 갖게 되며 그러므로 시작을 하지 않았다는 뜻의 임의값인 0을 할당해주게 되었습니다.

하지만, 이 경우 코리가 말씀해주신 것 처럼 값이 갖는 상징성이 모호해져 유지보수 시 뜻을 유추하기가 어려워질 수 있다고 판단하여 computerValue를 옵셔널 타입으로 변경했습니다.

또한, value라는 네이밍이 너무 추상적이기 때문에 computerChoice로 네이밍을 변경하여 보다 명료하게 표현하고자 했습니다.

2023-09-11 09:19 UTC, janine-kang commented on RockPaperScissors/RockPaperScissors/RspService.swift
> +    private var userInput: Int? = -1
아래 상황들과 같이, 임의값 그 이상 이하의 뜻도 가지지 않습니다 😓 해당 부분 반영하여 수정하였습니다!

2023-09-11 09:21 UTC, janine-kang commented on RockPaperScissors/RockPaperScissors/RspService.swift
> +enum  Progress: String {
넵! 해당 사항 반영했습니다!

2023-09-11 09:22 UTC, janine-kang commented on RockPaperScissors/RockPaperScissors/RspService.swift
> +struct RspService {
해당 사항 반영했습니다!

2023-11-22 01:05 UTC, closed without merging