묵찌빠 프로젝트 [STEP 1] Bamsak, SwainYun
tasty-code/ios-rock-scissor-paper pull request #16
Opened 2023-09-06 09:40 UTC by Remaked-Swain

# 묵찌빠 프로젝트 [STEP 1]
 @jryoun1
Bamsak & SwainYun

안녕하세요, Jake!
묵찌빠 프로젝트 실습하고 PR 요청 드립니다.

----------------------------------------

## 구조 설명
* Class
    * RockPaperScissors: 가위바위보 게임의 주요 메서드를 모아놓은 클래스입니다.
* Models
    * InterfaceScript: 플레이어에게 보여질 상황 별 문장을 열거형으로 모아놓았습니다.
    * Order: 플레이어가 입력할 수 있는 명령들을 열거형으로 모아놓았습니다.

----------------------------------------

## 프로젝트 진행 과정
### 1. 구조 설계
**InterfaceScript라는 모델을 열거형으로 만든 이유**
* '플레이어에게 보여질 메세지'들을 모아놓고 관리하고 싶었습니다.
* 열거형을 사용하면 이런 케이스들을 나열하여 표현하는데 적합하다고 생각되었습니다.
> 그렇다면 클래스나 구조체로는 이런 값들을 묶어놓는데 적합하지 않아서 그런 것인지, 아니라면 어떤 방식으로 접근해야 하는지 궁금합니다.

**Order**
* InterfaceScript와 동일한 이유, 그리고 재사용을 위해 열거형으로 작성하였습니다.
* 사용자 입력이 적절한지 확인하고 어떤 명령인지 식별하기 위해 각 케이스별로 원시값을 가지게 하였습니다.
* CaseIterable 프로토콜은 열거형으로 나열한 가위, 바위, 보 케이스를 재사용해서 배열로 만들고, 컴퓨터가 갖게 될 랜덤한 값을 추출하기 위해 채택했습니다.
> Order의 케이스는 모두 사용자 입력 종류라는 점에서 열거형으로 모아두었는데,
> 컴퓨터가 갖게 될 랜덤 값을 추출하는 부분에서 `exitProgram` 케이스를 제외한 다른 케이스만 사용한다는 점에서
> 새로운 열거형을 만들어서 관리하는게 적절한지 알고 싶습니다.

### 2. 기능 구현
**`calculateResult` method**
* 가위바위보 게임에서 승패 결과를 계산하는 로직을 어떻게 짜야할지 고민했습니다.
* 처음에는 `enum GameResult { ... }` 와 같은 방식으로 승패 조건 등을 표현하려고 했는데,
* 컴퓨터와 사용자가 낸 것을 비교하는 로직에서 switch문을 두 번 겹쳐 쓰게 되는 문제가 있었습니다.
* 이를 최대한 지양하고 싶었고 enum으로 관리하는게 아니라 다른 부분에서 규칙을 찾아 해결하려고 했습니다.
* 가위바위보를 숫자로 입력받는 이유에 대해 생각하게 되었고 규칙성을 발견하여
* 이중 switch문을 사용하지 않고도 승패 결과를 도출해낼 수 있었습니다.

2023-09-07 13:09 UTC, jryoun1 requested changes
두 분 다 고생하셨습니다! 
코드 가독성도 좋고 대부분 잘 작성해주신 것 같네요 💯 
다만 몇가지 개선하면 좋을 부분들이 있을 것 같아서 코멘트 남겨두었습니다!
확인부탁드려요 🙏

2023-09-07 13:09 UTC, jryoun1 commented on RockPaperScissors/RockPaperScissors/Class/RockPaperScissors.swift
> +final class RockPaperScissors {
final 키워드를 사용하셨네요 👏 
어떤 이유로 사용하셨는지 궁금합니다! 

또한 class로 RockPaperScissors를 생성한 이유도 궁금하네요 🙋‍♂️

2023-09-07 13:09 UTC, jryoun1 commented on RockPaperScissors/RockPaperScissors/Models/InterfaceScript.swift
> +enum InterfaceScript {
enum을 사용해서 프로젝트에 필요한 문자열들을 모아두셨군요 👏 
이렇게 관련있는 문자열들을 모아두기 위한 공간을 name space라고 명칭합니다. 

말씀해주신 것처럼 name space의 경우에는 struct, class를 사용해서도 가능할텐데 enum으로 구현하신 이유가 있을까요?

2023-09-07 13:09 UTC, jryoun1 commented on RockPaperScissors/RockPaperScissors/Models/InterfaceScript.swift
> +    enum Menu: CustomStringConvertible {
CustomStringConvertible Protocol도 채택해보셨군요 👏 
해당 프로토콜은 어떤 경우에 사용하게 되는 걸까요?

2023-09-07 13:09 UTC, jryoun1 commented on RockPaperScissors/RockPaperScissors/Models/InterfaceScript.swift
> +    enum Failure: Error, CustomDebugStringConvertible {
에러처리를 위해서 Error 프로토콜 채택해주셨군요. 좋습니다 👍🏻

2023-09-07 13:09 UTC, jryoun1 commented on RockPaperScissors/RockPaperScissors/Models/Order.swift
> +enum Order: Int, CaseIterable {
CaseIterable도 채택하셨군요 👍

2023-09-07 13:09 UTC, jryoun1 commented on RockPaperScissors/RockPaperScissors/Class/RockPaperScissors.swift
> +    }
함수명은 userOrder를 받는 함수인데 내부에서 computerHandSign의 값도 할당해주고 있네요.
즉, 함수가 2가지 일을 하고 있는 것 같습니다! 함수는 한 가지 일만 할 수 있도록 분리해주세요 :)

2023-09-07 13:09 UTC, jryoun1 commented on RockPaperScissors/RockPaperScissors/Class/RockPaperScissors.swift
> +    private var computerHandSign: Order? = nil
computerHandSign은 property로 선언된 이유가 궁금합니다!

2023-09-07 13:09 UTC, jryoun1 commented on RockPaperScissors/RockPaperScissors/Class/RockPaperScissors.swift
> +    private func inputUserOrder() throws -> Order {
throws를 통해 error 처리를 해주셨네요 👏

2023-09-07 13:09 UTC, jryoun1 commented on RockPaperScissors/RockPaperScissors/Class/RockPaperScissors.swift
> +        guard let computer = Order.allCases.filter({ $0 != .exitProgram }).randomElement() else { return nil }
> Order의 케이스는 모두 사용자 입력 종류라는 점에서 열거형으로 모아두었는데,
컴퓨터가 갖게 될 랜덤 값을 추출하는 부분에서 exitProgram 케이스를 제외한 다른 케이스만 사용한다는 점에서
새로운 열거형을 만들어서 관리하는게 적절한지 알고 싶습니다.

고민해주신 것처럼 지금의 경우에는 크게 다른 입력 사항들이 없어서 문제가 되지 않을 것 같아보입니다.
만약 추후에 입력 사항들이 많아지게 되면, 그때 명확한 사용성을 위해서 분리하는 것도 좋을 것 같네요 :)

2023-09-07 13:09 UTC, jryoun1 commented on RockPaperScissors/RockPaperScissors/Class/RockPaperScissors.swift
> +            run()
재귀함수를 사용해서 계속해서 프로그램을 돌리도록 하셨네요. 👍🏻
이때 while과 같은 반복문을 사용할 수도 있었을 것 같은데 재귀함수를 사용하신 이유가 있을까요? 
추가로 반복문을 사용했을 때와 재귀함수를 사용했을 때의 장단점은 무엇일까요? 🙋‍♂️

2023-09-07 13:09 UTC, jryoun1 commented on RockPaperScissors/RockPaperScissors/Class/RockPaperScissors.swift
> +    }
2중 depth를 만들지 않기 위해서 위와 같이 구현해보셨군요 👏 
작성해주신 것처럼 두 enum의 rawValue의 차이를 이용해서도 충분히 문제를 해결할 수도 있지만, 만약 이 코드를 구현하지 않은 다른 팀원이 해당 코드를 보고 수정해야하는 경우가 발생한다면 각각의 distance가 나오는 case를 확인하기 위해서 시간이 소요될 것 같은 생각이 드네요.

물론 지금은 case가 적고 간단하지만 만약 가위바위보에서 낼 수 있는 case가 늘어나게 된다면 
실제로 `case -1, 2, -3:` 이런식으로 늘어나게된다면 저 숫자들이 명확하게 어떤 것을 의미하는지 알기 어려울 것 같습니다.

따라서 해당 부분을 코드를 작성하지 않은 사람이 봐도 직관적이게 알 수 있도록 개선해 볼 수 있을까요?

2023-09-07 14:33 UTC, Remaked-Swain commented on RockPaperScissors/RockPaperScissors/Class/RockPaperScissors.swift
> +final class RockPaperScissors {
팀 메이트 밤삭과 '가위바위보 게임을 어떻게 표현하고 설계 해야할까?' 에 대한 의견을 서로 나눴었습니다.
컴퓨터가 낸 제스처같은 게임 진행을 위해 저장해야 할 상태와 적절한 동작을 만들어주기로 하였습니다.
그래서 프로퍼티와 메서드를 가질 수 있는 타입이 필요했고 이런 이유로 enum으로 구현하는 선택지는 제외했습니다.

struct, class라는 선택지가 남은 상태에서, 게임 진행 중에 컴퓨터가 낸 제스처가 바뀌는 상황, 즉 제스처를 기억하고 있던(저장하고 있던) 프로퍼티 값이 바뀌고 그 값을 이용하여야 했는데 이를 위해서는 struct과 class 중 무엇이 더 적합한가 고민해보았습니다.

mutating 키워드를 사용하지 않는 이상 프로퍼티를 변경시킬 수 없는 struct 타입으로는 이 부분을 만들기 어렵다고 판단했고,
그래서 class로 게임을 구현하기로 결정했습니다.


추가 내용: struct & class의 차이에 대해 비교하는 자료를 찾아보다 보니 ARC라는 것이 자주 언급되고 있었습니다.
ARC가 정확히 무엇인지는 모르겠으나 참조 타입인 class는 ARC의 도움을 받아 그 어디에도 참조 중이지 않을 때 deinit되어 메모리에서 내려가게 된다는 정보를 얻을 수 있었습니다.
관련하여 mutating 키워드를 쓰면서 struct로 구현하는 것이 좋을지, class로 구현하는 것이 좋을지도 궁금합니다.

2023-09-07 14:34 UTC, bamsak commented on RockPaperScissors/RockPaperScissors/Class/RockPaperScissors.swift
> +final class RockPaperScissors {
추가로 final 키워드는 저의 의견이 반영이 되었는데, 저의 생각으로는 현 프로젝트에서 더 이상 상속이 될 class가 아니라고 판단하여 final 키워드를 사용하였고, final 키워드 사용 시에 상속이 불가함 뿐만이 아니라  인스턴스 생성시 heap의 메모리 공간에 따로 메모리 주소를 찾지 않고 스택처럼 차곡차곡 쌓이는 점이 성능적으로 조금은 이 점이 있는 키워드라고 알고 있어서 final 키워드를 사용하게 되었습니다.

2023-09-07 16:05 UTC, Remaked-Swain commented on RockPaperScissors/RockPaperScissors/Models/InterfaceScript.swift
> +enum InterfaceScript {
InterfaceScript라고 이름 붙힌 이유도 말씀드리고 싶은데요!
게임이 사용자에게 메세지를 프린트하면서 진행되는데,
첫번 째로, 하드코딩한 문자열을 일일이 집어넣고 싶지 않았습니다.
예를 들어 출력할 문자열에 오타가 발견되어 정정해야하는 경우엔?? 하드코딩된 곳을 전부 뒤져서 바꿔주어야 하겠구나 싶었어요.
두번 째로, 이 출력물을 어떤 유사한 목적 또는 컨셉을 기준으로 일반화 시킬 수 있었습니다.
상황, 유형 별로 '사용자에게 보여지는 출력물' 을 모아두었다는 의미에서 InterfaceScript라고 명명했습니다.
관련있는 문자열들을 모아두기 위한 공간을 namespace라고 한다는 것을 배워갑니다!

struct, class로도 namespace를 구현할 수 있지만 같은 컨셉을 가지는 것들을 '나열'해서 모아두었다는 점에서
enum으로 구현하는게 적절하다고 봤습니다.

namespace를 구현할 때는 그 이름공간의 특성과 용도를 고려하여 struct, class 또는 enum을 선택하는 것이 좋다고 생각합니다.

2023-09-07 16:28 UTC, Remaked-Swain commented on RockPaperScissors/RockPaperScissors/Models/Order.swift
> +enum Order: Int, CaseIterable {
각 케이스로 이루어진 배열을 만들고 그 중에서 하나를 뽑아내면 되지 않을까? 라는 생각으로 시작해서
밤삭이 .allCases() 라는 것이 있다고 알려주었고 이것을 쓰기 위해 CaseIterable 프로토콜을 채택하게 되었습니다.

2023-09-07 16:31 UTC, Remaked-Swain commented on RockPaperScissors/RockPaperScissors/Class/RockPaperScissors.swift
> +    private func inputUserOrder() throws -> Order {
do, try, catch, throw처럼 에러 핸들링에 자주 보이는 키워드들을 더 알아보겠습니다 :)

2023-09-07 16:40 UTC, bamsak commented on RockPaperScissors/RockPaperScissors/Models/InterfaceScript.swift
> +    enum Menu: CustomStringConvertible {
현 프로젝트에서는 console에 print를 이용하여 각 케이스별로 Custom한 String으로 변환하는 작업을 해주기 위해 해당 프로토콜을 채택했는데,
다른 경우에는 어떠한 이유로 해당 프로토콜을 사용하는 경우가 있는지 고민을 해보았습니다. 
앱을 개발하는 프로젝트에서는 print문 사용을 제가 확인하기 위한 것 이 외에 print문을 사용하지 않는다는 의견이 있었습니다.
그럼 결국 String으로 변환을 하는 방법이 해당 프로토콜을 채택하지 않고 형변환 하는 방법이 여러가지가 있다고 생각하는데, 굳이 강제성이 강한 프로토콜로 채택하여 String으로 변환하는 과정이 왜 필요한지에 대한 의문이 들었습니다.
혹시 이 의문점을 해결할 키워드라도 알려주실수 있으실까요?

2023-09-07 16:57 UTC, bamsak commented on RockPaperScissors/RockPaperScissors/Models/InterfaceScript.swift
> +    enum Failure: Error, CustomDebugStringConvertible {
감사합니다! 현 프로젝트에서 사용자의 입력이 잘못되었을 때, 콘솔 창에 "잘못 입력되었습니다."를 출력하여 보여주는 것이 사용자뿐만이 아니라 개발자에게도 Error가 나타난 상황이라고 판단을 해서 출력을 해야한다고 생각을 했고 이런 이유로 Error 프로토콜을 채택하여 error handling을 하게 되었습니다.

2023-09-07 17:02 UTC, Remaked-Swain commented on RockPaperScissors/RockPaperScissors/Class/RockPaperScissors.swift
> +    }
컴퓨터 의사 결정 함수, 사용자 입력 받는 함수로 나누게 되면 더욱 무슨 일을 하는지 명확할 것 같습니다.
조언 감사합니다!

2023-09-08 01:42 UTC, Remaked-Swain commented on RockPaperScissors/RockPaperScissors/Class/RockPaperScissors.swift
> +        guard let computer = Order.allCases.filter({ $0 != .exitProgram }).randomElement() else { return nil }
사용성을 고려해서 폴더링할지 분리할지 생각해 보아야 겠네요 :)

2023-09-08 09:30 UTC, bamsak commented on RockPaperScissors/RockPaperScissors/Class/RockPaperScissors.swift
> +            run()
팀 메이트인 스웨인과 프로젝트 시작 당시 재귀 함수와 반복문 둘 중 어떤 것으로 관리해야 할 지에 대해 고민이 있었습니다.
사실 저희가 두가지 방법에 대해 서로 어쩐 장단점이 있는지를 파악을 못한 상태에서 프로젝트를 재귀 함수로 진행하기로 했습니다.
이 후 이번 코멘트에 대해 어떻게 작성할 지 고민을 하며 스웨인과 함께 자료를 찾아보았는데,
자료들에서는 재귀함수를 사용하면 함수가 계속 stack 메모리에 할당이 되어 많은 재귀를 할 경우 stack overflow를 일으킬 수 있다는 사실을 알게되었습니다.
하지만 아직 둘 중 어떤 것이 이점이 있는지, 판단이 서지 않습니다.
조금 더 탐구해보는 시간을 가져보도록 하겠습니다.
혹시 괜찮으시다면 이런 부분을 탐구하는데에 있어서 참고할만한 키워드가 있는지 알려주시면 감사드리겠습니다!

2023-09-08 09:30 UTC, Remaked-Swain commented on RockPaperScissors/RockPaperScissors/Class/RockPaperScissors.swift
> +    private var computerHandSign: Order? = nil
설계 단계에서부터 루프를 반복문으로 구현할지 재귀 형태로 구현할지 팀메이트와 서로 많은 대화 나누었고,
저희는 재귀 형태로 구현하기로 선택했습니다.

그런데 저장 프로퍼티를 만든 부분은 지금 보니 루프를 반복문으로 구현한 경우에 더 가까운 것 같다고 생각이 듭니다.
아마도 제가 재귀 형태보다는 반복문을 사용하는데에 더 익숙해서 이것이 무의식 중에 반영 된 것 같습니다.

computerHandSign 프로퍼티는 게임 진행 중에 컴퓨터가 낸 제스처를 보관하기 위한 목적으로 선언했던 부분인데,
이러한 저장 프로퍼티를 만들지 않고 다음 재귀 호출 시 값을 전달하는 개념이 재귀 형태의 루프에 가까운 방식이라고 생각합니다.

반복문, 재귀함수에 대해 더욱 이해할 수 있도록 공부하겠습니다.

2023-09-08 09:41 UTC, Remaked-Swain commented on RockPaperScissors/RockPaperScissors/Class/RockPaperScissors.swift
> +    }
어떻게 해야 각 손 제스처를 비교하고 상하관계를 표현할 수 있을지 찾아보았습니다.
Comparable 프로토콜을 채택하면 각종 비교 연산자를 정의하여 위 문제를 해결할 수 있다고 배우게 되었습니다.

이번 단계에서 Comparable 프로토콜을 사용하지 않은 이유는,
정확하게 모른 채 사용하는 것은 안쓰느니만 못하다는 의견이 팀메이트 밤삭과 일치했기 때문입니다.

이번 PR에서 피드백 주신 모든 부분에 대해 답변을 준비하면서 많은 고민을 하며 알고 있다고 생각했던 것들도 더욱 탐구하는 시간을 가졌습니다.
따라서 이번 리뷰에서 받은 피드백을 토대로 [Step1]을 리팩토링 해볼 계획인데 Comparable 프로토콜도 추가로 공부해서 말씀 주신 부분을 개선시켜보겠습니다.

2023-09-08 10:10 UTC, jryoun1 commented on RockPaperScissors/RockPaperScissors/Class/RockPaperScissors.swift
> +final class RockPaperScissors {
두 분이서 많은 고민을 해보신것이 여기까지 느껴지네요 👏 💯 
우선 두 분이서 코드를 작성하실 때 선택에 이유가 있는지 궁금해서 여쭤봤던 것이고 코드에는 정답은 없다는 것 알아주시면 좋을 것 같네요 ㅎㅎ 지금 말씀해주신 이유때문에 class로 작성하셨다면 괜찮은 것 같습니다. 

다만 이번 프로젝트가 끝난 뒤에도 다음 프로젝트들을 나아가면서 struct와 class에 대해서는 앞으로도 더 자세히 알아보고 둘 중에 뭘 써야할지 선택해야 할 텐데, 앞으로 더 자세히 알아보시면 좋을 것 같네요 :) 
또한 final 키워드에 대해서도 잘 사용해주신 것 같고, 말씀해주신 이점에 대해서는 나중에 [WWDC 영상](https://developer.apple.com/videos/play/wwdc2016/416/) 보시면서 공부해보시면 더 좋을 것 같네요 👍

2023-09-08 10:13 UTC, jryoun1 commented on RockPaperScissors/RockPaperScissors/Models/InterfaceScript.swift
> +enum InterfaceScript {
넵 좋은 이유로 잘 구현해주신 것 같네요 👍 
다만 [이 글](https://sujinnaljin.medium.com/namespace-%EC%A7%80%EC%A0%95%ED%95%98%EA%B8%B0-struct-vs-enum-ce86d5717d95)을 읽어보시고 인스턴스화 측면에서도 셋 중에 어떤 것을 선택할 수 있는지 확인해보시면 도움이 될 것 같네요 🙏

2023-09-08 10:18 UTC, jryoun1 commented on RockPaperScissors/RockPaperScissors/Models/InterfaceScript.swift
> +    enum Menu: CustomStringConvertible {
말씀해주신대로 print 할 때 필요하다면 프로토콜을 준수하는 것도 좋다고 생각되네요!

2023-09-08 10:18 UTC, jryoun1 commented on RockPaperScissors/RockPaperScissors/Models/Order.swift
> +enum Order: Int, CaseIterable {
좋네요! 다만 꼭 모든 comment에 답변을 의무적으로 달지는 않으셔도 됩니다 ㅎㅎ

2023-09-08 10:21 UTC, jryoun1 commented on RockPaperScissors/RockPaperScissors/Class/RockPaperScissors.swift
> +            run()
`Swift 재귀함수와 반복문`이라던지 `Swift 꼬리 재귀` 관련해서 검색해보시면 도움이 되지 않을까 싶네요 🙏

2023-09-08 16:21 UTC, Remaked-Swain commented on RockPaperScissors/RockPaperScissors/Models/InterfaceScript.swift
> +enum InterfaceScript {
알려주신 링크로 들어가서 자료 읽어보았습니다.
글에서 다루는 내용이나 진행이 익숙하게 느껴지는 것이 왠지 몇 번 지나치면서 읽은 적이 있는 것 같은데
그때는 '뭔 말인지 모르겠다' 하면서 넘어갔지만 지금 보니 알 듯 말 듯한 느낌이 들면서도 또 새롭네요!


* 나름 이해한대로의 정리
1. struct나 class의 이니셜라이저를 막은 뒤 타입 프로퍼티를 선언해서 이용하면 인스턴스화 없이 이름공간 목적으로 활용할 수 있다.
2. enum의 경우 원래부터 인스턴스화 작업 없이 타입에 접근해 쓸 수 있는 성질이 있으니 1번보다 상대적으로 이름공간을 구현하기 쉽다.
3. 그런데 enum은 프로토콜 채택하고 어쩌고 할 수 있으니 숙련된 개발자가 아니라면 이름공간으로 쓰일 열거형인지 아닌지 바로 알아볼 수 없다는 문제 등등이 있다.
4. 그래서 `namespace` 라는 키워드를 소개한다!

덕분에 namespace 키워드를 새롭게 알게 됐습니다. 감사합니다 :)

2023-11-22 01:05 UTC, closed without merging