묵찌빠 프로젝트 [STEP 1] Mango, Mond
tasty-code/ios-rock-scissor-paper pull request #18
Opened 2023-09-07 01:02 UTC by Dongjun-developer

@protocorn93

안녕하세요 콘 묵찌빠 프로젝트[STEP1] Mango, Mond 코드 리뷰 부탁드려요 

●코드 설명

1. boolGame : Bool 변수를 이용해 True면 while문을 다시 돌리고 False면 while문이 종료되도록 하였습니다.
2. comNum : 컴퓨터의 선택 번호를 random 함수를 사용하여 1~3번 숫자 중에서 랜덤으로 배정되도록 하였습니다.
3. print("가위(1), 바위(2), 보(3)! <종료: 0> : ", terminator: "") : print 함수에는 자동 줄바꿈 기능이 있어 terminator: “” 를 이용해 사용자의 입력 받는 위치가 다음 줄로 넘어가지 않도록 하였습니다.
4. RockPaperScissors 함수 : 2개의 Int 값을 받도록 하였습니다. 차례대로 사용자가 입력한 숫자, 랜덤으로 지정된 컴퓨터 숫자를 받습니다. If를 사용하여 사용자가 이기거나 지거나 0을 입력하면 false를 비기거나 0~3의 값 외의 숫자를 입력하면 true을 boolGame에 저장되도록 하였습니다
5. 승패 여부 확인하기 위해서 코드에 컴퓨터의 선택번호를 출력하도록 하였습니다.

●궁금한점
-Nil-coalescing operator방식의 defaultValue의 초기 값을 ""로 작성을 했는데 defaultValue의 초기값에는 아무 의미가 없습니다.
이러한 방식은 가독성을 해친다고 수업을 들어서 guard let 방식으로 받고 싶었는데 optional unwrapping이 어려웠습니다. 혹시 어떤 방식으로 입력값을 받는 게 좋을까요?

2023-09-07 11:33 UTC, protocorn93 requested changes
두 분 코드 잘 봤습니다.👍 동작에는 무리가 없어보여요. 

다만 더 좋은 코드를 작성해볼 수 있는 포인트가 보이네요. 코드는 절대 혼자서 작성하진 않아요. 동료가 내 코드에 덧붙일 수도 있고, 나도 동료 코드에 덧붙일 수 있어요. 

그리고 당장 옆에 동료가 없더라도 과거의 내가 작성한 코드를 내가 못 알아보는 일은 정말 개발자에게 있어선 일상이에요. 이러한 것을 최대한 방지할 수 있는 다양한 방법이 있으니 새싹 과정을 통해 학습해나가셨으면 좋겠어요. 

`readLine`에 대한 처리는 코멘트로 제 생각을 적어놓았어요.

2023-09-07 11:33 UTC, protocorn93 commented on RockPaperScissors/RockPaperScissors/main.swift
> +//}
뒤 커밋에서 제거되었지만, 최대한 커밋에는 불필요한 주석은 제거해서 올려주시면 좋아요. git의 fixup 기능을 활용해보세요.

2023-09-07 11:33 UTC, protocorn93 commented on RockPaperScissors/RockPaperScissors/main.swift
> +func RockPaperScissors(user: Int, com: Int) -> Bool{
```suggestion 
func RockPaperScissors(user: Int, com: Int) -> Bool {
```

중괄호 이전과 다음에는 공백이 들어가는게 좋아요. https://www.swift.org/documentation/api-design-guidelines/ 스위프트 코딩 스타일을 한번 살펴보시는걸 권장드려요.

2023-09-07 11:33 UTC, protocorn93 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    if user == com{
```suggestion
    if user == com {
```

여기두요.

2023-09-07 11:33 UTC, protocorn93 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }else if user == 1 && com == 2{
```suggestion
    } else if user == 1 && com == 2 {
```

여기두요.

2023-09-07 11:33 UTC, protocorn93 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    boolGame = RockPaperScissors(user: userNum, com: comNum)
`RockPaperScissors` 메서드가 두 가지 역할을 하고 있어요. 

1. 승패 판정 
2. 게임 게속 진행 여부

`RockPaperScissors`는 승패 판정 한 가지 역할만 하는 것이 좋아보여요.

2023-09-07 11:33 UTC, protocorn93 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    guard let userNum = Int(readLine() ?? "") else { throw NSError() }
`throw`를 한 이유가 무엇인지 궁금해요. 사용자는 왜 서비스가 종료되었는지 몰라 당황스러워하지 않을까요?

좀 더 사용자 친화적인 예외 처리가 필요해보여요.

2023-09-07 11:33 UTC, protocorn93 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }else if user == 1 && com == 3{
지금은 코드가 적고 1개의 파일이지만 대규모 서비스를 만든다고 가정해보면 동료 개발자는 0, 1, 2, 3이 무엇을 의미하는데 꽤나 오랜 시간이 걸릴 수 있고, 혹은 잘못 이해해서 다른 버그를 만들 수도 있어요. 

개발자 친화적인 방법으로 이를 표현해주면 좋을 것 같아요. enum은 어떨까요?

2023-09-07 11:33 UTC, protocorn93 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    guard let userNum = Int(readLine() ?? "") else { throw NSError() }
`readLine` 호출의 결과를 `??` 연산자를 통해 `""`로 처리하는 대신 이 역시 guard-let 문으로 처리하고 예외 처리해주면 좋을 것 같아요.

2023-09-08 02:21 UTC, Dongjun-developer commented on RockPaperScissors/RockPaperScissors/main.swift
> +//}
fixup기능은 아직 이해가 잘 안되서 좀 더 찾아보고 반영해볼게요.

2023-09-08 02:23 UTC, yeji1008 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    }else if user == 1 && com == 3{
enum을 사용하여 0, 1, 2, 3 대신 rock, paper, scissors, end 로 입력하였습니다.

2023-09-08 02:24 UTC, Dongjun-developer commented on RockPaperScissors/RockPaperScissors/main.swift
> +    guard let userNum = Int(readLine() ?? "") else { throw NSError() }
else에 return 이나 throw를 사용하라고 나와서 return 값을 활용하지 않을 것 같아서 상세 오류 내용을 알려주는 
NSError()를 사용해봤어요. 수정 사항에서는  "잘못된 입력입니다."을 return 하도록 수정했어요.

2023-09-08 02:25 UTC, yeji1008 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    guard let userNum = Int(readLine() ?? "") else { throw NSError() }
readLine() 호출의 결과, userNum을 Int형으로 변환한 결과의 코드를 따로 나누어 2개의 부분 다 guard-let 문으로 처리하였습니다.

2023-09-08 02:26 UTC, yeji1008 commented on RockPaperScissors/RockPaperScissors/main.swift
> +func RockPaperScissors(user: Int, com: Int) -> Bool{
공백 반영했습니다.

2023-09-08 02:26 UTC, yeji1008 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    boolGame = RockPaperScissors(user: userNum, com: comNum)
두 가지의 역할을 나누어 코드를 다시 작성하였습니다.

2023-09-08 02:27 UTC, Dongjun-developer commented on RockPaperScissors/RockPaperScissors/main.swift
> +//}
git 사용이 서툴러서 불필요한 내용이 들어간 커밋이 같이 올라간것 같아요 맨 마지막 커밋을 봐주시면 감사하겠습니다.

2023-09-08 08:04 UTC, closed without merging