[STEP1] JaeGeun, UNO
tasty-code/ios-rock-scissor-paper pull request #2
Opened 2022-08-16 07:46 UTC by wormsJJG

# 작업내용
최초 실행시 출력문 출력
사용자에게 값 입력받기
컴퓨터의 임의의 수 만들고 승패를 결정
잘못된 값을 입력 했을때의 처리
# 고민한 점
유저와 컴퓨터의 승패를 결정 하는 기능을 구현할때 어떻게 하면 복잡하지 않게 구현할 수 있을지 고민후 많은 코드를 작성해
보았고 아래에 코드로 이 기능을 구현하였습니다.
```swift
func dicisionWinOrLose(_ human: Int, _ computer: Int) {
    if human == computer {
        print("비겼습니다!")
        startGame()
    } else if human == 1 && computer == 2 || human == 2 && computer == 3 || human == 3 && computer == 1 {
        print("졌습니다!")
    } else if human == 1 && computer == 3 || human == 2 && computer == 1 || human == 3 && computer == 2 {
        print("이겼습니다!")
    } else if human == 0 {
        print("게임 종료")
    } else {
        print("잘못된 입력입니다. 다시 시도해주세요.")
        startGame()
    }
}
```
# 어려웠던 점
변수 및 함수 네이밍.....

2022-08-17 01:55 UTC, jaemuYeo requested changes
재근 우노 스텝1 아주 빠르게 PR보내주었군요 👍
코드를 실행해본 결과 특별한 에러나 싫행예시와 다른 부분은 찾지못했어요!
그 부분에 대해 매우 좋습니다 👏😀
다만 제가보기에 아쉬운 부분들을 몇 가지 코멘트 남겨놓겠습니다!

아참 그리고 프로젝트 제약사항을 확인하고 짝 프로그래밍을 진행해주세요~!

2022-08-17 01:55 UTC, jaemuYeo commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +func startGame(){
현재 startGame이 맡아서 하고있는 기능들을 생각해봤습니다
1. 게임 메뉴프린트 (가위바위보 종료)
2. 유저 번호 입력
3. 컴퓨터 랜덤 숫자 생성

기능별로 함수를 생성해보면 좋을 것같아요!
그리고 그 이유도 고민해보시길 바랍니다 😉

2022-08-17 01:55 UTC, jaemuYeo commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +    let userInputValue = readLine()
이 상수를 선언하지 않고 바로 바인딩 할 수있는 방법은 없을까요?? 🤔

2022-08-17 01:55 UTC, jaemuYeo commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +    let computerNumber: Int = Int.random(in: 1...3)
1과 3은 무엇을 의미하는 걸까요?
이렇게 코드만 보았을때 의미가 없는 숫자를 `매직 넘버`라고하며 지양하는 편입니다!
매직넘버는 어떤 것이고 어떻게 처리할 수 있을까요??
그 외에 매직넘버들도 한 번 수정해볼 수 있을까요?

2022-08-17 01:55 UTC, jaemuYeo commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +        print("잘못된 입력입니다. 다시 시도해주세요.")
아래의 함수에도 똑같은 문구의 문자가 있는데 어떻게 처리하면 좋을까요?

2022-08-17 01:55 UTC, jaemuYeo commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +    if human == computer {
복잡해지지 않기위해 노력하셨군요!!
다만 지금 봤을때는 논리연산자가 길어져서 가독성이 떨어지는 것 같습니다😫
특정 팀 또는 회사에서는 코드의 길이를 제한하는 곳도 있답니다 ㅎㅎㅎ
가독성을 높이기 위한 방법은 무엇이 있을까요??
프로젝트 페이지에 참고해야하는 문서를 꼭 필독하고 적용해보아요!

2022-08-17 02:05 UTC, wormsJJG commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +    let computerNumber: Int = Int.random(in: 1...3)
열거형으로 한번 수정해보겠습니다.

2022-08-17 02:06 UTC, wormsJJG commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +    if human == computer {
한번 생각해보겠습니다.

2022-08-17 02:06 UTC, wormsJJG commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +    let userInputValue = readLine()
반영하겠습니다!

2022-08-17 02:06 UTC, wormsJJG commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +func startGame(){
넵

2022-08-17 04:46 UTC, wormsJJG commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +        print("잘못된 입력입니다. 다시 시도해주세요.")
함수로 만드는게 좋을것 같습니다.

2022-08-18 02:41 UTC, jaemuYeo requested changes
피드백 반영하느라 고생많으셨습니다!! 👏
rawValue를 통한 프린트도 잘 해주었네요 !
조금 더 간결해질 수 있을 것같지만 많은 작업이 필요하기때문에
문제가 되는 부분만 코멘트 남겨놓았습니다 😀
이번 코멘트에 대한 수정이 이루어지면 머지 진행하도록 할게요!!!

2022-08-18 02:41 UTC, jaemuYeo commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +enum rockScissorsPaper {
‼️ 타입의 네이밍은 어떻게 하는지 한 번더 살펴보길 바래요~ 

전역변수와 타입의 static 변수의 차이점과 장단점은 어떤 것이었나요?

2022-08-18 02:41 UTC, jaemuYeo commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +    static let exitGame = 0
이 친구는 가위바위보에 속하지 않는거 같군요 🤔

2022-08-18 02:41 UTC, jaemuYeo commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +enum result: String {
이 곳도 네이밍 확인해주세요!

또한 열거형에 description을 활용한 문자열 출력방법도 알아보면 좋을 것 같아요 👍

2022-08-18 02:41 UTC, jaemuYeo commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +func menu() {
동사가아닌 명사로 되어있네요! 메뉴의 무엇을 해주고있죠?

2022-08-18 02:41 UTC, jaemuYeo commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +    guard let stringValue = readLine(), let userNumber = Int(stringValue) else {
현재 이 바인딩에서 치명적인 에러가 발생하고있습니다!!
Hit. 여러번 입력을 잘못하고나서 정상적인 입력을 해보세요

2022-08-18 02:41 UTC, jaemuYeo commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +    switch human {
코드의 양은 조금 더 많아져지만 경우의 수가 더 명확해진거같다 생각해요 😀
재근과 우노의 생각은 어떠신가요??

2022-08-18 02:50 UTC, wormsJJG commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +    switch human {
가독성이 굉장히 높아진것같습니다

2022-08-18 02:50 UTC, wormsJJG commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +func menu() {
showMenu로 바꾸는것이 좋겠네요

2022-08-18 02:51 UTC, wormsJJG commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +    static let exitGame = 0
수정하겠습니다.

2022-08-18 03:22 UTC, jaemuYeo commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +func menu() {
넵 또는 pirntMenu도 괜찮은 것 같아요 ^_^

2022-09-08 05:20 UTC, closed without merging