[STEP 2, Feat] Comdori, Eddy
tasty-code/ios-rock-scissor-paper pull request #20
Opened 2023-09-07 09:06 UTC by JUNY0110

### 리뷰어
- @monsteel

### 학습 목표
- [x] 간결하고 명확한 코드 작성
- [x] Optional 안전하게 처리하기
  - Unconditional unwrapping(!) 사용하지 않기
  - 적극적인 guard let ~ else { return } 사용
- [x] 재귀 함수와 반복문 장단점 비교 및 이해
- [x] 기능단위 Commit 작업
- [x] Git Commit Convention에 맞춘 로그 작성
- [x] 1함수 1기능 원칙 준수

### 학습 내용
- 기존의 가위바위보 코드를 리팩토링 과정을 거쳤습니다.
  - while문 제거 후, 재귀 함수 구현 ( 되도록 메모리 관리가 가능하게 구현하려고 노력했습니다. )
  - <img width="500" alt="스크린샷 2023-09-07 오후 5 52 32" src="https://github.com/tasty-code/ios-rock-scissor-paper/assets/98405970/7309d114-2ef2-4b43-9976-e65867562def">

  - 1기능 1함수를 위해 최대한 기능단위 분리
  - 명확한 naming 사용
- frozen어노테이션을 사용해 enum에 새로운 case가 등록되지 않도록 제한하였습니다.
- private 접근제어자 사용 및 final키워드를 활용했습니다.
- Closure를 활용해 필요한 시기에 원하는 print()를 출력하도록 구현했습니다.
  ```swift
    private func checkResult(of userChoice: RpsChoice, with computerChoice: RpsChoice, message: (String) -> ()) -> GameResult {
        switch (userChoice, computerChoice) {
        case (.scissors, .paper), (.rock, .scissors), (.paper, .rock):
            message(GuideMessage.win)
            return .win
        case (.paper, .scissors), (.scissors, .rock), (.rock, .paper):
            message(GuideMessage.lose)
            return .lose
        default:
            message(GuideMessage.draw)
            return .draw
        }
    }
  ```

### 궁금증
- frozen 키워드가 enum에 새로운 case가 등록되지 않도록 해서 안정성을 높인다는 것을 알게 되어 사용해봤으나, 외부에서 enum에 새로운 case를 추가하는 방법이 있는지를 모르겠습니다. 혹시 enum에 새로운 case를 추가하는 방법이 있을까요?

2023-09-08 10:12 UTC, Monsteel requested changes
안녕하세요 컴도리, 에디 👍 step2도 수고 많으셨습니다!

PR보내신 이후에도 코드에 대해 고민해주시고 반영해주신 모습이 인상깊었습니다 👍 
discord로 상황도 설명해 주시고, pr내용에도 포함시켜 주셔서, 두분의 생각 흐름에 따라 리뷰를 진행할 수 있었어요. 고맙습니다.

코드에 대한 리뷰는 이전과 마찬가지로 아래 코멘트 참고 부탁드립니다~

### 궁금증
> 1. `@frozen` 키워드가 `enum`에 새로운 `case`가 등록되지 않도록 해서 안정성을 높인다는 것을 알게 되어 사용해봤으나, 외부에서 `enum`에 새로운 `case`를 추가하는 방법은 알 수 없었습니다. 혹시 **`enum`에 새로운 `case`를 추가하는 방법**이 있을까요?
    - 기존에 잘못 이해했던 것 같습니다. 외부에서 case를 추가하는 게 아닌, 개발자에게 case가 고정되었음을 명시하는 용도인 것 같습니다.
    - 참고자료 [frozen은 무슨 의미일까?](https://chibest.tistory.com/99)를 통해 이해한 바로는 컴파일러가 case가 더이상 생기지 않는다는 것을 알게 되어 switch문 사용 시 별도의 default를 작성하지 않아도 되며, 개발자도 실수없이 코드를 작성할 수 있게 된다고 이해했습니다.
    
LGTM 👍  좋습니다!

> 3. ( 9월 7일 21시 30분 추가 ) `RpsChoice enum`의 기존 `case(가위바위보)`를 재사용하기 위해 `static func`을 만들어 묵찌빠에 적용시켰습니다. 그런데, 묵찌빠를 위한 enum을 별도로 만드는 것이 더 나은 선택인가? 라는 생각이 들었습니다. 고민했던 내용은 아래와 같습니다.
    - 의문1. `RpsChoice enum` 내에서 `static func`을 활용하면 **불필요하게 데이터 영역을 사용하게 되는 게 아닐까요?** 
    - 의문2. **`묵찌빠 enum`을 만드는 것이 더 직관적이고 사용이 용이한데, 현 단계에서 재사용성이 이보다 중요할까요?**

우선 enum 내에 함수를 두는, 굉장히 멋진 구조로 코드를 작성해 주셨네요 👍 
말씀주신 재사용의 장점 외에도, 이런 구조는 각각의 객체들의 역할과 그 관계들을 명확하게 표현할 수 있어, 여러모로 용이한 면이 있습니다 👍 

**의문1에 대한 대답:**
굳이 `static func`을 사용하신 이유가 있으신가요?

아래와 같이 Instance func을 선언하여 사용할수도 있습니다 👍 

```swift
enum Menu {
    case bob // 밥
    case kimch // 김치
    case gim // 김
    
    func print() -> String {
        switch self {
        case .bob:
            return "밥입니다"
        case .kimch:
            return "김치입니다"
        case .gim:
            return "김입니다"
        }
    }
}

Menu.bob.print()

```

의문2에 대한 대답:
재사용성과, 명확성 그 두마리 토끼를 다 잡을 수 있는 방법은 없을까요?
예를들어, 두 개념(MCP, RPS)을 모두 포용할 수 있는 네이밍을 지어주는 등의 시도를 해볼 수 있을것 같아요 👍 

다만, 현 시점에서 RpsChoice를 MCP에서 그대로 사용하는건, 명확한 코드를 만드는데에 방해가 되는 요소같아요. 코드단에는 코멘트를 남기지 않았지만, 꼭 개선이 되었으면 합니다 👍 
+ 누군가 이 코드를 보았을 때 MCP와 RPS간의 관계를 이해하고, "중복된 개념이라 통합했구나"라는 결론에 다다르기 까지에는 많은 시간이 걸릴 수 있어요.

== 

번외로, 약어 사용에 대한 수정사항은 잘 확인했습니다 👍
잘 적어주신 `README.md` 에 해당 약어에 대한 언급이 있으면 좋을것 같아요!

추가적으로 궁금한 사항 있으시면 코멘트 or 디코 부탁드려요~
step2 수고 많으셨고, 리뷰 확인 후 반영해주시면 이어서 리뷰 진행할 수 있도록 하겠습니다~ 👍

2023-09-08 10:12 UTC, Monsteel commented on RockPaperScissors/RockPaperScissors/RockPaperScissors.swift
> +    enum RpsChoice: Int {
약어사용 시, 대소문자 사용을 통일해서 약어임을 더 명시적으로 표현하면 좋을것 같아요 👍  (Rps, rps, RPS / Mcp, mcp, MCP...)

2023-09-08 10:12 UTC, Monsteel commented on RockPaperScissors/RockPaperScissors/RockPaperScissors.swift
> +        guard let userInput = Int(readLine() ?? "0"),
readLine()도 guard문으로 처리할 수 있었을것 같은데, 이처럼 구현하신 배경이 궁금합니다~
+ readLine()의 반환값으로 nil이 넘어오는 상황도 `0~3이 아닌 값을 입력받은 경우` 조건에 포함되어야 할 것 같아요 👀

2023-09-08 10:12 UTC, Monsteel commented on RockPaperScissors/RockPaperScissors/RockPaperScissors.swift
> +        default:
default문을 사용하면, 누락된 케이스를 컴파일러 단에서 확인하기 어려워집니다ㅜ
default에 해당되는 case들을 명시적으로 표현해보는건 어떨까요?

2023-09-08 10:12 UTC, Monsteel commented on RockPaperScissors/RockPaperScissors/RockPaperScissors.swift
> +    // MARK: - Property
복수형 *properties 로 수정 부탁드려요 👍

2023-09-08 10:12 UTC, Monsteel commented on RockPaperScissors/RockPaperScissors/RockPaperScissors.swift
> +    }
input과, choice가 어떤 차이를 가지는지 설명해주실 수 있을까요?

2023-09-08 10:12 UTC, Monsteel commented on RockPaperScissors/RockPaperScissors/RockPaperScissors.swift
> +        guard let computerChoice = RpsChoice(rawValue: Int.random(in: 1...3)) else { return }
`Int.random(in: 1...3)` 이 코드 내에서 두번 사용되고 있는데요, 컴퓨터가 선택해야할 케이스가 늘어나면, 수정해야하는 곳이 두곳. 즉, 관리포인트가 늘어나는 상황이 생기게 됩니다. 하나로 통합하면 좋을것 같아요 👍

2023-09-08 10:12 UTC, Monsteel commented on RockPaperScissors/RockPaperScissors/RockPaperScissors.swift
> +            print("[사용자 턴] \(GuideMessage.mcpChoiceMenu)", terminator: "")
이 코드에서 `terminator` 프로퍼티가 어떤 의미를 가지나요? 👀

2023-09-08 10:12 UTC, Monsteel commented on README.md
> +지금껏 리스크관리가 필요한 재귀함수는 잘 사용하지 않았었는데, 재귀함수를 사용해보니 코드 뎁스가 줄어 코드가 깔끔해보이는 효과를 얻을 수 있었다. 짝프로그래밍을 하면서 알고 있다고 생각한 개념을 설명하는 과정도 연습이 필요하다는 것을 느꼈다. 또한 리뷰어로부터 내 코드에 대해 리뷰를 받을 수 있고, 그 과정에서 애매하다 생각하는 부분들을 질문할 수 있었기
> 개념을 설명하는 과정도 연습이 필요하다는 것을 느꼈다.

👏👏👏

2023-09-08 10:12 UTC, Monsteel commented on README.md
> +- Comdori : 항상 내 방식대로 프로그래밍을 하다가 처음 으로 짝-프로그래밍과 각종 룰(?)을 적용해 진행해 보았는데 내가 생각하지 못한 좋은 로직이 있음을 경험 하였고, 협업에서 지켜야 하는 규칙들이 중요한지를 알 수 있어서 좋은 시간이 되었던 것 같다. 더불어 리뷰어 PR을 통해 프로젝트외 다른 사항도 고민해볼수 있는 시간이 있어서 배우는 즐거
> 더불어 리뷰어 PR을 통해 프로젝트외 다른 사항도 고민해볼수 있는 시간이 있어서 배우는 즐거움을 느꼈다.

✨👀🎉🙇🏻‍♂️

2023-09-10 07:03 UTC, JUNY0110 commented on RockPaperScissors/RockPaperScissors/RockPaperScissors.swift
> +        guard let userInput = Int(readLine() ?? "0"),
> readLine()도 guard문으로 처리할 수 있었을것 같은데, 이처럼 구현하신 배경이 궁금합니다~
> * readLine()의 반환값으로 nil이 넘어오는 상황도 `0~3이 아닌 값을 입력받은 경우` 조건에 포함되어야 할 것 같아요 👀

### Update commit
- 6fa9d7a

### readLine()에 nil-coalescing을 사용한 이유

- readLine()도 `guard let input = readLine() else { return }`으로 같이 묶일 수 있겠으나, 변수를 과하게 분리했다는 생각이 들어 따로 변수를 생성하지 않았습니다.
  - 작성 당시 생각한 부분은 아니지만, Stack영역일지라도, `guard let input = readLine() else { return }` 에서 input을 위한 메모리 공간을 할당해야 한다는 점도 단점이 될 수 있겠습니다.
- 또한 readLine()의 값이 실질적으로 nil이 되는 경우는 없다 라고 판단해 nil-coalescing 연산을 사용해 기본값을 전달하는 방식을 선택했었습니다. 
- 하지만, nil-coalescing 연산을 통해 기본값을 0으로 주게 되면, 혹시나 있을 nil값에 대한 대응에 오류가 발생하므로 enum case에서 제공하지 않는 rawValue인 -1을 주는 것으로 수정하였습니다.
```swift 
guard let userInput = Int(readLine() ?? "-1"),
      let userChoice = RpsChoice(rawValue: userInput) else {
    print(GuideMessage.inputError)
    return nil
}
```
- 아래는 [readLine() - 애플 공식문서](https://developer.apple.com/documentation/swift/readline(strippingnewline:))에 대한 스크린샷으로, readLine()이 optional 타입인 이유에 대한 설명입니다.
- 해석하자면, `EOF(End Of File)가 readLine()이 호출되기 전 먼저 도달하면, 결과값이 nil이 되기 때문이다.` 라고 설명하고 있습니다.
![스크린샷 2023-09-10 오후 3 46 47](https://github.com/tasty-code/ios-rock-scissor-paper/assets/98405970/64aba63b-df6e-4412-b440-3f38d18a1e66)

2023-09-10 07:10 UTC, JUNY0110 commented on RockPaperScissors/RockPaperScissors/RockPaperScissors.swift
> +    // MARK: - Property
> 복수형 *properties 로 수정 부탁드려요 👍

### Update commit 
- 930fede
- `Enum -> Enums`, `Property-> Properties`, `Helper Method -> Helper Methods`
- 여러 개의 메서드 및 객체를 갖고 있는 Mark에 대해서 복수형으로 수정하였습니다. Mark 주석 명칭을 복수형으로 작성하는 것까진 생각하지 못했네요. 확인 감사합니다. 👍👍

2023-09-11 00:35 UTC, comdori-wj commented on RockPaperScissors/RockPaperScissors/RockPaperScissors.swift
> +            print("[사용자 턴] \(GuideMessage.mcpChoiceMenu)", terminator: "")
https://developer.apple.com/documentation/swift/print(_:separator:terminator:)
터미네이터 프로퍼티는 기본값 (default value)이 있는 매개변수는 호출할 때, 매개변수를 생략 하는 기능을 가지고 있습니다.
그래서 보통 프린트문만 사용하면 줄바꿈이 되지만 터미네이터 프로퍼티를 사용하여 ""안에 아무것도 넣지 않으면 줄바꿈이 진행되지 않습니다.

2023-09-11 08:13 UTC, merged