[STEP 2] Janine, Dora
tasty-code/ios-rock-scissor-paper pull request #26
Opened 2023-09-08 09:34 UTC by janine-kang

> 리뷰어: @corykim0829
버드: @janine-kang @KSK9820

## 구현 기능
![image](https://github.com/tasty-code/ios-rock-scissor-paper/assets/76927263/4900e004-89ec-48c0-ae07-ec9c16a14e45)

## 파일 구조
RockPaperScissors
- main.swift
- RspService.swift

## 구현 기능
### 공통
- [x] 모든 프로퍼티와 run()함수를 제외한 나머지 메서드의 은닉화
- [x] 두 가지 게임을 처리할 수 있는 하나의 run() 함수로 타입 캡슐화

### STEP1
- [x] 프로그램 실행 시 사용자 입력값 받기 기능
- [x] 가위바위보 게임 룰에 따른 로직 구현
- [x] 주어진 값이 아닌 경우 예외 처리 구현
### STEP2
- [x] 코드 중복 최소화를 위해 가위바위보 게임 메서드를 재사용하여 묵찌빠 게임 구현
- [x] 첫번째 라운드에서의 프롬프트 메시지와 그 이후의 프롬프트 메시지 변경 - 이전 위너값 저장
- [x] 게임의 승패 상태와 게임의 승자 로직 분리
- [x] 게임의 진행 상황(GameStatus)과 승패 상태(GameResult)을 나타내는 열거형 타입에서 메시지를 분리하여 명시성 추가

## 구현 상세
![image](https://github.com/tasty-code/ios-rock-scissor-paper/assets/76927263/1f3bb9d9-bf44-4e07-a338-df576f07276e)
- main함수에서 struct인 RspService의 인스턴스를 생성하고, run()함수를 호출함.
- 호출 시 매개변수로 원하는 게임 타입을 넘기며, 현재 STEP2 게임 타입을 임의적으로 지정해둠

### Method
- `run()` : 프로그램 구동을 위한 함수. public으로 설정
  - `while loop`를 통해 프로그램의 전체적인 흐름도를 관할
  - `isFirstRound`라는 플래그값을 통해 STEP1과 STEP2 프롬프트 메시지를 구분하여 출력
- `getUserInput()` : 유저의 입력값 처리
  - 유저의 입력값을 `readLine()`으로 받아, 옵셔널 값을 unwrapping
  - String보다 Int값이 보다 stable하므로 String -> Int로 변환하여 `userInput` 프로퍼티에 저장
- `checkInputValidation()` : 유저 입력값에 따라 게임의 진행 상태 변경
  - case가 0일 때, 게임을 종료하므로 상태값을 `.end`로 변경
  - case 1, 2, 3일 때, 다음 단계로 넘어가므로 상태값을 `.onGoing`으로 변경
  - 나머지 상황에 대해, 처음으로 돌아가야 하므로 상태값을 `.tryAgain`으로 변경
    - 이 부분을 Error 케이스로 처리하고 싶었으나, 구조를 어떻게 나눠야 할지 그리고 어떤 Syntax를 사용해야 하는지 찾아내지 못함
- `getOpponentChoice()` : 컴퓨터의 값을 랜덤하게 추출(Range: 1...3)
- `endGame()` : "게임 종료"라는 메시지 출력 후 while loop 탈출
- `game()` : 가위바위보 게임의 핵심 로직
  - 사용자 입력값과 컴퓨터 입력값의 대소비교를 통해 승자 결정
  - 승자 결정 시, 1과 3을 택한 경우는 우선적으로 예외 처리
  - 사용자 입력값이 Optional<Int> 타입이므로 guard let 구문 이용하여 옵셔널 값 제거
  - 승패 여부만을 결정짓고, 판정 로직은 별개로 둠
- `step1Result()` : STEP1에 게임 방식에 따라 사용자의 승패 판정 결과를 출력
  - 비긴 경우, 메시지 출력 후 처음으로 돌아가게 함
  - 나머지 경우, 메시지 출력 후 `isFirstRound` 값을 변경하여 다음 라운드 진행을 가능케 함
- `step2Result()` : STEP2에 게임 방식에 따라 사용자의 승패 판정 결과를 출력
  - 비기는 경우, 승자를 판정 짓고 while loop를 탈출하여 게임을 종료시킴
  - 나머지의 경우, 이전 승자 값을 현재 승자 값으로 저장시키고 현재의 승자를 출력함
- `checkFlow()` : game()의 결과값에 따라 다음 단계 진행 결정
  - STEP1과 STEP2의 승자 결정 방식이 다르므로 switch case문을 통해 각각의 게임 흐름을 구분
  - 게임 타입이 STEP1인 경우, 승패가 결정되면 게임이 종료되는 단일성을 가지므로 `isFirstRound`값의 변경과 무관함 (코드의 재사용성 향상)
  - 게임 타입이 STEP2인 경우, 비길 때까지 게임이 진행되어야 하는 연속성을 가짐

## 고려한 점
- 단일 책임 원칙(SRP)에 따라 하나의 함수가 하나의 책임과 기능을 처리하도록 구현하고자 노력했습니다
- 직관적인 코드 이해와 각 기능에 적합한 네이밍을 고려했습니다
- 상수 데이터를 이용하여 프로그램 내부에서 발생할 수 있는 상황들을 제어하고자 했습니다
- 관심사 분리를 통해 코드 가독성과 재사용성을 높이고, 유지 보수를 용이하게 했습니다
- 강제적인 옵셔널값 제거(`!`)를 지양하고 `guard let`을 사용하여 안전하게 옵셔널 값을 처리하고자 했습니다
- if문과 switch 조건문의 차이를 이해하고, 보다 적합한 상황에 맞게 쓰고자 했습니다
- 기능 단위로 커밋을 나누고 카르마 스타일의 commit message 형식에 맞춰 메시지 작성했습니다
- 합의된 코딩 컨벤션을 따르려 노력했습니다

## 배운 점
- enum 활용 방법을 배웠습니다
- 코딩에 들어가기 앞서 서로 설계를 그리고 구조를 작성한 다음 코드로 옮기는 것이 훨씬 협업에 좋다는 것을 배웠습니다
- 은닉화에 대해서 고민하고 실행하며 체득했습니다
- struct 구조에서 프로퍼티의 값을 변경할 때 `mutating` 키워드를 붙여아 한다는 것을 배웠습니다
- SRP 원칙을 수행해보며 하나의 기능은 하나의 함수에 담는 방법을 배웠습니다
- 다양한 옵셔널 처리 방법을 배우고, 코드 속에서 각 상황에 맞는 방법을 채택하여 적용했습니다

## 궁금한 점
1. GameStatus 안에서 상태를 세분화해놓고 각각의 상태별로 필요 시 message를 사용할 수 있게 만들었는데, 메시지를 사용하지 않는 상태일 때의 경우가 애매하다고 느꼈습니다. 따라서 GameStatus 자체가 잘 추상화된건지 궁금합니다.
```
enum  GameStatus: String {
    case start
    case tryAgain
    case end
    case onGoing
    case notYet
    
    var message: String {
        switch self {
        case .start:
            return "가위(1), 바위(2), 보(3)! <종료 : 0> :"
        case .tryAgain:
            return "잘못된 입력입니다. 다시 시도해주세요."
        case .end:
            return "게임 종료"
        default:
            return "" // 사용되지 않는 trash value
        }
    }
}
```
2. Struct구조의 메모리 경제성의 이점을 취하기 위해 `RspService`의 타입을 구조체로 채택하였습니다. 그러나 모든 메서드에서 프로퍼티의 값을 변경하기 때문에 모든 메서드에 `mutating` 키워드를 붙이게 되었는데, 이런 경우에도 Class보다 Struct의 이점이 더 큰지 궁금합니다. 실제 프로덕트 레벨에서 이런 경우를 만났을 경우엔 주로 Class로의 타입 변경을 시도하나요?

2023-09-10 05:29 UTC, corykim0829 requested changes
수고 많으셨습니다!!

이전에 step1에 추가적으로 피드백 해드린 부분과 이번 step2에서 피드백해드린 부분을 같이 반영해서 이 PR에서 수정하고 이야기 나누면 좋을 것 같습니다!

궁금한점

> 1. GameStatus 안에서 상태를 세분화해놓고 각각의 상태별로 필요 시 message를 사용할 수 있게 만들었는데, 메시지를 사용하지 않는 상태일 때의 경우가 애매하다고 느꼈습니다. 따라서 GameStatus 자체가 잘 추상화된건지 궁금합니다.

제가 이 부분에 대해서는 해당 부분에 리뷰를 남겨드렸는데요, GameStatus의 존재 자체도 고민해보면 좋을 것 같네요!

> 2. Struct구조의 메모리 경제성의 이점을 취하기 위해 RspService의 타입을 구조체로 채택하였습니다. 그러나 모든 메서드에서 프로퍼티의 값을 변경하기 때문에 모든 메서드에 mutating 키워드를 붙이게 되었는데, 이런 경우에도 Class보다 Struct의 이점이 더 큰지 궁금합니다. 실제 프로덕트 레벨에서 이런 경우를 만났을 경우엔 주로 Class로의 타입 변경을 시도하나요?

이 부분은 정답이 없고, 제가 답변을 해드리는건 어렵기 때문에, class와 struct의 차이점을 정리해보시고 ㅁ엇을 사용해야한다고 생각하는지 말해주시면 좋을 것 같습니다!!

2023-09-10 05:29 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/RspService.swift
> +    var message: String {
깔끔하게 enum 프로퍼티로 메세지를 잘 구현하셨네요! 👍

2023-09-10 05:29 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/RspService.swift
> +enum GameType {
최종적으로 하나의 프로젝트 코드를 작성하는 것이기 때문에 step을 enum 타입으로 나누면서까지 코드들을 가져갈 필요가 없어보입니다!

2023-09-10 05:29 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/RspService.swift
> +    private var opponent: Int = 0
상대방을 의미하는 opponent가 추상적이여서 어떤 역할을 하는 코드인지 유추하기 어려운 것 같습니다!

2023-09-10 05:29 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/RspService.swift
> +    private var userInput: Int? = nil
초기값을 넣지 않으면 어떻게 되나요?

2023-09-10 05:29 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/RspService.swift
> +            }
이 부분을 함수로 따로 빼서 정리하면 어떨까요?

2023-09-10 05:29 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/RspService.swift
> +            switch status {
그냥 status라고 하면 추상적이여서 문맥을 파악하기 어려운 것 같아요.

구체적인 객체 안에서의 일반적인 용어 사용은 괜찮지만,
현재 이 구조체명도 RspService인 상황에서 status는 여러 상태를 의미할 수 있어서 혼란을 줄 수 있을 것 같네요.

2023-09-10 05:29 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/RspService.swift
> +                break
break문이 없어도 될 것 같아요. 정리부탁드립니다.

2023-09-10 05:29 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/RspService.swift
> +    private mutating func game() {
game과 같이 명사형 함수명을 사용하면 특정값을 반환할 것 같은 네이밍입니다. 이 부분을 고민해보면 좋을 것 같네요

2023-09-10 05:29 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/RspService.swift
> +            return
여기에 매직넘버들을 정리해야할 것 같아요. 이 조건문만 보고는 어떤 값인지를 분기처리하는지 알기 어렵습니다.

2023-09-10 05:29 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/RspService.swift
> +enum GameWinner: String {
GameWiner와 GameResult가 중복되는 값을 처리하고 있는 것 같습니다. 중복이 되지 않도록 변경해보면 어떨까요?

2023-09-10 05:29 UTC, corykim0829 commented on RockPaperScissors/RockPaperScissors/RspService.swift
> +    case notYet
notYet은 꼭 필요한 값인가요? 조금 더 고민을 해보면 좋을 것 같아요!

2023-09-11 09:29 UTC, KSK9820 commented on RockPaperScissors/RockPaperScissors/RspService.swift
> +    private mutating func game() {
동사형 playGame()으로 수정하였습니다.

2023-09-11 09:30 UTC, KSK9820 commented on RockPaperScissors/RockPaperScissors/RspService.swift
> +    private var opponent: Int = 0
computerChoice로 변수명을 변경하였습니다.
더불어 userInput 또한 userChoice로 변경하였습니다.

2023-09-11 09:36 UTC, KSK9820 commented on RockPaperScissors/RockPaperScissors/RspService.swift
> +    private var userInput: Int? = nil
struct에 모든 변수들의 값을 지정하지 않으면 컴파일 에러가 발생하여 초기값을 지정하였는데, 옵셔널 역시 마찬가지라 생각해서 초기값을 지정하였습니다. 해당 부분 초기값을 지정하지 않는 것으로 수정하였습니다.

2023-09-11 09:36 UTC, KSK9820 commented on RockPaperScissors/RockPaperScissors/RspService.swift
> +                break
확인해서 수정했습니다.

2023-09-11 09:43 UTC, KSK9820 commented on RockPaperScissors/RockPaperScissors/RspService.swift
> +enum GameType {
최종적으로 하나의 프로젝트 코드를 작성하는 것이라면 step을 enum 타입으로 나눌 필요가 없지만 사용자가 가위바위보 게임만 하고 싶을 수도 있고, 묵찌빠도 하고싶을 수도 있기 때문을 생각하여 enum으로 step1, step2를 나누게 되었습니다.
또한 step1을 동작할 수 있게 하는 코드에서 수정 없이 step2도 동작할 수 있게 하고 싶어 같은 playGame() 함수를 재사용하면서, case를 나누게 되었습니다.

2023-09-11 09:46 UTC, KSK9820 commented on RockPaperScissors/RockPaperScissors/RspService.swift
> +            }
해당 부분을 checkRound() 함수로 분리하였습니다.

2023-09-11 09:52 UTC, KSK9820 commented on RockPaperScissors/RockPaperScissors/RspService.swift
> +            switch status {
status는 게임의 진행 상황을 뜻하는 의미로 지었는데, 이보다는 단계별로 진행(진행, 오류, 종료, 시작 전)을 의미하는 것이 좋을 것 같아 변수명을 status -> stage 변경하고, 해당 타입을 GameStatus -> GameStage로 수정하였습니다.

2023-09-11 09:58 UTC, KSK9820 commented on RockPaperScissors/RockPaperScissors/RspService.swift
> +            return
가위, 바위, 보를 뜻하는 매직넘버를 enum Rsp 로 따로 빼서 가독성을 높이는 방향으로 수정하였습니다.

2023-09-11 10:03 UTC, KSK9820 commented on RockPaperScissors/RockPaperScissors/RspService.swift
> +    case notYet
run() 함수의 switch의 default에 들어가도록 .notyet을 제거하였습니다.

2023-11-22 01:05 UTC, closed without merging