[STEP 1] Songmani, Rookie
tasty-code/ios-rock-scissor-paper pull request #3
Opened 2022-08-17 02:15 UTC by chaeyoon1101

리뷰 잘 부탁드립니다 😊

## STEP 1 기능 구현
- 컴퓨터가 임의의 패를 생성하는 `makeComputerValue` 함수 구현
- 프로그램 실행 시 게임이 시작되는 `startGame`함수 구현
- 유저의 패를 입력 받는 `inputUserValue` 함수 구현
- 유저의 입력이 예시 입력 값과 일치하는 지 확인하는 `checkUserValue` 함수 구현
- 유저의 승리와 패배를 판단하는 `checkWinOrLose` 함수 구현

## 궁금한 점
함수가 한 가지 일만 할 수 있도록 최대한 기능 분리를 하는데 노력했습니다 기능을 분리하다보니 코드가 조금 복잡해지는 듯한 느낌도 받았습니다 함수 분리한 것에 대해 자세히 리뷰 해주실 수 있으신가요?

2022-08-17 04:45 UTC, jaemuYeo requested changes
송만이 루키 첫 팀프로젝트 잘 수행해주었군요 👏
저를 태크 해주었어야했는데 타코캣을 태그 했더라구요!! ㅎㅎ
다음 PR때 확인 부탁해요!!
번갈아가며 커밋한 부분도 아주 좋습니다!!
코드를 실행해본 결과 사용자가 빈 값 또는 문자를 입력했을때는 종료가 되어요!
프로젝트 내용을 다시 한 번 읽어보고 시도해보세요 😀
함수 기능 분리에 대한 부분은 너무 좋아요 👍
고민한 티가 많이 납니다 ㅎㅎ 다만 제 생각을 코드에 조금 더 적어 놓겠습니다~~

2022-08-17 04:45 UTC, jaemuYeo commented on rockPaperScissors/rockPaperScissors/main.swift
> +    return Int.random(in: 1...3)
1 2 3 은 무엇을 뜻할까요??
저렇게 코드만 봤을때 알아보기 힘든 숫자를 `매직넘버`라고 부른답니다
매직넘버에 대해 조사해보고 어떻게 해결할 수 있을지 고민해보면 좋을 것 같아요 🤔
아래의 매직넘버도 참고해서 개선해보면 좋겠습니다!!

그리고 이렇게 return이 바로 오는 한줄짜리 함수는 return을 적지않아도 된답니다 ㅎㅎ
단, 이 곳에서 return을 작성하지 않았다면 다른 단행 함수에서도 통일성을 맞춰주세요~
저는 return에는 변수 또는 상수로 저장후 retrun 하는 편입니다!

2022-08-17 04:45 UTC, jaemuYeo commented on rockPaperScissors/rockPaperScissors/main.swift
> +func inputUserValue() -> Int? {
이 친구의 반환타입을 옵셔널로 선택한 이유가 무엇인가요?
내부적으로 옵셔널 바인딩을 하면 외부에서 바인딩해서 사용할 필요가 없을 것 같아요 🤔

2022-08-17 04:45 UTC, jaemuYeo commented on rockPaperScissors/rockPaperScissors/main.swift
> +    let userValue = readLine() ?? "nil"
옵셔널 바인딩을 사용하지 않고 nil 병합연산자를 사용한 이유가 궁금합니다!!🤔

2022-08-17 04:45 UTC, jaemuYeo commented on rockPaperScissors/rockPaperScissors/main.swift
> +func checkWinOrLose(_ userValue: Int?) {
승패를 체크하는 함수에서 컴퓨터의 번호가 생성되고 있어요
매개변수를 활용하면 비교만 가능할 것 같습니다!

2022-08-17 04:45 UTC, jaemuYeo commented on rockPaperScissors/rockPaperScissors/main.swift
> +    if userValue == 1 && computerValue == 3 || userValue == 2 && computerValue == 1 || userValue == 3 && computerValue == 2 {
논리연산자를 사용하여 코드가 길어져 가독성이 매우 떨어져보입니다 ㅠ_ㅠ
특정 팀이나 회사에서는 코드의 길이를 제한하는 곳도 있답니다 ☺️
switch-case 와 같은 것을 사용해 구현해볼 수 있을 거 같아요!

2022-08-17 04:45 UTC, jaemuYeo commented on rockPaperScissors/rockPaperScissors/main.swift
> +func startGame() {
이 함수는 startGame 말그대로 게임시작함수인데
무언가를 출력하고 사용자의 입력을 요구는 기능이 있네요!
내부에 함수 호출로만 구현된다면 좋을 것 같아요 😀

2022-08-17 04:45 UTC, jaemuYeo commented on rockPaperScissors/rockPaperScissors/main.swift
> +    guard let _ = userValue else {
```swift
guard let userValue = inputUserValue() else {
    return
}
```
이렇게 하면 위에 userValue 상수가 필요없지 않을까요??

2022-08-17 07:12 UTC, chaeyoon1101 commented on rockPaperScissors/rockPaperScissors/main.swift
> +func inputUserValue() -> Int? {
다시 수정해보겠습니다

2022-08-17 07:12 UTC, chaeyoon1101 commented on rockPaperScissors/rockPaperScissors/main.swift
> +    let userValue = readLine() ?? "nil"
옵셔널 바인딩을 사용하는 방법으로 다시 수정해보겠습니다

2022-08-17 07:13 UTC, chaeyoon1101 commented on rockPaperScissors/rockPaperScissors/main.swift
> +    if userValue == 1 && computerValue == 3 || userValue == 2 && computerValue == 1 || userValue == 3 && computerValue == 2 {
조금 더 가독성 있는 방법으로 수정해보겠습니다

2022-08-17 07:14 UTC, seunghui5247 commented on rockPaperScissors/rockPaperScissors/main.swift
> +    return Int.random(in: 1...3)
값을 변수에 담아서 return 하는것으로 수정해보겠습니다

2022-08-17 07:15 UTC, seunghui5247 commented on rockPaperScissors/rockPaperScissors/main.swift
> +func checkWinOrLose(_ userValue: Int?) {
컴퓨터의 번호를 다른 곳에서 생성해 매개변수로 받는 것으로 수정하겠습니다

2022-08-17 07:16 UTC, seunghui5247 commented on rockPaperScissors/rockPaperScissors/main.swift
> +func startGame() {
다른 기능을 빼도록 수정하겠습니다

2022-08-17 07:16 UTC, seunghui5247 commented on rockPaperScissors/rockPaperScissors/main.swift
> +    guard let _ = userValue else {
수정하겠습니다

2022-08-18 03:14 UTC, jaemuYeo requested changes
루키 송마니 코멘트 반영하느라 고생하셨습니다!!
다만 아직 아쉬운 부분이 남아서 조금 더 고민하는 시간을 가져보았으면 좋겠습니다 😀
그리고 프로젝트 문서에서 `꼭 읽고 참고해야 하는 문서`의 자료들은
이번 프로젝트에 적용하면 좋은 것들을 모아놓았어요!!
그 중에서 열거형에 대해 알아보고 적용해보았으면 좋겠습니다 💪
당장에 적용해보기 힘들면 실행에 있어서 문제될 것은 없기때문에
코멘트에 대한 마무리만 이뤄진다면 스텝2에서 적용해봐도 될 것같아요 ☺️

2022-08-18 03:14 UTC, jaemuYeo commented on rockPaperScissors/rockPaperScissors/main.swift
> +    let randomComputerValue = Int.random(in: 1...3)
아직도 1 2 3이라는 값이 무엇을 의미하는지 모르겠습니다 🤔
매직 넘버에 대해 조사해보았나요??

2022-08-18 03:14 UTC, jaemuYeo commented on rockPaperScissors/rockPaperScissors/main.swift
> +func checkWinOrLose(_ userValue: Int,_ computerValue: Int) {
이 함수의 로직에 대해 이해가 잘 되지않아요,, ㅠㅠ
-2 와 1 그리고 0은 어떤 것을 의미하나요?

2022-08-18 03:14 UTC, jaemuYeo commented on rockPaperScissors/rockPaperScissors/main.swift
> +func inputGameValue() {
gameStart라는 함수가 사라지고 게임 값 입력이라는 함수가 생겼군요!!
저의 의도랑 다른 것 같아요 ㅠ_ㅠ
여전히 두 가지 이상의 일을 하고있고 함수의 네이밍과 내부 구현 내용이 다른 것 같습니다
이전 처럼 startGame은 유지하되 그 내부에서 이루어지던 기능들을 외부함수로 구현하여 starGame에 호출하는 것을
의도했었습니다!!

2022-08-18 03:14 UTC, jaemuYeo commented on rockPaperScissors/rockPaperScissors/main.swift
> +inputGameValue()
개행을 하면 좋을 것 같아요!

2022-08-18 03:14 UTC, jaemuYeo commented on rockPaperScissors/rockPaperScissors/main.swift
> +    guard let userValue = inputUserValue() else {
`inputUserValue`함수가 옵셔널을 반환하지 않는다면 이 곳에서 바인딩할 일이 없을텐데말이죠 🤔
만약 `inputUserValue`가 여러곳에서 사용해야하는 함수라면 사용할때마다 바인딩을 해줘야할텐데
너무 번거로운 일 아닐까요??

2022-08-19 08:17 UTC, jaemuYeo reviewed
송마니 루키 이번 스텝 두번의 리뷰가 있었는데 반영하시느라 너무너무 고생하셨어요!!
아직도 조금은 아쉬운 부분이 있지만 다음 스텝에서 진행하며 수정해도 될 부분이 있기에
머지 진행하겠습니다!
함수를 기능별로 나눈 부분도 칭찬합니다 👍
몇 가지 코멘트들에 대해서는 반영이 필요한 경우 같이 꼭 토론해보길 바래요!!

2022-08-19 08:17 UTC, jaemuYeo commented on rockPaperScissors/rockPaperScissors/main.swift
> +enum RockScissorPaper: Int {
열거형을 활용한 매직넘버 처리를 너무 잘 해주었습니다 👍
열거형은 프로토콜 채택을 통해 또는 Description을 활용해 다양하게 사용할 수 있어요!
추후애도 게속 사용되는 개념이니 더 조사해보면 좋을 것같아요 ☺️

‼️ 타입의 네이밍은 어떻게하는게 좋을까요??
일반화와 추상화에 대해 수업했었죠??
강아지 고양이 토끼 -> 동물 처럼 일반화를 했었는데
현재의 네이밍을 보면
가위 바위 보 -> 가위 바위 보 라고 하는 것 같네요 🤔

2022-08-19 08:17 UTC, jaemuYeo commented on rockPaperScissors/rockPaperScissors/main.swift
> +    let randomNumberRange = 1...3
위에서 열거형으로 1, 2, 3에 대한 값을 주었는데 
이곳에서는 반영하지 않았군요!!
함수의 반환타입 또한 Int보다는 가위바위보를 반환하면 좋을 것같다는 생각이 들어요 ㅎㅎ

2022-08-19 08:17 UTC, jaemuYeo commented on rockPaperScissors/rockPaperScissors/main.swift
> +func checkUserValue(_ userValue: Int) -> Int {
이 함수도 위의 함수와 같은 문제에 대해 아쉬움이 있네요!

2022-08-19 08:17 UTC, jaemuYeo commented on rockPaperScissors/rockPaperScissors/main.swift
> +    switch compareValue {
튜플을 활용한 승패출력을 시도한 부분은 너무 좋습니다!!
다만 이겼습니다와 졌습니다 비겼습니다 등을 서로 같이 묵어서 케이스를 관리하고
종류별로 개행을 통해 구분하기 쉽게하면 좋을 것 같아요!

2022-08-19 08:17 UTC, jaemuYeo commented on rockPaperScissors/rockPaperScissors/main.swift
> +    case (RockScissorPaper.scissor.rawValue, RockScissorPaper.paper.rawValue):
rawValue로 값을 가져오지 않고 또 다른 방법은 어떤 것이 있을까요?

2022-09-08 05:20 UTC, closed without merging