묵찌빠 프로그램 [Step1] 카일, 미르
tasty-code/ios-rock-scissor-paper pull request #31
Opened 2023-11-22 06:38 UTC by mireu930

@ryan-son
안녕하세요! 라이언! 미르, 카일입니다.
첫 PR보내드립니다! 잘부탁드립니다!

## 🧐 고민했던점
- ### 열거형을 사용한 이유?
    - 구현사항에서 가위,바위,보에 해당하는 값이 1,2,3으로 주어져 있어 값을 비교할 때 명확하지 않았습니다. 따라서, 1,2,3이 무엇을 의미하는지 명시적으로 나타내기 위해 `enum`타입으로 순서에 맞게 원시값을 바꿔줘 가위, 바위, 보를 표현했습니다.
    
        ```swift
        enum Choice: Int {
            case scissor = 1
            case rock = 2
            case paper = 3
        }
        ```
- ### 은닉화를 입힌 이유?
    - 객체가 직접적으로 일하지 않는 메서드, 프로퍼티를 외부에 보여줄 필요가 없다고 생각하여 `private` 접근제어자를 통해 은닉화를 구현해줬습니다.
   
        ```swift
        struct RockScissorPaper {
            private var isRunning: Bool = true
            private mutating func compareChoice(user: Choice, computer: Choice) {
                /*{code}*/
            }
    
            private mutating func checkingResult(user: Int, computer: Int) {
                /*{code}*/
            }
    
            private func checkingComputerChoice() -> Int     {
                /*{code}*/
            }
        }
        ```
- ### 기능(파일)분리를 한 이유?
    - 메서드가 무엇을 의미하는지 알기 위한 명확함과 가독성을 위해 분리를 해줬습니다.
    
        - 수정 전
        ```swift
        struct RockScissorPaper {
            private var isRunning: Bool = true
            // 게임 실행 함수
            mutating func choiceRockScissorsPaper() {
                /*{code}*/    
            }
        }
        ```
        - 수정 후

        ```swift
        struct RockScissorPaper {
            private var isRunning: Bool = true
            // 게임 시작 함수
            mutating func playRockScissorPaper() {
                /*{code}*/    
            }
            // 결과 확인 함수
            private mutating func checkingResult(user: Int, computer: Int) {
                /*{code}*/
            }
    
        }
        ```
- ### 옵셔널 바인딩에 if let / guard let중 어떤 것을 쓸지?
    - 옵셔널을 언래핑하기 위해 옵셔널 바인딩중 `if let` / `guard let`을 고민하였는데, 바인딩된 값을 전역상수로 사용해야 됐기 때문에 guard let 옵셔널 바인딩을 선택했습니다.
    - 또한, 코드의 가독성을 높이고 옵셔널 추출 시 성공/실패 중 해당하는 구문만 제어하기 때문에 빠르게 [exit](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/controlflow/#Early-Exit) 할 수 있다는 장점이 있다고 생각하여 선택했습니다.
- ### class / struct 중 어떤 타입으로 선택할지?
    - 우선, [공식문서](https://developer.apple.com/documentation/swift/choosing-between-structures-and-classes)에서 기본적으로 `struct`를 지향하고 안내된 `class`를 선택해야되는 경우와 현 프로젝트와 맞지 않아 `struct` 타입을 선택했습니다.
    - 또한, 프로젝트 내에서 상속이 불필요했고, `Heap`, `Stack`에 할당되는 `class`보다 `Stack`에만 할당되는 `struct`가 속도면에서 좀더 빠르다고 생각하기 때문에 `struct` 타입을 선택했습니다.
    - `struct` 선택 후 `mutating` 키워드 이유?
        - 값 타입의 경우 기본적으로 내부에서 인스턴스 메서드를 수정할 수 없어 `mutating` 키워드를 사용하여 수정하고 메서드가 종료될 때 변경한 내용을 기존 `struct`에 기록할 수 있게 했습니다.

- ### NameSpace + CustomStringCovertible를 사용한 이유?
    - 프로젝트에서 게임 결과를 출력하는 부분이 많아 하드코딩을 줄이고 코드의 가독성을 높이기 위해 해당 부분을 `NameSpace`로 만들어 활용했습니다.
    - `CustomStringConvertible 프로토콜`을 채택하여 해당 케이스 별로 출력하는 String 값을 반환할 수 있게 구현했습니다.
    
        ```swift
        enum Result {
            case draw
            case win
            case lose
            case quit
            case error
        }

        extension Result: CustomStringConvertible {
            var description: String {
                switch self {
                    case .draw:
                        "비겼습니다!"
                    case .win:
                        "이겼습니다!"
                    case .lose:
                        "졌습니다!"
                    case .quit:
                        "게임종료"
                    case .error:
                        "잘못된 입력입니다. 다시 시도해주세요."
                    }
            }
        }
        ```
- ### while / 재귀함수 중 어떤 것을 쓸지?
    - 코드길이가 길어진다는 단점이 있지만, 직관적으로 이해하기 쉽고, 반복이 일어날 때마다 새로운 스택을 생성하지않아 메모리적으로 사용이 적다는 장점 때문에 재귀함수보다 `while`문을 사용했습니다.
- ### Foundation을 import 하지 않은 이유?
    - `Foundation`은 '*데이터 저장 및 지속성, 텍스트 처리, 날짜 및 시간 계산, 정렬 및 필터링, 네트워킹을 포함하여 앱 및 프레임워크에 대한 기본 기능 레이어를 제공한다*'고 공식문서에서 확인되어 현재 프로젝트에서는 [Swift에서 제공하는 라이브러리](https://developer.apple.com/documentation/swift/swift-standard-library)만 사용하고 있기에 `Foundation`을 삭제해줬습니다.
___

## 🤔 조언을 얻고 싶은 부분
- 코드 컨벤션 및 네이밍(프로퍼티, 메서드, 타입 등)이 적절한지 조언을 얻고 싶습니다.
- 현재 프로젝트에서 SOLID에서 단일 책임 원칙을 적용한다면 구현된 함수를 타입별로 모두 분리해줘야 하는건지 궁금합니다.
---

2023-11-22 17:22 UTC, ryan-son requested changes
카일, 미르, 모두 고생 많으셨습니다. 상세한 내용은 코드에 달아두었으니 본문에서 여쭈어보신 내용과 짚어볼만한 내용만 본문에서 다뤄볼게요.

>- ### 은닉화를 입힌 이유?
 >   - 객체가 직접적으로 일하지 않는 메서드, 프로퍼티를 외부에 보여줄 필요가 없다고 생각하여 `private` 접근제어자를 통해 은닉화를 구현해줬습니다.

- 외부에서 사용하지 않는 인터페이스를 숨긴 것은 객체지향 프로그래밍 관점에서 중요한 개념입니다. 잘 적용하셨네요.
- 아무것도 선언하지 않았을 때 접근제어는 어떤 수준으로 선언되는지, 그리고 또 다른 접근제어 방식이 있는지 알아보세요. 그리고 그 접근제어 방식은 어떤 경우에 이용할 수 있는지 용례를 고민해보시면 좋습니다.

> - ### 옵셔널 바인딩에 if let / guard let중 어떤 것을 쓸지?
>    - 옵셔널을 언래핑하기 위해 옵셔널 바인딩중 `if let` / `guard let`을 고민하였는데, 바인딩된 값을 전역상수로 사용해야 됐기 때문에 guard let 옵셔널 바인딩을 선택했습니다.
- 전역(global) 보다는 메서드 내에서 활용할 것이므로 지역(local) 상수라고 표현하는 편이 더 적합할 것 같네요.

>    - 또한, 코드의 가독성을 높이고 옵셔널 추출 시 성공/실패 중 해당하는 구문만 제어하기 때문에 빠르게 [exit](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/controlflow/#Early-Exit) 할 수 있다는 장점이 있다고 생각하여 선택했습니다.
- if와 guard만으로 개발자의 의도를 명확하게 표현할 수 있다고 생각합니다. 말씀하신 것과 같이 옵셔널 바인딩 또는 원하는 조건에 부합하지 않는 경우에 이른 탈출을 통해 이후의 로직을 실행하지 않겠다고 표현하는 것이 guard, 옵셔널 바인딩 또는 해당 조건에 부합하는 경우 추가적인 로직을 수행하는 경우에 if를 사용할 수 있습니다. 물론 특정 조건에 부합하는 경우를 if로 시작하여 이른 탈출을 시킬 수 있으나, Swift 표현상 구분하여 사용하는 편이 더 적합하다 생각합니다.

>- ### class / struct 중 어떤 타입으로 선택할지?
>    - 우선, [공식문서](https://developer.apple.com/documentation/swift/choosing-between-structures-and-classes)에서 기본적으로 `struct`를 지향하고 안내된 `class`를 선택해야되는 경우와 현 프로젝트와 맞지 않아 `struct` 타입을 선택했습니다.
- 현 프로젝트와 어떻게 맞지 않나요?

>    - 또한, 프로젝트 내에서 상속이 불필요했고, `Heap`, `Stack`에 할당되는 `class`보다 `Stack`에만 할당되는 `struct`가 속도면에서 좀더 빠르다고 생각하기 때문에 `struct` 타입을 선택했습니다.
1. 상속이 필요한 경우는 언제인가요?
2. 메모리 할당 영역에 따라 성능상 이점이 있다는 표현인가요?
3. struct는 class에 비해 항상 성능 측면에서 우월한가요?

>- ### while / 재귀함수 중 어떤 것을 쓸지?
>    - 코드길이가 길어진다는 단점이 있지만, 직관적으로 이해하기 쉽고, 반복이 일어날 때마다 새로운 스택을 생성하지않아 메모리적으로 사용이 적다는 장점 때문에 재귀함수보다 `while`문을 사용했습니다.
- 코드 상 재귀적으로 처리하신 부분이 남아있는 것 같네요. 다시 점검해보시면 좋을 것 같아요.

>## 🤔 조언을 얻고 싶은 부분
>- 코드 컨벤션 및 네이밍(프로퍼티, 메서드, 타입 등)이 적절한지 조언을 얻고 싶습니다.
- 코드에 남겨둔 리뷰를 참고하시면 되겠습니다.

>- 현재 프로젝트에서 SOLID에서 단일 책임 원칙을 적용한다면 구현된 함수를 타입별로 모두 분리해줘야 하는건지 궁금합니다.
- 단일책임원칙에 따라 UI 표현(print)을 담당하는 타입, 승부 로직을 가지고 게임 결과를 만드는 타입 등으로 구분할 수 있으나 이러한 유연성을 통해 얻는 이점이 있는지 판단해보시는 것이 좋습니다. 구현에 유연성을 부여하는 것은 일반적으로 좋은 선택이지만 가독성을 떨어뜨리고 변경이 일어나지 않을 부분에 변경을 위한 구현이 추가될 수 있다는 점에서는 좋지 않은 선택이 될 수도 있습니다. 현업에서는 일반적으로 구현에 충분한 시간을 사용할 수 있는 기회가 많지 않기 때문에 개발자에게 할당된 리소스와 좋은 구조 사이에서 절충점을 찾는 것 또한 중요한 일이라 할 수 있습니다.
---

Step 1 수행하시느라 고생 많으셨습니다. 코멘트나 프로젝트 수행 상 궁금한 점이 있으시면 언제든지 말씀해주세요.

2023-11-22 17:22 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/Choice.swift
> +}
1. 묵찌빠 게임에서는 이를 벗어난 선택지가 없는만큼 열거형을 잘 활용하셨다 생각합니다 👍 ! 이미 알고계시겠지만 열거형은 선택지가 명확하게 정의되어 변경되지 않는 개념에 적용하면 의도에 맞게 잘 구현할 수 있습니다. 한편으로는 열거형의 케이스의 수의 증감 또는 이름의 변경이 일어날 때는 컴파일 시점에 처리해야할 로직을 빠뜨리지 않을 수 있다는 점이 장점 또는 단점이 될 수 있는데, 장점으로 보는 시각은 의도한 구현을 빠뜨리지 않을 수 있다는 점을, 단점으로 보는 시각은 switch-case에 따른 매칭으로 열거형이 변경될 때 반드시 구현을 변경해야하므로 유연성이 떨어진다는 점을 들 수 있습니다.
2. 모듈 내부에서 공유되는 타입인만큼 `Choice`라는 이름만으로는 어떤 역할을 수행하는 타입인지 알기 어려울 것 같네요. 명확한 이름을 사용하거나 Scope를 변경해주는 것이 좋을 것 같아요. 현재 위치를 유지한다면 `RockScissorPaperChoice`, `RockScissorPaper` 타입 내부로 정의를 옮긴다면 `Choice`라는 이름을 유지해도 괜찮을 것 같네요.

2023-11-22 17:22 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/Result.swift
> +}
마찬가지로 어떤 Result인지 파악하는 데 어려움을 겪을 수 있을 것 같아요. 또한 win, lose, draw 뿐만 아니라 quit과 error도 함께 정의되어 있어 애플리케이션 상태를 설명하는 결과와 승부의 결과가 혼재되어 있으니 이를 명확히 파악할 수 있도록 정의를 분리하는 것이 좋을 것 같아요.

2023-11-22 17:22 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/Result.swift
> +}
`CustomStringConvertible` 프로토콜을 사용한 것은 좋은 시도라고 생각합니다만, 한편으로는 해당 케이스에 대한 `description`이 사용자와 마주하는 User Interface에 제공할 메시지라는 것이 의아하게 느껴질 수 있다고 생각합니다. 해당 프로토콜에 대한 구현이 아니라 `message`와 같은 네이밍으로 사용처를 명확하게 구분해주는 것이 의도를 더 명확하게 나타낼 수 있다는 점에서 장점이 있을 것 같네요.

2023-11-22 17:22 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/RockScissorPaper.swift
> +struct RockScissorPaper {
타입의 이름만으로는 어떤 역할을 수행하는지 명확하게 알기 어렵네요. 게임의 의미를 이름에 포함하는 것이 좋을 것 같아요..

2023-11-22 17:22 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/RockScissorPaper.swift
> +    private var isRunning: Bool = true
1. `isRunning`이라는 flag를 통해 while loop를 통제하는 것은 개발자의 의도를 명확하게 파악할 수 있어 좋다고 생각해요.
2. 1에도 불구하고 `isRunning`이 정의된 위치에 대해서는 한 번 생각해볼만한 요소인 것 같네요.
    - 타입의 인스턴스 변수로 사용되면서 `playRockScissorPaper`, `compareChoice`, `checkingResult` 인스턴스 메서드에서 모두 참조되고 있으며 모든 인스턴스 메서드에서 변경 권한이 있기 때문에 어떤 흐름에서 해당 변수가 변경되고 참조되는지 알기 어려울 수 있어요.
    - `playRockScissorPaper`, `checkingResult` 메서드의 while 루프를 제어하는 조건이면서, `checkingResult`가 `playRockScissorPaper` 실행 흐름 상에 존재한다는 점이 실행 흐름을 파악하기 어렵게 만들고 있으며 불필요한 로직이라고 볼 수 있습니다. 다르게 말하면, `checkingResult`에서 1, 2, 3 이외의 input은 `Choice.init(rawValue:)` 이니셜라이저에 의해 guard의 else 구문으로 탈출하여 `playRockScissorPaper` 메서드를 다시 호출하는데, 메서드를 재귀적으로 호출하고 있으므로 while 루프가 추가적으로 필요하지 않다는 것이죠.
    - 이와 같은 이유로 `isRunning`은 `playRockScissorPaper` 메서드의 지역변수로 정의해 사용하거나, 조건 없는 무한 루프를 일으키되 특정 조건이 충족되면 `break`를 통해 탈출하는 방법을 생각해볼 수 있을 것 같습니다. 이렇게된다면 각 메서드가 인스턴스 변수를 변경하는 역할을 수행하지 않으니 mutating 키워드를 사용하지 않아도 되겠네요.

2023-11-22 17:22 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/RockScissorPaper.swift
> +            let computer = checkingComputerChoice()
1. 타입의 이름에 게임이라는 의미가 포함되면 play만으로 메서드의 역할이 모두 설명될 것 같아요.
2. 사용자가 유효하지 않은 입력을 한다면 컴퓨터의 선택이 사용되지 않을 것이므로 컴퓨터의 선택은 사용자와 결판을 짓기 직전에 결정하는 것이 좋아보입니다.

2023-11-22 17:22 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/RockScissorPaper.swift
> +                let input = readLine(),
콘솔 앱이지만 User interface에 해당한다고도 볼 수 있을 것 같네요. 화면에 의도한 요소를 보여주고, input을 받는 동작을 하나로 묶는다면 개발 경험이 좋아질 것 같아요.

2023-11-22 17:22 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/RockScissorPaper.swift
> +                let user = Int(input)
1. userInput, command와 같이 명확한 네이밍을 사용해보는 건 어떨까요? 
2. input을 정수와 같은 원시 타입(primitive type)으로 처리해 사용하기보다 의도하지 않은 입력인 경우 이 단계에서 탈출시킬 수 있도록 구성해보는 것도 좋을 것 같네요. 아래는 예시입니다만, 여러분은 여러분이 원하시는 방식대로 구현해보세요~

```swift
struct Command {
    let value: Int

    // 아래와 같이 상황에 맞는 기능을 추가할 수 있음.
    var isQuit: Bool {
        return value == 0
    }

    func toChoice() -> Choice? { ... }

    init?(value: String) {
        // 유효성 검증 수행 
        guard let converted = Int(value) else { return nil }
        let validInputs = [0, 1, 2, 3]
        let isValid = validInputs.contains(converted)

        guard isValid else { return nil }
        self.value = converted
    }
}

func play() {
    ...
    guard let command = Command(value: input) else { continue }
    guard !command.isQuit else { break } // break 또는 isRunning flag를 변경한 후 continue
    // 유효성 검증을 수행했으므로 1, 2, 3 이외의 value를 가지는 Command는 없다고 간주할 수 있음.
    ...

// 유효한 명령을 아래와 같이 정의할 수도 있음.
// 1.
enum ValidCommand: Int, CaseIterable {
    case quit
    case rock
    case scissor
    case paper
}

let validCommands = ValidCommand.allCases
let validInputs = validCommands.map(\.rawValue)

// 2.
struct Command {
    private static let validInputs = [0, 1, 2, 3]

    init(value: String) {
        ...
        let validInputs = Self.validInputs
        ...
    }
}



```

- [Failable Initializer - Swift Programming Language](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/initialization/#Failable-Initializers)
- [Key-Path expression - Swift Programming Language](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/expressions/#Key-Path-Expression)

2023-11-22 17:22 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/RockScissorPaper.swift
> +            checkingResult(user: user, computer: computer)
1. 컴퓨터 입력을 메서드의 인터페이스로 제공한 건 좋은 선택이네요. 사용자의 선택에 따라 어떤 응답이 나올지 알 수 없는 메서드보다는 항상 결과를 의도한대로 통제할 수 있는 방식으로 만드는 것이 좋은데, 그렇게 구성하셨군요.
2. 메서드의 네이밍은 동사(수행하는 행위) + 명사로 작성하는 것이 일반적입니다. 이런 의미에서 `checkResult`가 일반적인 네이밍이긴 하지만, 이 이름만으로는 정확히 어떤 역할을 수행하는지 이해하기 쉽지 않네요. `makeResult` 또는 `createResult`와 같은 이름으로 변경하되 메서드 이름에 맞게 `result`를 반환해주고 이에 따라 로직을 이어나가면 더 가독성이 높아질 것 같습니다.

2023-11-22 17:22 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/RockScissorPaper.swift
> +    private mutating func compareChoice(user: Choice, computer: Choice) {
1. 메서드 인터페이스는 사용자와 컴퓨터의 선택을 비교해서 결과를 반환할 것 같은데 아무것도 반환하지는 않고 있네요. 결과 도출 뿐 아니라 isRunning 인스턴스 프로퍼티의 변경을 이 메서드에서 담당하고 있어 흐름을 따라오기 쉽지 않아 보여요. 적절한 값을 반환하고 이 값을 토대로 호출하는쪽 메서드에서 변수를 변경하는 책임을 지면 좋겠어요.
2. playRockScissorPaper 메서드에서 private method를 호출하는 순서는 checkingResult -> compareChoice 이므로 타입 내부에서 구현도 이 순서대로 정렬해주시면 로직을 파악하거나 읽는데 더 도움이 될 것 같아요.

2023-11-22 17:22 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/RockScissorPaper.swift
> +            isRunning = false
튜플 타입으로 승부를 결정하는 로직을 구성해보셨네요. 묵찌빠에 의한 승패 로직을 잘 구성하셨다고 생각합니다.

2023-11-22 17:22 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/RockScissorPaper.swift
> +            playRockScissorPaper()
PR 본문에는 재귀함수 호출보다 while 루프로 실행 흐름을 통제한다고 생각했는데, 무승부면 재귀 호출을 하는군요?

2023-11-22 17:22 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/RockScissorPaper.swift
> +                let computerChoice = Choice(rawValue: computer)
`init?(rawValue:)` 이니셜라이저를 상황에 맞게 잘 사용하셨네요.

2023-11-22 17:22 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/RockScissorPaper.swift
> +            }
유효하지 않은 입력이 들어오면 재귀적으로 함수를 호출하는군요. 몇 번 하고나니 콜스택이 이렇게 되어버렸읍니다...

<img width="1048" alt="image" src="https://github.com/tasty-code/ios-rock-scissor-paper/assets/69730931/c8326e7f-84e7-4163-91e7-fb81b2ddb51c">

2023-11-22 17:22 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/RockScissorPaper.swift
> +                return
quit은 `Choice(rawValue:)`를 수행하기 이전에 검증해서 탈출시켜주는 것이 게임 의도에도 맞고 불필요한 비용을 들이지 않을 수 있어 좋다고 생각합니다.

2023-11-22 17:22 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/RockScissorPaper.swift
> +                continue
여기로 들어오는 건 어떤 경우인가요?

2023-11-22 17:22 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/RockScissorPaper.swift
> +    }
무작위 수를 원하는 범위에서 선택하는 로직을 구성해보셨군요. 향후 로직을 검증할 때 원하는 결과를 의도적으로 도출하는 경우 이런 로직이 포함되어 있으면 검증하기 어렵게 됩니다. 랜덤한 요소를 인터페이스에서 제공받을 수 있도록 구성해보면 좋을 것 같아요.

2023-11-22 17:22 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/main.swift
> +var rockScissorPaper = RockScissorPaper()
상수로 선언이 되지 않았던 이유가 있었을까요? 구조체와 클래스의 참조 방식의 차이로 발생하는 것이니 명확하게 이유를 알아두시면 좋습니다.

2023-11-23 02:11 UTC, Changhyun-Kyle commented
- **현 프로젝트와 어떻게 맞지 않나요?**
    - 공식문서를 확인했을 때, 
        | `class` | `struct` |
        |:-------:|:--------:|
        |`Objective-C` 상호 운용성이 필요할 때 |기본적으로 구조체 선택|
        | 동일성 제어가 필요할 때 |동일성 제어가 필요하지 않을 때| 
        
        위와 같이 안내되어 있습니다. 따라서, 현 프로젝트 단계에서 인스턴스를 `main에서` 하나만 생성하기 때문에 동일성 제어가 필요하지 않고 `Objective-C` 상호 운용성이 필요하지 않다고 판단했습니다.
- **상속이 필요한 경우는 언제인가요?**
    - 기존 클래스의 속성과 메서드를 새로운 클래스에서 재사용할때와 새로운 기능을 추가하거나 기존 기능을 변경하려면, 기존 클래스를 수정하지 않고 새로운 클래스를 만들어 상속할때 필요로 합니다.
- **메모리 할당 영역에 따라 성능상 이점이 있다는 표현인가요?**
    - 해당 프로젝트에선 데이터가 작고 간단하여 오버헤드가 class보다 부담이 적다고 생각하여 이러한 부분에 있어서 class보다는 struct가 적절하다고 생각하다는 표현이었습니다.
- **struct는 class에 비해 항상 성능 측면에서 우월한가요?**
    - `struct`가 항상 우월하다고 생각하진 않습니다.
    - `class`가 우월한 상황:
        클래스는 참조 타입이므로 인스턴스의 주소를 전달하기 때문에 데이터의 크기가 크거나 복잡한 데이터를 다룰 때 구조체의 값 복사 비용을 피할 수 있기에 구조체보다 효율적입니다. 
    - `struct`가 우월한 상황:
        구조체는 값 타입이기 때문에 작은 크기의 데이터를 다룰 때 효율적입니다. 값 복사가 발생하며 메모리 할당 및 해제가 비교적 간단하기 때문입니다.

2023-11-23 02:41 UTC, mireu930 commented on RockPaperScissors/RockPaperScissors/Choice.swift
> +}
`Choice` 열거형 네이밍을 `RockScissorPaperChoice`으로 수정하였습니다!

2023-11-23 02:43 UTC, mireu930 commented on RockPaperScissors/RockPaperScissors/Result.swift
> +}
`Result`의 네이밍을 `GameResult`로 수정하였고, `quit`, `error` case의 경우는 `ApplicationStatus`열거형으로 분리해줬습니다.

2023-11-23 02:44 UTC, mireu930 commented on RockPaperScissors/RockPaperScissors/Result.swift
> +}
`CustomStringConvertible`프로토콜을 해제한후 message 변수를 선언하여 사용처를 명확하게 구분해줬습니다.

```swift
enum GameResult {
    case draw
    case win
    case lose
}

extension GameResult {
    var message: String {
        switch self {
        case .draw:
            "비겼습니다!"
        case .win:
            "이겼습니다!"
        case .lose:
            "졌습니다!"
        }
    }
}
```

2023-11-23 02:47 UTC, mireu930 commented on RockPaperScissors/RockPaperScissors/RockScissorPaper.swift
> +struct RockScissorPaper {
`RockScissorPaperGame`으로 수정했습니다!

2023-11-23 06:26 UTC, mireu930 commented on RockPaperScissors/RockPaperScissors/RockScissorPaper.swift
> +    private var isRunning: Bool = true
'isRunning`을 메서드안에 지역변수로 정의해줬습니다!

2023-11-23 06:27 UTC, Changhyun-Kyle commented on RockPaperScissors/RockPaperScissors/RockScissorPaper.swift
> +    }
`let computerChoice = Int.random(in: 1...3)` 선언부를 `startGame()` 내부로 이동하여 `user` 값과 비교하기 전에 선언했습니다!

2023-11-23 06:34 UTC, mireu930 commented on RockPaperScissors/RockPaperScissors/RockScissorPaper.swift
> +            let computer = checkingComputerChoice()
1. `playRockScissorPaper` -> `play`로 수정을해줬습니다!
2. guard문에 이후에 선언하도록 수정했습니다!

2023-11-23 06:50 UTC, Changhyun-Kyle commented on RockPaperScissors/RockPaperScissors/main.swift
> +var rockScissorPaper = RockScissorPaper()
구조체 타입은 값 타입으로 인스턴스 생성 시 값을 복사하게 됩니다. 따라서, 인스턴스를 선언한 후 해당 인스턴스의 속성을 변경할 수 있어야 합니다. 하지만, 인스턴스를 상수로 선언한다면, 한 번 값이 할당된 이후에는 해당 값이 변경되지 않기 때문에 구조체의 활용하는 데 제약이 생길 수 있다고 생각합니다!

2023-11-23 06:58 UTC, mireu930 commented on RockPaperScissors/RockPaperScissors/RockScissorPaper.swift
> +            playRockScissorPaper()
해당부분 잘못기입하여 수정하였습니다!

2023-11-23 07:01 UTC, mireu930 commented on RockPaperScissors/RockPaperScissors/RockScissorPaper.swift
> +                continue
해당부분은 Int를 잘못적어줬을때 들어온다고 생각했는데, 값이 들어오는 경우가 없어 return 수정해줬습니다.

2023-11-23 07:02 UTC, Changhyun-Kyle commented on RockPaperScissors/RockPaperScissors/RockScissorPaper.swift
> +            }
재귀함수로 호출되는 부분을 모두 수정하여 while문으로 동작할 수 있게 수정했습니다!

2023-11-23 07:40 UTC, mireu930 commented on RockPaperScissors/RockPaperScissors/RockScissorPaper.swift
> +                return
게임종료를 Choice를 수행하기 이전에 검증을 하기위해 수정해줬습니다.
```swift
 guard
            user != 0
        else {
            print(ApplicationStatus.quit.message)
            return false
        }
        
        guard
            let userChoice = GameChoice(rawValue: user),
            let computerChoice = GameChoice(rawValue: computer)
        else {
            print(ApplicationStatus.error.message)
            return true
        }
        
        return compareChoice(user: userChoice, computer: computerChoice)
```

2023-11-23 07:44 UTC, mireu930 commented on RockPaperScissors/RockPaperScissors/RockScissorPaper.swift
> +            checkingResult(user: user, computer: computer)
`checkingResult`를 `makeResult`로 네이밍 수정해줬습니다.

2023-11-23 07:46 UTC, mireu930 commented on RockPaperScissors/RockPaperScissors/RockScissorPaper.swift
> +    private mutating func compareChoice(user: Choice, computer: Choice) {
`Bool타입`으로 반환을 해줬고, `checkingResult(->makeResult)` -> `compareChoice`순서로 정렬해줬습니다.

2023-11-23 07:53 UTC, mireu930 commented on RockPaperScissors/RockPaperScissors/RockScissorPaper.swift
> +                let input = readLine(),
guard문으로 선언한 input상수를 compareChoice함수에서 인자로 받아오도록 구현을 했어서 해당부분을 다른 함수로 기능 분리를 하면 받아올수 없게 됩니다. 다른방법이 있는지 궁금합니다.

2023-11-23 08:37 UTC, mireu930 commented on RockPaperScissors/RockPaperScissors/RockScissorPaper.swift
> +                let user = Int(input)
말씀주신 바와 같이 유효성검증을 하는 타입을 분리를 해줘 의도하지 않은 입력인 경우 이 단계에서 탈출시킬 수 있도록 구성해봤습니다.
다만, 유효성을 검사하는 구조체와 프로퍼티의 네이밍이 어떻게 표현해야 적절한지 잘몰라서 라이언이 써주신대로 네이밍했는데, 보통 어떻게 네이밍을 해주는지 궁금합니다.

2023-11-26 16:17 UTC, ryan-son approved these changes
미르, 카일, 고생 많으셨습니다. 
코멘트 달아둔 내용은 금요일 저녁에 회의실에서 이야기 나누었던 이야기를 글로 표현해 둔 것입니다. 마이너한 사항이니 필요하다고 판단되시는 것들은 Step 2에서 함께 반영해보시면 좋을 것 같네요.

2023-11-26 16:17 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/NameSpace/ApplicationStatus.swift
> +}
ApplicationStatus가 Game의 상태를 표현하기 위한 목적이 아니라 단순히 메시지 제공에 의의가 있다면 아래와 같이 메시지라는 의미를 담은 namespace를 만들어 사용할 수도 있을 것 같습니다.

```swift
enum ApplicationStatusMessage {
    static let quit = "게임종료"
    static let error = "잘못된 입력입니다. 다시 시도해주세요."
}
```

2023-11-26 16:17 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/NameSpace/Validator.swift
> +struct Validator {
어떤 것의 유효성을 검사하는 타입인지 이름으로는 명확히 파악하기 어려운 면이 있어 보입니다.

2023-11-26 16:17 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/NameSpace/Validator.swift
> +    }
유효성 검증과는 거리가 있는 기능인 것 같습니다. Validator라면 유효성 검증 기능만을 포함하고 있는 것이 응집도 측면에서 더 나은 결정이 될 수 있을 것 같아요.

2023-11-26 16:17 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/NameSpace/Validator.swift
> +    }
failable initializer를 통해서도 검증할 수 있겠지만, Validator라는 이름을 가진 타입이라면 validate(_:)라는 시그니처를 가진 메서드를 제공한다면 더 자연스러운 형태로 사용할 수 있을 것 같아요. 만약 `validator.validate(input)`과 같은 형태로 사용하는 것이 유사한 어구가 등장해서 더 축약하고 싶다면, Swift 언어가 익숙해진 시점에 `callAsFunction` 키워드로 더 알아보시면 좋을 것 같네요.

- [[SE-0253] Callable values of user-defined nominal types - swift-evolution](https://github.com/apple/swift-evolution/blob/main/proposals/0253-callable.md)

2023-11-26 16:17 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/RockScissorPaperGame.swift
> +        }
while loop를 제어하기 위한 isRunning이라는 변수는 선언해 사용하고 있지만, 실제로 이 flag를 제어해서 통제하고 있지는 않네요. 실행 흐름에서 isRunning flag를 변경해 loop를 통제하거나 isRunning 변수를 선언하지 않는 방식으로 변경하면 의도를 더 정확히 파악할 수 있을 것 같습니다.

2023-11-26 16:17 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/RockScissorPaperGame.swift
> +            guard start() else { return }
1. start()라는 메서드가 Boolean을 반환한다는 것이 의아하게 느껴질 수 있겠네요. 메서드 이름을 고민해보실 수 있을 것 같습니다.
2. isRunning flag를 유지하실 생각이시라면 이 메서드에서 반환한 Boolean을 할당하는 방식으로 활용해볼 수 있을 것 같습니다.

2023-11-26 16:17 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/RockScissorPaperGame.swift
> +    private func start() -> Bool {
외부에 공개하지 않아도 될 메서드에 접근제어를 걸어두셨네요. 멋집니다! 👍

2023-11-26 16:17 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/RockScissorPaperGame.swift
> +        guard let validator = Validator(value: userInput) else {
Validator의 failable initializer에 코멘트 남겨둔 것과 동일한 이야기입니다. userInput에 따라 유효성 검증 기능을 수행할 것으로 예상되는 Validator가 초기화에 실패할 수도 있다는 점이 조금은 의아하게 느껴질 수도 있을 것 같습니다. 유효성 검증을 수행하는 Validator의 초기화 작업과 유효성 검증을 수행하는 메서드를 분리하는 것이 좋은 선택이 될 수 있을 것 같습니다.

2023-11-26 16:17 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/RockScissorPaperGame.swift
> +        guard !validator.isQuit else {
validator이 유효성 검증을 넘어선 범위의 작업을 하고 있는 것 같습니다. 다른 방식으로 풀어가볼 수 있을 것 같네요.

2023-11-26 16:17 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/RockScissorPaperGame.swift
> +    private func makeResult(user: Int, computer: Int) -> Bool {
메서드의 이름을 따라서 반환 타입도 GameResult가 된다면 로직을 이해하기 더 수월할 것 같아요. makeResult의 결과가 Boolean이되면 GameResult에 비해 그 의도를 한번 더 들여다 볼 필요가 있을 것 같네요.

2023-11-26 16:18 UTC, merged