[STEP 1] Asher, NERO
tasty-code/ios-rock-scissor-paper pull request #34
Opened 2023-11-22 08:16 UTC by tawans

@cherrishRed
묵찌빠 프로젝트 STEP1
묵찌빠 요소(가위,바위,보)를 선언할때 처음에는 배열로 선언해서 해보고 
Enum 타입으로 한정된 요소에 접근하도록 코딩하는것에 대해 많이 생각해보았습니다.
입력값 유효성 검사 부분에서 guard let으로 검사하는 부분에 대해 고민을 좀 많이 해서 작성했었습니다.
해결이 되지 않은 점은 딱히 없습니다.
저희가 작성한 코드에서 불필요한 코드가 있다면 조언해주시고
더 나은 방법으로 개선점이 있다면 조언해주시면 감사하겠습니다.

2023-11-22 09:51 UTC, cherrishRed requested changes
안녕하세요! Asher, NERO 👋
@tawans @ODDNERO
리뷰어 🔴레드 입니다. 잘부탁 드려요 :)

STEP 1 너무 수고하셨습니다!

제가 드리는 코멘트 들은 정답이 아니라, 그냥 조언 정도로 생각해 주시면 될 것 같아요.
코드에는 정답이 없는 것 다들 아시죠?😉

제 코멘트를 보시고, 이해가 안되거나, 궁금하신 부분은 댓글로 남겨 주시거나, 디스코드로 DM 주시면 됩니다. 다시 댓글 남겨드릴 수 있고, 필요하시다면 직접 디코방에서 이야기를 나눠 볼 수도 있을 것 같아요!

## 메모리가 늘어나요.
코드를 다운받아서 돌려보니, 간단한 코드임에도, 가위 바위 보를 할 수록 계속 메모리가 늘어나더라구요.
왜 그럴까요? 생각해보시고, 답글로 알려주세요!

## 실패는 .rock 이 아니다.
이건 제가 답글에도 남겨 놓았는데요, 실패 했을 때는 어떻게 해야 할까요? 
그리고 왜 실패했을 때, .rock 을 리턴하면 안되는지 생각해보세요☺️

나머지 사항들은  답글을 참고해 주세요!

2023-11-22 09:51 UTC, cherrishRed commented on RockPaperScissors/.DS_Store
.DS_Store 이라는 파일을 같이 커밋 하셨네요!
이 파일은 무슨 파일 일까요? 읽을 수 가 없네요.

2023-11-22 09:51 UTC, cherrishRed commented on RockPaperScissors/RockPaperScissors/main.swift
> +enum Result: String {
`Result` 라는 이름의  enum을 만드셨네요.
enum을 활용하신 부분 너무 좋습니다!
그런데, 지금은 괜찮지만 `Result` 란 이름은 예약어라서 잘 사용하지 않는데요, 예약어가 뭘까요? 왜 사용하지 않는 것일까요?

2023-11-22 09:51 UTC, cherrishRed commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
randonChoice 를 뽑아내고 있군요, 그런데 실패했을 경우 .rock 을 return 하도록 되어있네요. 
.rock 을 리턴하는 이유는 뭘까요? 🤔

2023-11-22 09:51 UTC, cherrishRed commented on RockPaperScissors/RockPaperScissors/main.swift
> +        printResult(result: result)
이 메서드 내부를 보니 한줄 밖에 되지 않는데, 따로 메서드로 빼신 이유가 궁금하네요.

2023-11-22 09:51 UTC, cherrishRed commented on RockPaperScissors/RockPaperScissors/main.swift
> +        let playerChoice = Choice.allCases[playerChoiceInt - 1]
allCases 배열에서 (playerChoiceInt -1)의 배열의 값을 가져온다는 코드가 조금 추측하기 어려운 코드 같아요. 
조금 더 알기 쉽게 enum을 활용해 볼까요?

2023-11-22 09:51 UTC, cherrishRed commented on RockPaperScissors/RockPaperScissors/main.swift
> +        let result = playGame(player: playerChoice, computer: computerChoice)
randomChoice() 를 바로 computer 넣지 않고 변수를 한번 빼신 이유가 무엇인가요?

2023-11-22 20:29 UTC, tawans reviewed
Red 첫번째 PR에 코드리뷰 해주신 것에 대한 답변 작성

2023-11-22 20:29 UTC, tawans commented on RockPaperScissors/.DS_Store
**해당 내용 검색 후 알게된 점** 
- .DS_Store는 macOS 운영 체제에서 파일 및 폴더의 메타데이터를 저장하는 숨김 파일입니다. 이 파일은 Finder에서 폴더를 열거나 보기를 할 때 폴더의 레이아웃 및 모양과 관련된 정보를 저장합니다. 이 정보에는 폴더의 아이콘 위치, 보기 설정, 배경 이미지 등이 포함될 수 있습니다.

- .DS_Store 파일은 주로 로컬 개발 환경에서 사용되며, 다른 사람과 프로젝트를 공유하거나 협업할 때 문제가 발생할 수 있습니다. 이 파일은 특정한 운영 체제에 종속되어 있기 때문에, 다른 운영 체제를 사용하는 팀원들과 코드를 공유할 때 문제가 될 수 있습니다.

- 이 파일은 Git 저장소에 포함될 필요가 없으며, 오히려 여러 팀원이나 다양한 운영 체제를 사용하는 경우에는 불필요한 충돌을 발생시킬 수 있습니다. 따라서 일반적으로 이러한 운영 체제 특정 파일들을 .gitignore 파일에 추가하여 Git이 이 파일들을 무시하도록 설정합니다.

---

**해결 방법**

1. .DS_Store 파일 삭제 커밋
2. .gitignore 내용 추가하여 추후에 불필요한 파일이 올라가지 않도록 설정
```
### macOS ###
# General
.DS_Store
.AppleDouble
.LSOverride
```

위 방법을 통해 해결하였습니다. 
프로젝트 레포지토리를 생성할때 gitignore 설정을 잘 하였는지
확인하는 버릇을 들이도록 하겠습니다. 감사합니다 :D

2023-11-22 20:29 UTC, tawans commented on RockPaperScissors/RockPaperScissors/main.swift
> +enum Result: String {
**예약어에 대하여 조사**
> 예약어(Keyword)는 프로그래밍 언어에서 미리 사용하기로 약속되어 있는 단어로, 식별자로 사용할 수 없는 단어를 뜻합니다. 키워드는 프로그래밍 언어 문법의 일부로, 특별한 의미를 갖는 단어를 뜻합니다. 스위프트의 키워드는 대부분 예약어입니다.

**잘 사용하지 않는 이유에 대하여 조사** 
- 명확성과 가독성: Swift는 명시적이고 가독성이 뛰어난 코드를 선호합니다. 예약어를 enum의 이름으로 사용하는 것은 코드의 가독성을 떨어뜨릴 수 있습니다. 예약어는 이미 언어에서 특별한 용도로 예약되어 있기 때문에 해당 enum이나 코드 블록의 목적을 명확하게 이해하기 어려워집니다.

- 충돌의 위험성: Swift에서는 특정 예약어를 이미 언어의 일부로 사용하고 있기 때문에, 해당 예약어를 다시 사용하면 충돌이 발생할 수 있습니다. 이는 코드가 예상치 못한 방식으로 해석되거나 실행되는 문제로 이어질 수 있습니다.

- 언어의 일관성 유지: Swift는 언어의 일관성을 중요시하며, 예약어를 특정 목적으로 예약해 두는 것은 이 일관성을 유지하는 데 도움이 됩니다. 이는 개발자들이 코드를 이해하고 유지보수하는 데 도움이 되며, 코드베이스가 일관된 스타일과 패턴을 유지할 수 있도록 도와줍니다.

**결론**
위와 같은 이유들로 특정 예약어가 의미적으로 적절한 이름이라면, 유사한 의미를 가진 다른 용어를 선택하는 것이 좋다 라고 생각했습니다. 앞으로는 예약어 부분을 이름으로 사용하지않도록 주의해서 사용하도록 하겠습니다.

```swift
enum GameResult: String {
    case win = "이겼다!"
    case draw = "비겼다!"
    case lose = "졌다!"
}
```

위 이름으로 변경하였습니다. :D

2023-11-22 20:29 UTC, tawans commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
강제언래핑(!)을 쓰지 않기 위해 If let 바인딩을 사용했었는데요. 
실패했을때의 기본 return 값을 필수로 넣어줘야해서 어차피 실패할 확률은 없을거야 라고 
무심코 기본값으로 .rock으로 넣었었네요. 무식하게 했었던 것 같습니다. 지금보니 부끄럽네요. 
코멘트 해주신 내용을 보고 어떻게 수정할까 고민하다가 
```swift
func randomChoice() -> Choice? {
    return Choice.allCases.randomElement()
}
```
위 코드로 옵셔널값으로 리턴하도록 변경해서 
```
    guard let computerChoice = randomChoice() else {
        continue
    }
```
아래 computerChoice에서 guard let 바인딩으로 언래핑하는 방법으로 변경해보았습니다.
더 스마트하게 짤 수 있는 방법이 있다면 힌트를 주시면 감사하겠습니다..! :D

2023-11-22 20:29 UTC, tawans commented on RockPaperScissors/RockPaperScissors/main.swift
> +        printResult(result: result)
코드에서 함수로 빼보는 연습을 하려고 또 뭐가 있을까 하다가 Result 출력하는 부분도 함수로 한번 빼볼까 하는
막연한 생각으로 따로 뺐었습니다. 다시 보니 한줄의 코드인데 지금보니 불필요한 부분이라고 생각되서 해당 함수는 제거 하였습니다.
```swift
        let result = playGame(player: .scissors, computer: computerChoice)
        print(result.rawValue)
```
바로 print문으로 출력하도록 변경했습니다. :D

2023-11-22 20:29 UTC, tawans commented on RockPaperScissors/RockPaperScissors/main.swift
> +        let playerChoice = Choice.allCases[playerChoiceInt - 1]
말씀주신대로 고민해보고 코드 변경 했습니다.
enum과 switch문을 활용해서 가독성과 이해하기 쉬운 코드로 작성해보려고 노력해보았습니다. :D

```swift
    switch playerChoiceInt {
    case 0:
        isEnd = true
    case 1:
        let result = playGame(player: .scissors, computer: computerChoice)
        print(result.rawValue)
    case 2:
        let result = playGame(player: .rock, computer: computerChoice)
        print(result.rawValue)
    case 3:
        let result = playGame(player: .paper, computer: computerChoice)
        print(result.rawValue)
    default:
        break
    }
```

2023-11-22 20:29 UTC, tawans commented on RockPaperScissors/RockPaperScissors/main.swift
> +        let result = playGame(player: playerChoice, computer: computerChoice)
위 코드를 작성 할 때를 한번 다시 떠올려보니
일단 randomChoice() 리턴값을 받을 수 있는 상수를 만들자 그냥 무심코 만들었던 것 같구요.
뭔가 가독성 부분에서 제가 읽기 쉬운 코드였던 것 같습니다.
말씀 주신것처럼 굳이 변수로 받지 않고 파라미터값으로 넣어도 됐을 것 같은데
바로 넣는 방법이 좀 더 좋은 방법이라면 앞으로는 코드 짤때 더 신경써서 불필요한 변수 선언을 하지 않도록 생각해야 할 것 같습니다.

2023-11-22 20:38 UTC, tawans commented
메모리가 늘어나요.
코드를 다운받아서 돌려보니, 간단한 코드임에도, 가위 바위 보를 할 수록 계속 메모리가 늘어나더라구요.
왜 그럴까요? 생각해보시고, 답글로 알려주세요!
---
위 코멘트 주신 부분 관련해서 왜 늘어날까 하고 찾아보고 고민해봤는데 아직 답을 찾지는 못했습니다.
의심가는 상황으로 while 반복문에서 계속 반복 하면서 뭔가 메모리에서 해제되지않고 
계속 쌓이는 걸까하는 의심이 되는데 아직 찾아내지는 못했습니다.
관련해서 힌트나 참고할 만한 내용이 있다면 알려주시면 감사하겠습니다! :D

2023-11-23 07:44 UTC, cherrishRed commented on RockPaperScissors/.DS_Store
.gitignore 활용 너무 좋습니다!

2023-11-23 07:45 UTC, cherrishRed commented on RockPaperScissors/RockPaperScissors/main.swift
> +enum Result: String {
`GameResult` 너무 좋습니다!

2023-11-23 07:45 UTC, cherrishRed commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
옵셔널 활용하신 부분 너무 좋았습니다!

2023-11-23 07:49 UTC, cherrishRed commented on RockPaperScissors/RockPaperScissors/main.swift
> +        let result = playGame(player: playerChoice, computer: computerChoice)
가독성이 좋다고 생각하시면, 변수로 두셔도 상관 없습니다!
그냥 이유가 궁금해서 여쭤 봤을 뿐입니다ㅎㅎ

2023-11-23 07:50 UTC, cherrishRed commented on RockPaperScissors/RockPaperScissors/main.swift
> +        let playerChoice = Choice.allCases[playerChoiceInt - 1]
enum 과  switch 문의 조화 너무 보기 좋습니다!

2023-11-23 07:54 UTC, cherrishRed approved these changes
밤새 리펙토링 하시느라 수고하셨습니다!

메모리에 관한 이야기는, 지금 당장 해결할 필요는 없구요 프로젝트가 아직 남았으니 기간 동안 생각해보시면 좋을 것 같습니다. 

`call stack`, `재귀` 로 검색하시면 실마리를 찾으실 수 있으실 거예요!

Approve 드립니다👍

2023-11-29 04:17 UTC, merged