묵찌빠 프로그램 [Step 1] Paul, Hong
tasty-code/ios-rock-scissor-paper pull request #35
Opened 2023-11-22 08:23 UTC by ujhong7

안녕하세요 코든! 묵찌빠 프로젝트 Step1의 PR입니다.

코드의 구조에 대한 간략한 구현은 readme에 작성해 두었습니다: https://github.com/earths-voluble/ios-rock-scissor-paper/blob/8ee0a532cbc97b1a382601c0241ea50c39bf7857/README.md

강제 언래핑을 할 수 없기 때문에 optional이 최소화되는 방향을 생각했습니다.

전체적인 기능 구현 완료 후 handleSelection함수가 필요없는게 아닌가 하는 의문에 commit 93eb176에서 한 차례 리팩토링을 거쳤습니다.

handleSelection 함수는 걷어냈지만, 대신 runningGame함수의 복잡도가 다소 늘어나고 형변환으로 인해 가독성이 저하된 것 같은데, 이 부분에 대한 의견이 어떠신지 궁금합니다.

readme문서에 부족한 점은 없는지, 보완할 점이 있을지도 궁금합니다.

2023-11-22 16:24 UTC, ictechgy requested changes
안녕하세요 @ujhong7 , @earths-voluble !     
STEP1 진행하시느라 정말 고생 많으셨습니다!🥳 벌써 Readme도 작성해보시다니 멋있네요! 👍   
   
제가 지금부터 드리는 피드백은 제 의견이 많이 들어가있습니다. 때문에 정답이 아닙니다!   
참고용으로 읽어보시면 좋을 것 같아요~   

---
## exit()에 대하여
exit을 이용하여 프로그램이 종료되도록 구현해주셨는데요!   
[애플에서는 앱의 강제적인 종료는 지양하도록 안내](https://developer.apple.com/library/archive/qa/qa1561/_index.html#//apple_ref/doc/uid/DTS40007952)하고 있습니다.   
프로그램 종료에 대해 exit이 아닌 다른 형태로 구현해보면 어떨까요? 

<br/>

## Readme에 대해서
고민의 과정과 flow 설명을 자세히 잘해주셔서 너무 좋았는데요! 그림적인 자료와 제목/내용간 구분이 조금 더 잘 되면 좋을 것 같습니다!      
(급한건 아니니까 시간 여유가 있으면 진행 부탁드려요!)

<br/>

## handleSelection에 대하여
Readme를 보면 handleSelection이 불필요해보여서 제거하였다고 하셨는데 어떠한 점때문에 불필요하다고 느끼신건가요? 그 이유를 더 자세히 말씀해주시면 제가 더 자세한 피드백을 드릴 수 있을 것 같습니다.       
그리고 함수가 많아지지만 가독성이 높아지는 것과 / 함수는 적어지지만 복잡해지는 것 두 선택의 장단점은 어떤게 있을까요? 두 분의 의견을 한번 들어보고 싶네요!

<br/>

## 그외
커밋 메시지를 보았는데요! 이모지를 쓰신점 너무 좋습니다! 어떠한 점 때문에 이모지를 쓰신건가요? 궁금하네요 ㅎㅎ   
더불어 저의 경우에는 이모지와 함께 commit type을 작성해주는데요! 요 점은 그냥 참고용으로만 봐주시면 좋을 것 같습니다~
ex) `[♻️ refactor] 사용자 입력 함수 시간복잡도 개선`

2023-11-22 16:24 UTC, ictechgy commented on .DS_Store
PR을 올리기 전까지는 이 파일이 같이 딸려들어왔다는 것을 알기 어려웠을 것 같은데요!   

이 파일이 무엇인지, 그리고 꼭 PR에 포함되어야 하는 내용일지 한번 찾아보시면 좋을 것 같습니다!

2023-11-22 16:24 UTC, ictechgy commented on README.md
> +### 3조 묵찌빠 프로젝트 저장소
크으! 벌써 Readme를 작성하시다니 대단한데요?! 👍👍   
매주 금요일마다 Readme 데이가 있으니 지금 완벽하게 모든것을 풀어내려 하진 않으셔도 될 것 같아요~!

지금은 큰 틀에서 어떠한 점이 수정되면 좋을지 말씀드려볼게요!

2023-11-22 16:24 UTC, ictechgy commented on README.md
> +#### Step 1 가위, 바위, 보 게임 구현 (23.11.20 ~ 23.11.22)
Step에 대한 제목과 하단 내용의 폰트 크기가 동일해서 구분하기가 쉽지 않은데요   
크기를 다르게 가져가보시면 좋을 것 같습니다!

2023-11-22 16:24 UTC, ictechgy commented on README.md
> +
어떻게 이러한 코드를 짜게 됐는지, 어떠한 고민을 가지고 계셨는지 아래에 잘 설명해주신 것 같아요!   

실행화면이나 순서도(flow chart)도 만들어서 넣어주시면 더 잘 이해가 될 것 같습니다. (순서도는 나중에 여유가 생기시면 도전해보는 걸로 해요. 스텝 진행이 먼저니까요!)

2023-11-22 16:24 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +enum Selection: String {
열거형으로 사용자 입력을 구분해주신점 너무 좋습니다! 😆     

다만 `Selection`이라는 네이밍은 조금 더 고민해보면 좋을 것 같아요~   
단순히 선택이라고 하기보다 조금 더 구체적으로 지어보면 어떨까요?

2023-11-22 16:24 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +func runningGame(_ myChoice: Selection) {
running이라는 네이밍은 명사적인 의미로 더 다가오는데요!    
이렇게 이름 지어주신 이유가 무엇인가요??

2023-11-22 16:24 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +while true {
while 반복문을 사용해주셨군요!      
for문 또는 재귀함수를 써볼 수도 있을 것 같은데 while을 쓰신 특별한 이유가 있을까요?    

그리고 세가지(while, for, 재귀) 반복 구현방식의 차이는 무엇일까요?

2023-11-22 16:24 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +        exit(0)
`exit()`말고 프로그램을 종료시키는 다른 방법은 없을까요??

2023-11-22 16:24 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +       let select = Selection(rawValue: input) {
if let 바인딩을 써서 깔끔하게 처리하셨네요! 😄    
다른 옵셔널 바인딩 방식이 아닌, if let을 쓰신 이유가 있을까요?

2023-11-24 07:25 UTC, earths-voluble commented on .DS_Store
gitignore의 필요성과 사용방법에 대해 알아보고, 적용해 보았습니다. 다만 DS_Store파일 자체는 삭제하고 푸시한 것 같은데 리포지토리에서는 내용만 비어있는 채로 사라지지 않는 이유는 아직 잘 모르겠습니다.

2023-11-24 07:25 UTC, earths-voluble commented on README.md
> +
순서도는 작성방법을 익혀서 리드미 보강과 함께 프로젝트 마무리 전까지는 추가해보도록 하겠습니다!

2023-11-24 07:27 UTC, ujhong7 commented on RockPaperScissors/RockPaperScissors/main.swift
> +enum Selection: String {
주석 없이 변수의 이름만 가지고도 그 의미를 완벽히 이해할수있도록 만들어야하기 때문에 좀 더 구체적인 변수명이 필요하다는걸 깨달았습니다.

2023-11-24 07:28 UTC, ujhong7 commented on RockPaperScissors/RockPaperScissors/main.swift
> +func runningGame(_ myChoice: Selection) {
홍: 변수명을 작성할 때 명사, 동사적 의미를 생각해보지는 못했습니다. 메서드는 명사보다는 동사적 표현이 더 어울리는 표현일까요? 

폴: 네이밍에 대해 리뷰해주신 부분은 runningGame은 RockScissorsPaperGame으로, Selection은 RockScissorsPaper로 비교적 직관적인 이름으로 바꾸었습니다. Step2에서는 묵찌빠 게임으로 함수가 추가될 수 있기 때문에 확실히 구별되는 네이밍이 좋을 것 같다고 생각했습니다.

2023-11-24 07:28 UTC, ujhong7 commented on RockPaperScissors/RockPaperScissors/main.swift
> +while true {
홍: 재귀함수에 대해서는 알지 못했고 종료 입력을 받기 전까지는 계속해서 프로그램이 실행되어야 하기 때문에 조건이 참인 동안 무한히 반복되는 while문을 선택하였습니다.

폴: 홍이 정리해둔 while 문과 for문의 용법을 봤을 때, 몇 번 반복될지 모르는 이번 프로젝트의 특성상 for보다는 while이 적절했다고 생각합니다. 재귀함수에 대해서는 아직 생각해보지 못했습니다.

2023-11-24 07:28 UTC, ujhong7 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        exit(0)
exit함수는 들어내고, while문을 빠져나가는 방식으로 프로그램이 종료되도록 하였습니다.

2023-11-24 07:30 UTC, ujhong7 commented on RockPaperScissors/RockPaperScissors/main.swift
> +       let select = Selection(rawValue: input) {
홍: if let과 guard let바인딩의 차이를 인지하지 못하고 그냥 if let을 사용했습니다. 검색해보니 'if let은 특정 블록 내에서만 변수를 사용하고자 할 때 유용하고 guard let은 일반적으로 함수나 메서드의 시작 부분에서 조건을 검사하고 빠르게 종료할 때 사용됩니다.' 라고 찾아볼수있었습니다. 작성한 코드에서는 guard let 으로 수정하는 것이 더 적절할 것 같다고 생각하는데… 어떤 코드가 더 적절한 코드인가요?

폴: 여러가지 언래핑 방법이 있지만, 강제 추출을 제외하고는 if let이 가장 보편적이고 간편하기도 하고, 저희의 메인 로직 코드가 함수가 아니라 guard let은 사용하지 않았던 것 같습니다.

2023-11-24 07:48 UTC, earths-voluble commented
`handleSelection`에 대해서는, 최대한 간결하고 가독성 좋은 코드를 추구하는 맥락에서 이 열거형을 삭제하더라도 기존의 함수에 몇가지 로직을 추가하면 대체할 수 있기 때문에 삭제해도 좋지 않을까 생각했습니다. 하지만 다른 팀원들의 다양한 구현방법과 결과물을 보니, 꼭 간결하기만 할 필요는 없겠다는 생각을 했습니다. 클래스나 구조체를 활용해서 좀 더 많은 코드를 사용하더라도 확장성 있으면서도 책임이 분리되어 유지보수가 편리한, 객체지향에 부합하는 코드를 작성해보고 싶어 조금씩 구현해보는 중입니다.

커밋 메시지의 이모지는 사전과제를 하면서 알게 된 `gitmoji`라는 툴을 사용했는데, 컨벤션을 미리 정해놓는다면 텍스트만 사용하는 것 보다는 한눈에 들어올 수 있겠다고 생각해서 적용해 보았습니다. 다만 말씀하신 대로 텍스트도 병기하는게 다른 사람들이 보기에 혼란스럽지 않겠다는 생각이 들어 병기하도록 컨벤션을 수정했습니다.

2023-11-26 15:53 UTC, ictechgy commented on .DS_Store
혹시 gitignore에 추가한 뒤 삭제/푸시를 하셨나요 아니면 삭제/푸시를 먼저 하고 gitignore에 추가하셨나요?? 

템플릿의 경우에는 https://www.toptal.com/developers/gitignore 요런 곳도 있다는 것 참고해보시면 좋을 것 같습니다!

2023-11-26 15:54 UTC, ictechgy commented on README.md
> +
넵~ 천천히 해보세요!!

2023-11-26 15:57 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +enum Selection: String {
타입명을 말씀하신거겠죠?? ㅎㅎ   

변경된 이름이 `RockScissorsPaper`인 것을 봤는데요! 너무 잘 지어주신 것 같습니다! 👍😆

2023-11-26 16:15 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +func runningGame(_ myChoice: Selection) {
메서드가 꼭 동사일 필요는 없습니다! [API Guidelines](https://www.swift.org/documentation/api-design-guidelines/)에도 side effect와 관련하여 설명을 할 뿐 '꼭 어떠해야 한다'라고 말하고 있지는 않습니다.       
다만, runGame과 같이 동사적 이름으로 되어있다면 호출자 입장에서 '아 게임을 시작(run)하는구나' 더 직관적으로 받아들일 수 있지 않을까 해서 말씀드린 거였습니다.   
이 부분은 제 개인적인 입장이기 때문에 그냥 참고만 해주셔요~~!

2023-11-26 16:16 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +func runningGame(_ myChoice: Selection) {
RockScissorsPaperGame, RockScissorsPaper
-> 게임 함수도, 열거형도 더 직관적인 이름을 가지게 된 것 같네요! 👍👍

2023-11-26 16:16 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +func runningGame(_ myChoice: Selection) {
Step 2에 대한 확장성도 고려하신점 좋습니다!!

2023-11-26 16:20 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +while true {
ㅎㅎ 타당한 선택을 하신 것 같군요! 좋습니다!! 😎👍

재귀함수도 정말 중요한 개념중에 하나인데요! 구글이나 유튜브에서 간단한 개념정도라도 학습해보시길 추천드려요!
(당장 공부하고 바로 적용해보실 필요는 없습니다! 프로젝트 진행에 여유가 되신다면 공부해보세요)

2023-11-26 16:22 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +        exit(0)
좋습니다. 한번 확인해볼게요!

2023-11-26 16:36 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +       let select = Selection(rawValue: input) {
- 홍은 현재 코드의 어떠한 부분때문에 `guard let`이 더 적절해보인다고 생각하신건가요? 그 이유에 대해 말씀해주신다면 저도 제 의견을 더 잘 이야기 해볼 수 있을 것 같습니다!
- 어떤 점에서 if let이 더 보편적이라고 생각하신 건지 궁금합니다 폴!

2023-11-26 17:31 UTC, ictechgy commented on .gitignore
> +.DS_Store
gitignore를 추가하셨군요. 좋습니다~~! 👍
gitignore 사용 방법에 대해서도 따로 공부해보시면 좋을 것 같아요! (파일 및 디렉토리 추가 또는 제외하기 등)

2023-11-26 17:31 UTC, ictechgy commented on README.md
> +- 동대문 1기 🤖 홍, 📸 폴
제가 이전에 말씀 안드렸던 부분이 있는데요!    
참가자 닉네임에 각자의 github 링크를 연계해두면 더 좋을 것 같아요!

2023-11-26 17:31 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
>  import Foundation
여기서 하나만 짚고 넘어가자면, Foundation은 왜 import 되어있을까요? 꼭 import 해야하는걸까요?

2023-11-26 17:31 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +enum RockScissorsPaper: String {
직관적인 네이밍 좋습니다!!

2023-11-26 17:31 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +func RockScissorsPaperGame(_ myChoice: RockScissorsPaper) -> Bool {
직관적인 네이밍 좋습니다! 다만 함수가 Bool값을 반환하게 되었는데 이 부분은 [여기](https://www.swift.org/documentation/api-design-guidelines/#strive-for-fluent-usage:~:text=Uses%20of%20Boolean%20methods%20and%20properties%20should%20read%20as%20assertions%20about%20the%20receiver%20when%20the%20use%20is%20nonmutating%2C%20e.g.%20x.isEmpty%2C%20line1.intersects(line2).)를 한번 참고해보시면 좋을 것 같아요!

2023-11-26 17:31 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +while true {
이 while 구문은 전역적으로 선언되어있다고 볼 수 있을 것 같은데요! 꼭 전역에 두어야 할지 한번 고민해보시면 좋을 것 같습니다

2023-11-26 17:31 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let myChoice = Int(myChoice.rawValue)
내 선택을 rawValue로 뽑아낼 수도 있지만 다른 이름으로 뽑아내보면 어떨까요? 아래 내용을 참고해보시면 좋을 것 같습니다
- [Computed Property](https://www.swift.org/documentation/api-design-guidelines/#strive-for-fluent-usage:~:text=Uses%20of%20Boolean%20methods%20and%20properties%20should%20read%20as%20assertions%20about%20the%20receiver%20when%20the%20use%20is%20nonmutating%2C%20e.g.%20x.isEmpty%2C%20line1.intersects(line2).)
- [CustomStringConvertible](https://developer.apple.com/documentation/swift/customstringconvertible)

2023-11-26 17:31 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let comChoice = Int.random(in: 1...3)
`comChoice`라고 줄여서 이름 붙이신 특별한 이유가 있을까요??

2023-11-26 17:31 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +    return false
요구사항에 맞춰 동작을 잘 설계해주셨어요!! 👍👍😆

2023-11-26 17:31 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +            break
break 구문 들여쓰기에 대해서는 한번 고민해보시면 좋을 것 같습니다!    
(이 부분은 제약사항에서 요구하고 있는 것 중 하나라 꼭 확인해주셨으면 해요)

2023-11-26 17:33 UTC, ictechgy commented
## 말씀해주신 handleSelection과 관련하여
- 저도 동일한 생각입니다! 기능이 분리되어 확장성이 용이한 구조라면 코드가 조금 길어지더라도 괜찮지 않을까요? 

## commit 로그
- gitemoji에 commit type을 추가해주신 점 너무 좋습니다! 커밋 메시지를 이해하기가 더 쉬워진 것 같아요~!! 🙌

## 한가지 더 확인해주세요!
- 타겟 브랜치가 잘 설정되어있는지 확인 부탁드립니다!

2023-11-26 17:45 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +    if let input = readLine(),
실행을 해보면 숫자 입력을 받는 문구와 입력한 숫자 위치가 요구사항 명세와는 다른데요! 이 부분도 같이 맞춰주시면 좋을 것 같아요!

2023-11-26 17:51 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +    return false
다만 true / false를 반환하는 위치가 제각기 다른데 이렇게 만들어두신 이유가 있을까요??

2023-11-29 16:07 UTC, ictechgy commented
@ujhong7 , @earths-voluble  안녕하세요!  말씀드릴 사항이 두가지정도 있습니다!

---

### 첫번째는 target branch인데요! 
pr의 맨 위를 살펴보시면 아래와 같은 부분을 확인하실 수 있습니다. 
<img width="627" alt="image" src="https://github.com/tasty-code/ios-rock-scissor-paper/assets/39452092/017f7173-34a3-44ad-bbf9-f3da03aa9217">

여기서 두 분이 작업해주신 브랜치가 `earths-voluble:main`이고 해당 코드가 병합되고자 하는 목적지 브랜치가 `tasty-code:main`인데요
(내가 작업한 내용을 어떤 브랜치(가지)로 반영시킬 것인가를 선택하는 부분입니다)   
➡️ 목적지(타겟) 브랜치는 `d_paul` 또는 `d_hong`과 같이 `d_`로 시작하는 브랜치로 설정해주셔야 합니다!


<br/>

### 두번째는 STEP에 대한 내용입니다.
현재 PR은 STEP1에 대한 PR이고 따라서 STEP1의 내용만 포함해주셔야 합니다! 최근 작업해주신 내용을 보면 STEP2(묵찌빠)에 대한 내용으로 바꾸고 계신게 보이는데요~

<img width="578" alt="image" src="https://github.com/tasty-code/ios-rock-scissor-paper/assets/39452092/98468e39-36d3-4983-a484-4a445ca8600b">   

프로젝트 명세에서는 이전 STEP이 병합된 뒤 다음 STEP을 진행하기로 되어있습니다. 이 부분은 꼭 지켜주셔야 하는 부분입니다. 
(스텝진행이 합쳐져 있으면 안됩니다🥲 )

우선은 타겟 브랜치만 변경해주시면 병합 approve로 진행하도록 하겠습니다. 
STEP2는 그대로 진행해주시고 추후 프로젝트 하실 때에는 꼭 지켜주셨으면 좋겠습니다!    
(명세서 및 요구사항들을 꼼꼼히 읽는 것 정말 중요합니다..! 항상 확인 부탁드릴게요!)

혹시나 이해가 잘 안되거나 어려운 부분 있으면 꼭 DM 주세요!! 😊

2023-11-30 01:01 UTC, earths-voluble commented
확인하고 타겟 브랜치 변경했습니다! 명세를 제대로 체크하지 못해서 이슈가 많았네요 ㅜㅜ 죄송합니다🙇
Step2 계속 진행해보도록 하겠습니다!

2023-11-30 17:57 UTC, ictechgy commented
고생하셨습니다~

2023-11-30 17:57 UTC, merged