[STEP 1] Poodle, CU
tasty-code/ios-rock-scissor-paper pull request #4
Opened 2022-08-17 02:35 UTC by parkseyoon

@Tacocat-tastycode 코드리뷰 부탁드립니다 :)

# 작업내용
- 메뉴 출력 함수 구현
- 사용자 입력 함수 구현
- 사용자 입력값 유효성 검사 함수
- 승패 비교 함수 구현

# 코드를 작성할 때 고민되었던 점
사용자 숫자를 입력받는 함수 `getUserNumber`의 입력 부분에서 옵셔널 처리에 대해 굉장히 많이 고민했고, `guard let`을 사용하려 했으나 아직 미숙한 점이 있어 사용하지 못하고 `if let`과 `??` 를 섞어 처리하게 되었는데 과연 이게 최선이었을지 생각을 많이 하게 되는 부분이었습니다.

2022-08-17 06:48 UTC, jaemuYeo requested changes
페어프로그래밍을 통해 첫 PR보내느라 고생많았어요 👏
다만 벌갈아가며 커밋을 진행하지 않은 것은 아쉽게 느껴집니다!!
프로젝트의 제약사항을 보며 다음번에는 한 번 시도해보세요😀

guard let에 대한 내용은 if let과의 차이점이 무엇인지 각각의 특징은 무엇인지
조사해보면 어느 경우에 사용할지 감이 잡힐거예요!!
아쉬운 부분은 지금 처럼 guard let에 대해 몰랐다면 현재 코드가 최선의 방법이었겠지만
몰랐던 부분에 대해 학습하고 적용해보고나서 최선의 코드를 작성했다면 어땠을까요??

여기서 말씀드리고 싶은 것은 PR이 우선이 아니라는 것을 말씀드리고싶어요!!
PR을 보내기 전에는 최대한 많은 시도를 해보고나서 결과물을 테스트 후에
신중히 보내는 쪽으로 진행하면 좋을 것 같습니다 🙏
이 곳에서 실수도 많이해보고 학습과 질문도 많이 하면 물론 너무너무 좋지만
간단한 토이프로젝트라 할지라도 '내가 프로젝트 요구사항에 대해 얼마나 충족했는가'에 대해
많은 고민을 해보았으면 좋겠습니다 😉

## 실행 결과
실행 예시와 다른 부분을 몇 곳 발견했습니다!!
1. 승패에 대한 출력 후 결과
2. 사용자가 가위를 냈을때

2022-08-17 06:48 UTC, jaemuYeo commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +func printMenu() {
메뉴를 출력하는 곳에서 많은 일들이 일어나고 있군요!
1. 메뉴 출력
2. 사용자 숫자 입력
3. 숫자 유효성 검사
4. 컴퓨터 숫자 생성
5. 컴퓨터 유저 숫자 비교

함수 하나당 하나의 기능만 가질 수 있도록 분리해 볼 수 있을까요?

2022-08-17 06:48 UTC, jaemuYeo commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +    let computerNumber: Int = Int.random(in: 1...3)
1 2 3이라는 숫자는 무엇을 의미하나요??
코드만 보았을 때는 1 2 3 이라는 모호한 숫자가 무엇을 의미하는지 전혀 모르겠어요
`매직 넘버`라는 개념에 대해 알아보고 어떻게 하면 매직넘버를 처리할 수 있을지 적용해보아요!!
아래에도 몇 몇 매직넘버가 보입니다 😀

2022-08-17 06:48 UTC, jaemuYeo commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +    print()
개행 처리에 대해 이 방법말고 조금 더 명확한 방법을 찾아보세요 😀

2022-08-17 06:48 UTC, jaemuYeo commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +    if let userNumber: Int = Int(readLine() ?? "") {
한 번의 바인딩으로 여러개를 처리 할 수도 있답니다!
```swift
if let input = readLine(), let userNumber = Int(input) {
        
}
```

2022-08-17 06:48 UTC, jaemuYeo commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +func isValidNumber(userNumber: Int) -> Bool {
유효성 검사를 switch-case를 통해 멋지게 해주었군요! 좋아요 👍

2022-08-17 06:48 UTC, jaemuYeo commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +        print("잘못된 입력입니다. 다시 시도해주세요.\n")
이 출력도 어떻게 보면 하나의 기능분리를 할 수 있지 않을까요? printMenu처럼요!

2022-08-17 06:48 UTC, jaemuYeo commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +    if (computerNumber == 1 && userNumber == 3) || userNumber < computerNumber {
승패 결과가 달라요!! 어디가 잘 못되었을까요??
현재 논리, 비교 연산자를 활용해서 표현해주었는데 가독성이 좋지 않은 것같습니다!
여러 `케이스`를 통해 표현할 수 있는 방법은 없을까요?

2022-08-18 03:25 UTC, Schro2109 commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +func printMenu() {
현재 각 함수에서 목적에 따라 하나의 기능만 담당하도록 수정 후 게임을 시작하는 함수를 따로 만들어 구현하고 있습니다!

2022-08-18 03:27 UTC, Schro2109 commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +    print()
print() 를 사용해 빈 줄을 넣는 방식 대신 결과 출력 함수에서 결과 문자열 뒤에 \n 을 붙이는 방식으로 변경해보았습니다!

2022-08-18 03:27 UTC, Schro2109 commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +func isValidNumber(userNumber: Int) -> Bool {
감사합니다!

2022-08-18 03:28 UTC, parkseyoon commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +    let computerNumber: Int = Int.random(in: 1...3)
코드를 짜는 입장에서는 매직 넘버가 무엇을 뜻하는지 보이는데 코드를 읽는 입장에서는 매직 넘버의 의미가 잘 전달되지 않는 것 같아요. 😅
이런 세세한 차이 하나하나가 코드를 읽을 때 확연히 보이네요. 😮
상수를 이용하여 매직 넘버를 제거하니 보다 확실히 코드가 눈에 쏙쏙 들어옵니다. 😆

2022-08-18 03:29 UTC, Schro2109 commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +    if (computerNumber == 1 && userNumber == 3) || userNumber < computerNumber {
기존의 if문을 지우고 컴퓨터와 유저의 숫자를 딕셔너리로 저장한 후 switch case 문을 통해 이긴 경우, 진 경우, default(비긴 경우) 로 승패를 표현하도록 수정해보았습니다!

2022-08-18 03:29 UTC, parkseyoon commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +    if let userNumber: Int = Int(readLine() ?? "") {
저런 방법이 있는지 알 수 있는 계기가 되어서 너무 좋습니다. 감사합니다 :)

2022-08-18 03:30 UTC, parkseyoon commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +        print("잘못된 입력입니다. 다시 시도해주세요.\n")
맞아요..! 거기 까지 생각하지 못했는데 함수로 구현하는 편이 좋을 것 같아요~~

2022-08-19 05:11 UTC, jaemuYeo requested changes
코멘트 반영하느라 고생많았어요 👏
이전 코드보다 많이 개선되었고 고민한게 보입니다!!
다만 아직 아쉬운 부분이 남아 몇 가지만 더 코멘트 남기게 되었어요~
그리고 실행예시와 다르다고 전에 말했던 부분중
`승패에 대한 출력 후 결과`가 있었는데 프로젝트 요구사항중에서는
비겼을때 이외에는 게임이 종료되어야 합니다 😀

2022-08-19 05:11 UTC, jaemuYeo commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +let cardNumbersRange = 1...3
특정값들을 이렇게 담아서 사용하는 것은 매우 좋습니다!!
다만 제가 의도했던 것과 많이 달라요 🤔
`매직넘버`가 무엇인지 어떻게 개선할 수 있을지 알아보았나요??
1 2 3 각각의 의미를 담는 코드가 되었으면 좋겠습니다!

2022-08-19 05:11 UTC, jaemuYeo commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +func printMenu() {
이전보다 이 함수의 기능이 확실해졌네요!! 아주 좋아요 👍

2022-08-19 05:11 UTC, jaemuYeo commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +   }
여기 띄어쓰기 실수가 있군요! ㅎㅎ

2022-08-19 05:11 UTC, jaemuYeo commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +    return -1
return 값인 -1은 무엇을 의미하나요??

2022-08-19 05:11 UTC, jaemuYeo commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +func judgeNumber(computerNumber: Int, userNumber: Int) -> Void {
함수의 본 네이밍과 매개변수의 네이밍이 중복되는 것은 그렇게 좋지는 않은 방법입니다!
한 문장처럼 읽히는게 가장 베스트라고 생각해요!
`컴퓨터와 유저의 숫자를 판단하다` 처럼 말이죠!
Void는 생략해도 될것같아요 ㅎㅎ

2022-08-19 05:11 UTC, jaemuYeo commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +    case [1: 2], [2: 3], [3: 1]:
이곳에서도 무엇을 의미하는지 모를 숫자들이 난발하고 있군요!! ㅎㅎ
저번부터 계속 매직넘버를 강요하는 이유는 무엇일까요??
게임의 룰에 대해 또는 작성자 이외의 다른 개발자가 이 코드를 보면 어떤 생각이 들까요?

2022-08-19 06:39 UTC, parkseyoon commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +func printMenu() {
함수에 기능에 따라 네이밍과 기능수행... 아직 어렵지만 열심히 해보겠습니다...!

2022-08-19 07:00 UTC, Schro2109 commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +let cardNumbersRange = 1...3
확실히 의미가 부여되지 않아서 보기 힘들겠네요..
지금은 해결을 위해서 열거형, 딕셔너리 등을 시도해보고 있습니다!

2022-08-19 07:01 UTC, Schro2109 commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +   }
저런 곳에 실수를 했다니.. 앞으론 더 꼼꼼하게 확인해보겠습니다!

2022-08-19 07:06 UTC, Schro2109 commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +    return -1
if let으로 옵셔널 처리 후 정상적인 입력값 반환을 30번줄에서 담당하고
33번줄의 return -1 값은 위 조건을 만족하지 못한 nil값이 들어왔을 시 -1로 대체하여 오류를 표현하는 식입니다!

하지만 다시 생각해보니 guard let을 사용한다면 더 의미가 확실해질 것 같아 수정해보도록 하겠습니다!

2022-08-19 07:09 UTC, Schro2109 commented on rock-scissor-paper/rock-scissor-paper/main.swift
> +    case [1: 2], [2: 3], [3: 1]:
값을 어떻게 가공하고 처리해야 할 지 생각하지 못해 매직넘버를 사용하게 된 것 같습니다..
하지만 이번에 배운 열거형이나 딕셔너리 등을 사용해서 rock, scissor, paper로 표현할 수 있도록 노력해보겠습니다!

2022-09-08 05:20 UTC, closed without merging