묵찌빠 프로그램 [STEP 1] 이안,엘
tasty-code/ios-rock-scissor-paper pull request #42
Opened 2023-11-23 04:03 UTC by rlwhs12

@GREENOVER
안녕하세요 이안,엘 입니다. 
첫 PR보내드립니다. 잘부탁드립니다.

<h1>구현한 이유</h1>

<h3> enum을 사용한 이유 </h3>

- 사용할 수 있는 값이 정해져 있는 경우에 enum을 사용하면 좋다고 배웠습니다. 가위,바위,보 같은 경우는 값이 3가지 경우가 정해져 있어서 적용해봤습니다.
- 유저가 입력한 값과 컴퓨터가 랜덤으로 뽑아내는 값이 숫자이기 때문에 열거형의 원시값을 이용해서 해당 케이스의 rawValue값을 뽑고  switch문에서 분기처리를 하기 위해 사용했습니다.

```swift
enum RpsCase: Int{
    case scissors = 1
    case rock
    case paper
}
``` 

<h3> while문을 사용한 이유 </h3>

- 사용자의 입력값을 대기하기위해서 while문을 사용하였습니다.
- 재귀함수로 반복할수있지만 스택오버플로우 현상이 일어날수도 있어서 최대한 사용을 지양했습니다.

```swift
while keep {
    userInput()
}
``` 

<h3> 짧은코드지만 함수로  처리한 이유</h3>

- 반복되는 코드는 재사용성이나 유지보수를 편하게 하기위해서 함수로 처리하였습니다.
```swift
func rpsMenu() {
    print("가위(1), 바위(2) 보(3)! <종료: 0>")
}

func comRandomInput() -> Int{
    return Int.random(in: 1 ... 3)
}
``` 

<h3> Switch문을 사용한 이유</h3>

- 코드의 가독성 높이기 위해 사용하였습니다. 스위치문과 튜플을 사용했습니다.

```swift
func compareRps(user: RpsCase, com: RpsCase) {
    switch (user, com) {
    case (.scissors, .paper), (.rock, .scissors), (.paper, .rock):
        print("이겼습니다.")
        print("게임 종료")
        keep = false
    case (.paper, .scissors), (.scissors, .rock), (.rock, .paper):
        print("졌습니다.")
        print("게임 종료")
        keep = false
    default:
        print("비겼습니다.")
        rpsMenu()
    }
}
``` 

<h3> userInput 함수</h3>

- !를 사용해 강제로 unwrapping 한 이유는 위쪽에서 이미 nil값 확인 , Int값을 확인하기 때문에 사용하였습니다.

```swift
func userInput(){
    let randomValue = comRandomInput()
    guard let inputvalue = readLine() else { return }
    if let num = Int(inputvalue) , num >= 1 && num <= 3 {
        compareRps(user: RpsCase(rawValue:num)!, com: RpsCase(rawValue:randomValue)!)
    } else if let num = Int(inputvalue) , num == 0 {
    } else {
        print("잘못된 입력입니다. 다시 시도해주세요.")
        userInput()
    }
}
``` 

<h1>진행하면서 궁금했던 부분</h1>

- 저는 코드가 짧고 가독성이 좋은 코드를 선호합니다.  그래서 코드를 if문 보다는 함수로 빼주고  guard문으로 처리하는 경우가 많은데  이게 좋은 코드인지 궁금합니다!

- 코드에는 정답이 없지만 그린이 생각하는 좋은 코드는 무엇인지 궁금합니다!

- 옵셔널 바인딩 해제할때 if let과 guard let 중에 어느걸 선택해서 해야되는지가 궁금합니다.
둘중에 하나를 선택해서 하나만 사용해야되는지 아니면 , 둘다 사용한다면 어느기준을 두고 구분하는지 궁금합니다.
제가 if let과 guard let를 사용한 기준은 guard let은 else 에서 종료되는 경우(조기종료 성격이 강한 경우 와 종료)에 사용하였고 if let은 else 인 경우 다른 일을 해야될때 사용하였습니다. 

- 최근에 은닉화를 배웠는데 짧은 코드지만 지금부터 은닉화를 하는 연습을 하는게 좋은지 
아니면 나중에 해도상관없는지 궁금합니다. 은닉화를 하는 기준은 사용자가 접근하지 않으면 모두다 은닉화를 하면 좋은지도 궁금합니다.

2023-11-23 05:30 UTC, GREENOVER requested changes
@rlwhs12 @LeeSe0ngYe0n 
안녕하세요 이안, 엘! 
이번 묵찌빠 프로젝트 같이 진행하게된 그린입니다~!
처음 인사드립니다ㅎㅎ 2주간 잘부탁드려요!! 🙇🏻
우선 전체적인 로직이 아주 잘짜여지게 가위바위보 스텝1을 빠르게 구현하셨네요 👍
이에 조금 네이밍이나 로직적인 부분에서 디테일하게 한번 리뷰를 드려보겠습니다!
아! 제 리뷰는 답이 아닌 하나의 다양한 의견으로 받아들여주시면 좋을것 같아요.
즉, 모든 리뷰 코멘트에 대해 무조건 수정해야해!가 아닌 다시 한번 코드 작성하신걸 돌아보는 포인트로 보시고 의견이 다르거나 제가 잘못 이해하고 코멘트를 단 부분도 있을수 있기에 그럴때는 가감없이 말씀주세요 🙇🏻
***
### 칭찬 드리고 싶은 부분
- 메서드가 하나의 역할을 분리하여 잘 할 수 있도록 나눠진 점 💯
- 커밋 메시지를 잘 쪼개서 이력 관리 하신 점 💯
- 로직적으로 짜임새가 잘 구성되었네요! 💯
***
### 궁금하신 부분에 대한 저의 의견
- 저는 코드가 짧고 가독성이 좋은 코드를 선호합니다.  그래서 코드를 if문 보다는 함수로 빼주고 guard문으로 처리하는 경우가 많은데  이게 좋은 코드인지 궁금합니다!
  - 아마 아시겠지만 상황에 따라서 그 역할에 적절한 코드가 있어서 if문보다 항상 메서드로 빼주는것이 더 나은 코드다라고는 할 수없겠지만 현재 구현하신것을 보았을때 최대한 메서드를 분리하시고 switch, if let 구문도 적절히 사용하시는것을 보아 지향하시는 짧고 가독성 좋은 코드를 구현해주시고 계신것 같아 현 상황에서 가독성 좋고 적절한 코드라고 생각합니다 🙋🏻
- 코드에는 정답이 없지만 그린이 생각하는 좋은 코드는 무엇인지 궁금합니다!
  - 제가 생각할때 좋은 코드는 여러가지가 있겠지만 가장 1순위로 꼽는것은 우선 가독성이라고 생각해요ㅎㅎ
  코드도 글처럼 컨벤션과 적절한 네이밍과 잘 분리가 되어있다면 가독성이 높아질것이고 이는 추후 다른 개발자가 함께 하더라도 코드를 파악하는데 큰 어려움이 없을거에요.
  저는 이점을 가장 베스트로 뽑습니다!
  코드가 화려하고 어려운 로직을 짜는것이 좋은 코드는 아니라고 생각해요.
  개발자는 혼자가 아닌 협업을 해야하고 1인 개발을 하더라도 이 가독성을 신경쓰지 않는다면 본인이 짠 코드를 몇개월 후 볼때 전혀 감이 안올 수 있기에 가독성이 좋은 코드를 1순위로 생각합니다 🙋🏻
- 옵셔널 바인딩 해제할때 if let과 guard let 중에 어느걸 선택해서 해야되는지가 궁금합니다.
둘중에 하나를 선택해서 하나만 사용해야되는지 아니면 , 둘다 사용한다면 어느기준을 두고 구분하는지 궁금합니다.
제가 if let과 guard let를 사용한 기준은 guard let은 else 에서 종료되는 경우(조기종료 성격이 강한 경우 와 종료)에 사용하였고 if let은 else 인 경우 다른 일을 해야될때 사용하였습니다.
  - if let과 guard let 사용 구분은 상황에 따라 저는 명확히 다르게 사용하긴 합니다.
  예를들어 현재 userInput 메서드를 구현해주신곳에서 사용한 if let 상황처럼 해당 바인딩한 num이 해당 분기에서만 사용되지 않을 경우 if let을 이용하고 guard let은 알고 계신것처럼 함수의 빠른 탈출과 바인딩해서 가져온 값이 해당 메서드 내에서 다른 부분으로 변수처럼 사용될 경우 (조건 분기처리가 필요 없는 경우)에 주로 사용합니다 🙋🏻
- 최근에 은닉화를 배웠는데 짧은 코드지만 지금부터 은닉화를 하는 연습을 하는게 좋은지
아니면 나중에 해도상관없는지 궁금합니다. 은닉화를 하는 기준은 사용자가 접근하지 않으면 모두다 은닉화를 하면 좋은지도 궁금합니다.
  - 현재 코드부터 조금씩 연습을 해보시는것도 좋다고 생각해요ㅎㅎ
  네! 최대한 사용자와의 최 앞단에서가 아닌 부분들은 은닉화 해주시는것이 사이드이펙트를 방지할 수 있습니다 🙋🏻
***
### 보완되면 더 좋을 부분
- 리뷰 코멘트에 많이 남겼지만 전체적으로 네이밍에 대해 한번 더 명확한 네이밍을 생각해보시면 좋을것 같아요ㅎㅎ
네이밍이 무조건 짧다고 가독성이 좋은 코드가 아니기에 다른 사람이 전체적인 흐름없이 해당 코드 라인 한줄만 보아도 어떤 역할을 하는건지 어떤 값을 갖는건지 구체적이고 명확하게 알 수 있는 네이밍을 고민해보면 더 프로젝트가 보완될것 같습니다..!
- main 파일에서는 간단히 게임을 돌려주는것만 가져가고 나머지 코드들은 별도 파일로 분리하여 구조화를 해보면 어떨까요~?
예를들어, RpsCase나 rpsMenu부터 userInput 메서드까지는 사실 가위바위보를 위한 기능들이니 별도 파일로 분리해줘도 좋을것 같아서요~
왜냐하면 추후 바로 Step 2에서 묵찌빠 구현이 추가될것 같은데 모두 main에 들어있으면 파일 자체가 비대해지기에 미리 다이어트 시켜놓도록 구조를 가져가도 좋을것 같습니다 🙋🏻
***
다시 한번 스텝 1 고생 많으셨습니다!
우선 요구사항하고 한 부분이 맞지 않는것 같아서 (0 입력 시 게임종료가 기획 요구사항으로 제가 봤어가지구요!) 확인 부탁드려요ㅎㅎ
우선은 Request Changes로 드리고 언제든지 리팩토링 및 다시 재 리뷰를 원하시면 요청해주세요!

2023-11-23 05:30 UTC, GREENOVER commented on RockPaperScissors/RockPaperScissors/main.swift
> +enum RpsCase: Int{
Int와 { 사이 한칸 띄워주는건 어떨까요~? 🙋🏻

2023-11-23 05:30 UTC, GREENOVER commented on RockPaperScissors/RockPaperScissors/main.swift
> +func userInput(){
요 부분도 중괄호 앞 한칸 띄워주면 코드의 통일성이 높아질것 같습니다!

2023-11-23 05:30 UTC, GREENOVER commented on RockPaperScissors/RockPaperScissors/main.swift
> +    } else if let num = Int(inputvalue) , num == 0 {
현재 STEP 1 요구사항을 볼때 0이 들어오면 게임 종료되는것으로 기획 요구가 보이는데 구현과 다른것 같아 확인 부탁드립니다..! 🙋🏻

2023-11-23 05:30 UTC, GREENOVER commented on RockPaperScissors/RockPaperScissors/main.swift
> +var keep = true
어떤걸 keep하는건지 전체적인 맥락이 아닌 해당 변수의 네이밍만 보고는 유추하기가 힘든것 같아요 🥲
조금 더 명확한 네이밍을 가져가는건 어떨까요~?

2023-11-23 05:30 UTC, GREENOVER commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
실제 초기 게임을 시작하는 이 두 로직을 하나의 메서드로 만들면 더 가독성이 좋을것 같아보이는데 어떻게 생각하시나요!? 🤔

2023-11-23 05:30 UTC, GREENOVER commented on RockPaperScissors/RockPaperScissors/main.swift
> +func rpsMenu() {
메서드 네이밍만보면 rps메뉴를 어떻게 하는것인지 명확해보이지 않는데 조금 더 명확하게 네이밍을 해보면 어떨까요~?
현재는 메서드보다 프로퍼티의 네이밍 느낌이 강해서요 🥲
예를들어 displayRpsMenu 같이 해당 메서드의 행동 주체를 조금 더 확실히 나타내면 좋을것 같습니다!

2023-11-23 05:30 UTC, GREENOVER commented on RockPaperScissors/RockPaperScissors/main.swift
> +        print("게임 종료")
프린트 출력문으로 사용되는 String들을 네임스페이스로 관리하는것도 추후 유지보수에서 더 쉬운 방법일 수 있습니다 🙋🏻

2023-11-23 05:30 UTC, GREENOVER commented on RockPaperScissors/RockPaperScissors/main.swift
> +func comRandomInput() -> Int{
중괄호 앞 한칸 띄우면 좋을것 같아요..!

2023-11-23 05:30 UTC, GREENOVER commented on RockPaperScissors/RockPaperScissors/main.swift
> +
다른 메서드 사이는 개행이 한줄인데 여기만 두줄 개행하신 이유가 궁금합니다 🙋🏻

2023-11-23 05:30 UTC, GREENOVER commented on RockPaperScissors/RockPaperScissors/main.swift
> +func compareRps(user: RpsCase, com: RpsCase) {
해당 메서드는 private해도 되지 않을까요~?

2023-11-23 05:30 UTC, GREENOVER commented on RockPaperScissors/RockPaperScissors/main.swift
> +func comRandomInput() -> Int{
해당 메서드도 조금 더 메서드스러운 네이밍을 고민해봐도 좋을것 같아요..!
그리고 해당 메서드는 private 접근 레벨을 가져가도 되지 않을까요~? 🙋🏻

2023-11-23 05:30 UTC, GREENOVER commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let randomValue = comRandomInput()
컴퓨터의 랜덤 값이라는것을 인지할 수 있도록 조금 더 네이밍이 되면 좋을것 같아요..!

2023-11-23 05:30 UTC, GREENOVER commented on RockPaperScissors/RockPaperScissors/main.swift
> +    guard let inputvalue = readLine() else { return }
input과 value를 합한 워딩이니 카멜케이스를 따라 inputValue가 더 적절해보입니다 🙋🏻

2023-11-23 05:30 UTC, GREENOVER commented on RockPaperScissors/RockPaperScissors/main.swift
> +    if let num = Int(inputvalue) , num >= 1 && num <= 3 {
컴마(,)가 사이 앞뒤로 한칸씩 띄워져있는데 의도하신건가요~?
위 compareRps 메서드 내에서 , 사용하고 컨벤션이 다른것 같아요 🙋🏻
(아래 else if 구문도 동일)

2023-11-23 05:30 UTC, GREENOVER commented on RockPaperScissors/RockPaperScissors/main.swift
> +enum RpsCase: Int{
enum으로 사용하신거 아주 나이스합니다 👍

2023-11-23 07:27 UTC, LeeSe0ngYe0n commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
리팩토링을 하던 중 while문을 유저가 입력하는 함수 부분으로 넣어주다가 생각난 것인데 함수 내부에 반복문이 돌아가는 것과 반복문 안에서 함수가 돌아가게 하는 것의 메모리적으로 차이가 있는지 궁금합니다!

2023-11-23 08:01 UTC, GREENOVER commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
반복문 내 함수를 실행하면 반복문이 돌때마다 함수가 호출되기에 함수 호출 시 스택 메모리 공간에 실제적으로 할당되기에 호출 횟수만큼 메모리를 더 사용할것으로 예측되는데 이 부분은 한번 테스트 해보셔도 좋을것 같아요~!

2023-11-23 08:26 UTC, LeeSe0ngYe0n commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
넵 감사합니다!

2023-11-27 02:29 UTC, GREENOVER approved these changes
스텝 1 리팩토링 하시느라 고생 많으셨습니다!
훨씬 더 가독성이 좋고 코드별 분리가 잘 되었네요 👍
또한 동작도 요구사항과 정확히 일치하기에 이번 스텝은 여기서 충분히 잘 수행하셨다고 생각합니다.
어프로브 > 머지 하겠습니다ㅎㅎ
추가로 간단한 코멘트 몇가지만 남겨봤습니다~
다시 한번 고생 많으셨고 스텝 2도 화이팅입니다 💪

2023-11-27 02:29 UTC, GREENOVER commented on RockPaperScissors/RockPaperScissors/Display.swift
> +
다른 코드에선 import와 실제 구현 코드 사이 개행이 한줄인데 몇몇 파일에선 2줄인 이유가 있는건가요~?

2023-11-27 02:29 UTC, GREENOVER commented on RockPaperScissors/RockPaperScissors/Enums.swift
> +enum StringNameSpace {
파일명을 Enums로 하기보다 그룹을 Enums로 상위로 두고 각 Enums를 파일로 구분해도 좋을것 같아요..!
해당 Enums라는 파일명만 볼때는 어떤 성격인지 유추하기가 어렵습니다 ㅠ
추후 더 많은 Enum 타입들의 정의가 들어오면 해당 Enums 파일이 비대해질것 같아서요..!

2023-11-27 02:29 UTC, GREENOVER commented on RockPaperScissors/RockPaperScissors/main.swift
> +var isWorkingRockScissorsPaper = true
RockScissorsPaperLogic 파일에 위치하지 않고 해당 main 파일에 위치해야하는 이유가 궁금합니다 🙋🏻

2023-11-27 02:29 UTC, merged

2023-11-27 02:30 UTC, rlwhs12 commented
수정사항 중 질문사항

출력문구 관리하기 편하게 enum 으로 수정했는데요. 
출력문구를 사용할때 rawValue를 사용하는거보다 rawValue를 사용하지않고 출력문구를 사용하는게 가독성이 더 좋은거같아서 static let 를 사용했는데요 이게 더 좋은 코드일까요?? 아니면 그냥 rawValue를 사용하는게 더 좋을까요?