묵찌빠 [STEP 1] 노움, 에피
tasty-code/ios-rock-scissor-paper pull request #43
Opened 2023-11-23 05:49 UTC by hyeffie

민쏜 안녕하세요. 노움 에피입니다! 첫 리뷰 잘 부탁드려요.

저희는 이번 스텝에서 각 객체의 역할을 명확히 구분하고, 코드의 가독성을 높일 수 있는 방향으로 [⛺️코딩 컨벤션](https://github.com/rohhyungwoo/ios-rock-scissor-paper/wiki/%E2%9B%BA%EF%B8%8F-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%EB%A3%B0)을 지키는 걸 중점으로 작업을 진행했는데요.

객체의 역할과, 객체 간의 소통을 중점적으로 리뷰해주시면 정말 많은 도움이 될 것 같습니다.

## 설계 설명

### RSPApp

- **Menu**는 사용자 입력에 따라 게임 진행 / 게임 종료를 표현하는 열거형입니다.
- **App**은 루프를 돌며 사용자 입력에 따라 게임을 진행하고, 게임 결과를 출력합니다.

### RSPPlayable

- **Hand**는 플레이어가 내는 가위 / 바위 / 보를 표현하는 열거형입니다.
- **Playable**을 채택한 타입은 **Hand**를 속성으로 가져야 합니다.
- **UserPlayer, PCPlayer**는 **RSPPlayable**을 채택하고,
- **PCPlayer**는 생성 시점에 랜덤한 **Hand**를 초기화합니다.
- **UserPlayer**는 전달된 **Hand**로 초기화됩니다.

### Judge

- 두 플레이어 중 승자를 가려 결과를 리턴하는 역할의 객체입니다.
- `judgeIf` 메소드는 무승부 또는 누군가 이긴 상황을 표현하는 **RSPResult** 타입을 리턴합니다.

## 질문

### Optional인 Player의 값을 어떻게 보장해야 할까

원래는 RSPPlayer의 hand를 Hand?로 선언해서, 기본적으로 App의 userPlayer와 pcPlayer는 초기화 되어 있고, 사용자 입력이 들어오면 플레이어의 hand에 값을 설정하도록 구현했었는데요. 심판을 하기 전에 플레이어의 hand에 값이 있는지 확인하는 로직이 필요한데, 이 로직이 누락될 가능성이 있다는 생각이 들었습니다.

그래서 기존 hand의 타입을 non-optional Hand로 교체하고, hand를 전달해 플레이어를 생성하도록 구현을 수정했습니다.

```swift
protocol RSPPlayable {
    var hand: Hand { get set }
}

final class UserPlayer: RSPPlayable {
    var hand: Hand
    
    init(hand: Hand) {
        self.hand = hand
    }
}

final class PCPlayer: RSPPlayable {
    var hand: Hand
    
    init() {
        self.hand = PCPlayer.randomizeHand()
    }
    
    private static func randomizeHand() -> Hand {
        Hand.allCases.randomElement() ?? .rock
    }
}
```

하지만 여전히 App의 레벨에서는 다음처럼 userPlayer와 pcPlayer가 존재하는지 확인하는 로직이 필요한 상태입니다.

```swift
private func playOneRound(with userHand: Hand) {
        self.userPlayer = UserPlayer(hand: userHand)
        self.pcPlayer = PCPlayer()
        guard let userPlayer, let pcPlayer else {
            return
        }
        let result = self.judge.judgeIf(userPlayer, wins: pcPlayer)
        handleResult(result)
    }
```

혹시 현재의 구현보다 더 나은 구현 방법이 있는지 궁금합니다!

### 가위바위보 로직과 로직의 위치

현재 가위 바위 보에서 승자를 판단하는 로직은 두 단계로 이루어져 있습니다.

1. 두 개의 Hand, 즉 가위, 바위, 보 사이에서 한 Hand가 이겼는지 아닌지를 판단하는 로직
    
    ```swift
    enum Hand: Int, CaseIterable {
        case rock = 2
        case scissor = 1
        case paper = 3
        
        func wins(_ another: Hand) -> Bool {
            switch self {
            case .rock:
                return another == .scissor
            case .scissor:
                return another == .paper
            case .paper:
                return another == .rock
            }
        }
    }
    ```
    
2. 임의의 두 플레이어가 비겼는지, 또는 누군가가 이겼는지를 판단하는 로직
    
    ```swift
    final class Judge {
        func judgeIf(_ leftPlayer: RSPPlayable, wins rightPlayer: RSPPlayable) -> RSPResult {
            let lhs: Hand = leftPlayer.hand
            let rhs: Hand = rightPlayer.hand
            if lhs == rhs {
                return .tie
            } else {
                let winner = lhs.wins(rhs) ? leftPlayer : rightPlayer
                return .winning(winner)
            }
        }
    }
    ```
    

두 단계를 나누고, 로직의 위치를 고민하다가 1번 단계는 Hand 의 기능으로, 2번은 Judge의 기능으로 분리했는데요. 각 객체들에게 각각의 역할이 어울린다고 생각하시는지 민쏜의 의견이 궁금합니다~

### 심판 로직과 사용자 승리를 판단하는 로직

RSPApp의 `judgeIfUserWins` 메소드에서 심판으로부터 받아온 가위바위보 결과(RSPResult)의 승자가 App이 가지고 있는 userPlayer와 같은지 확인하는 로직을 다음처럼 구현했는데요.

```swift
private func judgeIfUserWins(winner: RSPPlayable) {
        if let winner = winner as? UserPlayer, winner === userPlayer {
            printMessage(.winning)
        } else {
            printMessage(.losing)
        }
    }
```

결과의 승자(RSPPlayable)을 UserPlayer로 캐스팅하고, 이 유저와 App의 현재 유저의 동일성을 비교하는 로직인데요. 현재 user가 옵셔널인데다가, 변수로 선언되어 있어서 지금과 같은 로직으로 구현된 것 같은데, 이런 방식이 적절한지, 더 좋은 방식이 있는지 민쏜의 의견이 궁금합니다.

2023-11-24 14:59 UTC, minsson requested changes
안녕하세요, 노움, 에피!
반갑습니다. 저도 첫 리뷰 잘 부탁드려요!

Step 1 진행하시느라 고생 많으셨어요.

객체의 역할을 명확하게 구분하는 걸 중점으로 작업을 진행하셨다고 했는데, 그에 맞게 코드가 너무 깔끔하고, 객체 분리도 무척 세세하게 되어 있어서 무척 놀랐습니다.

PR 본문도 세세하게 적어주셔서 코드를 읽고 이해하는 데에 도움이 되었어요. 감사합니다.

PR을 받고 고민을 좀 했어요. 너무 잘 해주셔서 어떤 걸 어느 정도로 피드백해야 할지 판단하기 어려웠어요. 이번 프로젝트에서 해야 할 핵심 경험은 물론이거니와, 그 이상까지 해주셔서 피드백을 드리는 게 맞을지, 그리고 제가 '옳은' 피드백을 해드릴 수 있을지 고민했어요. 오히려 제가 두 분의 코드를 보고 '이렇게도 할 수 있구나'라고 생각하며 감탄했던 지점도 많이 있었고요.

다만 커리큘럼 관점에서 보면 완벽한 오버엔지니어링이라고 생각합니다. 좋은 의미에서요. 더 이상 말씀드릴 게 없을 정도로요. 하지만 커리큘럼 수준을 뛰어넘었다고 칭찬만 하고 리뷰를 마무리하면 두 분의 고민과 노력에 답하지 못하는 거라는 생각이 들었어요. 두 분도 많이 아쉽고 허무하실 것 같았고요.

그렇기 때문에 정말 말 그대로 한 명의 동료 개발자 입장에서 코드 리뷰를 진행해봤어요.

바둑판을 바라보는 제3자의 입장이 되니, 제 실력이 조금 부족하더라도 바둑을 두시는 두 분이 놓치고 지나간 부분도 언급할 수 있기를 바랄 뿐이에요.

아래의 질문에 대한 답변도, 그리고 코드 코멘트들은 제가 뭔가 확신을 갖고 말하는 것 같은 말투를 사용하더라도 결국 제 개인적인 생각일 뿐이에요. 두 분도 저와 생각이 다르시면 바로 말씀해주세요. 저에게도 많은 공부가 될 것 같아요.


## 질문에 대한 답변

### Optional인 Player의 값을 어떻게 보장해야 할까

질문의 의도가 명확히 이해되지 않아요. Optional인 Player의 값을 보장할 방법은 없어요. 애초에 값이 있다는 걸 보장할 수 없다는 걸 나타내기 위해 Optional 타입이 존재하는 거니까요. 여러 방법으로 Optional을 Unwrapping 할 수 있는데, 이때 값이 있으면 값이 나오고, 없으면 nil이 나올 거고요. 

다만 질문의 의도는 위와 관련된 내용이 아니었다고 생각해요. 그러므로 질문을 'RSPApp에서 Player가 Optional인 게 적절한가, 이런 구현보다 더 나은 구현 방법이 있는가'라고 생각하고 답변해볼게요.

PR 본문에도 관련 코드를 제시해주셨는데, 저도 코드를 보면서 '왜 Player가 Optional 해야 하는가?'라는 의문이 있었어요. 위에서 제가 '값이 있다는 걸 보장할 수 없다는 걸 나타내기 위해 Optional 타입이 존재한다'고 말씀드렸는데, 현재의 구조에서 Player가 없을 일이 있을까요? 저는 무조건 있어야 한다고 생각해요. 그렇지 않으면 다른 모든 코드가 의미가 없을테니까요. 그렇다면 Player들이 Optional인 건 부자연스럽다는 말이 돼요.

때문에 우선은 이러한 부자연스러움을 없애는 게 더 나은 구현 방법이 될 것이라는 답변을 드릴 수 있을 것 같아요.

이와 관련해 제 생각을 바로 말씀드리기 보다는 아래의 질문을 드리고 싶어요.
- 왜 RSPApp에서 Player들이 Optional이어야 했을까요? Optional이 아니게 만들면 어떻게 되나요?
- 왜 playOneRound에서 self.userPlayer와 self.pcPlayer에 Player들을 이니셜라이즈할 수밖에 없었나요?

부가적으로, 이 부분과 관련해 코드 코멘트에도 여러 질문과 의견을 남겨두었으니 참고 부탁드려요!

### 가위바위보 로직과 로직의 위치

전 이 고민 과정에서 Hand, Judge 뿐만 아니라 RSPApp의 역할까지 같이 고민하면 좋을 것 같아요. RSPApp에도 judgeIfUserWins라는 메서드가 있으니까요. Hand는 가위, 바위, 보라는 case들이 뭘 이기는지를 결정하고, Judge 객체는 Player를 전달 받아 승리한 Player의 인스턴스를 반환하고, RSPApp에서는 승리한 Player의 인스턴스를 바탕으로 어떤 문장을 print하는지 정하고 있네요.

개인적으로는 Hand가 wins라는 로직을 갖고 있는 부분이 좋았어요. 현실세계 관점에서는 이상해 보일 수 있지만, 컴퓨터 세계에서는 응집도 높은 객체라는 생각이 들었어요. 

그런데 나머지가 좀 모호하게 느껴져요. 처음에는 Judge를 보고 객체 분리를 무척 잘하셨다고 생각했는데, 생각해볼수록 Judge의 역할이 애매해보여요. Judge의 역할까지 RSPApp이 하는 게 좋을지, RSPApp이 Judge의 역할까지 하는 게 좋을지, 아니면 그 외에 다른 방법이 있을지 저도 단언하기가 어려워요.

한편, 어쩌면 Judge라는 객체는 현실세계를 불필요하게 반영한 것일 수도 있겠다는 생각이 들었어요.

### 심판 로직과 사용자 승리를 판단하는 로직

`현재 user가 옵셔널인데다가, 변수로 선언되어 있어서 지금과 같은 로직으로 구현된 것 같은데` 라고 말씀해주셨는데, Player를 옵셔널로 해놨기 때문에 어쩔 수 없이 `judgeIfUserWins(winner:)` 메서드를 지금처럼 구현할 수 밖에 없었다는 뜻으로 이해하면 될까요?

저는 오히려 반대로 생각했어요. PR 본문의 세세한 질문을 읽기 전, 객체에 대한 대략적인 설명을 읽고 코드부터 봤거든요. 처음 코드를 보고 왜 Player를 class로 구현해놓으신 건지 궁금했는데, `judgeIfUserWins(winner:)` 메서드에서 `winner === userPlayer`라는 코드를 보고 '이렇게 판정하려고 class로 구현하셨구나'라고 생각했어요.

그런데 어쩔 수 없이 `judgeIfUserWins(winner:)` 메서드를 지금처럼 구현할 수 밖에 없었다면, 처음에 어떤 이유로 Player를 class로 구현하신 건가요? struct도 고려해보셨나요? 혹시 class와 struct를 선택하는 기준에 관한 공식문서도 읽어보셨나요?

질문에도 직접적으로 답변 드리자면, 개인적으로는 적절하지 않다고 생각했어요. `winner === userPlayer` 라는 코드를 제외하면, 이 프로젝트의 기능을 구현하기 위해 굳이 Player가 class가 될 이유가 없다고 생각해요.

2023-11-24 14:59 UTC, minsson commented on RockPaperScissors/RockPaperScissors/RSPApp.swift
> +        Swift.print(message.rawValue, terminator: terminator ?? "\n")
print 메서드와 readline 메서드를 사용하실 때 `Swift.`는 어떤 이유로 붙이신 건가요?

2023-11-24 14:59 UTC, minsson commented on RockPaperScissors/RockPaperScissors/RSPApp.swift
> +}
개인적으로는 이 extension 블럭에서 `Message` 열거형과 `printMessage(_:terminator:)` 메서드의 효용성이 잘 이해되지 않아요. `printMessage`라는 메서드가 있다는 점을 잘 알고 있지 않으면, 그냥 `print(Message.winning.rawValue)` 같은 방식으로 사용할 수도 있다는 생각이 들어요. 이와 관련해 별도의 객체로 분리하는 방법도 있을 것 같은데, 두 분은 어떻게 생각하시나요?

2023-11-24 14:59 UTC, minsson commented on RockPaperScissors/RockPaperScissors/Hand.swift
> +    case paper = 3
처음 봤을 때는 어떤 의미로 2, 1, 3이 써있는 건지 알기 어려웠어요. 지금은 프로젝트가 워낙 작아서 코드를 조금만 살펴보면 알 수 있지만, 좀 더 복잡했더라면 유저가 입력하는 0, 1, 2, 3과 이 코드의 연관성을 알기 어려웠을 것 같아요. 

혹시 이게 입력과 관련된 값이라는 걸 더 알기 쉽게 만들 수 있을까요?

2023-11-24 14:59 UTC, minsson commented on RockPaperScissors/RockPaperScissors/Hand.swift
> +    }
보고 감탄했어요..! 👏👏👏👏👏

2023-11-24 14:59 UTC, minsson commented on RockPaperScissors/RockPaperScissors/Judge.swift
> +        let rhs: Hand = rightPlayer.hand
어떤 이유로 lhs, rhs라고 네이밍 하신 건가요?

2023-11-24 14:59 UTC, minsson commented on RockPaperScissors/RockPaperScissors/RSPPlayable.swift
> +}
처음에 봤을 때는 무척 깔끔하다는 생각이 들었는데, 보면서 생각할수록 여러 의문이 들었어요. 

- 현재의 구조 내에서 생각해봤을 때
    - UserPlayer와 PCPlayer 모두 RSPPlayable 프로토콜을 채택한 구체 타입인데, UserPlayer는 의존성 주입을 받고, PCPlayer는 그렇지 않다는 점에 대해 어떻게 생각하시나요? 어떤 점이 PCPlayer가 그럴 수밖에 없게 만드나요?

- 전반적인 구조를 다시 생각해봤을 때
    - UserPlayer와 PCPlayer가 따로 나눠져 있어야 하는 이유가 무엇일까요? Player라는 객체를 두고, 유저가 인풋을 넣는 사람인지, PC인지 등을 구분하는 방법은 어떨까요?
    - 만약 PC가 랜덤한 Hand를 반환해야해 randomizeHand()라는 메서드를 구현해야 했고, 그로 인해 객체를 두 개로 나눠야 했던 상황이라면, Hand 객체 자체가 랜덤하게 가위, 바위, 보 중 하나를 반환하는 방향은 어떨까요?

2023-11-24 14:59 UTC, minsson commented on RockPaperScissors/RockPaperScissors/RSPApp.swift
> +            processMenu(menu)
processMenu라는 네이밍만 봐서는 정확히 어떤 작업을 하는지 이해되지 않네요..! 좀 더 명확하게 바꿀 수 있을까요?

2023-11-24 14:59 UTC, minsson commented on RockPaperScissors/RockPaperScissors/Judge.swift
> +final class Judge {
struct, enum, class 중 class를 택하신 이유가 무엇인가요?

2023-11-24 14:59 UTC, minsson commented on RockPaperScissors/RockPaperScissors/Menu.swift
> +}
개인적으로는 Menu라는 객체를 만든 게 좀 과한 분리라는 생각이 들었어요. 이것과 관련된 processMenu라는 메서드도 어색하게 느껴졌고요. RSPApp에서 처리해도 되지 않았을까라는 생각이 들어요. 

다만 이런 부분은 객체의 역할을 얼마나 엄격하게 분리하느냐에 대한 관점이 서로 달라서 그런 것 같은데요, 두 분은 어떤 기준으로 Menu라는 객체를 만드셨고, 어떤 역할을 하는 거라고 보셨나요?

2023-11-24 14:59 UTC, minsson commented on RockPaperScissors/RockPaperScissors/RSPApp.swift
> +    private var pcPlayer: PCPlayer?
개인적으로는 옵셔널은 '없을 수도 있다'를 전제로 두고 사용하는 편이에요. 그래서 처음 이 부분을 봤을 때는 플레이어가 없을 수도 있겠다는 생각이 들었어요. 또, 이게 없을 수가 있나? 라는 의문도 따라 왔고요.

현재 구조에서는 playOneRound(with:) 메서드에서 userPlayer, pcPlayer를 생성해줘야 하기 때문에 옵셔널이 될 수밖에 없었을 것 같아요. 사실은 무조건 있을 건데 말이죠.

좀 더 개선할 수 있을까요?

2023-11-24 14:59 UTC, minsson commented on RockPaperScissors/RockPaperScissors/RSPApp.swift
> +    }
result라는 네이밍이 불명확하게 느껴지는데, 좀 더 명확하게 바꿀 수 있을까요?

2023-11-24 14:59 UTC, minsson commented on RockPaperScissors/RockPaperScissors/RSPApp.swift
> +    }
Judge라는 객체가 있고, playOneRound(with:) 메서드에 judge.judgeBetween(userPlayer, pcPlayer)라는 코드가 있는데, RSPApp에도 judge가 들어간 메서드가 정의되어 있어요. 이 맥락에서 RSPApp의 역할과 Judge의 역할을 어떻게 구분하신 건지 궁금해요. print를 기준으로 나누신 건가요?

2023-11-24 14:59 UTC, minsson commented on RockPaperScissors/RockPaperScissors/RSPApp.swift
> +    }
코드를 보면서 왜 Player들이 class여야 했는지 궁금했어요. `===`를 쓰셨는데, 이걸 사용하기 위해 Player들이 class가 된 걸까요?

2023-11-24 15:11 UTC, minsson commented
리뷰에서 언급하지 못했던 부분이 있어서 추가해요.
- 아래 코드에서 RSPPlayable라는 protocol이 필요한 이유는 무엇인가요?
- RSPPlayable, UserPlayer, PCPlayer 없이, Player라는 객체 하나만 사용해서 컴퓨터인지, 유저인지 알 수는 없을까요?
- UserPlayer는 hand를 의존성 주입 받고, PCPlayer는 이니셜라이저 안에서 생성하고 있어서 부자연스러워보여요. PCPlayer에서 randomizeHand() 메서드를 써서 자신의 hand가 무엇인지 정해야하기 때문인 걸로 보이는데, 이걸 개선할 방법이 있을까요? 
- 위 질문과 관련해, 컴퓨터 세계의 객체와 현실 세계의 객체는 어떤 차이를 가질 수 있다고 생각하시나요?

```swift
protocol RSPPlayable {
    var hand: Hand { get set }
}

final class UserPlayer: RSPPlayable {
    var hand: Hand
    
    init(hand: Hand) {
        self.hand = hand
    }
}

final class PCPlayer: RSPPlayable {
    var hand: Hand
    
    init() {
        self.hand = PCPlayer.randomizeHand()
    }
    
    private static func randomizeHand() -> Hand {
        Hand.allCases.randomElement() ?? .rock
    }
}
```

2023-11-26 06:03 UTC, hyeffie commented on RockPaperScissors/RockPaperScissors/RSPApp.swift
> +        Swift.print(message.rawValue, terminator: terminator ?? "\n")
print를 디버깅용으로 쓰는 걸 방지하는 차원이 가장 컸어요. 콘솔 출력용 print 코드는 앞에 Swift를 붙여서 디버깅용이 아니라는 걸 인지 시키고 싶었어요.

이 부분에 대해서 콘솔 출력용 입출력 객체를 만드는 방법도 있을 것 같아서 적용해보려고 하는데 어떻게 생각하시나요?

2023-11-26 06:04 UTC, hyeffie commented on RockPaperScissors/RockPaperScissors/RSPApp.swift
> +}
입출력용 객체를 만들고 메서드로 정의한다면 지금 App에서 처리하고 있는 부분도 좀 더 자연스러워지고, 콘솔 출력을 명시하고자 했던 의도도 잘 전달할 수 있을 것 같아요. 적극적으로 반영해보겠습니다!

2023-11-26 06:04 UTC, hyeffie commented on RockPaperScissors/RockPaperScissors/Hand.swift
> +    case paper = 3
맞아요. rawValue를 정의했던 건 기본 제공하는 이니셜라이저를 사용할 수 있다는 이점 때문이었는데요. 

사실 무턱대로 를 사용하는 것이 마음에 걸리기도 했는데, `inputNumber` 등의 계산 속성을 만들고 매치할 수 있는 init을 선언한다면 좀 더 가독성있게 개선할 수 있을 것 같아요.

2023-11-26 06:04 UTC, rohhyungwoo commented on RockPaperScissors/RockPaperScissors/RSPApp.swift
> +        Swift.print(message.rawValue, terminator: terminator ?? "\n")
제가 아는 내용으로는 디버깅을 할때 print를 사용한다? 라고 알고있어요 그 print와 여기서 사용하는 print에 대한 이름을 구분하고자 했습니다. readline의 경우는 디버깅 할때 readline을 사용하는지는 잘 모르겠지만 print와 같은 네이밍의 통일성을 위해서 붙였습니다

2023-11-26 06:05 UTC, rohhyungwoo commented on RockPaperScissors/RockPaperScissors/RSPApp.swift
> +}
Prompt에 출력되는 print message를 열거형을 사용하면 한 눈에 확인 할 수 있고 printMessage 메서드를 사용하면 .winning, .losing과 같이 어떤 내용을 print하는지 한눈에 확인 가능하다고 생각했어요. 

```swift
private func judgeIfUserWins(winner: RSPPlayable) {
        if let winner = winner as? UserPlayer, winner === self.userPlayer {
            printMessage(.winning)
        } else {
            printMessage(.losing)
        }
    }
```

말씀주신 대로 별도의 객체로 분리하면 더 좋은 코드가 될거 같아요!

2023-11-26 06:06 UTC, hyeffie commented on RockPaperScissors/RockPaperScissors/Judge.swift
> +        let rhs: Hand = rightPlayer.hand
이 지역 변수들은 편의상 약어를 사용한 거였어요. 

사실 약어를 지양하는 [API design guide의 정책](https://www.swift.org/documentation/api-design-guidelines/#:~:text=Avoid-,abbreviations,-.%20Abbreviations%2C%20especially)에 공감하기는 하지만, lhs, rhs 의 경우는 스위프트의 일부 구현([Comparable](https://github.com/apple/swift/blob/98e65d015979c7b5a58a6ecf2d8598a6f7c85794/stdlib/public/core/Comparable.swift#L149) 등)에서도 사용하고 있기도 하고, 또 여러 프로그래머들이 사용하는 약어들은 그 의미가 공유되고 있다고 생각했거든요.

그래서 합의 하에 이런 용어들은 예외로 적용하기로 했던 것 같아요. 관련 내용은 [코딩 컨벤션](https://github.com/tasty-code/ios-rock-scissor-paper/pull/43#discussion_r1403964890)에도 적어두었어요!

2023-11-26 06:07 UTC, rohhyungwoo commented on RockPaperScissors/RockPaperScissors/Hand.swift
> +    case paper = 3
위 코드를 사용함에 있어서 더 나은 방법이 있는지 몰라서 코드의 연관성을 생각하지 못했습니다.

2023-11-26 06:07 UTC, hyeffie commented on RockPaperScissors/RockPaperScissors/RSPPlayable.swift
> +}
말씀하신 것처럼 PCPlayer도 hand를 구현하고 있지만, 외부에 의해서 속성의 값이 결정되지 않고 내부적으로 randomize한 Hand로 설정하고 있어요.

애초에 두 플레이어 모두 hand가 필요하지만 hand가 초기화 되는 양상이 다르다보니 상속이 아닌 프로토콜로 인터페이스를 공유하도록 구현했던 것 같아요. 또 PCPlayer의 속성이 외부에 의해 결정되지 않도록 의도하다 보니 결과적으로 현재의 구현이 나온 것 같고요.

> • UserPlayer와 PCPlayer가 따로 나눠져 있어야 하는 이유가 무엇일까요? Player라는 객체를 두고, 유저가 인풋을 넣는 사람인지, PC인지 등을 구분하는 방법은 어떨까요?
> 

저도 현재 player가 App에서 계속해서 변경되는 부분이라던지, 또 그 타입이 옵셔널이라던지, 하는 문제 때문에 Player 타입 자체의 역할에 대해서 다시 고민하는 중인데요. 

제안해주신 방향처럼 구체 타입으로서의 Player나 또는 그에 준하는 다른 객체를 사용하고, 이 타입의 속성(isPlayer)으로 사용자인지를 판단하는 방식이 여러 문제를 해결할 수 있다고 생각해요. 좀 더 고민이 필요하겠지만 비슷한 방향을 적극적으로 반영해보려구요!

2023-11-26 06:08 UTC, rohhyungwoo commented on RockPaperScissors/RockPaperScissors/Judge.swift
> +        let rhs: Hand = rightPlayer.hand
lhs, rhs라는 변수가 개발자들에게 종종 사용 되는 약어라고 들었습니다. 해당 네이밍을 사용함에 있어 코드 내용상 이질감이 느껴지거나 이해하기 힘든부분이 없어 에피와 논의 후 사용하기로 했습니다

2023-11-26 06:08 UTC, hyeffie commented on RockPaperScissors/RockPaperScissors/RSPApp.swift
> +            processMenu(menu)
이 메소드가 생긴 건 Menu를 정의했던 의도와 연결되는데요. 사용자 입력에 따라서 가위바위보 게임을 진행하거나, 혹은 프로그램을 종료하는 두 가지 케이스가 있고, 전달된 메뉴를 처리한다는 의미에서 processMenu라고 지었어요.

다른 코멘트에서 말하게 되겠지만 지금의 Menu는 현재 다른 객체의 역할이 달라진다면 함께 달라질 가능성이 있기도 하고, (다음 스텝을 고려한다면) 분명 구현이 달라져야 하는 부분들이 있거든요. Menu에 대해서 고민해보고 이름을 다시 지어보도록 할게요!

2023-11-26 06:08 UTC, rohhyungwoo commented on RockPaperScissors/RockPaperScissors/RSPPlayable.swift
> +}
- 현재의 구조 내에서 생각해봤을 때

UserPlayer의 hand와 PCPlayer의 차이는 초기화 되는 변수 hand의 값을 가져오는 방식에 있다고 생각합니다.

 UserPlayer의 경우 사용자의 프롬포트 입력에 따라 값이 저장되는 방식이고 PCPlayer는 Hand.allCases 배열의 랜덤 메서드를 통해 저장되기 때문에 다른 클래스로 구현했습니다.

- 전반적인 구조를 다시 생각해봤을 때

PC, User가 하나의 클래스 내에서 존재하고 모두 값을 의존성 주입을 통해 받는다고 생각했을 때 굳이 다른 클래스로 구분할 필요가 없다는것을 깨달았습니다.

말씀하신 방법으로 구현하면 제 생각에도 더 좋을거 같습니다

2023-11-26 06:08 UTC, hyeffie commented on RockPaperScissors/RockPaperScissors/Judge.swift
> +final class Judge {
심판하는 역할을 Judge라는 객체로 만드는 것만 의도했지, 만들고 이렇게 보니 class여야 할 이유를 스스로 설득하지 못하겠네요…

지금 Judge는 앞서 언급해주셨던 것처럼 동작만 있는 객체이고, 그래서 객체여야 할 이유도 지금보니 없는 것 같다는 생각이 들어요. 🥲

App의 동작으로 바꾸거나, 사실 지금 한 라운드를 표현하는 객체를 만들어볼까 생각하고 있거든요. 라운드 내에서 결과가 판정되도록 해당 객체의 동작으로 이동하는 방향을 고려해 봐야 할 것 같아요.

2023-11-26 06:09 UTC, rohhyungwoo commented on RockPaperScissors/RockPaperScissors/RSPApp.swift
> +            processMenu(menu)
열거형 menu는 사용자의 입력으로 부터 게임 실행 혹은 게임 종료에 대한 2가지 case(게임 메뉴)를 구분하고 processMenu의 경우 구분된 case를 처리하기 위해서 만들었습니다. 

menu의 네이밍이 변경(더 좋은 네이밍을 찾는 경우)되지 않는다면 processMenu를 사용 하는것도 나쁘지 않다고 생각됩니다.

2023-11-26 06:10 UTC, rohhyungwoo commented on RockPaperScissors/RockPaperScissors/Judge.swift
> +final class Judge {
가위 바위 보 프로젝트를 진행하면서 각각의 기능 혹은 역할에 따라 클래스를 생성 하려 했습니다.

 게임의 승패 여부를 판단하는 역할을 정해두고 만들어서 불필요한 클래스를 만들게 되었던거 같아요

2023-11-26 06:11 UTC, rohhyungwoo commented on RockPaperScissors/RockPaperScissors/Menu.swift
> +}
위 Process Menu 네이밍에서 이야기 한것처럼 사용자 입력에 따른 case를 구분하기 위해서 만들었는데요

코드 재사용성을 생각하는 측면에서는 위 방법으로 메뉴를 구현하게 되면 묵찌빠가 아닌 다른 프로그램에서도 적용이 가능할것 이라고 생각했어요

2023-11-26 06:12 UTC, hyeffie commented on RockPaperScissors/RockPaperScissors/Menu.swift
> +}
Menu는 사용자 입력을 통해서 어떤 작업을 진행할지 결정하는 로직을 별도의 객체가 생성자로 하면 어떨까 라는 아이디어에서 만든 enum이었어요.

말씀하신 것처럼 이런 역할을 위한 객체라는 것이 어떻게 보면 인위적?이기도 하고, App의 레벨에서 충분히 해결할 수 있는 로직이기는 해요.

여러 코멘트를 읽으면서 느낀 게, 제가 현재 스텝의 요구사항을 읽고 설계하면서 무의식 중에 다음 스텝이나 다른 기능을 고려했다는 생각이 들더라고요. Menu도 어찌보면 그런 과정의 결과라고 할 수 있을 것 같고요.

다음 스텝을 적용한다면 이 Menu의 역할이 어떻게 바뀌게 될지는 모르겠지만, 일단은 유지하고 좀 더 고민해보겠습니다!

2023-11-26 06:12 UTC, hyeffie commented on RockPaperScissors/RockPaperScissors/RSPApp.swift
> +    private var pcPlayer: PCPlayer?
이게 없을 수 있나? 라는 의문. 저도 정말 공감해요. 사실 그래서 옵셔널에 대한 질문을 드렸던 거기도 하고, 옵셔널이 아닌 방향으로 다시 설계해야 한다고 생각해요.

```swift
private func playOneRound(with userHand: Hand) {
        self.userPlayer = UserPlayer(hand: userHand)
        self.pcPlayer = PCPlayer()
        guard let userPlayer, let pcPlayer else {
            return
        }
        let result = self.judge.judgeBetween(userPlayer, pcPlayer)
        handleResult(result)
}
```

지금은 App 의 playOneRound 메소드에서 player를 생성하고, judge에게서 판정을 가져오고 있는데요.

지금 이 메소드의 역할을 한 라운드를 표현하는 객체로 대체하는 방향을 고려하고 있어요. 이 객체에서는 플레이어(나 그에 준하는 객체)가 반드시 존재하고, 결과까지 객체 내에서 판정하게 될 것 같아요.

2023-11-26 06:13 UTC, rohhyungwoo commented on RockPaperScissors/RockPaperScissors/RSPApp.swift
> +    }
에피님의 생각(refinedInput 네이밍)에 동의합니다

2023-11-26 06:13 UTC, hyeffie commented on RockPaperScissors/RockPaperScissors/RSPApp.swift
> +    }
의도된 입력만 가져오도록 가공하고 있으니까 refinedInput 같은 이름은 어떤 것 같으세요?

2023-11-26 06:15 UTC, hyeffie commented on RockPaperScissors/RockPaperScissors/RSPApp.swift
> +    }
1

맞아요. 만약 심판이 리턴하는 게임의 결과를 나타내는 객체가 있다면, 이 객체는 사용자에 표시하는 형태는 몰라야 한다고 생각했어요. 그래서 App 레벨로 결과를 display하는 로직을 구현했던 거고요.

2

원래 Player들의 구현은 hand를 옵셔널 변수로 만들고 계속 바꿔주는 방식으로 게임을 진행하는 형태였어요.

그러다가 hand가 옵셔널인 부분에서 의문점이 생겼고, 논 옵셔널로 바꾸고 생성 시점에 값을 설정하는 형태로 바꾸게 된 거였어요.

그런데 저도 돌아보니 아쉬움이 많이 남아요. 바뀌지 않을 거라면 상수로 선언할 걸, player가 계속 바뀔 거라면 참조가 아닌 값 타입이어도 되지 않았을까? 이런 아쉬움들이요.

위에서 말씀 드린 것처럼 게임의 한 라운드를 표현하는 객체로 대체해 볼 생각인데, 그렇다면 자연히 hand를 가진 Player가 참조 타입일 필요는 없어질 것 같아요. 어쩌면 다른 이름, 다른 역할의 객체가 그 자리를 대신할 수도 있겠고요. 

더불어서 앞으로 리팩토링을 할 때는, 커밋 전에 변경사항에 따라서 바뀌게 된 설계가 여전히 이전의 설계의 의도에 머물러 있지 않은지 확인하는 습관을 가져야겠다는 생각이 드네요 😅

2023-11-26 06:15 UTC, rohhyungwoo commented on RockPaperScissors/RockPaperScissors/RSPApp.swift
> +    }
1
Judge 객체는 사용자의 입력과 PC의 랜덤 출력을 비교하고 RSPAPP의 Judge은 승자와 패자로 나뉘어진 결과물을 Prompt에 출력하기 위해 구분 되었습니다
print는 RSPApp에서 수행해야 된다고 생각되었습니다

2
플레이어들이 클래스가 되어야 한다고 생각했던건 hand가 기존 리팩토링 과정에서 옵셔널에서 옵셔널이 아니게 변경되었고 이전의 옵셔널인 hand를 사용하기 위해서 코드를 struct에서 class로 수정되어졌습니다
때문에 === 는 클래스를 사용해서 만들어진 코드여서 변경이 필요하다 생각되네요

2023-11-26 06:18 UTC, rohhyungwoo commented
마지막 리뷰에 관한 내용입니다

- RSPPlayable 프로토콜 필요한 이유

원래 목적은 userPlayer와 PCPlayer가 구분된 상태에서 서로 공통되는 부분을 뽑아서 Protocol 혹은 class로 상속되어 사용하고자 했습니다.

- Player 객체 하나만 사용

사실 아직 하나의 class혹은 struct만 사용해서 작업하는게 나은지 혹은 더 분리하는것이 나은지 잘 모르겠습니다

- userPlayer와 PC Player의 init 차이

서로 hand값을 초기화 하는 방법이 달라서 pc user로 클래스를 구분한게 같은데 차라리 하나의 클래스로 만들고 둘다 의존성을 주입 받는 방식으로 코딩하면 더 깔끔해질거 같아요

- 컴퓨터 세계의 객채 현실 세계의 객체 차이

위 답변과 마찬가지로 입력받는 방식에서 차이가 있다고 생각했습니다.

2023-11-26 06:20 UTC, hyeffie commented
RSPPlayable과 Player 객체들에 대해서서는 [위 코멘트](https://github.com/tasty-code/ios-rock-scissor-paper/pull/43#discussion_r1405331933)에서 답변을 한 것 같아서 마지막 질문에 대한 생각을 이야기 해볼게요.

> 바로 위 질문과 관련해, 컴퓨터 세계의 객체와 현실 세계의 객체는 어떤 차이를 가질 수 있다고 생각하시나요?

프로그래밍에서의 객체는 표현하고자 하는 맥락이 있어요. 그래서 실제 세계 객체의 특정 측면만을 그려서 사용하는 반면, 현실 세계에는 없는 또 다른 역할을 가진 객체를 만들 수 있는 것 같아요.

현실의 가위바위보는 두 명의 플레이어가 필요하지만 실제 한 번의 가위바위보 게임을 진행하면서 필요한 건 플레이어들이 현재 라운드를 위해 내민 손 뿐일 거예요. 그런 의미에서 내민 손이 사용자의 것인지 아닌지 판단할 수 있다면 굳이 UserPlayer와 PCPlayer를 나눌 필요도, 초기화 동작을 다르게 할 필요도 없을 수 있어요.

사실 위에서 Hand.randomize() 같은 느낌으로 랜덤 로직을 이동시키는 걸 제안해주셨을 때, 왜 그 동작을 플레이어가 아닌 Hand가 해야 하지? 하고 이해가 잘 안 됐어요.

그런데 이 질문을 읽고 생각해보니까 랜덤한 Hand를 고르는 걸 반드시 플레이어가 할 필요는 없다는 생각이 들어요. 그렇다면 Player은 어떤 역할을 하는 객체지? 하고 자연스럽게 다른 객체의 역할에 대해서도 재고해보게 되네요.

프로그래밍에서 필요한 정보들은 현실 세계에서 필요한 정보들과는 확실히 차이가 있고, 그래서 그 정보들을 어떻게 묶느냐도 여러 가지 방법이 있는 것 같아요.

사실 다른 코멘트에서 이야기 했던 것처럼 현재의 설계가 요구사항 외의 기능이나 다음 스텝을 무의식적으로 고려했던 것 같다는 느낌을 받는 것도, 나중에는 이런 게 필요하지 않을까? 그런 기능이 필요하다면 객체로 분리해야 하지 않을까? 하면서 확장된 형태가 되었기 때문인 것 같기도 해요.

지금의 고민들을 담아서 정말 필요한 정보들을 가진 객체들을 만들고, 필요한 소통을 할 수 있도록 다시 설계해보려구요. 많은 걸 돌아보게 하는 코멘트들 너무 감사합니다! @minsson

2023-11-28 01:11 UTC, merged

2023-11-28 04:34 UTC, minsson commented on RockPaperScissors/RockPaperScissors/RSPApp.swift
> +        Swift.print(message.rawValue, terminator: terminator ?? "\n")
의도는 이해가 됐는데, 제 생각에는 유의미한 구분이 될 것 같지는 않아 보여요..! 😅 에피가 말씀하신 것처럼, 만약 구분이 필요하다면 콘솔 출력용 입출력 객체를 만들어보는 것도 좋은 방법 같아요.

참고로, 디버깅이라고 말씀하실 때 버그를 찾는 용도를 말씀하시는 거라면 print를 사용하는 방법의 경우 가능은 하지만 권장하는 방법은 아니에요. 다만 초반에는 학습할 내용이 워낙 많다보니, 디버깅 용도로 print를 쓰면 된다는 말을 듣게 되는 것 같아요.

그런데 점점 뭔가를 바꿀 때마다 매번 print문에 값을 넣어주고, 원하는 값을 찾으려고 값을 바꾸고, 빌드하고, 또 바꾸고, 또 빌드하면 많이 답답해지실 거예요. 나중에는 Break Point 등을 찍어보는 등 Xcode에서 제공하는 툴을 이용하면 좋을 것 같아요! LLDB도 찾아보시고요. (이 부분은 저도 아직 잘 못하고, 배워나가는 중이에요) 

또, 로깅과 관련해서 OSLog, debugPrint 등도 여유가 되시면 검색해보셔도 좋을 갓 같아요! (저도 아직 나중에 공부할 내용으로 남겨놓은 상태예요... 😅)

2023-11-28 04:38 UTC, minsson commented on RockPaperScissors/RockPaperScissors/Judge.swift
> +        let rhs: Hand = rightPlayer.hand
`lhs`, `rhs`의 경우 `Equatable` 프로토콜 등에서 사용하기는 하지만, 이 경우에는 값을 특정할 수 없어서 사용한 거라고 생각해요. 두 개의 값을 비교하는데 그 값을 포괄적으로 표현하기 어려우니까요. 그런데 두 분이 작성하신 코드에서는 무조건 Hand 객체가 들어올 거라는 걸 알고 있으니, `leftPlayerHand`, `firstPlayerHand` 등 좀 더 구체적인 네이밍을 사용하면 이해하기 좋을 것 같아요.

2023-11-28 04:43 UTC, minsson commented on RockPaperScissors/RockPaperScissors/Judge.swift
> +final class Judge {
객체 분리의 의도는 다른 곳에서 말씀을 드렸어서, 여기서는 이 객체가 struct, enum, class 중 왜 참조 타입인 class가 된 건지 여쭤보고 싶었어요. 더 정확히 말씀 드리자면, 값 타입과 참조 타입의 차이를 이해하고 사용하시는 건지 궁금했어요. 아래 공식문서를 읽어보시면 좋을 것 같아요.

[Choosing Between Structures and Classes](https://developer.apple.com/documentation/swift/choosing-between-structures-and-classes)

2023-11-28 04:46 UTC, minsson commented on RockPaperScissors/RockPaperScissors/RSPApp.swift
> +    }
저라면 `trimmedInput`이라고 했을 것 같아요! 취향 차이니까 이렇게 네이밍하는 사람도 있구나.. 정도로 보시면 될 것 같아요 😅

2023-11-28 04:51 UTC, minsson commented
두 분 Step 1 고생 많으셨어요!

저야말로 두 분의 좋은 코드를 통해 많이 생각하고, 고민하고, 배울 수 있었어요!
저희 모두 '정답'을 찾기보다는 서로 궁금한 걸 묻고, 생각을 공유하며 함께 성장할 수 있었던 것 같아요.

Step 2도 화이팅이에요! 😁