묵찌빠 프로그램 [STEP 1] Andy, Lj
tasty-code/ios-rock-scissor-paper pull request #45
Opened 2023-11-23 08:18 UTC by nation81

@keeplo
**팀원들 각각 STEP1을 구현해보고 두명이 작성한 코드중 좀 더 적합한 코드를 commit하기로 협의를  하였습니다.**

### 코드 작성이유

- 가위바위보의 결과는 승리,패배,비김 이렇게 세가지 경우만 존재하기에 결과값을 enum으로 정의를 하였습니다.

- 프로젝트 특성상 print문의 출력이 자주 있었고 반복되는 print문이 있었기에 재사용성의 향상을 위해서 print할 문장들을 하나의 Constant 구조체로 만들었습니다.

- exit()를 사용할 수 없다는 제약사항이 있었기에 while문안에서 break를 통해 프로그램을 종료시키기로 하였습니다. 

### 고민했던점

- 해당 프로젝트의 핵심 로직은 가위바위보의 결과를 계산하는것이라 할 수 있는데, 이 결과를 계산하기 위한 로직을 고민하는 과정에서 일종의 법칙을 발견하였습니다.

- 유저가 선택한 숫자(1~3 사이의 수)와 컴퓨터가 낸 숫자의 차이를 가지고 승리, 패배, 비김 상황을 판별할 수 있었습니다.

- 유저가 Int 타입이 아닌것을 입력하였을때, 에러가 발생하였는데 재귀함수를 활용하여 유저가 Int 타입을 입력해야만 게임이 진행되도록 구성하였습니다.

2023-11-23 14:17 UTC, keeplo requested changes
@ijs1103 @nation81

우선 Step 1 PR 이지만 처음 컨벤션이나 함께 코드를 작성하는데 
쉽지 않고 적응할 부분도 많으셨을텐데
첫 프로젝트 진행하시느라 고생하셨습니다~ 🙏

역시 기능 구현이나 설계에서 여유가 느껴집니다.
전체적으로 탄탄하게 구성됨을 느꼈어요!

---

우선 처음 리뷰 드리는 데 앞서서 설명을 드리고 싶은 부분이 있어요!
저도 아직 대단한 경험을 쌓은 개발자는 아니지만, 
실제 저희 팀이나 제 경험에서 기준과 거의 유사하게 진행했어요.
> 제가 남긴 리뷰 안건은 저희 팀원은 무조건 동일한 리뷰를 저한테 받는다고 보시면되요 ㅎㅎ

일부분은 지금은 이해가 안되거나 그렇게까지 해야되나 싶은 부분이 혹여나 있을 수도 있지만,
저는 두 분이 앞으로 진행하실 수 많은 프로젝트에서 알고 안하는 것과 아예 모르는 것은 
전혀 다른 상황이 될 수 있다고 감히 생각하고 있어요
그래서 작은 부분 하나하나를 더 생각해보길 바라는 의도가 있다는점 이해해주시면 감사하겠습니다!

---

### 프로젝트를 보며 좋았던 부분
- 설계가 탄탄합니다!
   파일을 각 개체별로 분리한다거나 개체 단위를 나누는 부분이 노련함이 느껴졌습니다.
   프로그램의 라이프 사이클 (main) 에서 각 기능의 의도가 적절하게 배치되었다고 생각해요!
- 언어에 이해도
   Swift 언어에 주어진 기본적인 기능을 잘 이용하신다는게 느껴집니다!
- Commit 단위 분리
   각 커밋이 단계별로 프로젝트가 생성되는 구조를 파악하기 좋게 잘 나눠진 것 같습니다.
   // TODO: 같은 주석을 이용해서 단계별로 처리되는 구현이 너무 좋았습니다.
- 정해진 기한 맞추기
   정해진 기한에 목표를 이루는 연습도 중요하다고 생각합니다
   그런면에서 Step 1 기한을 맞춰서 완성한 부분도 아주 좋습니다!

### 고민해보면 좋을 부분
- 꼼꼼함?!
  <img width="500" alt="스크린샷 2023-11-23 오후 9 17 25" src="https://github.com/tasty-code/ios-rock-scissor-paper/assets/24707229/2f214879-d8f2-42de-96b2-d689d740cee6">
   프로젝트 명세예시와 달리 사용자 입력문이 줄바꿈이 되어 있습니다.
   실무에서도 이런 실수는 많이 발생하지만, 발생하지 않도록 확인하는 연습을 하면 좋을것 같아요!
   때로는 기획자 또는 디자이너가 의도와 다른 동작을 보면, 
   개발자가 실수로 빠뜨렸다 단순히 생각하기보다 계획과 다른 기능에 당황할 수도 있습니다!
- [Swift API Design Guidelines](https://swift.org/documentation/api-design-guidelines/) - 특히 Naming 파트
   별표 다섯개 곱하기 다섯개의 5제곱입니다.
   필독 정독 하셔야하고 고민되는 부분은 함께 토론하면 좋을것 같아요!
- 실력으로 넘어가버린 부분들
   개인적인 생각일 수 있지만, 프로젝트 명세에서 주어진 부분들이 생략됨을 느꼈습니다.
   `프로젝트 제약사항` 중에 짝 프로그래밍도 좋은 경험이 될 수 있습니다. 지금처럼 쉬운 설계에서 꼭 시도해보세요!  
   저도 같은 프로세스를 경험한 입장에서 미리 예고편을 보여드리자면 다음 프로젝트에는 `이번 프로젝트를 수행함에 있어 꼭 읽고 참고해야 하는 문서` 이 부분의 명시된 내용의 양이 절대 줄어들지 않습니다. 더 많아집니다...
   프로젝트 명세에 작성된것처럼 Step 1, 2 진행보다 이 문서를 아는 내용이더라도 정독하고 정리하는 부분이 정말 큽니다! 물리적으로 잘 안배하셔서 주말에 꼭 마침표를 찍는 형태로 학습을 하시는걸 권장합니다. ~~~여기 부캠 프로그램 정말 좋아요 대신 정말 힘듭니다 ㅎ 6개월이 누군가의 3년이 될 수 있습니다~~~

---

감히 누군가를 평가하는 수준이 절대 아니지만, 
두 분에게 학습의 목적으로 고민해볼만한 부분들을 리뷰와 코멘트로 남겼습니다.   
지금 너무 많은 내용에 당황하실수도, 불필요한 내용이라고 생각 하실수도 있어요.
일부는 분명 배울 부분도 있겠지만, 물론 정답은 없고 일부는 제 경험에 범위에서 `대세` 일뿐 일 수 있습니다.
리뷰에서 의도나 기준이 명확한데 제가 캐치하지 못했다면  꼭 설명해주시고, 
저는 저의 리뷰에 반박해서 저를 납득시키는게 좋은 경험이 될 수도 있다고 생각합니다!

Request Change 남겼습니다.
리뷰남긴 부분들을 고민해보시고 수정 또는 답변 남겨주시고 노티주세요!

남은 기간도 화이팅입니다! 👊

2023-11-23 14:17 UTC, Marcorable commented on RockPaperScissors/RockPaperScissors/Models/Result.swift
> +}
승패 결과를 표현하는 방법으로 `enum`을 이용하셨군요!
[코멘트](https://github.com/tasty-code/ios-rock-scissor-paper/pull/45#issue-2007682833) 에서 전달해주신   
> 가위바위보의 결과는 승리,패배,비김 이렇게 세가지 경우만 존재하기에 결과값을 enum으로 정의를 하였습니다.    

내용과 다르게 4가지의 결과가 작성되어있는데 범위 이외에 `none` case 가 존재하는데, 
의도된 `Result` 네이밍에서 벗어난 범위의 용도가 되지 않을까요?     

enum과 case 를 사용하시는 의도와 용도를 어떤기준을 가졌는지 말씀해주실 수 있을까요?

2023-11-23 14:17 UTC, Marcorable commented on RockPaperScissors/RockPaperScissors/Models/Result.swift
> +enum Result: String {
case 의 RawValue 타입을 문자열 String으로 결정하셨군요!

case 와 RawValue 는 어떤 관계를 가지면 좋을까요?   
혹시나 동일한 내용의 문자열이 RawValue로 사용될 가능성은 없을까요?

2023-11-23 14:17 UTC, Marcorable commented on RockPaperScissors/RockPaperScissors/Constant.swift
> +}
반복되거나 재사용을 고려해서 문자열을 따로 관리하는 구조체로 분리해주셨네요! 
의도하신 장점뿐 만아니라 수정에도 용이할것 같다는 생각이 드네요

구조체를 선언한다면 해당 구조체 인스턴스가 초기화 될 수 있는 위험성이 있을 것 같아요.
전역 static 프로퍼티가 아니라 구조체의 static 프로퍼티로 선택한 이유가 있을까요?

2023-11-23 14:17 UTC, Marcorable commented on RockPaperScissors/RockPaperScissors/Game.swift
> +final class Game {
`final` 키워드를 사용하셨네요!

final 선언을 한다면 default class 선언과 어떤 차이점이 있는지 설명해주실 수 있으신가요?

2023-11-23 14:17 UTC, Marcorable commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    private var inputNum: Int = 0
기준은 커뮤니케이션에서도, 이해해야하는 범위를 좁히는데도 중요한 역할을 한다고 생각해요!
우리나라에 공식적인 문서에서 외래어를 표기하면 로마자표기법 같은 기준이 있더라구요

그런면에서 프로젝트를 진행하기에 앞서 팀 컨벤션을 결정하셨을텐데요.
Swift 언어에서는 유일하게 존재하는 기준은 [Swift API Design Guidelines](https://swift.org/documentation/api-design-guidelines/) 가 있어요

이 가이드에서는 약어를 사용하거나 완전하지 않은 단어를 지양하기를 권장하고 있어요.
Num 이라는 표기가 Number를 떠올릴 수도 있지만 다른 단어를 떠올릴 수도 있고
이런 표현은 습관처럼 굳어지면 다양한 네이밍에서 명료함을 전달하지 못할 수 있다고 생각해요

프로그래밍에서 index를 idx 같은 표기로 하는 관습은 C언어 탄생 시절에 생겨난건데,
그 당시에는 두 텍스트의 용량마져 연산에 영향이 부담스러울 정도로 영향이 가기 때문에 그랬다고 해요
지금은 글자가 많건 적건 텍스트에 용량이 성능에 영향을 주지 않으니 기준을 맞춰주는게 좋을것같아요!

2023-11-23 14:17 UTC, Marcorable commented on RockPaperScissors/RockPaperScissors/Game.swift
> +
줄바꿈의 기준이 혹시 있을까요?

가독성을 해치지 않는 좋은 방향은 무엇이 좋을지 고민해보면 좋을것 같아요!
정답은 없고 기준이 없다면 기준을 만들어보시는것도 좋을것 같습니다!

2023-11-23 14:17 UTC, Marcorable commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    private func playRps() {
Rps 는 당연히 Rock Scissors Paper 라는점은 저도 알고 두분도 알수 있어요.
지금은 가위바위보이지만 만약 특별한 기능이었다면, 저희 셋다 퇴사 또는 다른 부서로 옮기고 
이 프로젝트를 유지보수 해야하는 개발자라면 Rps를 보면서 어떤 기능인지 파악하기 무척 힘들거라고 생각돼요

단순히 이 부분에 Rps 부분이 길어지는것 뿐만아니라
class 네이밍에 가위바위보 게임이라는 의도가 들어가고
이 부분은 단순히 play 가 된다면 좀더 이 클래스와 클래스의 메서드를 이해하기 편해질 거라는 생각이 문득 듭니다!

2023-11-23 14:17 UTC, Marcorable commented on RockPaperScissors/RockPaperScissors/Game.swift
> +        let diff: Int = randomInt - input
1, 2, 3 간의 관계를 형성해서
랜덤 난수와 사용자 입력을 이용한 가위바위보 게임을 실체화 해주셨군요!

아주 좋은 아이디어네요!

2023-11-23 14:17 UTC, Marcorable commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    private func calcRps(with input: Int) {
우선 줄임말 네이밍은 본래 단어를 사용하는 가이드를 따라서 다시 변경할 필요성이 있어요!

두번째로는 메서드의 네이밍에 의도를 조금 더 고민해보면 좋을것 같아요!

좋은 아이디어로 만들어주신 게임을 실현화 해주는데 
이걸 `계산하다`로 표현한다면 표면적인 의도가 되고,
`판정`, `결과` 같은 형태로 표현한다면 추상적일것 같은데,

어떤 표현을 쓰는게 좋을지 두 분에 생각이 궁금합니다!

2023-11-23 14:17 UTC, Marcorable commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    }
메서드는 하나의 기능이되기도 하고 개체의 부품이 되기도 하죠
그리고 개체가 모이면 하나의 앱이 되기도 합니다!

그런면에서 이 메서드는 중요한 기능으로써 존재하는데요
두 분이 만들때는 의도를 가졌지만, 다른 사람이 수정 또는 개선해야하는 상황이 된다면 어떨까요?

목적이 명확하고 메서드가 본래의 목표를 완전히 이루는 구조가 아니라고 생각되요
가위바위보게임 개념은 이 메서드 자체의 기능에서는 외부요인이라 알 수 없는데요
이 부분을 고려한다면 0, -1, 2 라는 숫자가 들어온다는 전제가 깔려있지 않으면,
반대로 이외의 숫자는 아무 동작없이 메서드가 끝나게되요

그렇다면 이 메서드를 수정하는 사람은 
`0, -1, 2는 무언가를 하고 이외의 숫자는 아무것도 안한다` -> `왜 안할까?` -> `왜 안하는지 이 메서드를 사용하는 다른 부분을 해석해야하네` 라는 의식에 흐름으로 다른 코드를 연쇄적으로 해석해야하는 상황이 될거에요
지금은 가위바위보지만 실무에서 어려운 기능이라면 이 메서드 수정을 위해서 어디까지 타고 갈지... 

`if` 조건문의 else나 `switch` 를 이용하면 좀 더 개선해볼 수 있을거라 생각해요
앞서 길게 말씀드린 메서드가 본래의 의도, 목표를 실현하는 데에 완전해지는 구조로 메서드 내부를 다시 설계해보면 좋을것 같아요!

2023-11-23 14:17 UTC, Marcorable commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    }
각 메서드의 주요 기능이외에 동작은 메서드로 기능을 분리해주셨군요! 
아주 좋습니다!

2023-11-23 14:17 UTC, Marcorable commented on RockPaperScissors/RockPaperScissors/Game.swift
> +        let diff: Int = randomInt - input
마찬가지로 네이밍을 고민해보면 좋을것 같아요!

2023-11-23 14:17 UTC, Marcorable commented on RockPaperScissors/RockPaperScissors/main.swift
> +Game().load()
게임 인스턴스를 생성하고 게임을 로드하는 동작을 작성해주셨네요.

따로 인스턴스를 할당하지 않은 의도가 있을까요?

2023-11-23 14:17 UTC, Marcorable commented on RockPaperScissors/RockPaperScissors/Game.swift
> +        guard let input = readLine(), let inputNum = Int(input) else {
guard 문을 이용해서 옵셔널 바인딩을 연쇄적으로 작성해주셨네요!
guard 문을 이용해서 바인딩하신 의도가 있으실까요? 
만약 특별히 없으시다면 if 바인딩으로 구현하는건 어떻게 생각하시나요?
또 다른 옵셔널 바인딩 형태는 무엇이 있을까요?

2023-11-23 14:17 UTC, Marcorable commented on RockPaperScissors/RockPaperScissors/Game.swift
> +            setInputNum()
원하는 입력이 아닌 경우에는 재귀함수를 이용해서 입력을 계속 시도하는 설계를 하셨군요.

혹시 이 구현을 가져가면 위험성이 있다는 점 알고 계신가요?
아신다면 그 위험성을 없앨 수 있는 방법의 아이디어를 고민해보면 좋을꺼같아요!
만약 모르신다면 한번 조사해보시고 고민해보셔도 좋을것 같아요!

> 너무 시간이 오래걸린다면 함께 고민해봐요! (디엠 환영합니다)

2023-11-23 14:17 UTC, Marcorable commented on RockPaperScissors/RockPaperScissors/Game.swift
> +        if [-1, 2].contains(diff) {
배열의 주어진 contains 메서드를 이용해서 값의 유무를 판별하셨군요! 좋습니다 👏🏻

2023-11-23 14:17 UTC, Marcorable commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    private var loopState: Bool = true
남겨주신 이유중에
> exit()를 사용할 수 없다는 제약사항이 있었기에 while문안에서 break를 통해 프로그램을 종료시키기로 하였습니다.

와 다른 형태여서 살짝 혼동이 있었어요!
혹시 이 형태로 구현하신 의도가 있을까요?

2023-11-24 02:20 UTC, ijs1103 commented on RockPaperScissors/RockPaperScissors/Models/Result.swift
> +}
코드가 변경되기전에는  `case none`이 필요한 상황이었으나 현상황에서는 필요없는 것 같습니다. 수정했어야 하는데 ㅠㅠ  

값에 따라 명확하게 case의 개수가 정해질때 (ex: 가위,바위,보) 혹은 rawValue를 사용 해야할 상황이라고 생각할 때 

enum을 사용하는 것 같아요

2023-11-24 02:20 UTC, ijs1103 commented on RockPaperScissors/RockPaperScissors/Models/Result.swift
> +enum Result: String {
1 : 1로 매칭되는 관계이고 enum에 type annotation을 하면 case의 이름 자체가 rawValue로 사용됩니다

2023-11-24 02:22 UTC, ijs1103 commented on RockPaperScissors/RockPaperScissors/Constant.swift
> +}
말씀하신 초기화의 위험은 `private init() {} `로 처리를 할 수 있을것 같네요. 다음부터는 꼭 적용하겠습니다 !!
상수들을 하나의 Struct로 묶으면 전역변수의 개수를 줄일 수 있다고 생각을 했습니다. 그리고 상수를 호출할때 위 코드의 경우`Constant.badInput`이 되는데요. 좀더 명시적으로 상수임을 나타낸다고 생각합니다.

2023-11-24 02:22 UTC, ijs1103 commented on RockPaperScissors/RockPaperScissors/Game.swift
> +final class Game {
final 키워드를 적용한 class는 상속을 할 수 없게 되며, 컴파일 타임에 메서드 호출이 결정되어 동적 디스패치보다 성능상의 우위에 있다고 알고 있습니다.

2023-11-24 02:22 UTC, ijs1103 commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    private var inputNum: Int = 0
넵~ 명심하겠습니다

2023-11-24 02:23 UTC, ijs1103 commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    private func calcRps(with input: Int) {
calculate를 전부 사용하기엔 길다고 생각을 해서 

제가 생각한 좀더 명시적인 함수명은 `calcResultOfRps`입니다..

2023-11-24 02:23 UTC, ijs1103 commented on RockPaperScissors/RockPaperScissors/Game.swift
> +        let diff: Int = randomInt - input
difference라고 명시적으로 변경하겠습니다 ~

2023-11-24 02:24 UTC, ijs1103 commented on RockPaperScissors/RockPaperScissors/main.swift
> +Game().load()
main 함수내에서 게임을 스타트하기 위한 목적이라서 인스턴스를 할당할 필요를 못느꼈습니다. 
클래스를 변수에 할당을 해야되는지 아닌지에 대한 정확한 근거는 없어서 ㅠ 어떤것이 좋은지는 모르겠네요 ;;

2023-11-24 02:24 UTC, ijs1103 commented on RockPaperScissors/RockPaperScissors/Game.swift
> +        guard let input = readLine(), let inputNum = Int(input) else {
guard let문을 사용하는 이유는 크게 두가지인데요. 
optional unwrapping과 early return을 하기 위함입니다. 
말씀하신대로 위 상황에서는 if let을 사용하면 else { }문 안에 있는 return 키워드를 사용하지 않아도 되서 좋을것 같습니다. 
제가 아는 opitonal binding은 if let, guard let으로 알고 있습니다.

2023-11-24 02:25 UTC, ijs1103 commented on RockPaperScissors/RockPaperScissors/Game.swift
> +            setInputNum()
넵~ 재귀함수의 위험성을 없애기 위해 무한루프에서 벗어날 수 있도록 비상탈출로를 최소 하나이상 구현해야 하는것으로 알고 있습니다

그러기 위해선 예시코드처럼 조건문 안에서 return을 하던지 아니면 반복문안에서 break, continue등을 사용할 수 있을것 같아요.

2023-11-24 02:25 UTC, ijs1103 commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    private var loopState: Bool = true
이부분은 혼동이 될 수 있게 말씀을 드린것 같아요.. 
while문안에서 빠져나간다는 얘기를 break라고 표현하였는데, 잘못 말씀 드린것 같습니다 ;; 
loopState 값을 변경해서 루프를 탈출 시키도록 구현한 이유는 while문 밖에서 접근하여 루프를 탈출 시킬수 있도록 하기 위함이었습니다.

2023-11-24 02:35 UTC, ijs1103 commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    private func playRps() {
넵 말씀하신 부분이 맞습니다 .. 
다만, playRps라고 네이밍을 한 이유는 STEP2의 묵찌빠 게임도 play를 해야하니 구분지어주기 위함 이었습니다

2023-11-24 02:48 UTC, andyanappdev commented on RockPaperScissors/RockPaperScissors/Models/Result.swift
> +enum Result: String {
Enum의 RawValue는 매칭되는 기본값을 정해서 Enum을 좀더 쉽게 활용하기 위한 방법으로 결정한다고 알고 있습니다. (Enum 타입에 또다른 정수 또는 문자열을 매칭 시켜주는 역할)

RawValue를 정의할때 hashable 한 타입은 모두 사용가능 한것으로 알고 있습니다. (대부분 ```Int```, ```String```을 사용)

이번 케이스의 경우 저희의 활용도는 게임의 결과에 따른 출력물로 활용하고자 (ex. win case의 경우 이겼습니다) 하는 의도를 가지고 결정하게 되었습니다.

활용 방법은 많이 있다고 생각합니다. 예를 들어 말씀해주신 것 처럼 동일한 내용을 사용하고 RawValue 값을 확인하여 저희가 원하는 출력물이 출력이 되도록도 가능하다고 생각합니다. 그럴 경우 그 조건을 확인하는 코드가 추가 적으로 필요하다고 생각 됩니다. 이것 또한 설계 자체를 바꾸어서 그 케이스를 처리해주는 방법도 있다고 생각 합니다.

2023-11-24 02:48 UTC, andyanappdev commented on RockPaperScissors/RockPaperScissors/Constant.swift
> +}
인스턴스가 초기화 될 가능성에 대한 위험 : private 생성자를 설정하여 외부에서 생성이 불가능하게 할수 있을것 같습니다.
저의 개인적인 의견으로는 static으로 프로퍼티를 설정 후 전역에서 접근하여 사용하는것 보다
Game이 생성될때 생성자로 주입 또는 Setter로 주입하여 사용하는 방법도 있을것 같습니다.
더 발전시킨다면 결합도를 낮추기 위해 DIP(의존성 역전, SOLID 원칙) 적용, 더 나아간다면 IoC(제어권 역전)  적용 까지 고려할수도 있겠지만 이 프로젝트에는 너무나도 과할수도 있다고는 생각 합니다.

2023-11-24 02:48 UTC, andyanappdev commented on RockPaperScissors/RockPaperScissors/Game.swift
> +final class Game {
일단 상속을 더이상 하지 않는 것이 명확한경우 final로 선언하는 것이 유리하다고 알고 있습니다.
이부분 공부한지 시간이 많이 자나서 모두다 기억이 나지는 않지만... 
</br>
default class의 경우 Table Dispatch로 작동 
- 함수의 포인터(메모리 주소)를 배열형태 보관후 실행
- 런타임에 결정, 클래스와 프로토콜에서 사용

fianl class의 경우 Direct Dispatch 작동 
- 코드 자체에 함수의 메모리 주소를 삽입 또는 함수의 명령 코드를 해당 위치에 코드를 심는다
- 컴파일 시점에 결정
- 장점 : 가장 빠른 속도
- 단점 : 다형성, 상속의 장점 적용 불가
</br>
이번 기회에 다시 한번더 정리해둔 내용을 보고 확실히 숙지하도록 하겠습니다.

2023-11-24 02:51 UTC, andyanappdev commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    private var inputNum: Int = 0
지적 사항에 100% 공감 합니다.
아직까지도 C언어 개발자들은 무조건 줄이고 간단히 쓰는 것 최고라고 생각하고 있더라구요
그 배경에는 한정된 리소스 안에서 프로그램이 돌아가야하고 사소한 하나하나 직접 다 컨트롤 해줘야 하는 언어적 특성 및 시대적 배경이 작용한것으로 알고 있습니다.
하지만 요즘 하드웨어의 급격한 발전함에 따라 확실히 리소스 부분에는 조금은 자유로워 진것 같다는게 저의 개인적인 생각 입니다
Swift API Design Guidelines 의 특히 Naming 부분을 다시 한번더 숙지하고 항상 따르는 습관을 기르도록 하겠습니다.

2023-11-24 04:14 UTC, andyanappdev commented on RockPaperScissors/RockPaperScissors/Game.swift
> +
LJ 코드를 작성할때 스타일이라고 하셔서 이번 저희 프로젝트에 한번 적용시켜 보자고 의견을 일치 했습니다.
이번 프로젝트에 적용한 간단한 코드 컨벤션 등을 프로젝트 그룹토의 페이지에 정리를 해두었습니다.
물론 진행하면서 추가할 부분 또는 그 반대의 경우가 발생할 경우 수정 하면서 적용하려고 합니다.
노션 페이지 : https://www.notion.so/tastycode/adb63c8e85a949f9849339a9dd7194f6?pvs=4

2023-11-24 07:16 UTC, andyanappdev commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    private func calcRps(with input: Int) {
즐임말 네이밍 관련된 부분 모두 수정하도록 하겠습니다.

저는 메서드가 어떻게 설계되어 작동하는지 그 역할과 용도에 따라 네이밍을 결정하는 것이 적절하다고 생각합니다. 
(메서드에 어떤 값이 전달되어 작동하는 지, 또는 어떤 값을 리턴하여 이 리턴값이 어디에 사용되는지 등에 따라 메서드의 역활을 표현하는 네이밍)
저희의 의견물 물어보신 포인트에 저의 답변이 부합하지 않는다고 생각 합니다만
저의 기본적인 생각과 원칙을 먼저 알려 드리고 세부적인 사항을 같이 논의하는것이 우선이라 판단 하였기 때문입니다.
이번 케이스의 경우 저는 게임결과전달 이런 느낌으로 할것 같습니다.
이유는 가위바위보 게임 계산 결과를 setResult에게 넘겨주고 있기 때문입니다.

2023-11-24 07:27 UTC, andyanappdev commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    }
사실 이부분에서 많은 이야기를 LJ와 나누었습니다.
이번 프로젝트의 Core에 해당되는 부분이기 때문에 가장 많은 대화를 한것 같습니다.

LJ의 아이디어가 정말 신선하고 저는 한번도 생각 조차 해보지 못한 접근 방법으로 풀어 가는것에 놀랬습니다.
그렇기에 저는 로직을 이해하는 부분에서 부터 진입장벽이 있었습니다.
그렇다면 다른 개발자가 이 코드를 본다면 이해할수 있을까? 하는 생각이 들었습니다.
그래서 좀더 명확하게 누가 보더라고 알아 볼수 있는 방법에 대해서 논의를 하였으나
LJ의 아이디어를 살리면서 로직이 누구나 이해할수 있도록 수정하는 것에는 실패 하였습니다.

혹시 이부분에 좋은 아이디어가 있으신지요? 궁금합니다.
if else 또는 switch 부분은 다시 설계 하겠습니다.

2023-11-24 07:37 UTC, andyanappdev commented on RockPaperScissors/RockPaperScissors/Game.swift
> +        guard let input = readLine(), let inputNum = Int(input) else {
옵셔널 바인딩
바인딩(상수나 변수에 할당)에 성공한다면 특정작업을 하겠다는 의미로
옵셔널 타입이 새로운 상수에 할당이 된다면 (nil 안담김, value가 있으면 담김) 새로운 상수에 담긴 value를 사용할수 있됩니다. (value가 있을 경우 옵셔널 타입이 일반 타입으로 추출되어 담기게 됨)
if let 바인딩 : if 조건으로 nil 체크 하는 원리
guard let 바인딩 : if let 바인딩과의 가장큰 차이는 담긴 상수의 사용가능 scope 차이라고 알고 있습니다.

2023-11-24 11:59 UTC, keeplo commented on RockPaperScissors/RockPaperScissors/Models/Result.swift
> +}
아아 수정중에 남겨진 부분이군요! 다음 수정때 같이 고려해서 변경해주세요

음 흥미로운 답변이에요 rawValue를 사용해야 할 상황
그런 상황은 어떤경우가 있을까요? 혹시 예시를 알려주실수 있으신가요?

2023-11-24 12:14 UTC, keeplo commented on RockPaperScissors/RockPaperScissors/Models/Result.swift
> +enum Result: String {
두 분 다 enum 에 대해 잘 이해하고 계시네요!

제가 질문드린 이유는 앤디의 마지막 문단에서 말씀해주신것과 연관되어있어요.
사실 구현하면 하는데로 활용 방법은 많을 수 있어요
그렇다보니 만약 rawValue를 두 분 처럼 사용하기로 결정한다면  
그 팀에서는 프로젝트 마다, 다른 모듈마다 동일한 방식을 고수해줘야 혼동을 주지 않을텐데
출력을 위한 문자열이 매번 rawValue 로 쓰여야한다거나 반대로 다른곳에서 또 사용된다면 불편할 수 있다고 생각해요

Swift 언어에서 `CustomStringConvertible` 프로퍼티를 제공하는데
이걸 이용해서 그 개체를 문자열로 표현해준다는 명시도 가능하고 주로 사용하고 있어요

앞서 말씀드린 부분을 한번 고민해보시면 좋을것 같아요!

아 물론 정답은 없습니다 ㅎㅎ 팀바팀 사바사

2023-11-24 12:31 UTC, keeplo commented on RockPaperScissors/RockPaperScissors/Constant.swift
> +}
오오 private init()을 사용하는 방법도 아주 좋네요! ㅎㅎ
static 만 사용하는 경우엔 enum 선언으로 하는 경우도 꽤 봤었어요 ㅎ

함수명에 관해 이야기할때와 유사한 질문인데 
상수 임을 명시하는 부분이 중요할까요? 아니면 용도를 명시하는게 더 중요할까요? 
두 분은 네이밍을 하는데서 어떤점이 더 중요하다고 생각하시는지 궁금하네요!

앤디의 답변처럼 static이 아니라 주입형태나 프로퍼티 형태로 상수를 사용할 수도 있을것 같은데
어떤 차이가 있을지 고민해보신적 있으신가요? 각 선택에 대한 장단점이 있다고 생각하시나요?
성능적인 차이는 없을까요?

2023-11-24 12:44 UTC, Marcorable commented on RockPaperScissors/RockPaperScissors/Game.swift
> +final class Game {
두 분다 개념을 명확히 파악하고 계시네요!

선물로 좋은 아티클 전달합니다 이미 보셨을수도 있지만..
[Increasing Performance by Reducing Dynamic Dispatch](https://developer.apple.com/swift/blog/?id=27)

Table Dispatch라는 용어는 처음보는것 같은데 혹시 `Witness Table` 를 말씀하시는 걸까요?
말씀하신 것처럼 면접 질문에서 답할 수 있게 명확하게 용어정리를 한번 해보면 좋을것 같아요!

2023-11-24 12:52 UTC, keeplo commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    private var inputNum: Int = 0
저는 여기에 관심이 많은 편이라 좀 더 말씀드리자면..

물론 개인적인 경험이지만 프로그래밍 언어론이란 수업을 들을때
교수님의 말이 기억에 남는데 말씀드리고 싶어요
비트 단위를 어셈블리어로 고급언어로 발전해온 목적은 결국 사람의 언어 -> 컴퓨터로 전달
이 목적이라 근데 그 대단한 일을 하는게 영어권으로 진행되다보니
영어로 말하듯 작성되는게 가장 언어를 만드는 사람의 목표가 아닐까 생각한다고 하셨어요

저는 좀 공감하는 편이라서 뭔가 숫자나 기호, 괄호가 많은 코드보다
문장 읽듣 코드를 읽고 바로 이해가 되는 코드가 좋은 코드가 아닐까 생각하는 편입니다!

네이밍의 목적이 결국 `지금을 잊은 미래의 나`, 또는 `동료`, `내 레거시를 마주할 어떤 개발자` 에 대한 배려와
시간 절약이라는 이득이라고 생각해요!

[클린 코드(Clean Code)](https://ebook.insightbook.co.kr/book/79)
혹시 안 읽어 보셨다면 TODO에 적으시고 읽어보셨다면 이런 부분에 관련된 아티클이 생각보다 많아요
한번 깊게 파보고 개발자로써의 철학을 하나씩 만들어보시는것도 추천합니다 ㅎ

2023-11-24 12:53 UTC, keeplo commented on RockPaperScissors/RockPaperScissors/Game.swift
> +
오우 아주 좋습니다!!

2023-11-24 12:57 UTC, Marcorable commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    private func playRps() {
저희에겐 Step 2라는 예상이 가능했지만, 미래를 생각해서 범용적인 네이밍을 하는것 너무 좋은것 같아요!

음 그런점을 고려해도 RPS 같은 줄임말은 피하는 편이 좋을것 같아요!

2023-11-24 13:02 UTC, keeplo commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    private func calcRps(with input: Int) {
Swift API Design Guidelines 에서 언급되기 때문에
함수명이 영어문법에 부합하는 동사 형태라거나 줄임말을 사용하지 않는 부분은 필수적으로 지켜야하는 부분이라고 생각해요!

두 분의 생각이나 두 분의 의견을 일치해서 팀 컨벤션으로 명칭에 기준이 잡히면 그걸로 충분하다고 생각합니다
앤디 말씀처럼 작성되는 방향도 아주 좋을것 같아요!

Swift API Design Guidelines 여기에 파라미터 관련해서도 자세히 있으시 참고해보시면 좋을것 같아요

2023-11-24 13:13 UTC, keeplo commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    }
제가 뭔가 명확하게 전달을 한게 맞나 싶어서 다시 언급하자면

if 문에 관해서만 재설계를 요청드리고 싶습니다! 

아이디어 저는 아주 좋다고 생각해요
처음 아이디어 채택부터 설계까지 저는 너무 좋은 흐름이라고 생각해요

고수해주시는게 좋을것 같고, 

다양한 경험은 좋은거니 제가 프로젝트 진행할때 
저희 팀원의 아이디어로 진행했던 다른 스타일은
프로젝트 마칠때 보여드릴게요! ㅎㅎ 

이 프로젝트가 그리 어려운 로직은 아니지만, 다양한 방면으로 고민해보신다니 너무 좋네요
이 작은 경험이 앞으로 개발인생에 큰도움이 될거라 확신합니다!! 🔥

2023-11-24 13:15 UTC, keeplo commented on RockPaperScissors/RockPaperScissors/main.swift
> +Game().load()
음 좋은게 있어서 드린 질문은 아니구요! ㅎㅎ
답변해 주신 이유면 충분합니다!

변수에 할당해서 유지하는것과 아닌것 차이점을 잠시나마 생각해본것만으로도 충분할것 같아요!

2023-11-24 13:15 UTC, Marcorable commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    private var loopState: Bool = true
아아 키워드라기보다 동작으로써 말씀해주신거군요 이해했습니다!

2023-11-24 13:18 UTC, keeplo commented on RockPaperScissors/RockPaperScissors/Game.swift
> +            setInputNum()
처음이네요! ㅎㅎ

제가 원하는 대답이 아닙니다! ㅎㅎㅎ
무한루프는 아주 표면적인 위험성이라 생각합니다!

조금 힌트드리자면 while 문으로 구현하시면 위험하지 않는데 지금 구조의 재귀함수로 구현하면 위험합니다.
추가로 재귀함수인데 `꼬리재귀` 키워드도 아시나요? 이 부분도 이해하면서 
다시 고민해보시면 좋을 것 같아요!

2023-11-24 13:23 UTC, keeplo commented on RockPaperScissors/RockPaperScissors/Game.swift
> +        guard let input = readLine(), let inputNum = Int(input) else {
두 분 모두 옵셔널 바인딩에 대한 이해를 명확히 가지고 계시네요!
지금 구현해주신 것처럼 guard 라는 키워드가 Early Return 같은 의도를 가지고 사용한다면
이 또한 코드의 흐름에서 중요한 소통 도구가 될 수 있어요!

일례로 저희 팀에서는 옵셔널 바인딩을 하고 메서드에 전달과 옵셔널 타입 인수 전달 중에
후자를 선택하고 guard 문을 메서드 초입에 항상 배치하는 등의 컨벤션을 가지기도 합니다.

2023-11-27 01:16 UTC, andyanappdev commented on RockPaperScissors/RockPaperScissors/Models/Result.swift
> +enum Result: String {
CustomStringConvertible Protocol을 알려 주셔서 감사합니다.
특정한 상황의 출력물을 정의하여 사용하는 좋은 방법인것 같습니다.
공부해서 정리하고 사용 예제를 찾아보면서 학습하여
다음 프로젝트에 적용해 보도록 하겠습니다.

2023-11-27 01:17 UTC, ijs1103 commented on RockPaperScissors/RockPaperScissors/Constant.swift
> +}
용도를 명시하는게 더 중요합니다. 현재 프로젝트에서 Constant라고 한 이유는 상수의 개수가 적어서였는데, 좀더 명시적으로 용도를 의미하는 상수 Naming을 하는게 더 좋을것 같습니다. 주입형태로 상수를 사용하면 테스트코드 작성에 용이할것 같습니다. 상수를 구조체로 분리하는 경우, 코드가 간결해지는 장점은 있는것 같습니다. 성능적인 부분은 미처 생각하지 못하였네요. 잘 모르겠습니다 ;;

2023-11-27 01:38 UTC, ijs1103 commented on RockPaperScissors/RockPaperScissors/Models/Result.swift
> +}
제 원래 의도는 'rawValue를 사용하면 좀 더 편리할 것 같다는 상황에 enum을 사용한다'는 말씀을 드리고 싶었는데 .. 

오해를 불러일으킬 수 있게 말씀드린것 같네요

enum의 각 case에 Int나 String을 매칭시키는 상황에서 rawValue를 사용하는 편입니다.

enum을 반드시 사용하는 상황이라면 네트워킹을 할 때 Model에 CodingKeys를 적용할 때인 것 같습니다.

2023-11-27 01:40 UTC, ijs1103 commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    private func playRps() {
넵 앞으로 줄임말은 최대한 생략하는 방향으로 네이밍을 해보겠습니다 !!

2023-11-27 01:46 UTC, andyanappdev commented on RockPaperScissors/RockPaperScissors/Constant.swift
> +}
저의 경우에는 무조건 용도를 명시하는것이 더 중요하다고 생각 합니다.
아래의 네이밍관련 저의 생각을 말씀 드렸듯이 역활 = 용도에 적합하도록 변경하도록 하겠습니다.
struct prompt 로 변경 (promptPrint, printPrompt)

주입하게 되면 의존성이나 결합도를 고려해야 할것 같고
mock 객체 주입 가능한 장점을 가져 갈수 있을것 같습니다.
Game 클래스 내에 프로퍼티 형태로 정의해서 사용했을 경우
메모리 운용의 장점(성능적인 차이)에 대해서는 솔직하게 정확하게 모르겠습니다. ㅜㅜ
이부분은 곰곰히 그림을 그려보면서 자료를 찾아볼 필요성이 있다고 생각 합니다.

2023-11-27 01:52 UTC, andyanappdev commented on RockPaperScissors/RockPaperScissors/Game.swift
> +final class Game {
Table Dispatch (동적 / Dynamic)
클래스나 프로토콜의 경우 테이블 형태? 메모리 주소를 배열형태로 보관 한다는 의미에 Table Dispatch 라고도 부를수 있다고 예전에 학습하면서 메모를 해둔 적이 있어서... 이번 기회에 다시 한번 찾아 보겠습니다.
클래스 테이블이 Virture Table
프로토콜 테이블 Witness Table

2023-11-27 01:54 UTC, ijs1103 commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    }
넵, switch문이나 if else문으로 변경하는것으로 해보겠습니다. 

리뷰어님이 해결하신 방식이 많이 궁금해지네요 ...ㅎㅎ 얼릉 봤으면 합니다

저희도 덕분에 다양한 방면으로 고민해보고 시도해볼수 있게 되었네요. 감사합니다 ~

2023-11-27 01:59 UTC, andyanappdev commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    private var inputNum: Int = 0
감사 합니다
관련된 부분에 저도 관심을 가지고 있어 책도 구입했지만 아직 정독완료 하지 못한 상태이긴 합니다.
좀더 깊이 고민하고 생각해 가면서 저만의 이유 있는 철학을 만들어 가겠습니다.

2023-11-27 06:25 UTC, ijs1103 commented on RockPaperScissors/RockPaperScissors/Game.swift
> +            setInputNum()
`꼬리재귀`라는 개념을 처음 알게 되었고, 찾아보니 어떠한 개념인지는 이해가 갔으나 저희 프로젝트에 적용하기가 쉽지가 않아서요.. 

혹시 힌트를 좀 얻을 수 있을까요? ;;ㅎ

2023-11-27 06:42 UTC, andyanappdev commented on RockPaperScissors/RockPaperScissors/Game.swift
> +        let diff: Int = randomInt - input
재귀 함수에서는 함수 호출이 스택에 계속 쌓이게 되는데, 이러한 스택의 쌓임이 많아질 경우 메모리를 많이 사용하고 성능에 영향을 미치지만 이를 해결? 최적화 하기 위해 꼬리재귀를 활용한다는 이론적인 내용만 인지 하고 있습니다.
(꼬리 재귀는 함수 호출 후 더 이상 수행할 작업이 없는 경우, 이전 호출 스택 프레임을 재사용하고 추가적인 스택 프레임을 쌓지 않는 방식으로 최적화)
아직 재귀에 대한 충분한 지식과 학습이 없어 명확히 이해를 못하고 있습니다.

2023-11-27 11:34 UTC, keeplo commented on RockPaperScissors/RockPaperScissors/Constant.swift
> +}
단순히 코드레벨로 바라보는게 현 프로젝트에서는 큰 문제가 없지만
큰 규모에 프로젝트인데 메모리 구조 이해가 없으면 성능에 부담을 줄 것 같아요

> `class` 인스턴스의 프로퍼티
> `struct` 인스턴스의 프로퍼티
> `static` 또는 `class` (정적) 프로퍼티

이런 할당 변수 또는 상수가 메모리 구조에서 어디에 할당되는지
조사해보면 좋을것 같아요!

2023-11-27 11:38 UTC, andyanappdev commented on RockPaperScissors/RockPaperScissors/Constant.swift
> +}
네 알겠습니다.
포인트를 알려 주셨으니 공부해서 정리해 두도록 하겠습니다
감사합니다.

2023-11-27 11:44 UTC, keeplo commented on RockPaperScissors/RockPaperScissors/Game.swift
> +            setInputNum()
함수 (function) 의 동작원리에 대해 이해가 필요합니다.
> 이 부분을 설명해주시면 좋을것 같아요 만약 어려우시면 디엠주세요!

---

위 내용을 아신다는 전제로 설명을 드리자면
함수가 return 되지 않고 계속 함수 호출부의 주소값이 메모리 Stack에 쌓입니다.
물론 최악의 경우라지만 `StackOverflow` 가 필연적으로 발생하는 구조에요
코드에서는 확률이 낮다고 해서 오류가 나지 않지 않기 때문에 

현재 재귀 구조는 가능하면 `반복문` 또는 `꼬리재귀` 형태로 변경하는 쪽이 좋습니다.

이번 Step에서 반복문 구조와 꼬리재귀 구조로 모두 구현해내는게 좋을것 같습니다! 다시 예시를 보시고 Swift 언어 형태로 프로젝트에 녹여주세요!

2023-11-27 11:47 UTC, keeplo commented on RockPaperScissors/RockPaperScissors/Game.swift
> +        let diff: Int = randomInt - input
어떤 `문제`가 발생하는지, 현재 구현된 재귀형태와 달리 꼬리재귀 형태는 왜 문제가 발생하지 않는지 이번 Step 에서 정확히 이해하고 넘어가는게 좋을것 같아요!

조금 더 이해하고 리펙토리를 해보는게 좋을것 같습니다
[duplicate comment](https://github.com/tasty-code/ios-rock-scissor-paper/pull/45#discussion_r1406041697)

2023-11-27 11:51 UTC, keeplo requested changes

2023-11-27 11:51 UTC, keeplo commented on RockPaperScissors/RockPaperScissors/Prompt.swift
> +    static let RockScissorsPaperChoice: String = "가위(1), 바위(2), 보(3)! <종료 : 0> :"
프로퍼티 네이밍은 소문자로 시작해주세요!

2023-11-27 14:17 UTC, ijs1103 commented on RockPaperScissors/RockPaperScissors/Prompt.swift
> +    static let RockScissorsPaperChoice: String = "가위(1), 바위(2), 보(3)! <종료 : 0> :"
넵 소문자로 수정하였습니다

2023-11-28 00:35 UTC, ijs1103 commented on RockPaperScissors/RockPaperScissors/Constant.swift
> +}
넵 메모리 관련해서 정리하고 숙지하도록 하겠습니다. 감사합니다 ~!

2023-11-28 01:23 UTC, ijs1103 commented on RockPaperScissors/RockPaperScissors/Game.swift
> +            setInputNum()
while문을 적용하여 재귀함수의 구조를 수정해보았습니다. 
continue와 break를 통해 재귀함수의 무한호출을 방지하는 방향으로 코드를 작성해보았습니다. 
꼬리재귀는 좀 더 체화시켜서 다음 기회에 적용 해보겠습니다 !!

2023-11-28 07:38 UTC, merged