묵찌빠 프로그램 [STEP 1] loffy, hoi
tasty-code/ios-rock-scissor-paper pull request #46
Opened 2023-11-23 09:33 UTC by kimdj1102

## 시작전에...

담당 리뷰어 : @junbangg (알라딘)
팀원: @kimdj1102 (loffy), @happykwon (hoi)

### 인사말
- loffy : 안녕하세요 알라딘! 인생 첫 PR이라 정말 떨리네요🤣 부족하지만 잘 부탁드립니다. 피드백으로 최대한 많은 정보를 얻어가서 성장하고 싶습니다!
- hoi: 안녕하세요 Hoi입니다. 잘부탁드립니다. 감사합니다.

## 코드에 관하여 

### 순서도 
<img width="400" alt="codeFlow" src="https://github.com/tasty-code/ios-rock-scissor-paper/assets/12614929/b4e93250-de4b-42c8-b02b-4cd68e7b30bf">

---
### 코드 구성 요소

> ### enum 
#### 1. ChoiceMenu
- 사용자가 입력하는 값을 분류하는 열거형 타입
- Int변환 하는 과정을 생략하기 위해 String타입으로 선언
- 가위, 바위, 보, 종료는 rawValue값 설정
- 그 외의 값은 other케이스에 해당

#### 2. Result
- 결과를 출력하는 값을 분류하는 열거형 타입
- 이김, 짐, 비김 각각의 case에 rawValue값 설정
 
> ### method
#### 1. startMessage()
- 일은 코드에게 시켜라"라는 야곰의 말을 듣고 최대한 method를 사용해서 동작하게 하고 싶어서 추가

#### 2. action()
- 유저와 컴퓨터 입력값에 대한 처리를 위한 method

#### 3. startGame()
- 이번 프로젝트의 가위바위보 각각에 대한 분기처리를 위한 method

#### 4. endGame() 
- 중복되는 부분이 많아서 함수로 따로 선언
- 게임종료 안내 출력 후 'isWorking'값 반전 (while문 종료를 위함)

> ### etc
#### 1. isWorking
- while문 실행여부를 결정하는 Bool값 변수
- 기본값은 true로 할당

#### 2. rps
- 컴퓨터가 선택할 수 있는 선택지를 담은 String타입 배열
- randomElement()를 사용해 선택지 중 한개를 랜덤으로 추출 (기본값 : "") 

#### 3. while문
- isWorking이 참일때 계속 실행
- if let을 사용해 사용자 입력값(readLine()) Optional Wrapping
- 그 후 action함수 호출
    - ChoiceMenu Enum타입의 rawValue값을 매개변수로 받음
    - comChoice의 기본값 : .scissor(가위) (임의로 설정)
    - userChoice의 기본값 : .ohter (0~3이외의 값을 입력받을 시 처리해주기 위함)
    
---
### 고민했던 점
#### loffi
1. 최대한 순서도에 작성한대로 로직을 짜려고 고민해보았습니다. 그 결과 한 함수당 한 개의 기능씩 최소 단위로 구현을 하려고 해보았습니다.

2. print출력값들을 enum타입으로 선언해서 사용해 보았습니다.
    - 이겼습니다! 문구 출력 시 `print("이겼습니다!")` 에서`print("Result.win.rawValue")`로 변경 
3. action 함수에서 사용자의 입력값을 받을 때 나올 수 있는 모든 경우의 수 (3가지)를 다 처리해보려고 시도했습니다. 
    - 그 결과 ChoiceMenu enum에 other를 선언
    - action함수로 모든 경우의 수 처리가능하게 됨

4. 가위바위보를 enum으로 설정해 보다 직관적으로 게임 결과를 연산하도록 함
   `comPick == 1 && userPick == 2`에서 `comPick == .scissor && userPick == .rock`로 변경

#### hoi
1. 더 줄일 방법을 고민해봤지만 떠오르는 방법이 없어서 포기했습니다.
```Swift =
 else if (comPick == .scissor && userPick == .rock) ||
                (comPick == .rock && userPick == .paper) ||
                (comPick == .paper && userPick == .scissor)
```

2. enum / struct중 써야할지 고민을 했고, 명확한 기준이 있고 구분이 가능하기 때문에 enum타입을 채택하였습니다. 
```Swift=
enum ChoiceMenu: String {
    case scissor = "1" , rock = "2", paper = "3", exit = "0"
    case other
```

```Swift=
enum Result: String {
    case win = "이겼습니다!"
    case lose = "졌습니다!"
    case draw = "비겼습니다!"
}
```

3. 최대한 단일 책임 원칙(SRP)를 해보려고 노력하였습니다.

---
### 조언을 얻고 싶은 부분
#### loffi
```
enum Result: String {
    case start = "가위(1), 바위(2), 보(3)! <종료: 0> : "
    case win = "이겼습니다!"
    case lose = "졌습니다!"
    case draw = "비겼습니다!"
    case exit = "게임 종료"
    case error = "잘못된 입력입니다. 다시 시도해주세요."
}

func printMessage(a: Result) {
    switch a {
    case .start:
        print(Result.start.rawValue, terminator: "")
    case .win:
        print(Result.win.rawValue)
    case .lose:
        print(Result.lose.rawValue)
    case .draw:
        print(Result.draw.rawValue)
    case .exit:
        print(Result.exit.rawValue)
    case .error:
        print(Result.error.rawValue)
    }
}
```
-  message를 출력하는 함수를 따로 만들어서 모든 메세지를 출력하게 끔하는 코드를 짜보았습니다.
    - enum타입으로 모든 경우의 수를 선언하고
    - 메세지 출력함수로 enum타입을 매개변수로 받아 rawValue를 출력
    - 코드가 조금 많이 길어질 것 같아서 반영하지는 않았는데, `효율적인 코드인지 궁금합니다!`
    
- while문을 사용해서 계속 실행이 되도록 했는데, 혹시 다른 방법이 있을지 궁금합니다. 재귀함수를 사용하는 방법은 알긴하는데, 이 while문을 재귀함수로 변경하려고 하니 잘 되지 않았습니다 😭 혹시 while문과 재귀함수 중 '어떤 방법이 더 효율적이다' 이런 경우가 있을까요? 제가 알기로는 이정도로 알고있습니다.
    - 재귀함수를 사용하면 코드의 가독성 향상
    - 반복문보다 더 단순함
    - 하지만 재귀의 깊이가 깊어지면 속도가 느려지고 과정이 복잡해짐

#### hoi
```Swift=
while isWorking {
    
    startMessage()
    
    func getUserChoice() -> ChoiceMenu? {
        
        guard let userChoice = readLine(), ["0","1", "2", "3"].contains(userChoice) else {
            return .other
        }
        return ChoiceMenu(rawValue:userChoice )
    }
    
    guard let userChoice = getUserChoice() else { continue }
    
    let comChoice = ChoiceMenu(rawValue: ["1", "2", "3"].randomElement() ?? "") ?? .other
    
    action(com: comChoice, user: userChoice)
    
}
```
- 위코드는 while isWorking절을 if let 에서 guard let으로 변경한 코드입니다.
if let 보다는 guard let을 의식적으로 사용하는게 좋다고 들었는데 이거에 어떤 코드가 더 좋은 코드인지 그리고 그 이유는 무엇인지 궁금합니다.

2023-11-23 16:48 UTC, junbangg requested changes
첫번째 PR 너무 고생 많으셨습니다!!
꼼꼼하게 작성하신 리드미 너무 좋습니다~~👍
문서화의 중요성을 또 배워가네요:)

그리고 리드미에 적어주신것 처럼 최대한 단일 책임 원칙(SRP)을 해보려고 노력하신거 아주 칭찬해요!!
코드에서도 고민이 느껴졌어요!
앞으로도 SRP에 대해서는 지속적으로 공부하고 연습하시는걸 적극 추천드립니다👍 (굉장히 중요하기 때문에)


질문 주신것에 대해 남길게요!

> 1. 더 줄일 방법을 고민해봤지만 떠오르는 방법이 없어서 포기했습니다.

요건 그냥 코드 댓글로 남길게요 :) 

> message를 출력하는 함수를 따로 만들어서 모든 메세지를 출력하게 끔하는 코드를 짜보았습니다.

요 부분에 대해서도 제가 리뷰 코멘트를 남겼는데요! 거기서 한번 대화를 이어 나가는게 좋을것 같네요~
그리고
`코드가 조금 많이 길어질 것 같아서 반영하지는 않았는데, 효율적인 코드인지 궁금합니다!`
이렇게 적어주셨는데! 
어떤 것을 반영하지 않으신건지~ 그리고 말씀하신 "효율적인 코드" 가 어떤것인지 설명 간단하게 해주시면 답변 드리기 조금 더 쉬울것 같습니당

> 재귀 vs while

말씀하신것 전부 맞습니다~
보통 재귀는 어떤 경우에는 간단하고~ 이해하기 쉬운 경우가 있을 수 있죠!
그러나 단점도 분명히 있습니다~ 

1. 복잡해질 수록 디버깅이 어려워진다(iteration 대비)
2. 조금 더 비효율적이긴 하다
- 이미 알고 계실 수도 있겠지만( 궁금하시면 따로 공부를 해보셔도 아아주 좋을것 같습니다)
재귀는 매번 호출될때마다 스택 메모리를 조금씩 사용하게 됩니다~  call stack 에 호출이 하나씩 쌓이게 되면서 동작을 하거든요!  어찌 됐든 오버헤드가 조금 더 발생하는거니까 덜 효율적인 방법은 맞을지도 모르겠네요..! 코딩테스트 공부하실때나, 메모리 구조 공부하실때 한번 더 고민 해보시는것도 좋을것 같네요:)
3. 잘못 짜면 위험하다.
- 그래서 만약에 재귀 함수를 잘못 짠다면, 영영 탈출을 못해서 그 유명한 **stack overflow** 가 발생할 수도 있습니다~ 


장단점이 있고 필요할때는 또 좋은 방법이 될 수도 있겠죠ㅎㅎ

> if let 보다는 guard let을 의식적으로 사용하는게 좋다고 들었는데 이거에 어떤 코드가 더 좋은 코드인지 그리고 그 이유는 무엇인지 궁금합니다.

흠 의식적으로 사용하기 좋은 쪽을 선택해서 사용하는것은 사실 사용하는 근거가 되기는 힘들것 같아요..!
if let 을 사용하는거랑, guard let 을 사용하는거랑 각각 필요한 경우가 분명히 있습니다! 
그 차이점을 한번 고민 해보고 기준을 세워두시는게 좋을것 같습니다:) 
한번 고민해보시고 말씀 주시면 같이 이야기 나눠보시죠!

2023-11-23 16:48 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/main.swift
> +        action(com: ChoiceMenu(rawValue: comChoice) ?? .scissor, user: ChoiceMenu(rawValue: userChoice) ?? .other)
옵셔널의 Default 값으로 ✌️랑 other를 설정 해주셨는데 특별한 이유가 있을까요?!

2023-11-23 16:48 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/main.swift
> +func action(com: ChoiceMenu, user: ChoiceMenu) {
action 이라는 이름만 봐서는 이게 무슨 일을 하는 메서드인지 조금은 알기 어려운것 같아요 개인적으로는..!메서드명이 조금 더 구체적이면 좋을것 같습니다!

2023-11-23 16:48 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/main.swift
> +func action(com: ChoiceMenu, user: ChoiceMenu) {
파라미터 com, user 이 뭔지 설명 부탁드립니다~🙏

2023-11-23 16:48 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/main.swift
> +    case other
여기서 other 는 뭔가요?! 가위, 바위, 보, other(?!)

2023-11-23 16:48 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/main.swift
> +        print("잘못된 입력입니다. 다ls시 시도해주세요.")
아하 other 이 여기서 나타나는군요??🤔
아까 저어 위에 있는 Enum 만 봤을때! other 이 어떤건지 설명이 되는 이름을 한번 생각해보는것도 좋을것 같습니당

2023-11-23 16:48 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/main.swift
> +        print("잘못된 입력입니다. 다ls시 시도해주세요.")
다ls시 !?!

2023-11-23 16:48 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
위에서도 사용을 하셨지만~ Struct 도 있고 Class 도 있는데 왜 enum 을 선택하신건가요??  (틀렸다는것은 절대 아닙니다~!🙅‍♂️)  
차이점에 대해서 비교를 해보고 선택 하신건지 궁금합니다~

리드미에 `enum / struct중 써야할지 고민을 했고, 명확한 기준이 있고 구분이 가능하기 때문에 enum타입을 채택하였습니다.` 라고 적어주셨는데

`명확한 기준이 있고 구분이 가능하기 때문에`  가 어떤것인지 궁금해요:)

2023-11-23 16:48 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/main.swift
> +    case scissor = "1" , rock = "2", paper = "3", exit = "0"
작은 궁금증이 하나 있는데요~
10번째 줄은 한줄로 처리를 하시고, 11번째 줄에 있는 other만 왕따 시킨 이유가 있을까요??? (틀렸다는 것은 아닙니다~)

2023-11-23 16:48 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/main.swift
> +let rps: [String] = ["1", "2", "3"]
흠 rps 가 뭔지 고민을 해봤는데요! rock paper scissor일 가능성이 높겠죠 아무래도?
지금은 추론할 방법이 있어서 그렇게 나쁘지만은 않지만! 

코드가 방대해지고 복잡해질 수록 네이밍 엄청 신경 쓴 코드도 읽기가 정말 힘들어지더라고요🥲(저만 그런걸지도 모르지만..)
특히 이 코드를 최초로 작성하지않은 다른 동료가 나아아중에 버그를 고친다거나~ 새로운 기능을 붙인다거나~ 하는 상황이 오면
친절한 네이밍일 수록 그 동료가 빠르게, 그리고 명확하게 코드가 작성된 배경과 의도를 이해하는 데 큰 도움을 줍니다. 생산성을 도와주는 일이죠👍
동료의 생산성이 곧 팀의 생산성이고 쫌 더 오바하자면 회사의 비용을 줄여주는걸로도 생각할 수도 있겠어요!

결론은, 한눈에 이해가 된다면!  조금은 긴 변수명이 오히려 좋다고 생각합니다~👍
["1", "2", "3"] 을 표현할 조금 더 나은 이름은 없을까요??

2023-11-23 16:48 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/main.swift
> +    if let userChoice = readLine() {
61번째 줄에 타입을 명시 해주셨는데요~ 63번째 줄에서는 안한 이유가 있을까요??? (틀렸다는거 아님)

2023-11-23 16:48 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/main.swift
> +        print(Result.lose.rawValue)
곧곧에 rawValue 라는 친구가 보이는데요!
Result 라는 enum 으로 jump to definition 안하고 딱! 이 코드만 봤을때~
rawValue 만 보고 rawValue가 뭔지 알 수가 있을까요?? (코드를 처음 보는 동료가 봤다고 상상해봤을때🤔)

요런 불편함을 해소할 수 있는 방법에는 뭐가 있을까요?? (저는 두가지 방법이 생각나요!)

2023-11-23 16:48 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/main.swift
> +    case scissor = "1" , rock = "2", paper = "3", exit = "0"
요 enum 을 보면서 제가 약간 어색함을 느낀 부분이 있는데요! 
한번 들어봐주세요

enum의 이름은 ChoiceMenu이고
각 case 는 scissor, rock, paper, exit, other 이며
rawValue 는 String의 형태를 하고있는 숫자 1,2,3,0

개인적으로 약간 짬뽕의 맛이 나는데🤔 
혹시 요렇게 타입이 설계된 이유가 있을까요??

2023-11-23 16:48 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/main.swift
> +let rps: [String] = ["1", "2", "3"]
https://www.swift.org/documentation/api-design-guidelines/ 

요 문서를 잘 읽어보시면 네이밍에 대한 가이드도 있습니다! 🙌

2023-11-23 16:48 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/main.swift
> +                (comPick == .paper && userPick == .scissor)
오 이거 Read Me에 남겨주신 내용이군요??
여기서 말씀드릴 수 있는것은 두가지가 있을것 같아요!

1. 단순히 조금 코드를 깔끔하게 줄일 방법으로는~ 요 기다란 else if 문을 Bool 변수로 빼도 되지 않을까요??

2. 지금 조건문을 이용해서 게임 결과를 도출(?) 해서 print(Result.draw.rawValue) 를 바로 하고 계신데, Result 를 계산해주는 메서드를 하나 만드는건 어떠신가요?? print 를 한번만 해도 되게 설계를 하는거죠

예를 들어 요런 느낌인거죠

let result: Result = 기똥찬메서드명(comPick, userPick)
print(result.rawValue)

2023-11-23 17:08 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let comChoice: String = rps.randomElement() ?? ""
옵셔널 default 값으로 "" 를 하셨는데
"" 더라도 처리가 되는것인가요?? (의도가 있는 "" 인지 궁금합니다 :) )

2023-11-24 07:16 UTC, happykwon commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
가위바위보 프로젝트는  (가위 / 바위 / 보)에 따라 (졌다/이겼다/비겼다/잘못입력했다)라는 결과를 명확하게 구분이 가능하고, 따라서 enum타입을 사용하면 아래와 같은 이점이 있다고 생각했습니다. 

1.  직관적인 코드
2.  case의 가지수가 적어 enum타입으로 손쉽게 작성 가능 
3. 유지보수 및 확장이 비교적 쉬움(2째주 기능추가 예정)
4. class / struct보다 다루기 쉬움 즉,헤맬 확률이 적음.... 

이렇게 네가지 이유에서 enum타입을 채택했습니다. 😎

2023-11-27 07:10 UTC, happykwon commented on RockPaperScissors/RockPaperScissors/main.swift
> +        print("잘못된 입력입니다. 다ls시 시도해주세요.")
```swift=
enum Result: String {
    
    case 이겼습니다
    case 졌습니다
    case 비겼습니다
    case errorDefault = "잘못된 입력입니다. 다시 시도해주세요."
    case quitGame = "게임종료"
}
```

other가 어떤 상황에서 쓰이는지 보다 명확하게 알 수 있게  errorDefault로 변경했습니다.

2023-11-28 02:13 UTC, happykwon commented on RockPaperScissors/RockPaperScissors/main.swift
> +        action(com: ChoiceMenu(rawValue: comChoice) ?? .scissor, user: ChoiceMenu(rawValue: userChoice) ?? .other)
1. scissor는 언랩핑을 하기 위한 임의의 값으로 설정
2. other는 사용자가 0, 1, 2, 3, 외 값을 입력했을 경우 erorr상황 처리를 위해 사용 
위 두가지 이유입니다. 
수정코드에서는 명확하게 하기 위해 guard let 구문을 사용하여 수정해봤습니다. 


```=swift
    guard let randomComChoice = comChoices.randomElement(), let comPick = UserInput(rawValue: randomComChoice) else {
        continue
    }
    
    guard let input = readLine(), let userPick = UserInput(rawValue: input), ["0", "1", "2", "3"].contains(userPick.rawValue) else {
        printMessage(for: .error)
        continue
    }


```

2023-11-28 02:16 UTC, happykwon commented on RockPaperScissors/RockPaperScissors/main.swift
> +func action(com: ChoiceMenu, user: ChoiceMenu) {
```
func calculateResult(comInput: ChoiceMenu, userInput: ChoiceMenu) -> Result {
    if userInput == comInput {
        return .draw
    } else if userInput == .exit {
        return .quitGame
    } else if (comInput == .scissor && userInput == .rock) ||
                (comInput == .rock && userInput == .paper) ||
                (comInput == .paper && userInput == .scissor) {
        return .win
    } else {
        return .lose
    }
}
```
calculatorResult라는 함수명으로 변경했습니다.

2023-11-28 02:18 UTC, happykwon commented on RockPaperScissors/RockPaperScissors/main.swift
> +func action(com: ChoiceMenu, user: ChoiceMenu) {
com : 컴퓨터가 선택한 값 
user : 유저가 선택한 값 입니다.

2023-11-28 02:20 UTC, happykwon commented on RockPaperScissors/RockPaperScissors/main.swift
> +        print("잘못된 입력입니다. 다ls시 시도해주세요.")
```enum Result: String {
    case win = "이겼습니다."
    case lose = "졌습니다."
    case draw = "비겼습니다."
    case errorDefault = "잘못된 입력입니다. 다시 시도해주세요."
    case quitGame = "게임종료"
}
```
```
enum ChoiceMenu: String, CaseIterable {
    case scissor = "1", rock = "2", paper = "3", exit = "0"
}
```
enum타입의 경우 유저가 입력할 수 있는 메뉴인 ChoiceMenu와 입력에 따른 결과 출력을 해주는 Result를 분리해서 좀 더 명확하게 
구분될 수 있게 했습니다.

2023-11-28 02:21 UTC, kimdj1102 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let comChoice: String = rps.randomElement() ?? ""
의도는 없고... randomElement() 반환값이 optional이라서 어쩔 수 없이 기본값으로 nil값을 넣어주었습니다.
그럴 상황이 있을 지는 모르겠지만 만약 nil값이 할당되면 처리가 되지 않을 것 같습니다. (입력값을 optional 타입으로 설정하지 않아서)

결국애는 guard let을 사용해서 안전하게 optional값을 처리하였습니다!
```
guard let randomComChoice = comChoices.randomElement(), let comPick = UserInput(rawValue: randomComChoice) else {
        continue
    }
```

2023-11-28 02:26 UTC, happykwon commented on RockPaperScissors/RockPaperScissors/main.swift
> +    case other
위쪽에
생각해보니 Scissor , rock , paper , exit 는 유저가 선택하는 값으로
쌩뚱맞게 other이 튀어나와 뭔가 안맞다는 생각이 들었습니다. 🤪

처음에는 에러처리를 위해 other이라는 case를 설정했지만 코드를 수정해 Result enum에 에러 문구를 사용했습니다.

2023-11-28 02:31 UTC, kimdj1102 commented on RockPaperScissors/RockPaperScissors/main.swift
> +                (comPick == .paper && userPick == .scissor)
말씀해주신 방법대로 코드를 수정해보았습니다.

1. else if문을 Bool 변수로 뺴기
```
let isPlayerWin: Bool = (comPick == .scissor && userPick == .rock) ||
                               (comPick == .rock && userPick == .paper) ||
                               (comPick == .paper && userPick == .scissor)
    
    if comPick == userPick {
        return .draw
    }
    
    if isPlayerWin {
        return .win
    }
    
    return .lose
```
그리고 각 조건마다 값을 return하고 종료가 되기때문에 더 좋은 가독성을 위해 else if를 사용하지 않고 if로만 구문을 채워보았습니다. 마지막 케이스는 `if !isPlayerwin { return lose }` 로 플레이어가 졌을 경우를 처리하려고 했는데 default return값을 따로 선언해주어야 한다고 해서 앞의 두 조건외의 모든 조건을 `return .lose`로 처리했습니다.

2. Resul를 계산하는 메서드 생성
```
func returnResult(comPick: UserInput, userPick: UserInput) -> Step1 {
    let isPlayerWin: Bool = (comPick == .scissor && userPick == .rock) ||
                               (comPick == .rock && userPick == .paper) ||
                               (comPick == .paper && userPick == .scissor)
    
    if comPick == userPick {
        return .draw
    }
    
    if isPlayerWin {
        return .win
    }
    
    return .lose
}
```
이 returnResult메서드에서 각각 값을 입력받아 result상수에 값을 할당하고,  상수를 출력하게끔 만들었습니다.
```
let result: Step1 = returnResult(comPick: comPick, userPick: userPick)
    
    printResult(for: result)
```

2023-11-28 02:31 UTC, happykwon commented on RockPaperScissors/RockPaperScissors/main.swift
> +let rps: [String] = ["1", "2", "3"]
rps를 삭제하는 대신 CaseIterable프로토콜을 채택해 컴퓨터도 ChoiceMenu에서 바로 결과값을 랜덤하게 가져와 변수에 담을 수 있게 설계를 변경했습니다. 

```
enum ChoiceMenu: String, CaseIterable {
    case scissor = "1", rock = "2", paper = "3", exit = "0"
}

```

```
  if let userInput = readLine(), let userPick = ChoiceMenu(rawValue: userInput) {
        guard let comPick = ChoiceMenu.allCases.filter({ $0 != .exit }).randomElement() else { continue }
        
       
        let result: Result = calculateResult(comInput: comPick, userInput: userPick)
        print(result.rawValue)
```

2023-11-28 02:33 UTC, happykwon commented on RockPaperScissors/RockPaperScissors/main.swift
> +    if let userChoice = readLine() {
내가 왜 그랬지라고 곰곰히 생각해봤지만.....🤔
아무 이유가 없다는 결론에 도달했습니다 .. 보통 readline()을 사용 할 때 타입을 명시해주는게 좋을까요?😅

2023-11-28 02:38 UTC, kimdj1102 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        print(Result.lose.rawValue)
제가 생각한 방법은 
1. rawValue값을 출력하는 함수를 따로 만들어서 함수 호출
```
func printResult(for situation: Result) {
    switch situation {
    case .menu:
        print(situation.rawValue, terminator: "")
    default:
        print(situation.rawValue)
    }
}
```

2. enum에 case로 말고 static let으로 선언을 해서 바로 상수명으로 호출할 수 있게함
```
enum Step1: String {
    static let win: String = "이겼습니다!"
}

print(Step1.win)
```
맞을 지 모르겠지만... 이정도로 유추해보았습니다! 맞는 방법일까요?

2023-11-28 02:41 UTC, kimdj1102 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    if let userChoice = readLine() {
음 이건... 저희가 변수나 상수 선언을 할 때 항상 타입을 명시해주기로 했는데 if let이나 guard let등의 구문에서도 타입을 명시해줘야 되는건지 애매해서 뻈던 것 같습니다. 선언이 많은 구절에서는 타입을 다 명시하면 코드가 너무 복잡해질 것 같아서요.
```
guard let input: String = readLine(), let userPick : UserInput = UserInput(rawValue: input), playerChoices.contains(userPick.rawValue) else {
        printResult(for: .error)
        continue
    }
```
이렇게 줄이 길어지더라도 타입 명시를 해주는게 맞을까요?

2023-11-28 02:44 UTC, kimdj1102 commented on RockPaperScissors/RockPaperScissors/main.swift
> +let rps: [String] = ["1", "2", "3"]
"1", "2", "3" 은 컴퓨터가 낼 수 있는 값이기 떄문에 comChoices로 수정해보았습니다!
`let comChoices: [String] = ["1", "2", "3"]`

2023-11-28 02:46 UTC, kimdj1102 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        print("잘못된 입력입니다. 다ls시 시도해주세요.")
앗..오타입니다😭

2023-11-28 04:00 UTC, kimdj1102 commented on RockPaperScissors/RockPaperScissors/main.swift
> +    case scissor = "1" , rock = "2", paper = "3", exit = "0"
이 enum에서 사용자의 입력(0, (1~3), 그 외)의 값을 처리하기 위함이었습니다.
하지만 ChoiceMenu이름으로 유추할때 사용자가 선택할 수 있는 값은 0과 1~3이기 떄문에 그렇게 두가지 case만 설정했고, 나머지 그 외의 입력값에 대한 처리는 guard let 구문에서 바로 처리했습니다.

```
enum UserInput: String {
    case scissor = "1"
    case rock = "2"
    case paper = "3"
    case exit = "0"
}

guard let input = readLine(), let userPick = UserInput(rawValue: input), playerChoices.contains(userPick.rawValue) else {
        printResult(for: .error) // 에외처리 (0~3 외의 입력값)
        continue
    }
    
```

2023-11-28 08:41 UTC, happykwon commented
달아주신 if let과 guard let 차이점과 어떤 시점에서 사용하는지에대한 정리입니다 ☺️
아직 경험이 많지 않아 정확하게 와닿지는 않지만 사전적 의미를 상투적으로 정리한다면 이정도로 정리 될 수 있을 것 같습니다. 

## if let
- 사용 시기: 주로 옵셔널 값이 필요한 부분을 처리하고자 할 때 사용
- 장점: 코드 블록 안에서 옵셔널 값을 처리하고 진행
- 단점: 중첩된 코드 블록이 발생할 수 있고, 코드의 가독성이 감소

## guard let
- 사용 시기: 함수, 메서드, 반복문 등의 블록 진입 전에 옵셔널 값을 처리하고, 이후 로직을 수행할 때 사용
- 장점: 코드 블록 상단에 옵셔널 값 처리로직을 두어 가독성을 높일 수 있고, 코드의 중첩을 피할 수 있음
- 단점: else 블록에서 반환을 해야 하기 때문에 조금 더 복잡? 할 수 있다(구현시)

## 그외.. 학습하면서 알아간점.
> 조기 리턴(Exit Early): 함수나 메서드 내부에서 빠르게 실패 조건을 처리하고자 할 때, guard let을 사용하여 조기 리턴을 하는 경우가 많음

> 로직 흐름과 가독성: if let은 블록 내에서 옵셔널 값 처리가 필요한 경우에 사용될 수 있습니다. 그러나, 중첩된 코드 블록이 많아질 수 있다면 가독성이 떨어질 수 있습니다.

2023-11-28 16:02 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/main.swift
> +        action(com: ChoiceMenu(rawValue: comChoice) ?? .scissor, user: ChoiceMenu(rawValue: userChoice) ?? .other)
코드가 명확해진거 같아서 좋습니다👍
가독성을 위해 가드문에 있는 조건들에 대해서 적절히 줄바꿈 시켜주는것도 좋을것 같네요!

2023-11-28 16:03 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/main.swift
> +func action(com: ChoiceMenu, user: ChoiceMenu) {
다른 코멘트에 비슷한 내용을 남겼던것 같은데 computer로 풀어 쓰는것도 좋을것 같습니다:)

2023-11-28 16:09 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/main.swift
> +let rps: [String] = ["1", "2", "3"]
변경된 내용 좋습니다! 
다만, 위 문서에도 이야기가 나와있는데 약어는 되도록이면 피하는게 좋을것 같아요!

com 에 대한 이야기 입니다😊

<img width="746" alt="Screenshot 2023-11-29 at 1 08 41 AM" src="https://github.com/tasty-code/ios-rock-scissor-paper/assets/33091784/8a799efc-e04f-457f-a479-ebdf0b446626">

2023-11-28 16:25 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/main.swift
> +    if let userChoice = readLine() {
일단 줄이 길어지면 줄바꿈을 해주면 되죠!😀

```
guard let input: String = readLine(),
      let userPick : UserInput = UserInput(rawValue: input),
      playerChoices.contains(userPick.rawValue) else {
        printResult(for: .error)
        continue
    }
```

타입 명시도 결국 컨벤션 나름이라고 생각합니다~ 정하기 나름인거죠ㅎㅎ
그치만 요런 것들은 생각해볼 수 있을것 같아요

#### 1. 가독성

코드를 작성하다보면 느껴보셨을 수도 있겠지만, 타입을 명시해주면서 가독성이 향상 되는것을 볼 수 있을거예요(읽는 사람이 타입이 뭔지 바로 알 수 있으니)

> 예시:

Before ( 타입이 뭔지 요것만 보고는 알 수가 없죠 )
```
let userPick = userPick.rawValue
```

After ( 한눈에 알 수 있죠 )
```
let userPick: String = userPick.rawValue
```


물론!  다음과 같은 경우에는 타입 명시를 안해도 딱히 가독성이 저해 되지 않는 것을 볼 수 있습니다

`let userPick = UserInput(rawValue: input)`

그래서 타입 명시에 대한 고민을 할때 생각해볼 수 있는 또 다른 포인트가 있죠

#### 2. 성능 향상

저희가 사용하는 Swift는 컴파일러가 직접 타입 추론이 가능합니다.
그러나! 이것도 어떻게보면 이론적으로는 자그만한 오버헤드라고도 볼 수 있어요 (컴파일러가 타입 추론을 해야하니.!)
물론, 눈에 띄는 성능 향상은 아니겠지만~ 요런 특징도 있다~~ 정도로 생각해주시면 될것 같습니다.

이건 나중에 공부를 할 기회가 생길 것으로 생각은 하는데궁금하시면 관련 WWDC 나중에 한번 찾아보시면 좋을것 같아요ㅎㅎ

2023-11-28 16:35 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/main.swift
> +        print(Result.lose.rawValue)
오 생각하신 방법들도 좋습니다!! 

제가 생각한건 말씀하신 1번의 방법과 약간 비슷한데요! 

Result라는 enum에 지금 rawValue 를 다음과 같이 정의 하셨잖아요??

```
enum Result: String {
    case win = "이겼습니다!"
    case lose = "졌습니다!"
    case draw = "비겼습니다!"
}
```

computed property 를 사용해보면 어떨까! 하는 생각이었습니다 :) 

바꿔보면 요렇게요

```
enum Result {
    case win
    case lose
    case draw
    
    var description: String {
        switch self {
        case .win:
            return "이겼습니다!"
        case .lose:
            return "졌습니다!"
        case .draw:
            return "비겼습니다!"
        }
    }
}
```

이렇게되면 
사용하실때도

```
let result: String = Result.win.description
print(result)
```

이걸 바로 밑에서 수정하신 방법과 합친다면 더더욱 좋을것 같네요!

2023-11-28 16:39 UTC, junbangg commented
guard let 과 if let 에 대해서 잘 정리 해주셨는데요!

어떤걸 사용해야될지 고민될때마다
정리해주신 내용에 대해서 한번 생각해보시고 사용하면 될것 같아요 근거가 생겼으니 !
너무 좋습니다👍

2023-11-28 16:59 UTC, junbangg approved these changes

2023-11-28 16:59 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
이전보다 훨씬! 깔끔해졌네요!! 

요런식으로 switch 문을 활용하는 방법도 한번 고민해보셔도 될것 같아요! 

```
func returnResult(comPick: UserInput, userPick: UserInput) -> Result {
    if comPick == userPick {
        return .draw
    }

    switch (comPick, userPick) {
    case (.scissor, .rock), (.rock, .paper), (.paper, .scissor):
        return .win
    default:
        return .lose
    }
}
```

2023-11-28 16:59 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/main.swift
> +func printGameResult(comPick: UserInput, userPick: UserInput) {
이거 메서드명이 위에 있는 `printResult` 랑 너무 비슷한데 하는 일은 또 좀 달라서 개인적으로는 조금 헷갈리네요..!

2023-11-28 16:59 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
혹시 요 enum의 역할은 무엇인가요??

여쭤보는 이유는 enum명 때문에 조금은 헷갈리는것 같아요 개인적으로!
`Result` 라면 가위 바위 보 게임의 결과를 예상했는데 (win, lose, draw) 와 같은 

case 들을 보니 그냥 유저에게 출력하는 모든 문자열인것 같기도 해서요!🤔

menu 와 같은

2023-11-29 05:52 UTC, happykwon commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
기존에 애매한 Result에서 게임 Prompt에 관련된 enum타입인 것을 명시하기 위해 이름을 변경했습니다 ! 

`enum gameMenuPrompt: String {
    case menu = "가위(1), 바위(2), 보(3)! <종료: 0> : "
    case win = "이겼습니다!"
    case lose = "졌습니다!"
    case draw = "비겼습니다!"
    case exit = "게임 종료"
    case error = "잘못된 입력입니다. 다시 시도해주세요."
}`

2023-11-29 06:02 UTC, happykwon commented on RockPaperScissors/RockPaperScissors/main.swift
> +func printGameResult(comPick: UserInput, userPick: UserInput) {
display -> 행위 
promptMenu -> 대상 
이렇게 행위와 대상을 명확하게 구분지어 가독성이 좋도록
displayPromptMenu로 메서드명을 변경했습니다 !

```
func displayPromptMenu(for situation: gameMenuPrompt) {
    switch situation {
    case .menu:
        print(situation.rawValue, terminator: "")
    default:
        print(situation.rawValue)
    }
}
```

2023-11-29 06:36 UTC, happykwon commented on RockPaperScissors/RockPaperScissors/main.swift
> +}
피드백 해주신대로 작성했더니 훨씬 ~ 코드가 보기 좋아졌어요 감사합니다 ☺️

2023-11-29 09:45 UTC, merged

2023-11-30 01:02 UTC, kimdj1102 commented on RockPaperScissors/RockPaperScissors/main.swift
> +let rps: [String] = ["1", "2", "3"]
네 com은 computer로 수정하도록 하겠습니다.

2023-11-30 01:04 UTC, kimdj1102 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        print(Result.lose.rawValue)
아~ 이렇게도 할 수 있군요 ㅎㅎ 한번 적용시켜 보겠습니다!!