묵찌빠 [STEP 1] llama, Harry
tasty-code/ios-rock-scissor-paper pull request #50
Opened 2023-11-23 12:27 UTC by llamang

# PR 준비

## 프로젝트 Step 1 - 진행 과정

맨 처음에 순서도와 클래스 다이어그램 그리기를 시도했을 때, 단순한 역할 정도만 구분했고 행위, 속성, 관계 등 세부적인 것들은 정하기 어려웠습니다. 

그래서 일단 코드를 구현해 보면서, 아이디어를 얻고 세부적인 것들을 정하기 시작했습니다. 

간단한 코드를 구현해 보면서, 클래스 다이어그램을 일차적으로 완성했습니다. 

해당 클래스 다이어그램을 바탕으로 코드를 전면 재구성하였고, 프로젝트를 진행하면서 클래스 다이어그램의 일부 변경 사항을 반영하면서 [Step 1]을 완료했습니다. 

## 고민했던 점과 궁금한 점

1. 변수명, 함수명, 타입명 고민 
    
    변수명 
    
    - `willRun`: GameManager 인스턴스에서 프로그램 실행 여부의 상태를 저장하기 위한 인스턴스 변수
    
    함수명
    
    - `getUserChoice(from userSelectedNumber: Int) -> RockPaperScissors?`
        
        [Question from 해리] `userSelectedNumber`를 함수 내부 파라미터로 사용하는데, 바로 위에 `guard let`에서 값을 꺼내와 저장하는 변수명도 `userSelectedNumber`라 같은 변수명을 사용한다면 가독성이 명확한지 궁금합니다. 
        
    - `typeInput() -> String`
        
        [Question from 해리] 해당 함수명에 type 글자와 유형(type) 의미는 다르지만 글자가 동일하므로 가독성이 어떤지 궁금합니다.
        
    - `shouldEndGame(with gameOutcome: GameOutcome) -> Bool`
        
        [Question from 해리] argument 레이블로 `with`가 적절한지 그리고 `from`도 괜찮은 것 같은데 의견을 부탁드려요.
        
    
    타입명
    
    - `RockPaperScissors`
        
        구현의 편의를 위해 `case termination = “0”`를 포함할지 고민했지만, `RockPaperScissors` 타입명과 논리적으로 연관이 없어 보여서 별도의 인스턴스 상수로 지정했습니다. 
        
2. `CaseIterable` protocol 채택 이유
    
    `CaseIterable` 프로토콜의 `allCases` 타입 변수를 활용하여 enum 타입의 case 값을 배열로 다루고 싶었습니다. 
    
3. enum 타입에서 함수 구현
    
    enum 타입의 값을 담은 변수(`let gameOutcome = determineGameOutcome(userChoice, computerChoice)`)가 어떤 case 값을 갖고 있든 상관없이 사용자 입장에서는 `notify()` 함수를 통해 적절한 메시지를 콘솔에 출력하도록 표현하기 위함입니다. 
    
4. 승부 판단에서 로직
    
    `(userChoice.rawValue + 1) % 3 == computerChoice.rawValue`
    
    - 가위 < 바위 < 보 < 가위 < 바위 < 보 < … 식의 순환 구조를 활용하여 구현
5. [Question] `computerChoice` 변수의 값을 할당할 때의 `guard let` 문의 `else` 구문
    
    ```swift
    private enum RockPaperScissors: Int, CaseIterable {
            case scissors = 1
            case rock = 2
            case paper = 3
        }
    
            guard let computerChoice = getComputerChoice() else {
                endGame**()**
                return
            }
    
            private func getComputerChoice() -> RockPaperScissors? {
            return RockPaperScissors.allCases.randomElement()
        }
    ```
    
    현재 `RockPaperScissors` enum 타입은 case 값이 있으므로 해당 `guard let` 문의 `else` 구문이 실행될 일은 없겠지만, 이럴 때 어떤 방식으로 로직을 구현하는 게 좋을지 궁금합니다.
    
6. [Question] `String()`
    
    ```swift
        private func typeInput() -> String {
            guard let Input = readLine() else {
                return String()
            }
            return Input
        }
    ```
    
    가독성 관점에서 봤을 때, `“”` 와 `String()` 중에 어떤 것을 추천하시나요?
    
7. [Question] `mutating` 키워드
    
    GameManager 구조체 인스턴스의 `endGame()` 함수를 호출할 때마다 `willRun` Bool 타입 변수를 변경하는 것이 괜찮은 방법인지 의문입니다. 
    
    GameManager를 구조체 대신 클래스로 구현하는 것은 어떤가요?
    
8. [Question] `canPlayGame()` 함수 안의 `let user = User()` 사용
    
    GameManager의 인스턴스 변수로 User 구조체의 인스턴스를  한 번만 만들고 사용하는 것과, `canPlayGame()` 함수만 사용하므로 게임이 실행될 때마다 `let user = User()`를 통해 인스턴스를 생성하는 것 중 어느 것이 좋은 방법인지 궁금합니다.

2023-11-24 09:55 UTC, FirstDo requested changes
안녕하세요!
첫번째 PR 정말 축하드립니다
2주동안 같이 열심히 해봐요 :)

## 잘하신점

- User, GameManager 객체를 나눈점
- 매서드를 최대한 분리하고 접근제어자를 사용하신점
- 전반적으로 에러처리가 매우 잘 되어 있습니다
- 순서도, UML 작성해 주신점

두분 실력이 상당하신것 같습니다!!!

아래는 질문에 대한 답변입니다.

## 궁금한 점 답변

#### getUserChoice(from userSelectedNumber: Int) -> RockPaperScissors?


- 제가 이해한게 맞다면, guard let 바인딩한 변수를 함수로 넘기는게 어색하지 않냐고 질문하신거죠??
문제 없습니다.

```swift
guard let userSelectedNumber = Int(userOption),
      let userChoice = getUserChoice(from: userSelectedNumber) else {
    notifyInvalidOption()
    return
}
```

#### typeInput() -> String

- type이 뜻이 달라서 문제라기 보다는 매서드가 동사로 시작하지 않는점이 naming guide에 위배되는것 같습니다.

#### shouldEndGame(with gameOutcome: GameOutcome) -> Bool

- 전치사는 그냥 읽었을때 어색하지만 않으면 괜찮습니다..! 애매하긴 하네요 ㅋㅋ

#### omputerChoice 변수의 값을 할당할 때의 guard let 문의 else 구문

실제 현업 코드라고 생각해보면,
작성시점에는 100% 안전하지만, 이 코드가 수많은 사람과 세월을 거치게 되면 정책이나 옵션이 바뀌면서 실패할 가능성이 있는 코드가 될 수도 있습니다

그래서 항상 올바른 에러처리를 해두는게 중요해요

지금 에러처리 해주신게 좋습니다
아니면 ??로 기본값을 줘서 애초에 옵셔널이 아닌 값을 반환하는 방법도 있습니다.

#### String()

99.99%는 ""로 쓸것 같습니다..!

#### mutating 키워드

mutating 자체는 우선 큰 문제는 없습니다
어떤 경우에 구조체와 클래스를 쓰는지 본인만의 명확한 기준이 중요한것 같아요

저는 참조/상속이 필요하면 클래스, 그외는 다 구조체로 작성하는 편입니다.

원본객체가 복사되어도 괜찮은지, 참조가 되어야 하는지가 가장 중요합니다.

#### canPlayGame() 함수 안의 let user = User()

구현의 차이인것 같습니다.
둘다 큰 상관 없습니다!

## 조언해드릴 점

첫번째 PR인데도 굉장히 좋은 코드를 작성해주신것 같습니다.

OOP 적으로 프로그램을 작성하셨으니 저도 그렇게 피드백을 드려볼께요.

현재는 User, GameManager 객체 두개가 존재합니다.
그리고 GameManager가 너무 많은 역할을 하고 있어요

좀 더 flow를 단순화 시키고, 새로운 객체를 만들어서 더 OOP적인 프로그램을 짤 수 있을 것 같습니다

User와 Computer 객체를 만들고,
두 객체가 GameManager 안에서 상호작용하는식으로요.

- User 가위바위보 입력
- Computer 가위바위보 입력
- 비교 및 결과출력 (그리고 재시도 여부)

현재 짜신 로직도 이것과 동일하긴 한데, 코드가 제 생각보다 더 긴것 같습니다.

이 세가지가 playGame안에서 일어나는 일이잖아요?

예를들어 아래코드를 한번보면

```swift
let user = User()
let userOption: String = user.chooseOption()

guard userOption != termination else {
    notifyGameOver()
    endGame()
    return
}

guard let userSelectedNumber = Int(userOption),
      let userChoice = getUserChoice(from: userSelectedNumber) else {
    notifyInvalidOption()
    return
}
```

이게 다 playGame에 박혀있을 필요가 없는것 같습니다.

`let option = user.chooseOption()`

자잘한 처리는 chooseOption 매서드에서 수행한 후 

그냥 가위바위보 enum을 바로 반환할 수 있게 하면 메인코드가 훨씬 더 깔끔할것 같아요
(컴퓨터도 마찬가지겠죠!)

두분이라면 훨씬 더 컴팩트 하게 짜실 수 있을것 같아요. 자세한건 코맨트로 추가로 남기겠습니다.

2023-11-24 09:55 UTC, FirstDo commented on RockPaperScissors/RockPaperScissors/User.swift
> +}
User객체를 만들고 매서드를 분리하신건 좋으나, chooseOption이라는 매서드는 지금 의미가 없는것 같습니다.
매서드 하나로 하는게 좋을것 같아요.

추가로 이친구는 String을 반환하는게 아니라 온전한 형태의 가위바위보 중 하나를 반환하는게 GameManager의 책임을 좀 덜 수 있는 방법이겠네요

2023-11-24 09:55 UTC, FirstDo commented on RockPaperScissors/RockPaperScissors/GameManager.swift
> +        print("가위(1), 바위(2), 보(3)! <종료: 0> : ", terminator: String())
보통 String() -> "" 로 쓰는 편입니다

2023-11-24 09:55 UTC, FirstDo commented on RockPaperScissors/RockPaperScissors/GameManager.swift
> +        return gameOutcome == .draw ? false : true
삼항연산자를 쓰신점 좋습니다.

2023-11-24 09:55 UTC, FirstDo commented on RockPaperScissors/RockPaperScissors/GameManager.swift
> +    }
이 친구들은 모두 각 객체에서 하는게 좋을것 같아요
게임매니저가 너무 무겁습니다

2023-11-24 09:55 UTC, FirstDo commented on RockPaperScissors/RockPaperScissors/GameManager.swift
> +        }
이 친구들 전체도 각 객체에서 하는게 좋을것 같습니다
```
let user = User()
let computer = Computer()

let userOption = user.choose()
let computerOption = computer.choose()
```

2023-11-24 09:55 UTC, FirstDo commented on RockPaperScissors/RockPaperScissors/GameManager.swift
> +        let userOption: String = user.chooseOption()
타입을 명시적으로 작성하던, 암시적으로 작성하던 하나로 통일시켜주시는게 좋습니다

```swift
let userOption: String = user.chooseOption()
let userOption = user.chooseOption()
```

두분 선택이긴 하지만, 저는 꼭 필요한 경우가 아니면 생략하는 편입니다

2023-11-24 09:55 UTC, FirstDo commented on RockPaperScissors/RockPaperScissors/GameManager.swift
> +    }
단순 getter를 위한 매서드는 지양하는 편이 좋습니다

willRun에 private도 걸려있지 않으니, 차라리 willRun으로 판단하는게 좋을것 같아요
네이밍도 게임을 할 수 있는지? 를 판단하려면 canRun이 더 나은것 같습니다

2023-11-24 09:55 UTC, FirstDo commented on RockPaperScissors/RockPaperScissors/GameManager.swift
> +    }
enum을 만드신점이 너무 좋습니다.
가독성이 정말 좋아요

2023-11-24 09:55 UTC, FirstDo commented on RockPaperScissors/RockPaperScissors/GameManager.swift
> +            }
취향의 차이일수는 있는데 notify() 매서드 자체가 조금 어색합니다.
출력할 문자열만 가지고 있고, 결과 출력은 게임매니저의 역할로 남겨두는게 어떨까요?

이런 케이스를 구분하는 enum의 경우 매서드 있는게 조금 어색한것 같습니다

```swift
var message: String  {
   switch self {
   case .draw:
      return "비겼습니다"
      ....
  }
}
```

2023-11-24 09:55 UTC, FirstDo commented on RockPaperScissors/RockPaperScissors/GameManager.swift
> +        willRun.toggle()
게임 종료라면 willRun = false로 설정해주시는게 좀 더 명확합니다

2023-11-27 12:14 UTC, hemil0102 commented on RockPaperScissors/RockPaperScissors/GameManager.swift
> +        willRun.toggle()
willRun = false로 변경해주었습니다.

2023-11-27 12:17 UTC, hemil0102 commented on RockPaperScissors/RockPaperScissors/GameManager.swift
> +            }
```
enum GameOutcome: CustomStringConvertible {
    case draw, win, loss
    
    var description: String {
        switch self {
        case .draw:
            return "비겼습니다!"
        case .win:
            return "이겼습니다!"
        case .loss:
            return "졌습니다!"
        }
    }
}
```

```
 PrintingHandler.notifyOutcome(of: gameOutcome)
```

위와 같은 방식으로 수정했습니다.

2023-11-27 12:17 UTC, hemil0102 commented on RockPaperScissors/RockPaperScissors/GameManager.swift
> +    }
감사합니다.

2023-11-27 12:19 UTC, hemil0102 commented on RockPaperScissors/RockPaperScissors/GameManager.swift
> +    }
```
public private(set) var canRun: Bool = true
```

canPlayGame() 삭제 및 willRun의 접근제한 수준을 원래 의도대로 public private(set)으로 재설정했습니다.

2023-11-27 12:22 UTC, hemil0102 commented on RockPaperScissors/RockPaperScissors/GameManager.swift
> +        }
```
        guard let userChoice = user.chooseSymbol(),
              let computerChoice = computer.chooseSymbol() else {
            shouldEndGameEarly() ? endGame() : PrintingHandler.notifyInvalidOption()
            return
        }
```

최선을 다해서 원하는 형식으로 맞춰보려했는데 추가로 좋은 의견 있으시면 답변부탁드려요,

2023-11-27 12:23 UTC, hemil0102 commented on RockPaperScissors/RockPaperScissors/GameManager.swift
> +        let userOption: String = user.chooseOption()
일관성 통일하여서 코드 타입 명시를 안하기로 했습니다.

2023-11-27 12:26 UTC, hemil0102 commented on RockPaperScissors/RockPaperScissors/GameManager.swift
> +    }
게임 매니저의 책임을 User, Computer 역할로 분산했습니다.

2023-11-27 12:27 UTC, hemil0102 commented on RockPaperScissors/RockPaperScissors/GameManager.swift
> +        return gameOutcome == .draw ? false : true
감사합니다. 이 부분은 추가로 로직 간소화를 할 수 있어 아래와 같이 변경했습니다. 

```
    private func shouldEndGame(basedOn gameOutcome: GameOutcome) -> Bool {
        return gameOutcome != .draw
    }
```

2023-11-27 12:28 UTC, hemil0102 commented on RockPaperScissors/RockPaperScissors/GameManager.swift
> +        print("가위(1), 바위(2), 보(3)! <종료: 0> : ", terminator: String())
알려주셔서 감사합니다.

2023-11-27 12:29 UTC, hemil0102 commented on RockPaperScissors/RockPaperScissors/User.swift
> +}
ChooseOption()의 이름을 chooseSymbol()로 변경하고 기능을 합쳤습니다.

2023-11-27 12:48 UTC, llamang commented on RockPaperScissors/RockPaperScissors/GameManager.swift
> +        willRun.toggle()
6b8b956c211838429ac0b749eb6cc0843b5139f6

2023-11-27 12:49 UTC, llamang commented on RockPaperScissors/RockPaperScissors/GameManager.swift
> +            }
e9cc3385a06722b21b968ffdb364f0a5b431923e

2023-11-27 12:50 UTC, llamang commented on RockPaperScissors/RockPaperScissors/GameManager.swift
> +    }
6b8b956c211838429ac0b749eb6cc0843b5139f6

2023-11-27 12:52 UTC, llamang commented on RockPaperScissors/RockPaperScissors/GameManager.swift
> +        }
6b8b956c211838429ac0b749eb6cc0843b5139f6

2023-11-27 12:52 UTC, llamang commented on RockPaperScissors/RockPaperScissors/GameManager.swift
> +    }
f48ecaa83fda588c23f258e1bb33b1936b8f17b9

2023-11-27 12:53 UTC, llamang commented on RockPaperScissors/RockPaperScissors/GameManager.swift
> +        return gameOutcome == .draw ? false : true
6b8b956c211838429ac0b749eb6cc0843b5139f6

2023-11-27 12:54 UTC, llamang commented on RockPaperScissors/RockPaperScissors/User.swift
> +}
f48ecaa83fda588c23f258e1bb33b1936b8f17b9

2023-11-27 13:00 UTC, llamang commented on RockPaperScissors/RockPaperScissors/Role/Referee.swift
> +}
GameManager의 determineGameOutcome 메서드(3cfa91e29bff9b854305de20664a303bb09d4e6d) -> Referee 구조체로 옮겼습니다.

2023-11-27 14:28 UTC, FirstDo commented on RockPaperScissors/RockPaperScissors/GameManager.swift
> +        return gameOutcome == .draw ? false : true
좋습니다!

가독성이 높은 코드를 작성하는것도 참 중요하잖아요?
아래코드들이 가독성이 낮다고 생각하는 개발자들도 꽤 있습니다

ex)

```swift
!array.isEmpty // ! 단항연산자가 앞에 붙은경우

guard !array.isEmpty else {  // 이중부정
 return 
}
```

저는 부정형을 쓰거나, guard, if문과 섞어쓸때는 조금 더 가독성에 신경을 쓰는 편이에요
그리고 개인적으로는 `!(condition)` 보단 `condition == false` 가 가독성이 훨씬 좋은것 같아요

수정사항은 아니고, 그냥 이런견해도 있다 정도로 인지하고 계시면 알거같아요

2023-11-27 14:49 UTC, FirstDo approved these changes
안녕하세요! 두분 고생많으셨습니다

사실 첫번째 리뷰에서, User, Computer 객체를 이야기할때, 프로토콜 or 상속 이야기를 할까말까 하다가 너무 스텝요구사항을 초과하는것 같아 안했는데요, 두분이 너무 잘 사용해 주셔서 깜짝 놀랐습니다...!!

또 코드를 보면 볼수록, 계속 새로운걸 찾아서 적용하고, 
특히 객체를 나누려고 많이 노력한 시도가 잘 보여서 좋았습니다.

User와 Computer를 Player로 추상화 하셨는데요!
그렇다면 코드도 다음과 같이 쓰는것이 좋습니다

AS - IS
```swift
    private var user = User()
    private var computer = Computer()
```

TO - BE
```swift
    private var user: Player = User()
    private var computer: Player = Computer()
```

현재 코드에서는 user, computer 객체의 매서드에 접근이 가능합니다 (물론 없지만요!)
그런식으로 코드를 작성한 후, 나중에 프로젝트 요구사항이 바뀌면 많은 수정이 필요해 질 수도 있습니다.

GameManager는 실제 타입을 알 필요가 없고 Player라는 추상타입만 아는것으로 충분할것 같네요
이러면 애초에 user, computer 모두 실제 타입과는 상관없이  Player 타입으로 취급되고,
코드도 그렇게 작성되게 됩니다.

추후 User, Computer의 내부가, 프로토콜 Player에 변화가 없는한 기존 코드는 수정할 필요가 없게 됩니다.

또한 enum을 활용한 여러가지 에러처리가 인상깊었습니다
다음 스텝에서 시간이 나신다면 ResultType이나, 
do - catch 를 활용한 에러처리도 도입해보셔도 너무 좋을것 같네요

두분 수준이 너무 높으셔서, OOP의 5원칙에 대해서도 한번 보시면 좋을것 같습니다.

또한 현재 객체가 굉장히 많은데, 
물론 객체가 많은건 좋습니다만, 자칫 너무 많은 객체를 만들고, 
또 객체간의 결합도가 지나치게 높은건 아닌지 의심해 봐야합니다.

객체간의 결합도가 높으면 (서로 엮여있으면), 특정 객체를 수정했을때, 해당 객체와 연관된 모든 객체를 뜯어고쳐야합니다.

그리고 static 매서드만 있는 객체는
enum으로 만들던가 클래스나 구조체라면 private init() { } 을 통해서 인스턴스를 생성할 수 없게 막는것이 개발자 의도대로 해당 객체를 사용할 수 있도록 강제할 수 있습니다

ex)
```swift
struct Logger {
   static func log() {
     print("로그에요")
  }
}
```

의도: `Logger.log()`
현실: `Logger()`  (?)

다음스텝도 기대됩니다!! 화이팅입니다
스텝 완료하시고 아무때나 dm주세요 ~

2023-11-27 14:49 UTC, merged