묵찌빠 프로그램 [STEP2] 카일, 미르
tasty-code/ios-rock-scissor-paper pull request #51
Opened 2023-11-28 04:23 UTC by mireu930

@ryan-son 안녕하세요, 라이언
STEP2 보내드립니다! 확인 부탁드립니다!

## 🧐 고민했던점
- ### 로직의 흐름 구상
    - 구조체 인스턴스화(사용자턴 vs 컴퓨터턴)
        - 가위바위보게임의 구조체를 묵찌빠에서 인스턴스를 생성하여 가위바위보게임의 승부결정이 나는것에 따라 턴을 넘겨 받으려고 하였습니다.
    - 불필요 함수 제거(`makeResult()`)
        - 기존의 가위바위보게임에서 makeResult 메서드가 쓰이지 않아 삭제해주고 makeResult 메서드의 로직을 continuGame에 넣어줬습니다.
    - 묵찌빠 게임용 열거형 생성
        - 가위바위보 게임과 같이 묵찌빠도 열거형을 생성하여 명시해줬습니다.

## 🤔 조언을 얻고 싶은 부분
- ### 지금 프로젝트에서 프로토콜을 채택하는게 좋은지?
    - 묵찌빠(`MukJjiPpa`)와 가위바위보(`RockScissorPaper`) 로직이 비슷한 부분이 많고 함수명이 동일하기 때문에 **프로토콜**을 채택하여 중복되는 메서드를 프로토콜에 구현하여 중복되는 부분을 줄이려고 했습니다. 코드를 재사용한다는 측면에서 장점이 될수 있지만 현재 프로젝트에서 굳이 써줘야할까라는 의문이 드는 부분도 있어 이러한 부분에 대해 라이언의 생각을 듣고 싶습니다.
- ### 원시값이 다른 열거형인 경우 구현 방법
    - 명세서에 안내된 `묵(1)찌(2)빠(3)`와 `가위(1)바위(2)보(3)`의 원시값이 달라 두개의 열거형을 만들어 구현했는데 위 두 열거형을 하나로 합칠 수 있는 방법이 있는 지 궁금합니다. 만약 있다면, 현재 두개의 열거형으로 구현하는 것이 나을 지 하나로 합치는 것이 나을 지 또한 궁금합니다.
- ### initializer VS 인스턴스화
    - 구조체 내에서 initializer로 구현하는 방법과 인스턴스를 직접 할당하여 구현하는 방법 중 어떠한 방법이 더 좋을 지 궁금합니다.

2023-11-28 04:32 UTC, Changhyun-Kyle commented on RockPaperScissors/RockPaperScissors/Command.swift
>      }
유효성 검사 측면보다 사용자의 명령을 관리하는 역할을 부여한 Command로 네이밍을 변경하였습니다.

2023-11-28 04:33 UTC, Changhyun-Kyle commented on RockPaperScissors/RockPaperScissors/Command.swift
> +        }
팀 그라운드 룰에서 정한 코드컨벤션에 따라 `guard`문 포맷팅

2023-11-28 04:35 UTC, Changhyun-Kyle commented on RockPaperScissors/RockPaperScissors/Game.swift
> +}
묵찌빠 구조체와 가위바위보 구조체에서 비슷한 로직과 같은 함수 네이밍을 갖기에 Game 프로토콜을 구현하였습니다.

2023-11-28 04:37 UTC, Changhyun-Kyle commented on RockPaperScissors/RockPaperScissors/MukJjiPpaGame.swift
> +    }
우선 initializer로 구현했습니다. 하지만, initializer로 선언했을 때와 인스턴스를 아래와 같이 직접 할당했을 때의 차이가 궁금합니다.
```swift
var rockScissorPaperGame = RockScissorPaperGame()
```

2023-11-28 04:44 UTC, mireu930 commented on RockPaperScissors/RockPaperScissors/MukJjiPpaGame.swift
> +        }
turn이라는 변수를 프로토콜의 프로퍼티로 선언했기 떄문에 rockScissorPaperGame의 turn을 받을 수 있게 구현했습니다. 또한, while true 문으로 수정해줬습니다.

2023-11-28 04:46 UTC, mireu930 commented on RockPaperScissors/RockPaperScissors/NameSpace/GameResultMessage.swift
> +}
message의 역할만 하기에 구조체이름을 명확하게 `GameResultMessage`로 수정하였고, 타입프로퍼티를 써줘 message의 역할만 하게 해줬습니다.

2023-11-28 04:56 UTC, mireu930 commented on RockPaperScissors/RockPaperScissors/NameSpace/GameChoice.swift
> +}
가위바위보와 묵찌빠를 열거형으로 구분을 해줬는데, `enum`타입 하나로 합치면 `compareChoice` 또한 프로토콜 메서드로 선언할수 있기 때문에 효율적이라고 생각합니다. 따라서 원시값 순서만 다를 뿐 같은 기능을 하는 `enum`타입을 한 곳에서 표현을 해줄 수 있는 방법이 있는지 궁금합니다.

2023-11-28 05:07 UTC, mireu930 commented on RockPaperScissors/RockPaperScissors/NameSpace/Turn.swift
> +}
사용자가 이기거나 졌을때 잘못입력했을때 Turn을 주고받을 수 있게 열거형으로 구현하였고, CustomStringConvertible 프로토콜을 채택하여 네이밍적인 역할을 부여했습니다.

2023-11-29 15:24 UTC, ryan-son requested changes
카일, 미르. Step 2도 고생 많으셨습니다. 이전처럼 질문에 대한 답변 짧게 남길게요. 자세한 내용은 코드에 달아둔 코멘트를 참고해주세요.

>## 🤔 조언을 얻고 싶은 부분
>- ### 지금 프로젝트에서 프로토콜을 채택하는게 좋은지?
>    - 묵찌빠(`MukJjiPpa`)와 가위바위보(`RockScissorPaper`) 로직이 비슷한 부분이 많고 함수명이 동일하기 때문에 **프로토콜**을 채택하여 중복되는 메서드를 프로토콜에 구현하여 중복되는 부분을 줄이려고 했습니다. 코드를 재사용한다는 측면에서 장점이 될수 있지만 현재 프로젝트에서 굳이 써줘야할까라는 의문이 드는 부분도 있어 이러한 부분에 대해 라이언의 생각을 듣고 싶습니다.

코드에도 코멘트를 남겨뒀지만, 프로토콜과 같은 추상화를 통해 어떤 효용을 얻을 목적이고, 잠재적으로 어떤 이득이 있을지 판단해보시면 좋을 것 같아요. 현재는 프로토콜을 통해 외부에 공개할 인터페이스 요구사항을 부여만 했을 뿐 코드 재사용이나 변경에 유연하게 대처할 수 있는 방향으로 구현이 되어있지는 않은 것 같습니다. 현재 수준의 요구사항에서는 추가적인 유연성을 부여하기 위한 작업이 불필요해보일 수 있지만, 단순히 요구사항을 만족시키는 것이 아니라 학습에 중점을 둔다면 요구사항의 변경에 어떻게 유연하게 대처할 수 있을지 고민해보는 것도 좋을 것 같네요. 예를 들어, 묵찌빠 이전에 가위바위보가 아닌 게임으로 승부를 낸다든지, 승부에 참여하는 사람이 여러명이 됐을 때와 같은 가정을 해보는거죠.

>- ### 원시값이 다른 열거형인 경우 구현 방법
>    - 명세서에 안내된 `묵(1)찌(2)빠(3)`와 `가위(1)바위(2)보(3)`의 원시값이 달라 두개의 열거형을 만들어 구현했는데 위 두 열거형을 하나로 합칠 수 있는 방법이 있는 지 궁금합니다. 만약 있다면, 현재 두개의 열거형으로 구현하는 것이 나을 지 하나로 합치는 것이 나을 지 또한 궁금합니다.

현재 수준에서 묵찌빠와 가위바위보 요구사항을 추상화해보면 '두 사람이 선택을 하고 이에 따른 승부를 겨루고 결과를 낸다.'라는거네요. 이에 따라 두 열거형이 추상화된 하나의 요구사항을 지키고, 이 요구사항을 만족한다면 두개의 선택을 주어졌을 때 승부의 결과를 제공하는 것까지는 고려해볼 수 있을 것 같아요. 저는 요구사항이 다른데 코드양을 줄이기 위해 구현을 억지로 합치는 방향에는 동의하지 않습니다. 룰이 다른 게임, 그리고 묵찌빠는 가위바위보와 달리 차례라는 시스템도 존재하기에 구현을 완전히 분리하는 것이 더 나은 선택이 될 수 있습니다. 이 과정에서 공통적으로 공유할 수 있는 구현을 추상화해서 구현해보는 방향을 고려해볼 수는 있겠네요. 예를 들어 아래와 같은 겁니다.

```
// 가위바위보와 묵찌빠 콘솔 앱의 공통점을 추상화해보자.
1. 콘솔에 게임별로 사용자를 위한 입력 안내 문구를 표시하고 사용자의 입력을 받는다.
2. 사용자의 입력의 유효성을 검증하여 이에 따라 게임 진행 여부를 결정한다.
3. 사용자의 입력이 종료라면 게임을 종료한다.
4. 사용자의 입력이 승부를 위한 것이라면 컴퓨터의 결정과 비교하여 승부를 낸다.
5. 승부의 결과에 따라 결과를 콘솔에 출력한다.
```

> - ### initializer VS 인스턴스화
>    - 구조체 내에서 initializer로 구현하는 방법과 인스턴스를 직접 할당하여 구현하는 방법 중 어떠한 방법이 더 좋을 지 궁금합니다.

코드에 남겨둔 코멘트를 참고해주세요.

이번에는 구현보다는 고민할 기회가 많은 Step이 될 것 같네요. 화이팅입니다! 궁금하신 점이 있으시면 언제든지 메시지 남겨주세요~

2023-11-29 15:24 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/Command.swift
>      init?(value: String?) {
Command 초기화에 failable initializer를 적용한 의도를 문서화 주석(Documentation comment)을 남겨둔다면 Command 타입을 사용하는 사람들에게 큰 도움을 줄 수 있을 것 같아요.
- [Writing symbol documentation in your source files - Apple Developer](https://developer.apple.com/documentation/xcode/writing-symbol-documentation-in-your-source-files)

2023-11-29 15:24 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/Command.swift
>          let validInputs = [0, 1, 2, 3]
구현부에 이러한 값을 둔다면 상세한 구현을 알지 못하는 동료가 수정하기 어려울 수 있습니다. 유효한 입력이 의존하는 구현의 변경에 따라 가변적으로 변할 수 있게 구성하거나 값을 별도로 관리하는 방법을 통해 향후 수정이 예상되는 부분과 구현부를 분리해보시는 것도 좋겠네요~

```swift
// Case 1. 의존하는 구현에 따라 가변적인 논리 구성. 목적에 따라 타입이 분리되어야 할 수 있음. 
// 예를 들어, 묵찌빠의 경우에는 이 구현과 별도의 Command가 필요함.
// 사용자의 input을 올바른 Command 인스턴스로 변환해주는 타입을 정의하는 것도 고려해볼만 함.
let validInputs = RockScissorPaperChoice.allCases.map(\.rawValue)

// Case 2. 변경이 예상되는 내용을 별도로 구성
enum Command {
    /// 종료, 가위바위보, 묵찌빠 명령에 대응하는 입력
    static let validInputs = [0, 1, 2, 3]
    ...
}
```

2023-11-29 15:24 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/Game.swift
> +}
현재는 인스턴스 프로퍼티와 메서드의 시그니처 요구사항을 포함만해둔 상태라 추상화의 의도와 실제 얻을 수 있는 효용이 보이지 않네요. 어떤 이득을 얻기 위해 프로토콜을 만들고 채택했는지, 그리고 잠재적으로 어떤 점이 좋을지 생각해보고 실제로 구현으로 옮겨보시면 더 좋을 것 같아요.

2023-11-29 15:24 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/MukJjiPpaGame.swift
> +    }
인스턴스 프로퍼티에 이니셜라이저로부터 전달받은 인스턴스가 아니라 직접 구체적인 인스턴스를 할당하는 방식은 두 가지 관점에서 단점이 있습니다.

1. 먼저 진행되는 게임의 실행 시점에 초깃값을 다르게 부여할 수 없습니다. 현 시점에서는 가위바위보 게임에 할당할만한 초깃값이 없지만, 가위바위보에 참여하는 인원들의 인스턴스나 사람수를 부여하거나 다른 룰을 가진 가위바위보를 해야 한다면 어떨까요? 인스턴스 프로퍼티에 직접 할당한 경우에는 컴파일 시점에 초깃값이 결정되어 버리기에 이를 외부에서 조작하는 방법밖에 없습니다. 초기 상태를 의도한대로 만들기 위해 외부에서 조작하는 일은 썩 좋은 결정은 아니겠죠.
2. 외부에서 의존하는 인스턴스를 제공받을 수 없기 때문에 구체적인 타입의 인스턴스에 의존할 수밖에 없게 됩니다. 구체적인 타입에 의존한다는 것은 그만큼 유연성이 떨어진다는 것이고, 이는 변화에 대처하기 어렵다는 것을 의미합니다. 두 가지 예시를 들어볼게요.
    1. 차량용 타이어는 여름용, 겨율용, 그리고 사계절 타이어가 있습니다. 여기에서 타이어는 추상적인 것, 그리고 여름용, 겨울용, 사계절용은 비교적 구체적인 타입이라고 볼 수 있습니다. 아래 1, 2 중 어떤 자동차가 계절 변화에 유연하게 대처할 수 있을까요?
            1. 여름용 타이어를 장착한 차량 (구체적인 것에 의존한 타입)
            2. 타이어를 장착한 차량 (추상적인 것에 의존한 타입)
    2. 묵찌빠를 하기 전에 가위바위보가 아닌 게임으로 승부를 낼 수 없습니다.

2023-11-29 15:24 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/MukJjiPpaGame.swift
> +        }
다른 게임의 결과를 통해 묵찌빠 게임의 턴을 결정하는 논리인데, 다른 게임의 인스턴스 프로퍼티에 접근해서 결과를 받는 점이 의아하게 느껴지네요. play()의 결과로 게임 결과 또는 승패를 전달받고 이를 통해 차례를 결정하는 방식으로 논리 구성을 해보는 건 어떨까요?

2023-11-29 15:24 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/MukJjiPpaGame.swift
> +            print(ApplicationStatusMessage.error)
'유효하지 않은 입력을 하면 컴퓨터에게 차례를 넘긴다'라는 요구사항을 모른다면 구현부를 살펴보는 입장에서 논리 흐름을 따라가기 어려울 수 있을 것 같아요. 이런 부분은 유효하지 않은 입력에 따른 처리라는 것을 명확하게 알 수 있게끔 메서드 분리를 해둔다면 흐름을 이해하기 쉬워집니다.

```swift
// 메서드 이름을 아래와 같은 방식으로 설정하는 것이 좋은 이유에 대해서도 생각해보시기 바랍니다.
private func invalidCommandEntered() {
    turn = .computer
    print(ApplicationStatusMessage.error)
}
```

continueGame에 문서화 주석으로 이러한 요구사항을 알 수 있게끔 작성하는 것도, 현재 지점에 논리 구성의 이유를 구현 주석으로 남기는 것도 모두 코드를 읽는 동료에게 도움을 줄 수 있지만, 사용자의 행동 또는 이벤트의 결과로 인한 처리를 메서드 단위로 분리해둔다면 별도의 주석 없이도 동료의 이해에 크게 도움을 줄 수 있다는 점을 알아두시면 좋겠네요.

2023-11-29 15:24 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/MukJjiPpaGame.swift
> +        case (.jji,.muk),(.muk,.ppa),(.ppa,.jji):
회의실에서 말씀드렸던 것처럼 쉼표 뒤에 한 칸 띄우는 것이 Swift의 일반적인 컨벤션입니다.

```suggestion
        case (.jji, .muk),(.muk,. ppa),(.ppa, .jji):
```

2023-11-29 15:24 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/MukJjiPpaGame.swift
> +            turn = .computer
이겨서, 져서 차례를 바꿀 때도 이러한 의미를 더 작은 단위로 분리해준다면 승부가 났을 때 추가적인 처리를 하기 좋을거예요.

2023-11-29 15:24 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/NameSpace/ApplicationStatusMessage.swift
> +    static let error = "잘못된 입력입니다. 다시 시도해주세요."
애플리케이션 상태와 잘못된 입력, 다시 시도는 의미상 맥락을 달리하는 부분이 있는 것 같네요. 진행 안내 메시지라든지 유효하지 않은 입력에 따른 메시지라든지 이름을 더 다듬을 수 있겠어요.

2023-11-29 15:24 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/NameSpace/GameChoice.swift
> +}
Choice들을 합치지 않더라도 이들을 추상화하고 이에 따라 승부를 결정하도록 구성할 수도 있습니다. Game 프로토콜의 요구사항에 부가 내용을 추가한다면 현재 상태에서도 compareChoice를 프로토콜의 요구사항으로 편입시킬 수도 있습니다. 하지만 compareChoice를 프로토콜의 요구사항으로 만들기 위해 이 작업을 진행하는 것은 타당하지 않아 보이네요. 현재 play() 이외의 인터페이스는 외부에서 사용될 필요가 없으므로 프로토콜의 요구사항으로 만드는 것은 적합하지 않아 보입니다. 불필요한 인터페이스를 요구해서 구현할 인터페이스를 늘리는 꼴이 되니까요. 이 부분에 대해서는 프로토콜로 추상화하는 것이 효용이 있는지, 있다면 어떤 부분에서 있을 수 있는지에 대해 조금 더 고민해볼만한 부분이 있다고 생각합니다. 조금 생각해보고 회의실에서 다시 이야기 나눠보면 좋을 것 같네요.

2023-11-29 15:24 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/NameSpace/GameResult.swift
> -}
저는 영문 모를 true/false 보다 승부 결과를 명확하게 알 수 있는 이 타입이 있어서 좋았는데 조금 아쉽네요.. 😋

2023-11-29 15:24 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/NameSpace/GameResultMessage.swift
> +}
이러한 namespace를 선언하는데 struct, class가 아닌 enum을 선택한 이유가 있나요?

2023-11-29 15:24 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/NameSpace/Turn.swift
> +}
미결정을 차례 열거형의 케이스로 정의할 수도 있지만, Optional.none을 통해서도 그 의미를 전달할 수 있을 것 같네요. 차례가 온전히 사용자와 컴퓨터만 표현할 수 있게 된다면, none이라는 상태를 고려하지 않아도 되니 턴 넘기기와 같은 편의 메서드를 거리낌 없이 만들 수 있을 것 같네요.

2023-11-29 15:24 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/RockScissorPaperGame.swift
> +    var turn: Turn = .none
1. 프로토콜의 요구에 따라 외부에 공개하지 않아도 되는 프로퍼티를 공개하게 되었네요. private(set)이라는 접근제한자를 통해 외부에서의 변경을 방지할 수 있겠지만, 이 인스턴스 프로퍼티를 Game 인터페이스에서 요구사항에 포함해야할지는 고민의 여지가 있어보여요.
2. 인스턴스 프로퍼티에 변수를 선언한다는 것은 어느 시점이나 모든 인스턴스 멤버가 해당 변수를 변경할 권리를 가지고 있다는 의미이기도 합니다. 어느 시점에 내가 예상하지 못한 메서드가 이 변수를 조작한다면 이는 버그라는 예상치 못한 결과를 낳게 됩니다. 이를 방지하는 방법으로는 메서드의 전달 인자과 반환으로 메시지를 주고 받는 방법을 사용할 수 있습니다. 조금 고민해보시고 이야기 나눠봅시다~

2023-11-29 15:24 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/RockScissorPaperGame.swift
>          case (.scissor,.paper),(.rock,.scissor),(.paper,.rock):
쉼표 뒤에 공백 하나씩 넣어주세요~

2023-11-29 15:24 UTC, ryan-son commented on RockPaperScissors/RockPaperScissors/main.swift
> +                                  rockScissorPaperGame: RockScissorPaperGame())
시작 시 의존하는 초깃값이 일정하다면 이니셜라이저에 기본값을 부여할 수도 있습니다.

2023-11-30 06:31 UTC, Changhyun-Kyle commented on RockPaperScissors/RockPaperScissors/Game.swift
> +}
서로 다른 구조체에서 공통된 메서드와 프로퍼티를 묶기 위해 도입하려 했습니다. 현재 프로젝트 규모에서 구현해야하는 지에 대한 의문은 들었지만 어떻게 사용되고 피드백 받기 위해 사용했습니다!

2023-11-30 06:46 UTC, Changhyun-Kyle commented on RockPaperScissors/RockPaperScissors/NameSpace/GameResultMessage.swift
> +}
인스턴스화를 통한 뜻하지 않는 초기화를 막고 순수히 `namespace`의 역할만 수행할 수 있게 `enum`으로 선택했습니다.

2023-11-30 06:53 UTC, Changhyun-Kyle commented on RockPaperScissors/RockPaperScissors/NameSpace/GameChoice.swift
> +}
associatedType을 통해 compareChoice() 또한 프로토콜의 요구사항으로 편입시키는 방향으로 진행했습니다. 위에 말씀드렸던 것과 같이 현재 프로젝트에서 효율적으로 사용할 수 있다기보단 경험으로써 적용해보았습니다. 하지만, 저희도 '프로토콜을 구현해볼까?'라는 생각이 들었을 때 라이언의 피드백과 마찬가지로 '억지로 프로토콜을 사용하기 위한 코드가 되지 않을까?'라는 의문이 들었기 때문에 제거하였습니다!

2023-11-30 06:59 UTC, Changhyun-Kyle commented on RockPaperScissors/RockPaperScissors/Command.swift
>      init?(value: String?) {
안내된 명세서에 코드 주석을 달지 말라고 되어있어서 모든 프로젝트의 주석을 달지 않고 진행했습니다🥺
![image](https://github.com/tasty-code/ios-rock-scissor-paper/assets/101093592/2dc6b14c-66d0-40d8-a044-2d9e2244a2e9)

2023-11-30 07:13 UTC, Changhyun-Kyle commented on RockPaperScissors/RockPaperScissors/NameSpace/GameResult.swift
> -}
해당 열거형이 `Message`를 출력하는 문자열만 담고 있어서 아래와 같이 `GameResultMessage`로 네이밍을 구체화 후 `static let`으로 선언하여 `namespace`의 의도에 맞게 수정했습니다!

2023-12-05 08:25 UTC, merged