묵찌빠 프로그램 [STEP 2] Sam, Dan
tasty-code/ios-rock-scissor-paper pull request #54
Opened 2023-11-28 07:00 UTC by eensungkim

리뷰어: @July911
버드: @ParkChanH, @eensungkim

가위바위보 이후 묵찌빠로 넘어가는 게임 로직이 추가되었습니다.
특히 이번 PR에서는 구조체와 클래스 등을 활용한 객체지향 프로그래밍에 대해 고민해 보았습니다.

# 코드 설명
## main.swift
gameMaster 인스턴스를 선언하고 게임을 실행합니다.

## structures.swift
Player 구조체는 게임에 참여하는 플레이어가 선택한 핸드(가위바위보, 묵찌빠)를 선택하고 저장할 수 있습니다.

## enumerations.swift
게임 진행을 위한 열거형들이 관리됩니다.

## classes.swift
InGameMessage 와 GameMaster 클래스가 정의되어 있습니다.

### InGameMessage 클래스
게임 내에서 사용되는 인게임 메시지를 저장하고 출력하는 클래스이며, 싱글톤으로 사용됩니다.

#### print 메서드
GameStatus, GameType, GameResult 열거형 값을 받아와서 문자열을 생성하고, message 딕셔너리의 key로 입력하여 대응하는 문자열 value를 가져옵니다.

### GameMaster 클래스
게임 로직과 상태 저장 등 게임 전반을 관리하는 클래스입니다.

#### gameType 프로퍼티
게임의 종류를 판단합니다.(가위바위보 or 묵찌빠)

#### user, computer 프로퍼티
user 또는 컴퓨터 플레이어 인스턴스를 관리합니다.

#### turn 프로퍼티
묵찌빠에서 선공권이 누구에게 있는지를 판단합니다.

#### message 프로퍼티
InGameMessage 싱글톤으로 초기화합니다.

#### evaluateMookJjiBba 메서드
user와 computer의 묵찌빠 핸드를 비교하여 승리 또는 선공권을 판단합니다.
결과에 따라 메시지 프로퍼티에 메시지 출력을 요청합니다.

# 질문
- 샘: 무조건 단축어를 쓰는게 나쁜 것일까요? 변수명이 길어지다 보면 가독성이 떨어져보이는 것 같아서 고민이 됩니다. (e.g. `playRockScissorsPaper -> playRSP`)
- 댄: Step1에서와 달리 Step 2에서는 객체지향 프로그래밍 방법에 대해 이해한 만큼을 최대한 녹여내려고 했습니다. 작성한 코드가 객체지향 프로그래밍 방식에 부합하는 코드인지 궁금합니다. 
- 댄: InGameMessage 싱글톤 클래스를 만들어 게임 내에서 print 되는 모든 메시지를 하나로 모으려고 했는데요. 가독성이 떨어지는 코드가 된 것 같기도 합니다. 참고할 만한 예시가 혹시 있을까요?
- 샘: 지금은 메시지이지만 공통되는 기능을 같이 써야 할 때 싱글톤을 활용하는지 궁금합니다.
- 댄: 게임을 실행하기 위해 필요한 모든 상태가 GameMaster에서 관리되고 있어 GameMaster의 책임이 과중한 것이 아닌가 하는 생각이 드는데요. 책임을 분산하는 방법이 있을지 궁금합니다.

2023-11-28 07:32 UTC, July911 requested changes

2023-11-28 07:32 UTC, July911 commented on RockPaperScissors/RockPaperScissors.xcodeproj/project.pbxproj
> +		1DC443792B142C4000A30D94 /* structures.swift in Sources */ = {isa = PBXBuildFile; fileRef = 1DC443782B142C4000A30D94 /* structures.swift */; };
파일에는 하나의 객체만 있는것이 가독성에 좋으며 그 파일 이름은 그 객체의 이름인것이 가장 좋습니다.

2023-11-28 07:32 UTC, July911 commented on RockPaperScissors/RockPaperScissors/classes.swift
> +    static let shared = InGameMessage()
이것이 의미하는바는 무엇일까요 ? 질문에도 주셨는데, 싱글톤은 무엇이며 
현 코드에서 외부에서 init할수없도록 하는 코드는 존재하나요 ?

2023-11-28 07:32 UTC, July911 commented on RockPaperScissors/RockPaperScissors/classes.swift
> +    private var message: [String : (String) -> String] = [
수정부탁드립니다. 가독성이 너무 좋지않습니다.

2023-11-28 07:32 UTC, July911 commented on RockPaperScissors/RockPaperScissors/classes.swift
> +        "evaluation,Optional(RockPaperScissors.GameType.rockScissorsPaper),Optional(RockPaperScissors.GameResult.win)" : { _ in "이겼습니다!" },
클로저를 value값으로 하신 이유가 있을까요 ?

2023-11-28 07:32 UTC, July911 commented on RockPaperScissors/RockPaperScissors/classes.swift
> +    func print( status: GameStatus, type: GameType? = nil, result: GameResult? = nil, playerName: String = "" ) {
파라미터가 많아지는게 유연하게 대처 가능한 메서드를 만들수도 있지만, 어떻게 접근해야할지 모르는 메서드를 만들수도 있습니다. 
지금은 후자인 것 같습니다.

2023-11-28 07:32 UTC, July911 commented on RockPaperScissors/RockPaperScissors/structures.swift
> +    private var name: String
추후에 변하나요 ?

2023-11-28 07:32 UTC, July911 commented on RockPaperScissors/RockPaperScissors/structures.swift
> +    func getName() -> String {
get이라는 동사는 지양하는게 좋습니다. 의미가 많아 경우에 따라 여러가지 의미를 내포할 수 있습니다.

2023-11-28 07:32 UTC, July911 commented on RockPaperScissors/RockPaperScissors/enumerations.swift
> +    case rockScissorsPaper, mookJjiBba
저라면 enum 연관값을 사용했을 것 같습니다.

2023-11-28 07:32 UTC, July911 commented on RockPaperScissors/RockPaperScissors/classes.swift
> +    func print( status: GameStatus, type: GameType? = nil, result: GameResult? = nil, playerName: String = "" ) {
대체하는 상황에서는 좋은 선택지겠지만, 대체 할 것이 아니라면 굳이 Swift에 있는 메서드명을 사용할 이유는 없는 것 같습니다.

2023-11-28 07:32 UTC, July911 commented on RockPaperScissors/RockPaperScissors/classes.swift
> +class InGameMessage {
class명으로 부적합한것같습니다.

2023-11-28 07:32 UTC, July911 commented on RockPaperScissors/RockPaperScissors/classes.swift
> +        if self.turn.getName() == "사용자" {
사용자와 컴퓨터가 있다면, 이 값이 enum에 어울릴 것 같습니다.

2023-11-28 07:46 UTC, July911 requested changes

2023-11-28 07:46 UTC, July911 commented on RockPaperScissors/RockPaperScissors/classes.swift
> +    private var computer: Player
변하지않는 값이라 생각이 드네요.

2023-11-28 07:54 UTC, eensungkim commented on RockPaperScissors/RockPaperScissors/structures.swift
> +    private var name: String
변하지 않아도 되는 값이라면 그냥 let 을 써도 충분했겠군요.
private var 를 배워보려다가 함정에 빠졌던 것 같습니다. 😅

2023-11-28 08:11 UTC, eensungkim commented on RockPaperScissors/RockPaperScissors/classes.swift
> +    static let shared = InGameMessage()
싱글톤은 단 한번만 인스턴스로 초기화되고, 그 이후에는 전역적으로 접근이 되고 공유되는 클래스라고 이해하고 있습니다.
[공식문서](https://developer.apple.com/documentation/swift/managing-a-shared-resource-using-a-singleton#Create-a-Singleton) 를 참고했을 때, static 키워드의 존재가 init을 한번만 할 수 있도록 해주는 것으로 이해했었습니다.

2023-11-29 00:41 UTC, eensungkim commented on RockPaperScissors/RockPaperScissors/classes.swift
> +    private var message: [String : (String) -> String] = [
InGameMessage 는 샘과 논의해서 수정하는 쪽으로 진행할 예정입니다!

2023-11-29 01:51 UTC, eensungkim commented on RockPaperScissors/RockPaperScissors.xcodeproj/project.pbxproj
> +		1DC443792B142C4000A30D94 /* structures.swift in Sources */ = {isa = PBXBuildFile; fileRef = 1DC443782B142C4000A30D94 /* structures.swift */; };
수정했습니다!

2023-11-29 01:52 UTC, eensungkim commented on RockPaperScissors/RockPaperScissors/classes.swift
> +    static let shared = InGameMessage()
InGameMessage를 삭제했습니다!

2023-11-29 01:52 UTC, eensungkim commented on RockPaperScissors/RockPaperScissors/structures.swift
> +    private var name: String
name을 제거했습니다.

2023-11-29 01:53 UTC, eensungkim commented on RockPaperScissors/RockPaperScissors/structures.swift
> +    func getName() -> String {
name 을 제거하면서 해당 메서드도 삭제했습니다.

2023-11-29 01:53 UTC, eensungkim commented on RockPaperScissors/RockPaperScissors/enumerations.swift
> +    case rockScissorsPaper, mookJjiBba
어떤 방법을 생각하신 건지 궁금합니다! 🙏

2023-11-29 01:54 UTC, eensungkim commented on RockPaperScissors/RockPaperScissors/classes.swift
> +        if self.turn.getName() == "사용자" {
enum 을 새로 생성하여 대체했습니다.

2023-11-29 01:56 UTC, eensungkim commented on RockPaperScissors/RockPaperScissors/classes.swift
> +    private var computer: Player
let 으로 선언해주는 편이 낫지 않겠냐는 의미로 받아들였는데요.
let 으로 바꾸게 되면 user 인스턴스에 접근하여 내부의 핸드를 변경하는 것이 불가능하더라구요.
private 을 명확히 이해하지 않고 사용한 것 같아 private 접근 제어자만 제외하는 것으로 수정했습니다.

2023-11-30 02:06 UTC, July911 requested changes

2023-11-30 02:06 UTC, July911 commented on RockPaperScissors/RockPaperScissors/enumerations/enumerations.swift
> +
불필요한 공백같습니다.

2023-11-30 02:06 UTC, July911 commented on RockPaperScissors/RockPaperScissors/enumerations/enumerations.swift
> +            let dictionary: [ RPS : RPS ] = [
무슨로직인가요 ? logic 이라고만 되어있으니 알아보기 힘드네요. 
[ RPS : RPS ] 앞뒤의 공백은 무엇인가요 ?

2023-11-30 02:06 UTC, July911 commented on RockPaperScissors/RockPaperScissors/main.swift
> +var gameMaster = GameMaster()
var인 이유가 있나요 ?

2023-11-30 02:38 UTC, eensungkim commented on RockPaperScissors/RockPaperScissors/enumerations/enumerations.swift
> +            let dictionary: [ RPS : RPS ] = [
승패를 판별하기 위한 logic입니다. 호출하는 쪽에서처럼 winningLogic 으로 변경하겠습니다.

공백은 개인적으로 공백이 있는 편이 타입을 식별하기 편하다고 생각해서 삽입이 된 것이라서요. 질문주신 것을 보니 일반적인 컨벤션과는 다른 것 같아 수정하도록 하겠습니다.

2023-11-30 02:38 UTC, eensungkim commented on RockPaperScissors/RockPaperScissors/main.swift
> +var gameMaster = GameMaster()
놓친 부분입니다!

2023-11-30 03:02 UTC, eensungkim commented on RockPaperScissors/RockPaperScissors/main.swift
> +var gameMaster = GameMaster()
playGame 메소드가 내부 프로퍼티를 변경하도록 구성되어 있어서 let으로 선언하면 메소드 호출이 안되어서 var로 선언했습니다.

2024-01-02 01:31 UTC, Tacocat-tastycode commented
프로젝트 진행 기간 종료로 PR Close

2024-01-02 01:31 UTC, closed without merging