묵찌빠 프로그램 [STEP 2] Sidi, Matthew
tasty-code/ios-rock-scissor-paper pull request #55
Opened 2023-11-28 07:30 UTC by jus1234

리뷰어: @Mino777

버드: @jus1234, @kimbs5899

### 코드 설명

- GameController : `gameStack` 에 게임이 담긴 경우 담긴 게임을 `pop`해 진행
- RockPaperScissorsModel : `Circular Queue`를 활용한 가위바위보 게임 로직 구현

### 고민 되었던 점

- 함수를 기능 단위로 분리해 작성해봤습니다. 코드가 간결해지고 재사용성이 높아지는 점은 좋았지만 너무 많은 함수가 생성된건 아닌가 라는 생각이 들었습니다.
- 변수, 함수 등 네이밍 할 때 지난 번에 공유해주신 가이드를 적용해 보는 과정이 생각보다 어려웠습니다.
- MVC 구조를 나눌 때 `print`함수를 실행하는 부분이 `View`라고 생각했습니다. 로직과 데이터를 처리하는 영역은 `Model`로 분리 했습니다. 구조를 나누는 과정에 고민이 많이 되었습니다.

### 궁금했던 점

- 가위바위보 승무패 별 로직을 `switch`나 `if`문을 사용한 분기처리를 할 경우 너무 많은 분기가 생겨 `Dictionary`에 `closure`를 담아 해당하는 `closure`를 실행하는 방법으로 코드를 작성해 봤습니다. 실무에서도 `closure`를 어떤 식으로 사용하는지 궁금 합니다!

Ex) `Dictionary` 사용

```swift
// 글로벌 영역
private var rockPaperScissorsResultDict: Dictionary<Match, () -> ()>

rockPaperScissorsResultDict[.win] = rockPaperScissorsWin
rockPaperScissorsResultDict[.draw] = rockPaperScissorsDraw
rockPaperScissorsResultDict[.lose] = rockPaperScissorsLose

// 로컬 영역
let result = model.matchResult(firstPlayer: userSelect, secondPlayer: computerSelect)

guard let process = mukJjiBbaResultDict[result] else { return }
process()

```

Ex) `Switch` 사용

```swift
// 로컬 영역
let result = model.matchResult(firstPlayer: userSelect, secondPlayer: computerSelect)

switch result{
case .win:
		rockPaperScissorsWin()
case .draw:
		rockPaperScissorsDraw()
case .lose:
		rockPaperScissorsLose()
}
```

### 스크린샷
![step2스샷](https://github.com/tasty-code/ios-rock-scissor-paper/assets/47639904/ad919b3a-b3a1-48cb-8c28-0587475210f6)

2023-11-28 11:51 UTC, jus1234 commented
@Mino777 마이노 마지막에 버그 발견해서 수정한 내용도 추가 했습니다! ㅜㅜ

2023-11-28 14:35 UTC, Mino777 requested changes
@jus1234, @kimbs5899

시디, 매튜 Step2 진행하시느라 고생 많으셨습니다👏👏

Step1에서 말씀드렸던 부분들을 하나도 빠짐없이 다 적용해주신점 정말 좋습니다👍👍

---------------------------------------------------------------------------------------

## 코멘트

### 고민 되었던 점

> - 함수를 기능 단위로 분리해 작성해봤습니다. 코드가 간결해지고 재사용성이 높아지는 점은 좋았지만 너무 많은 함수가 생성된건 아닌가 라는 생각이 들었습니다.

저도 똑같은 고민을 했었어서 괜시리 반갑네용ㅎㅎ 
이전에 코드 커멘트에도 남겨드렸듯이 저같은 경우 해당 고민을 더 상위 스코프로 확장 시켜서 해소했었습니다. 
오잉 메서드가 너무 많은데? 라는 생각이 든다면, 아 이제 메서드들의 역할과 책임은 충분히 나눴구나! 그럼 이제 이 메서드를 가지고있는 객체의 역할과 책임이 너무 많은건 아닐까? 
그리고 객체가 너무 많아지면, 이젠 이 객체들을 가지고있는 모듈의 역할과 책임이 너무 많은건 아닐까? 이런식으로 계속해서 확장시켜서 해소했던 것 같습니다.
이런 생각의 흐름으로 객체지향프로그래밍을 학습하시면서 계속해서 재설계, 재구조화, 최적화를 하시다 보면 자신도 모르게 공부 하지도 않은 어떤 디자인 패턴과 비슷한 코드가 되고, 어떤 아키텍처 패턴과 비슷한 코드가 되기도 하더라구요!
계속해서 이런 고민들을 하시면서 학습해가시면 좋을 것 같습니다😊
벌써부터 이런 고민을 하시는 것 자체가 정말 대단하신 것 같습니다👍👍

-------------------------------------------------------------------------------------
> - 변수, 함수 등 네이밍 할 때 지난 번에 공유해주신 가이드를 적용해 보는 과정이 생각보다 어려웠습니다.

사실 네이밍 같은 경우 계속해서 인지하고 고민해보시는 것 밖에 답이 없습니다ㅎㅎ
Swift 네이밍 컨벤션 문서 계속 보시면서 고민하시다보면 언젠가 그냥 툭툭 나오는 경험을 하시게 될꺼에요. 너무 스트레스 받지 않으셔도 됩니다. 
아니 근데 이번 스텝에서 네이밍 아주 잘해주셨어요! 이미 잘하고 계십니다👍👍

-------------------------------------------------------------------------------------

> - MVC 구조를 나눌 때 `print`함수를 실행하는 부분이 `View`라고 생각했습니다. 로직과 데이터를 처리하는 영역은 `Model`로 분리 했습니다. 구조를 나누는 과정에 고민이 많이 되었습니다.

아키텍처에 대한 고민 정말 좋습니다. 지금은 아무래도 콘솔이다보니 뭔가 애매하게 느껴지는게 당연합니다!
지금도 충분히 잘 나눠주신 것 같아서 앞으로 아키텍처 학습 하실 때 꿀팁을 드리자면, 꼭꼭 간단한 아키텍처 패턴이라고 생각이 드셔도, 샘플 프로젝트를 직접 짜보시고 직접 아키텍처에 대한 장점과 단점을 몸으로 느껴보시고 넘어가시는게 좋습니다.
그리고 뭐 어떤 아키텍처가 짱이다! 정답이다! 이런건 없으니,  각각의 아키텍처에 대한 이해도를 높여놓고, 나중에 어떤 상황이 왔을 때, 그 이해도를 통해 적재적소에 사용해야지! 라는 생각으로 학습하시는게 좋습니다👍👍

------------------------------------------------------------------------------------------------
### 궁금했던 점

> - 가위바위보 승무패 별 로직을 `switch`나 `if`문을 사용한 분기처리를 할 경우 너무 많은 분기가 생겨 `Dictionary`에 `closure`를 담아 해당하는 `closure`를 실행하는 방식으로 코드를 작성해 봤습니다. 실무에서는 이런 경우 어떤 식으로 해결하는지 궁금 합니다!

이렇게 자료구조를 최대한 활용하시는 것 정말 좋습니다😊
음 일단 이 질문에는 정답이 없습니다ㅎㅎ
팀에 따라, 상황에 따라 switch, if 문이 더 직관적이라 생각해서 선호하는 경우도 있고 이처럼 Dictionary를 활용해서 깔끔한걸 선호하는 경우도 있습니다.
그런데 그 이전에 실무에서는 앱단에서 코어한 로직과 관련된 분기가 많은 경우는 있으면 안된다고 보시면 됩니다.
앱단에서는 이런 분기문들과 비즈니스 로직을 최소화 시키는 방향으로 업무를 이끌어가시는게 가장 좋습니다ㅎㅎ
가장 큰 이유로는 앱 배포와 웹/서버 배포 방식의 차이와 관련이 있습니다.
만약에 업무를 진행하는데, 코어한 비즈니스 로직들이 앱단에 존재하는 경우엔 백엔드 개발자와 기획자를 붙잡고 "이런 로직들은 백엔드에서 녹여서 던져주셔야되요!!" 하시면 됩니다😎

------------------------------------------------------------------------------------------------

이번 PR의 경우 잘해주셔서 추가 코멘트는 필요 없을 것 같습니다!
아래 코드에 있는 코멘트들 잘 봐주시면 될 것 같습니다.
고생하셨습니다😁

라고 할려했는데, 하나만 더 말씀드릴게요!

이번 프로젝트는 이대로 진행하시고, 다음 프로젝트부터는 브랜치 관리 하실 때
피쳐 단위보단 한뎁스 더 들어가셔서 최상위 뎁스로 STEP1, STEP2 이런식으로 STEP 브랜치를 상위로 관리하시는게 좋습니다.
STEP1/feature/~~
요런 뎁스로 가시는게 좋습니다.
우선 가장 큰 이유로는 이제 앞으로 갈수록 프로젝트 볼륨이 커지고 그러다보면 각 STEP마다 README를 관리하시는게
나중에 보기도 좋고 관리도 좋습니다ㅎㅎ
STEP1에선 내가 이런 고민을 했고, STEP2에선 이런 고민을 했고 이런식으로요👍

2023-11-28 14:35 UTC, Mino777 commented on README.md
> +가위바위보 프로그램
와우..! 리드미를 작성하셨군요!! 정말 좋습니다.
순서도, UML, 출력물 스크린샷(출력물 스크린샷도 이번 스텝껄로 업데이트해주세요!) 까지!
너무 좋습니다👍👍

고민했던점과 해결과정, PR 링크 같은 것들도 추가해놓으시면 나중에 보기 편하실꺼에요🤗

2023-11-28 14:35 UTC, Mino777 commented on RockPaperScissors/RockPaperScissors/Controllers/GameController.swift
> +class GameController {
GameController가 이게 어떤게임 컨트롤러인지 명확하지 않은 것 같아요!

메서드 뿐만 아니라, 클래스 또한 네이밍이 명확하지 않네? -> 해당 객체,메서드가 맡고있는 책임, 역할이 많지 않을까? -> 한번 나눠볼까?! 라는 생각의 흐름을 연습삼아 계속 해보시는걸 추천드립니다ㅎㅎ

그러면 한번 나누어 볼까요? 단순하게 생각해보면 크게 가위바위보 게임, 묵찌빠 게임 컨트롤러로 나눠볼 수 있을 것 같네요!
이렇게 역할을 나눠 놓으면, 나중에 가위바위보 게임만 하고싶은 경우에 큰 수정없이 가위바위보 게임만 할 수 도 있고 너무 좋겠죠?!

어렵게 생각이 드실 수 도 있지만, 이미 기능 단위로 굉장히 잘 쪼개놓으셨기 때문에 쉽게 리팩토링 해보실 수 있을 것 같아요ㅎㅎ
막히시면 언제든지 DM 주세요!

2023-11-28 14:35 UTC, Mino777 commented on RockPaperScissors/RockPaperScissors/Controllers/GameController.swift
> +    private let view: View
접근제어자를 사용해보셨네요! 너무 좋습니다👏👏

캡슐화는 안전하고 이해하기 쉬운 코드를 만들기 위해서 꼭 필요합니다👍

2023-11-28 14:35 UTC, Mino777 commented on RockPaperScissors/RockPaperScissors/Controllers/GameController.swift
> +        view = GameView()
이렇게 생성이 필요한 인스턴스들은 해당 객체 밖에서 주입 해주는게 어떨까요?
ex)

```swift
init(model: ~model) {
    self.model = model
}
```

지금은 괜찮지만, 만약에 테스트를 위해 내가 원하는 인스턴스들을 넣어주고 싶을 때 지금과 같이 짜여진 객체라면
실제 객체의 코드를 수정해줘야겠죠?

이건 지금 수정 해보라고 말씀드리는건 아니고, 나중에 생각해보셔도 되는 문제이니, 심심하실 때 의존성 주입이라는 개념에 대해서 가볍게 읽어보시고, 이런 개념이 있구나~ 정도만 인지해보시고, 추후에 학습해보시면 좋을 것 같습니다ㅎㅎ
결국 의존성 주입이 테스트를 위한 코드에 있어서 코어한 개념이라고 저는 생각하기에 이런 개념이 있구나 라는걸 꼭 인지하시고 프로젝트들을 진행하시면 아주 좋습니다👍👍

2023-11-28 14:35 UTC, Mino777 commented on RockPaperScissors/RockPaperScissors/Controllers/GameController.swift
> +    }
위쪽에서 rockPaperScissorsWin, rockPaperScissorsDraw 같은 메서드가 있어서 보려고 했더니 코드라인이 상당히 아래에 있네요!
또 pushGame 메서드 같은 경우는 pushGame 메서드의 코드라인보다 하단에서 사용하고있는데 위쪽에 있네요!

메서드를 위치 시킬 때 판단하는 요소로 저는 가독성이 좋은가?(사용하는 순서대로 위치) -> 같은 역할들이 모여있는가? 단계로 생각해보고 위치 시킵니다.
메서드를 사용하는, 호출하는 순으로 메서드 위치를 나열해주면 코드를 읽을 때 코드점핑이 없이 스크롤이 턱턱 안걸리고 스무스하게 읽을 수 있습니다.

물론 이 부분은 개인적인 의견이므로 여러분들이 생각해보셨을 때 더 나은 방향으로 진행하시면 됩니다ㅎㅎ

2023-11-28 14:35 UTC, Mino777 commented on RockPaperScissors/RockPaperScissors/Controllers/GameController.swift
> +        guard let process = rockPaperScissorsResultDict[result] else { return }
guard문을 사용할 때 return scope의 경우 줄바꿈을 해주시는게 좋습니다.

디버깅시 이와 같이 한줄로 작성되있는 경우 return 되는 케이스에 브레이크포인트가 걸리지 않아서
결국 줄바꿈하고 브레이크포인트를 걸어야하는 일이 생깁니다🙄

```swift
guard let process = rockPaperScissorsResultDict[result] else {
 return 
}
```

2023-11-28 14:35 UTC, Mino777 commented on RockPaperScissors/RockPaperScissors/Controllers/GameController.swift
> +        let computerSelect = model.random()
model이 어떤 model 인지 직관적이지 않아서 다시 올라가서 보고 와야될 것 같아요!

길더라도 model 명까지 붙여서 네이밍 해주는게 좋을 것 같습니다👍
ex) sidiModel / mattewModel

2023-11-28 14:35 UTC, Mino777 commented on RockPaperScissors/RockPaperScissors/Controllers/GameController.swift
> +        }
public 접근제어자도 사용하셨군요! 좋습니다👍

지금이야 public, internal를 왜 굳이 나눠놨을까 라는 생각이 드실 수 도 있지만,
하나의 모듈이아닌 가위바위보 모듈, 묵찌빠 모듈 이런식으로 수많은 모듈로 모듈화 되었을 땐
public 키워드를 쓰지 않으면 컴파일 에러가 나게됩니다ㅎㅎ
지금부터 public과 interanl 키워드를 구분해서 사용하는 습관을 들여놓으면 나중에 편하실꺼에요😊

2023-11-28 14:35 UTC, Mino777 commented on RockPaperScissors/RockPaperScissors/Views/View.swift
> +}
protocol을 사용해보셨군요! 너무 좋습니다👍

가면갈수록 protocol의 사용 용도와 중요성은 점점 커지실꺼에요!
protocol 학습하실때도 깊게 학습하시는걸 추천드립니다😊

2023-11-28 14:35 UTC, Mino777 commented on RockPaperScissors/RockPaperScissors/Models/RockPaperScissorsModel.swift
> +    }
swift 네이밍 컨벤션에서 메서드 네이밍에 get을 붙이는것은 권장하지 않습니다.
(이유로는 보통 REST API 메서드 네이밍과의 혼용, Java와 헷갈림, 명확하지 않음 등등이 있습니다ㅎㅎ;;)

get이 너무 찰떡인 메서드의 경우 보통 연산 프로퍼티로 구현하거나, 아예 리턴하는 타입명으로만 네이밍을 하는 경우도 있습니다.
위 메서드의 경우 순환큐의 동작도 진행을 하기 때문에 next + 리턴 타입명 이런식으로 지어도 나쁘지 않을 것 같습니다.

메서드는 왠만하면 동사형 시작 or 형용사 + 리턴 타입명 이 두가지 케이스로 많이 사용합니다.
물론 네이밍은 컨벤션의 영역이기에 swift 컨벤션에서 권장하지 않는 네이밍을 제외하고는 팀 컨벤션을 따라가면 됩니다😊

2023-11-29 06:05 UTC, jus1234 commented
@Mino777 마이노! 리뷰 반영해 리팩토링한 내용 커밋 했습니다! 꼼꼼한 리뷰 감사합니다~~

2023-11-29 09:10 UTC, Mino777 approved these changes
@jus1234 @kimbs5899 
시디, 매튜! Step 2도 정말 고생많으셨습니다👏👏

너무 계속 말씀드리는 것 같지만 메서드, 객체들의 역할과 책임 분리에 대해서 항상 생각하시면서 앞으로도 프로젝트 진행하시면 너무 좋을 것 같아요👍👍 ([객체지향생활체조원칙](https://jamie95.tistory.com/99) 해당 내용도 인지하면서 개발하시면서 습관 들이시면 좋은 내용입니다!)
그리고 의존성 주입에 대해서도 가볍게 학습해보세요🤗

코멘트 드린 부분들 확인 및 간단한 수정들(굳이 수정 안하셔도 되긴 합니다!) 완료하시면 머지하도록 하겠습니다~!

궁금하신점 생기시면 언제든지 DM 주세요!!
앞으로도 빠이팅입니다💪💪

2023-11-29 09:10 UTC, Mino777 commented on RockPaperScissors/RockPaperScissors/Controllers/Controller.swift
> +}
크..! protocol을 통해 두 컨트롤러의 추상화까지 해보셨군요 정말 좋습니다👍👍

이렇게 되면, 이전에 말씀드렸던 의존성 주입을 진행한다면 해당 프로토콜 타입을 통해
가위바위보 컨트롤러도 주입할 수 있고, 묵찌빠 컨트롤러도 주입할 수 있게 됐네요🤗

ex) (너무 어거지로 대충짜서 그냥 이런 느낌이구나 하고 느낌만 보시면 될 것 같아요!)
```swift

public enum Constants {
  static let aControllerMessage: String = "A컨트롤러인 경우의 makeTestMessage 메서드를 테스트하고싶어!"
  static let bControllerMessage: String = "B컨트롤러인 경우의 makeTestMessage 메서드를 테스트하고싶어!"
  static let aControllerTestResultMessage: String = "오 내가 원하던 a 메세지가 나왔다! 해당 메서드는 잘 동작하네!"
  static let bControllerTestResultMessage: String = "오 내가 원하던 b 메세지가 나왔다! 해당 메서드는 잘 동작하네!"
  static let realControllerResultMessage: String = "실제 객체 데이터"
}

public protocol Controllerable {
  func makeMessage() -> String
}

public final class ExampleFactory {
  private let aController: Controller = ATestStub()
  private let bController: Controller = BTestStub()
  
  func makeExampleWithAController() -> Example {
    .init(controller: aController)
  }
  
  func makeExampleWithBController() -> Example {
    .init(controller: bController)
  }
}

public final class Example {
  private let controller: Controllerable
  
  init(controller: Controllerable) {
    self.controller = controller
  }
  
  func testController() -> String {
    if controller.makeMessage() == Constants.aControllerMessage {
      return Constants.aControllerTestResultMessage
    }
    
    if controller.makeMessage() == Constants.bControllerMessage {
      return Constants.bControllerTestResultMessage
    }
  }
}

final class RealController: Controllerable {
  func makeMessage() -> String {
    Constants.realControllerResultMessage
  }
}

final class ATestStub: Controllerable {
  func makeMessage() -> String {
    Constants.aControllerMessage
  }
}

final class BTestStub: Controllerable {
  func makeMessage() -> String {
    Constants.bControllerMessage
  }
}

```

2023-11-29 09:10 UTC, Mino777 commented on RockPaperScissors/RockPaperScissors/Controllers/MukJjiBbaController.swift
> +    internal var resultDict: Dictionary<Match, () -> ()>
internal은 명시하지 않아도 됩니다ㅎㅎ

func a()
internal func a()
두 메서드 모두 internal 접근제어를 가집니다.

물론 해당 부분이 팀의 컨벤션이라면 상관없습니다. 그런데 조금 귀찮잖아요?😎

2023-11-29 09:10 UTC, Mino777 commented on RockPaperScissors/RockPaperScissors/Controllers/RockPaperScissorsController.swift
> +struct RockPaperScissorsController: Controller {
이번엔 struct를 사용해보셨군요!! 좋습니다👍👍

기존 class에서 struct로 변경해보신 이유와 class, struct의 차이에 대해서 간략하게 설명해주세요!

2023-11-29 09:10 UTC, Mino777 commented on RockPaperScissors/RockPaperScissors/Controllers/RockPaperScissorsController.swift
> +    public mutating func process() {
mutating 키워드를 사용해보셨네요!

해당 키워드에 대한 간략한 설명 및 해당 키워드를 사용할 때 주의해야할 점에 대해서 설명해주세요~!

2023-11-29 09:10 UTC, Mino777 commented on RockPaperScissors/RockPaperScissors/Controllers/MukJjiBbaController.swift
> +class MukJjiBbaController: Controller {
와우,, 정말 빨리 리팩토링 하셨네요. 너무 좋습니다👍👍

앞으로도 뭔가 볼륨이 커지는게 느껴질때면 자연스럽게 해당 메서드, 객체의 책임이 많은지 부터 고민해보세요🤗

그리고 Controller들에 중복 메서드들이 조금 보이는 것 같아요! 해당 부분들도 ~Handler 느낌의 객체로 분리해보시면 좋을 것 같아요!
해당 부분은 학습 다하시고 시간 남으시면 각자 해보시면 될 것 같습니다ㅎㅎ

2023-11-30 00:40 UTC, kimbs5899 commented on RockPaperScissors/RockPaperScissors/Controllers/RockPaperScissorsController.swift
> +struct RockPaperScissorsController: Controller {
클래스는 참조 타입이고 클래스는 상속이 가능합니다!
구조체는 값 타입이고 상속이 불가능합니다~! 😄

2023-11-30 00:43 UTC, kimbs5899 commented on RockPaperScissors/RockPaperScissors/Controllers/RockPaperScissorsController.swift
> +    public mutating func process() {
구조체에서 저장변수의 값을 변경하는 매서드에 붙이는 키워드입니다!
주의할점은 구조체의 경우 값타입이기 때문에 인스턴스를 변경할 수 없습니다.
그래서 너무 많은 mutating이 사용되는 경우 인스턴스가 새로 많이 생성되는 경우가 발생할 수 있습니다~!!😆

2023-11-30 01:42 UTC, jus1234 commented
@Mino777 마이노! 핸들러 분리 작업해서 커밋 했습니다! 머지 부탁드려요~!

2023-11-30 02:14 UTC, Mino777 commented on RockPaperScissors/RockPaperScissors/Controllers/RockPaperScissorsController.swift
> +    public mutating func process() {
@jus1234 @kimbs5899 
좋습니다! 그런데 mutating을 사용할 때 인스턴스가 새로 많이 생성된다는 점은 조금 정정이 필요해보입니다ㅎㅎ

mutating 키워드는 변경된 인스턴스로 기존 인스턴스를 대체하는것이기 때문에 생성이 아닌, 변경한다고 이해하시면 좋을 것 같습니다ㅎㅎ (문서를 찾지는 못했는데, 변경된 필요없는 인스턴스가 메모리에 계속 남아있게 설계해놓지 않았을꺼에요!)

주의해야 할 점은, 메서드가 인스턴스의 상태를 변경할 수 있다는 것과 이러한 변경이 예상치 못한 사이드 이펙을 발생시킬 수 있다는 점! 꼭 알고 쓰시면 좋을 것 같습니다🤗

[공식문서](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/methods/)

2023-11-30 02:24 UTC, Mino777 commented on RockPaperScissors/RockPaperScissors/Controllers/Handler.swift
> +}
Handler 객체로 분리해보셨네요! 좋습니다

네이밍들이 조금 아쉽지만, 앞으로도 계속 네이밍 하실 때 가이드라인 문서 많이 보시고 명확성을 중점적으로 고민해보시길 바랍니다🤗

고생하셨어요!

2023-11-30 02:27 UTC, merged