묵찌빠 프로그램 [STEP 2] 이안,엘
tasty-code/ios-rock-scissor-paper pull request #56
Opened 2023-11-29 04:16 UTC by rlwhs12

@GREENOVER 

안녕하세요 
STEP2 묵찌빠 PR 입니다.

<h2>구현하려고 노력한 점</h2>

- 모르는 사람이 봐도 한 번에 알아볼 수 있게 가독성에 신경을 썼습니다. 
- 네이밍에 최대한 신경을 썼습니다. 네이밍만 봐도 무엇을 하는지 추측할수있도록 노력했습니다.
- 함수에 최대한 한가지 기능만 구현할라고 노력했습니다. 함수 하나당 한가지 기능만 있는게 좋다는 글을 봐서 그렇게 구현하려고 노력했습니다.

<h2>진행하면서 궁금한 점</h2>

- Private을 선언한 함수를 다른 파일에서 사용하기 위해 변수에 담아서 사용하는 것이 옮은 방법인지 궁금합니다.
- 지금코드는 입력을 한곳에서 받는데, 가위바위보를 입력받는 함수와 묵찌바를 입력받는 함수를 2개를 사용해서 구현하는게 더 좋은지 궁금합니다.
- 은닉화 및 캡슐화 시 클래스나 구조체로 만드는게 좋은방법인지 함수로 하는게 더 좋은방법인지 궁금합니다.
- 처음부터 클래스나 구조체로 구현하는게 더좋을까요. 어느 기준을 두고 함수로 설계할지, 클래스나 구조체로 설계를 할지 궁금합니다.
- 삼항연산자 보다는 if문이 더 가독성이 좋아 보인다고 생각이 드는데 가독성 측면에서 어떤게 더 좋은지 if문을 사용하는게 좋으지  삼항연산자를 사용하는게 더 좋은방법인지 궁금합니다.
- 함수로 다 나누니까 함수가 너무 많아지는거 이런경우에도 나눌수있는 경우에 함수로 계속 나누어야하는지 아니면 더 좋은방법이 있는지 궁금합니다.
- 파일을 나눌때 어떤 기준으로 나누는게 더 좋은방법인지 궁금합니다.
- 변경된 네이밍이 괜찮은지 네이밍 잘 짓는 방법이 있는지 궁금합니다.
- 현재 단계에서 어느것을 더 공부하면 좋을까요.

2023-11-29 05:52 UTC, GREENOVER requested changes
@rlwhs12 @LeeSe0ngYe0n 
두분 스텝 2도 고생 많으셨습니다!
동작에 이상없이 스텝 2 잘 마무리된것 같아요ㅎㅎ
코드 리뷰는 지금 현재 기초 단계에서 필요한 메서드, 로직 분리 등과 네이밍 등 가장 기본적인 부분들에 대해 주로 간단히 코멘트를 남겼습니다!
궁금하신 부분에 대해서 리뷰 드리고 싶은 코멘트도 겹쳐서 코멘트에선 생략하고 해당 PR 전체 코멘트로 답변도 남겨볼께요ㅎㅎ
***
### 칭찬 드리고 싶은 부분
- 커밋 이력 관리가 스텝 2도 잘 되었네요 💯
- 스텝 1때보다 코드의 네이밍 및 분리가 잘 이뤄져서 가독성이 좋아요 💯
***
### 궁금하신 부분에 대한 저의 의견
- Private을 선언한 함수를 다른 파일에서 사용하기 위해 변수에 담아서 사용하는 것이 옮은 방법인지 궁금합니다.
  - 보통 현재처럼 함수형으로 로직을 짜게 되었을때 다른 파일에서 사용하게 된다면 private하게 가지 않는것이 적절할거라고 생각이 들며, 말씀처럼 변수에 담아서 사용할 수도 있겠지만 객체로 만들어서 외부 internal한 메서드를 통해 private을 내부적으로만 사용하도록 하는것이 더 적절할것 같습니다!
- 지금코드는 입력을 한곳에서 받는데, 가위바위보를 입력받는 함수와 묵찌바를 입력받는 함수를 2개를 사용해서 구현하는게 더 좋은지 궁금합니다.
  - 현재 스텝2까지의 요구사항으로보면 필요없을 수 있지만 언제 어떻게 유지보수나 기능이 확장될지 모르기에 항상 최대한 분리해보면서 추후 확장성을 높여갈 수 있도록 분리해보는 연습을 추천드립니다 🙋🏻
- 은닉화 및 캡슐화 시 클래스나 구조체로 만드는게 좋은방법인지 함수로 하는게 더 좋은방법인지 궁금합니다.
  - 현재 프로젝트는 단순 콘솔 앱이기에 함수형으로 만들어도 충분히 괜찮습니다.
  다만 말씀처럼 은닉화와 캡슐화의 장점을 활용하면서 조금 더 구조적으로 가져가시려면 클래스나 구조체 즉, 객체로 가위바위보 로직, 묵찌빠 로직 등을 가져간다면 더 확장성과 코드 자체도 잘 활용할 수 있을것 같아요 🙋🏻
- 처음부터 클래스나 구조체로 구현하는게 더좋을까요. 어느 기준을 두고 함수로 설계할지, 클래스나 구조체로 설계를 할지 궁금합니다.
  - 함수형 vs 객체지향형 요 차이를 먼저 살펴보는것이 좋을것 같습니다.
  매 상황마다 다르겠지만 현재 프로젝트에서는 함수형으로 가도 충분히 무방합니다.
  그 외 앞으로 마주할 프로젝트들이 다양할텐데 기준을 두는 방법은 앞서 질문에서 말한 조금 더 현실로 끌어와보는겁니다.
  해당 가위바위보 로직을 예시로 들면 내부적으로 사용되는 메서드 및 프로퍼티들을 가지고 조금 더 코드를 재사용하고 확장할 여지가 있다면 그 프로퍼티 및 메서드들을 가진 객체로 사용하는편이 더 적절할것 같아요.
- 삼항연산자 보다는 if문이 더 가독성이 좋아 보인다고 생각이 드는데 가독성 측면에서 어떤게 더 좋은지 if문을 사용하는게 좋으지 삼항연산자를 사용하는게 더 좋은방법인지 궁금합니다.
  - 가독성 측면에서는 정말 케바케입니다.
  취향에 따라서 어떤것이 더 가독성이 좋게 느껴진다~ 라는것이 있을 수 있을것 같아요!
  다만 삼항연산자는 두개 이상 조건을 넘어가면 사용하지 못하겠지만, 두개의 조건이라면 어떤것을 써야하느냐는 정말 정말 스타일 차이라고 보여요.  
  제가 알기론, 성능에서도 차이가 없는 편입니다~
  그래도 저의 사용 기준을 말해보자면 간결하게 짧게 표현해도 될것 같으면 삼항연산자로, 추후 유지보수나 복잡한 조건일때 코드 가독성에 더 초점을 둘때는 if 조건문을 사용합니다 🙋🏻
- 함수로 다 나누니까 함수가 너무 많아지는거 이런경우에도 나눌수있는 경우에 함수로 계속 나누어야하는지 아니면 더 좋은방법이 있는지 궁금합니다.
  - 함수로 많이 나눠져서 코드가 길어질 순 있지만 오히려 더 명확하다고 생각합니다.
  그렇기에 최대한 잘게 쪼개보시면서 그 잘게 쪼갠 함수중 조건만 변경되어 비슷한 기능을 하는 함수가 있다면 합쳐 가는 방법으로 리팩토링 해보면 좋을것 같아요~!
  다만 어떤 프로퍼티 하나 바꾸는것도 별도 메서드로 분리하거나 이정도까지 잘게 쪼개는것은 취향이겠지만 저는 그렇게까지 나누지는 않습니다!
  이것도 스타일로 이게좋다 저게좋다라는건 없고 두 방식에서 장단점들이 각각 있어서 최대한 여러 방법을 해보시길 바래요!
  가장 중요한건 여러분들이 이유있게 여러분들의 스타일을 찾아보는것이 필요합니다 🙋🏻
- 파일을 나눌때 어떤 기준으로 나누는게 더 좋은방법인지 궁금합니다.
  - 파일을 나눌때 저는 목적과 용도를 기준으로 폴더 그룹 및 파일을 나누는 편입니다.
  예를들어, 현재 코드에서도 스텝 1때 말씀드린것처럼 Enums라는 폴더 그룹 안에서 네임 스페이스 파일을 나누듯이요..!
  그렇기에 같은 목적과 용도를 가진 코드들끼리 파일 및 폴더를 구성하는편이 추후 다른곳에서 사용될때 그리고 유지보수할때도 편리합니다.
  파일이 지금은 몇개 없지만 나중에 수천개가 될때 폴더 그룹화 및 파일명 그리고 파일을 생성한 기준들이 명확한것이 도움이 됩니다 🙋🏻
- 변경된 네이밍이 괜찮은지 네이밍 잘 짓는 방법이 있는지 궁금합니다.
  - 스텝 1보다 스텝 2에서 훨씬 네이밍에 짓는것에 대해 더 적절하게 코딩하신것 같습니다!
  네이밍도 답이 없지만 최대한 많은 여러 개발자들에게 익숙한 네이밍을 택하는것이 보편적으로 좋을것 같은데요.
  이에 뭐 프로퍼티는 명사형 메서드는 동사형 이런 기본적인것에서 벗어나서 가장 현실적으로 네이밍 작명에 대해 늘 수 있는 방법은 많은 코드를 보는것입니다.
  저도 그랬으며, 많은 외부라이브러리, 애플 공식문서에서 사용되는 예제들 이런것들에서 프로퍼티나 메서드들의 네이밍을 어떻게 짓는지, 어떤 워딩을 사용하는지를 자주 그리고 많이 보시면 익숙해지시고 늘거에요..!
- 현재 단계에서 어느것을 더 공부하면 좋을까요.
  - 지금이 가장 초기 즉, 기본 단계라고 생각해볼께요 🙋🏻
  그렇다면 Swift만 지금 많이 해보시는걸 추천합니다.
  이후 프로젝트들이 나올때 슬슬 iOS는 찐하게 접하실거라 Swift를 같이 병행할 시간이 부족할 수 있으니 지금 최대한 빡세게 굴려보면 좋을것 같아요.
  Swift의 기본에서 벗어나서 조금 더 딥하게 생각해보는거죠.
  예를들어, Swift에서 기본 자료형과 같은 타입을은 왜 Struct로 정의되어 있는지?
  어떤 이점과 생각을 가지고 그렇게 설계한것인지 가장 근본적인 부분을 파고들면 좋을것 같습니다.
***
고생 많으셨습니다!
동작은 이상없어 어프로브해도 무방하지만 한번 확인차 우선 리퀘스트 체인지로 드리겠습니다~
언제든 머지 요청해주세요!

2023-11-29 05:52 UTC, GREENOVER commented on RockPaperScissors/RockPaperScissors/MukchippaLogic.swift
> +var turnStatus = true
turnStatus라는 네이밍만 보면 뭔가 열거형으로 턴에 대한 상태들의 값을 가질것 같은데 Bool 타입이라 조금 어색해보입니다 🤔

2023-11-29 05:52 UTC, GREENOVER commented on RockPaperScissors/RockPaperScissors/MukchippaLogic.swift
> +let userTurn = true
Bool 타입과 어울리게 isComputerTurn과 같은 네이밍은 어떨까요~?

2023-11-29 05:52 UTC, GREENOVER commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperLogic.swift
> +func checkingWorkMukchippa(userInputNumber: Int, computerRandomNumber: Int) {
private 해도 되지 않을까요~?

2023-11-29 05:52 UTC, GREENOVER commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperLogic.swift
> +        checkingWorkMukchippa(userInputNumber: userInputNum, computerRandomNumber: computerRandomNum)
check와 checking 어떤 의미로 메서드에서 적절하게 구분하여 사용할 수 있을까요~? 🙋🏻

2023-11-29 05:52 UTC, GREENOVER commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperLogic.swift
> +    compareRockScissorsPaper(userInputNumber: RockScissorsPaperCase(rawValue: userInputNumber)!, computerInputNumber: RockScissorsPaperCase(rawValue: computerRandomNumber)!)
적절히 개행을 주면 어떨까요~? 가독성이 더 좋아질것 같아요!
예를들어 이런식으로요.

```swift
isWorkingMukchippa
? compareMukchippa(
  userInputNumber: RockScissorsPaperCase(rawValue: userInputNumber)!,
  computerInputNumber: RockScissorsPaperCase(rawValue: computerRandomNumber)!
)
: compareRockScissorsPaper(
  userInputNumber: RockScissorsPaperCase(rawValue: userInputNumber)!,
  computerInputNumber: RockScissorsPaperCase(rawValue: computerRandomNumber)!
)
```

2023-11-29 05:52 UTC, GREENOVER commented on RockPaperScissors/RockPaperScissors/RockScissorsPaperLogic.swift
> +        isWorkingMukchippa = true
아래와 동일한 로직이 반복되는데 메서드로 분리해보면 어떨까요?

2023-11-30 07:06 UTC, GREENOVER approved these changes
스텝 2 리팩토링된것 확인했습니다!
묵찌빠 프로젝트 2주간 고생 많으셨습니다ㅎㅎ

2023-11-30 07:06 UTC, GREENOVER commented on RockPaperScissors/RockPaperScissors/MukchippaLogic.swift
> +var isWhoTurn = true
isWhoTurn은 누구턴? 이라는 워딩으로 보여지는데 Bool 타입인게 조금 어색해보입니다 🥲

2023-11-30 07:06 UTC, GREENOVER commented on RockPaperScissors/RockPaperScissors/MukchippaLogic.swift
> +var isWhoTurn = true
Turn에 대한 Enum 타입을 사용하여 아래 isComputerTurn, isUserTurn들을 같이 묶어 표현해봐도 좋을듯합니다!

2023-11-30 07:07 UTC, GREENOVER commented
앗..!
머지하려보니까 현재 보시는것처럼 병합해야할 브랜치가 잘못설정되있습니다~
요 부분 수정 부탁드려요 🙋🏻
![스크린샷 2023-11-30 오후 4 06 49](https://github.com/tasty-code/ios-rock-scissor-paper/assets/72292617/6311ca8f-96a0-428f-a13e-6b53fd4b47c7)

2023-11-30 07:12 UTC, ianK0909 commented on RockPaperScissors/RockPaperScissors/MukchippaLogic.swift
> +var isWhoTurn = true
Bool 타입 네이밍을 다시 한번 신경써서 수정하겠습니다. 
Enum으로도 묶어보겠습니다.

2023-11-30 07:12 UTC, merged