묵찌빠 프로그램 [STEP 2] Andy, Lj
tasty-code/ios-rock-scissor-paper pull request #58
Opened 2023-11-29 06:35 UTC by andyanappdev

@keeplo
STEP1의 가위, 바위, 보 게임의 결과에 따라 묵찌빠 게임이 실행되도록 구현 하였습니다.

### 가장 신경쓴 부분
- 프로퍼티 및 메서드 Naming
- 재귀 함수로 인한 스택오버플로우를 방지하기 위해 while문으로 구현
- Completion을 활용한 구현
---
### Andy 의 생각
우선 꼼꼼하게 리뷰를 해주시는데 그에 걸맞지 못한 PR 메시지를 작성한점 사과 드립니다.

가장 신경쓴 부분 으로 표현한 이유에 대해 말씀드리겠습니다.

재가 STEP2를 시작하면서 엘제이에게 강조 한부분이
“최소한 STEP1 에서 comment 주신 내용과 똑같은 실수만큼은 하지 말자!” 였습니다.

- 프로퍼티 및 메서드 naming에 가장 많은 comment를 받았기에 STEP2 에서는 저도 적극적으로 저의 의견을 전달하였습니다. 코드 작성시 뿐만 아니라 PR 하기전 최종적으로 한 검토가 naming 부분이었습니다.
- STEP1 마지막 까지 저희에게 재귀 함수의 위험성과 이를 피하기 위한 방법을 스스로 학습할수 있도록 이끌어 주셨기에 이를 인지하고 구현하고 있음을 보여드리고 싶었습니다.
- Completion 활용 부분은, 유저 input을 받는 기존 메서드에 1. 재활용 또는 최소한의 변경으로 묵찌빠 게임에도 대응 할수 있어야 하며, 2. 현재 설계(프로퍼티에 값을 변경 할당하는 방식)를 유지, 이 두가지를 지키기 위한 방법으로 최적이 completion 사용이라는 결론을 엘제이가 내려 주었습니다.
    - 저는 프로퍼티 변경이 아닌 다른 방식의 아이디어를 제안 하였지만, 저의 아이디어는 전반적인 설계변경이 필요해지는 치명적인 문제가 있었습니다. 저희에게 주어진 한정된 resource 내에서 가장 합리적인 output 도출에는 적합하지 못했습니다.
    - 모든 프로젝트나 일에는 가장 중요한 deadline 이라는 것이 존재 합니다. 이 부분은 절대적이라 생각 합니다. 물론 말꼬와 상의를 통해서 조율이 가능 하다는 추가 옵션을 가지고 있지만 이것 또한 옵션일 뿐 그러니까 상황에 따라 deadline을 지키지 않아도 된다는 것은 아니라 생각합니다.
    - 그렇다면 설령 저의 아이디어가 유지보수 및 추후의 업데이트를 고려할때 더 올바른 방식일수도 있겠지만 deadline을 지킬수 없는 방법은 좋은 방법이 될수 없다고 저는 생각 합니다. 재가 전업하기전에 사회생활을 하면서 느낀 부분입니다. 아무리 훌륭하고 좋은 방법이라도 기한을 지키지 못하는 방법은 회사 관점에서는 그 방법은 무조건적으로 손해를 발생시키기 때문에 잘못된 방법이 되기 때문입니다.    

저는 설계에 좀 심할정도로 집착을 하는 스타일 입니다. 꼭 coding 뿐만 아니라 노트 정리 등등 저의 일상에 전반적으로 구조 설계 이런 부분에 집착이 심한 성격입니다.
그러다 보니 프로젝트를 시작할때 설계가 되지 않으면 코드로 구현을 하지 못합니다. ㅜㅜ 그리고 설계에 많은 시간이 투입되다 보니 다른 사람들보다 계발 진행 속도가 많이 늦고 시간이 오래 걸립니다.
이번 부트캠프 사전과제도 저는 Clean Architecture를 적용하여 구현 하였습니다. 그 이유는 유지 보수 및 업데이트에 용의하고 상황에 따라 갈아 끼울수 있는 유연한 설계의 위대함을 잘 알고 있기 때문에 Swift로 꼭 한번 해보고 싶었기 때문 입니다.

솔직하게 엘제이의 아이디어와 설계를 채택하여 진행하기로 결정이 된 이후 
저는 최대한 엘제이의 코드 작성 스타일 등을 존중 하면서 진행하자 라고 저 마음속으로 계속 되뇌었습니다.
페어코딩이 처음이라 어떻게 진행하는 것이 합리적인지 잘 몰랏기 때문입니다.

사실 PR을 보내기 전에 엘제이와 상당히 긴 시간 동안 회의를 했습니다.
이번 프로젝트에 재설계가 필요 한지? 만약 한다면 어떤 식으로 하고 싶은지에 대해서 서로의 의견을 교환 했습니다.
그 과정에서 저희가 내린 결론은 리팩토링을 하지 말자 이대로 가자 였습니다.
그 이유는 아래와 같습니다.
- Deadline
    - 저의 리팩토링 아이디어를 적용 한다면 완전히 모든것을 다 갈아 엎고 모든것을 다시 구현해야 하는데 그러기에 저희에게 주어진 시간 resource 의 deadline 을 엄수하지 못할 가능성이 매우 높다고 판단 했습니다.
- Input 대비 Output으로 얻을수 있는 이점
    - 저희 두명이 잠을 안자고 어떻게든 human and time resource를 투입해서 기한을 지켰다고 가정 했을때 이 프로젝트에서 얻을수 있는 이점이 크게 없다고 결론을 내렸습니다.
- 묵찌빠 프로그램이 첫번째 프로젝트로 선정된 이유? 이 프로젝트가 무엇을 학습시키기 위한 것인가?
    - 저의 관점에서는 묵찌빠 프로젝트는 컴퓨팅적인 사고를 연습시키기 위한 프로젝트라고 판단 했습니다. (코드가 순차대로 실행되는 과정에서 반복이 필요한 경우의 처리 방법, 조건을 확인하는 방법을 연습하고 학습하기 위함) OOP를 활용을 연습시키기 위한 프로젝트가 아니라고 보였습니다. 그렇다면 주어진 프로젝트가 무엇을 위한 것인지를 이해하고 그에 부합하도록 하는 것이 좀더 합리적이라고 저는 생각했고 저의 주장으로 엘제이를 설득 시켰습니다.
---
### LJ의 생각
우선은 STEP2에서 STEP1의 구조와는 다르게 두개의 클래스 구조로 혹은 진정한 의미의 객제지향설계를 고려하지 못한점에 대해서는 저희도 상당히 아쉽다고 생각합니다.
하지만, STEP1에서 배운 SWIFT API GUIDELINE에 맞는 네이밍 컨벤션을 적용하고 마찬가지로 재귀함수를 호출하는 경우에 위험을 제거하고 실제 코드에 적용하는데 저희도 나름대로 노력을 하였습니다.
저희의 구현력을 높이 평가해주셔서 너무 감사하지만, 아직은 과정 초반이기도 하고 객체지향프로그래밍이 익숙하고 아직 체화되지 않은 부분도 있고 시간적인 제약도 있어서 저희의 진행방향이 고차원적인 설계로 이어지지 못했던것 같습니다. 다음 프로젝트부터는 말씀하신대로 유지보수가 용이하고 스위프트가 지향하는 프로토콜, OOP에 알맞는 설계를 할 수 있도록 최선을 다하겠습니다.

처음 설계했을때 제 머릿속에 든 생각은 아직 OOP에 익숙치 않다보니, 우선 게임이 진행되는 절차, 즉 시간의 흐름대로 쭈욱 구현해보자는 것이었습니다.
그래서 while문안에 모든 비즈니스 로직이 들어가게 되었고, 사용자가 다시 입력을 해야하는 상황이 되었을때 처음에는 재귀로 처리를 하려고 했으나, 재귀 사용을 피하기 위해 while문을 쓰다보니 결과적으로는 이중 반복문이 될 수 밖에 없었던것 같습니다.
구현에 급급했던터라 지나고 나니 이중반복문은 확실히 유지보수에 적합하지 않다고 느꼈고 다음부터는 최대한 지양하는 방향으로 설계를 하겠습니다 !!

그리고 제가 개인적으로 궁금한 부분은 크게 두가지인데요.

언급하셨던 부분중에 “모든 함수가 프로퍼티 변경과 연관되었을때” 혹시 안좋은점이 뭔지 여쭤보고 싶습니다.

그리고 제가 프로젝트를 새로 설계한다면 가위바위보와 묵찌빠 class 두개가 존재하고 전체적으로 게임을 관장하고 실행시키는 컨트롤러 class로 나누려고 하는데요.
이에 대한 marco의 의견 혹은 marco라면 어떻게 설계를 하실지가 궁금해지네요.

2023-11-29 15:25 UTC, keeplo requested changes
@ijs1103 @nation81

Step 2 진행하시느라 고생많으셨어요!
예상보다 금방하셔서 탄탄한 구현력이 느껴집니다!

---

리뷰에 앞서서 전달드리고 싶은 내용이 있습니다!

PR을 남겨주실때  두 분이 고민한 점은 어떤점이 있는지, 
트레이드오프로 결정된 부분이 어떤점이 있는지 등등

개발 과정을 공유해주시면 좋을것 같아요!

`가장 신경쓴 부분` 으로 남겨주셨는데
구성하기 어려워서 신경 쓴 건지, 가장 시간을 많이 소요해서 그렇게 표현한건지
전달이 되지 않아서 코드만 보고 보여지는 내용만 답변 드릴 수 밖에 없었어요!

좀 더 배경지식을 만들어 주실수록 리뷰도 풍부한 방향을 고민해보실 수 있게 도와드릴 수 있을것 같아요

---

개발자 개인차가 있고 리뷰어마다도 스타일이 있을텐데
`저는 기능이 돌아가는건 기본` 이라는 깐깐한 스타일이에요! ㅎㅎ
다른 기능이 추가될때, 업데이트가 필요할때 등등 
과거를 잊은 미래의 나 나, 다른 개발자가 남이짠 코드를 잘 다룰 수 있게 하는 코드
유지보수가 용이한 구조를 지향하는 타입에 개발자에요

그러다보니.. while 반복문이 돌다 말고 묵찌빠 게임으로 넘어가서 다시 반복문이 도는 
특이하지만 결국 이중반복 구조안에 들어와있는 부분이라거나
모든 함수가 프로퍼티 변경과 연관되는 부분 등이 눈에 띄었어요

두 분이 지금까지 보여주신 구현력이라면
앱의 시나리오에서 가위바위보 게임 -> 묵찌빠 게임
상황 전환이 하나의 클래스에서 명령형의 구조로 진행되는게 아니라
분리되는 아이디어도 낼 수 있지 않을까 했어요!

--- 

사실 위처럼 코멘트를 남기는 이유는 두 분이 PR Comment를 통해서
제게 전달되는 배경지식이 적고 코드만 보다보니
표면적인 이야기 밖에 할 수 없고, 단순히 리뷰로 남긴 표면적인 부분만 수정하는 것보다 
두 분이 설계를 깊게 고민해보면 어떨까 하는 마음에 말씀드려봅니다!

우선 리뷰 코멘트 위주로 답변 또는 수정해보시고
제게 구현중 고민한점이나 궁금한점 같은 배경지식을 전달해주시고 
같이 그 내용으로 좀더 깊게 다뤄보거나,

제가 말씀드린 다른 깊은 고민을 한번 더 해보면 좋을것 같습니다!

2023-11-29 15:25 UTC, Marcorable commented on RockPaperScissors/RockPaperScissors/Game.swift
> +            print(Prompt.rockScissorsPaperChoice, terminator: " ")
언급했던 부분 잘 신경써주셨네요! 👍🏼

2023-11-29 15:25 UTC, Marcorable commented on RockPaperScissors/RockPaperScissors/Game.swift
> +
140# `func calculateMookZziBbaResult(with input: Int)` 부분 포함해서 

제가 경험한 컨벤션에서 못보기도 하고 스타일이 달라서 오는 가독성일 수도 있긴한데,
저는 불필요하게 줄바꿈이 많다고 생각하는데 

혹시 어떤 의도가 있는지 설명해주실 수 있을까요?

2023-11-29 15:25 UTC, Marcorable commented on RockPaperScissors/RockPaperScissors/Game.swift
> +                print(self.isPlayingMookZziBba ? Prompt.MookZziBbaChoice(self.currentPlayerTurn) : Prompt.rockScissorsPaperChoice, terminator: " ")
삼항연산자를 사용하셨군요!

사용해주신것처럼 단순한 플래그를 기준으로 두 값을 할당하기에 좋은 방법인것 같아요!

2023-11-29 15:25 UTC, Marcorable commented on RockPaperScissors/RockPaperScissors/Game.swift
> +                print(self.isPlayingMookZziBba ? Prompt.MookZziBbaChoice(self.currentPlayerTurn) : Prompt.rockScissorsPaperChoice, terminator: " ")
이 부분이 `isPlayingMookZziBba` 가 true 인 경우도 동작을 하나요?
로직에 대한 확인이 필요할 것 같아요!

2023-11-29 15:25 UTC, Marcorable commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    private func initMookZziBba() {
`init` 이라는 동사는 키워드가 겹치는 부분이 있으니 유사한 다른 동사를 이용하면 좋을것 같아요!

2023-11-29 15:25 UTC, Marcorable commented on RockPaperScissors/RockPaperScissors/Game.swift
>                  }
위 부분을 통해서 생각난 부분인데,

`userInput` 은 유효한지 검증하고 랜덤 수와 대결 후 결과를 얻고 난 뒤에 필요한 정보인가요?
프로퍼티로 할당하지 않고 구현해보면 어떨까요?

전체적인 설계가 함수의 반환은 사용하지 않는데
새로운 방향을 고려해볼 수 있게 바꿔보면 좋을것 같아요.

추가로 `mutating` 라는 키워드를 아시나요?

2023-11-29 15:25 UTC, Marcorable commented on RockPaperScissors/RockPaperScissors/Prompt.swift
> +    }
먼저, 네이밍은 소문자로 시작하도록 작성해주세요!

추가적으로 네이밍 규칙은 동일하게 지켜져야할 것 같아요.
함수(메서드)의 명칭이라는 점 - 염두해서 동사형 네이밍
또는 반환값을 표현하는 명사형의 명칭을 사용하기도 해요
추가적으로 API Design Guidelines 에 따르면 상황에 따라 form 접두사를 제공하는 부분을 언급합니다.

Prompt.winner -> Prompt.winnerMessage (반환값 표현)
Prompt.allChoices -> Prompt.makeAllChoicesMessage (동사형)

같은 예시를 참고해서 개선해주면 좋을것 같아요

2023-11-29 15:25 UTC, Marcorable commented on RockPaperScissors/RockPaperScissors/Game.swift
> +        let randomInt: Int = Int.random(in: 1...3)
함수를 제거하신 이유가 있나요?
어떤 의도를 가졌는지 궁금합니다!

2023-11-29 15:25 UTC, Marcorable commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    }
유사한 부분이 많은것 같은데

`enum` 을 활용해서 다른 호출로 다른 동작을 기대하는 하나의 메서드로 만들면 어떨까요?

2023-11-29 15:25 UTC, Marcorable commented on RockPaperScissors/RockPaperScissors/Game.swift
> +                completion()
Closure 형태를 파라미터로 전달해서 사용하셨군요!

괜찮은 아이디어라고 생각합니다! 👍🏼

2023-11-29 15:25 UTC, Marcorable commented on RockPaperScissors/RockPaperScissors/Game.swift
> +        while true {
가위바위보 게임과 달리 
반복문의 조건으로는 탈출할 수 없는 구조를 구성하셨네요!

기준이 같으면 어떨까요?
같은 프로퍼티가 아니더라도 같은 설계 방식을 유지하는게 좋을까요?

2023-11-29 15:25 UTC, Marcorable commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    private let MookZziBbaDictionary: [Int: String] = [1: "묵", 2: "찌", 3: "빠"]
우선 대문자로 시작하는 프로퍼티명은 소문자로 바꿔주세요!

가위바위보 일대는 1,2,3 이 묵찌빠와 다른데 
이런데서 오는 문제점은 없을까요?   

이런 raw 데이터는 DB나 JSON을 통해서 받게되는데
앱 내에서 보다 헷갈리지 않고 안전하게 사용하는 방법은 없을까요?

2023-11-30 02:05 UTC, ijs1103 commented
우선은 STEP2에서 STEP1의 구조와는 다르게 두개의 클래스 구조로 혹은 진정한 의미의 객제지향설계를 고려하지 못한점에 대해서는 저희도 상당히 아쉽다고 생각합니다.
하지만, STEP1에서 배운 `SWIFT API GUIDELINE`에 맞는 네이밍 컨벤션을 적용하고 마찬가지로 재귀함수를 호출하는 경우에 위험을 제거하고 실제 코드에 적용하는데 저희도 나름대로 노력을 하였습니다.
저희의 구현력을 높이 평가해주셔서 너무 감사하지만, 아직은 과정 초반이기도 하고 객체지향프로그래밍이 익숙하고 아직 체화되지 않은 부분도 있고 시간적인 제약도 있어서 저희의 진행방향이 고차원적인 설계로 이어지지 못했던것 같습니다. 다음 프로젝트부터는 말씀하신대로 유지보수가 용이하고 스위프트가 지향하는 프로토콜, OOP에 알맞는 설계를 할 수 있도록 최선을 다하겠습니다.

처음 설계했을때 제 머릿속에 든 생각은 아직 OOP에 익숙치 않다보니, 우선 게임이 진행되는 절차, 즉 시간의 흐름대로 쭈욱 구현해보자는 것이었습니다.
그래서 `while`문안에 모든 비즈니스 로직이 들어가게 되었고, 사용자가 다시 입력을 해야하는 상황이 되었을때 처음에는 재귀로 처리를 하려고 했으나, 재귀 사용을 피하기 위해 `while`문을 쓰다보니 결과적으로는 이중 반복문이 될 수 밖에 없었던것 같습니다. 
구현에 급급했던터라 지나고 나니 이중반복문은 확실히 유지보수에 적합하지 않다고 느꼈고 다음부터는 최대한 지양하는 방향으로 설계를 하겠습니다 !!  

그리고 제가 개인적으로 궁금한 부분은 크게 두가지인데요.

언급하셨던 부분중에 “모든 함수가 프로퍼티 변경과 연관되었을때” 혹시 안좋은점이 뭔지 여쭤보고 싶습니다.

그리고 제가 프로젝트를 새로 설계한다면 가위바위보와 묵찌빠 `class` 두개가 존재하고 전체적으로 게임을 관장하고 실행시키는 컨트롤러 `class`로 나누려고 하는데요. 
이에 대한 marco의 의견 혹은 marco라면 어떻게 설계를 하실지가 궁금해지네요.

2023-11-30 02:24 UTC, ijs1103 commented on RockPaperScissors/RockPaperScissors/Game.swift
> +                print(self.isPlayingMookZziBba ? Prompt.MookZziBbaChoice(self.currentPlayerTurn) : Prompt.rockScissorsPaperChoice, terminator: " ")
코드의 흐름상 묵찌빠 -> 가위바위보로 전환되는 상황은 존재하지 않아서 위 코드대로 작성을 하였는데 지금 생각해보니 말씀하신대로 일말의 가능성이라도 존재해서는 안되는게 맞는것 같습니다. 수정하겠습니다.

2023-11-30 04:39 UTC, ijs1103 commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    private func initMookZziBba() {
좀더 명시적으로 묵찌빠의 초기설정을 하다는 의미로 `makeInitialSettingForMookZziBba`로 변경하겠습니다.

2023-11-30 06:34 UTC, ijs1103 commented on RockPaperScissors/RockPaperScissors/Game.swift
> +
저희 프로퍼티는 한칸씩 띄우기로  코딩 컨벤션으로 정해놓고 간 부분인데, 불필요하게 많다고 미처 생각을 하지는 못하였습니다.
다음 프로젝트에서는 실질적으로 좀 더 고민해보고 컨벤션 원칙을 정하겠습니다 !!

2023-11-30 07:01 UTC, ijs1103 commented on RockPaperScissors/RockPaperScissors/Game.swift
>                  }
반환 값을 사용하여 프로퍼티를 최소화하도록 구현해보겠습니다. 

`userInput`은 랜덤수와 대결 전에 필요한 정보입니다. 

`struct/enum`은 기본적으로 메서드내에서 프로퍼티를 변경할 수 없는데, `mutating` 키워드를 메서드 앞에 붙이면 프로퍼티를 변경할 수 있게 됩니다.

2023-11-30 07:11 UTC, ijs1103 commented on RockPaperScissors/RockPaperScissors/Game.swift
> +        let randomInt: Int = Int.random(in: 1...3)
함수이름에 1~3사이의 수를 얻는다는 정보가 들어가있지 않으면 모호해진다는 생각이 들기도 하였고, `randomInt()` 함수자체가 한줄밖에 안되는 코드이기에 재사용성을 해치지 않는다고 생각이 들어서 제거하게 되었습니다.

2023-11-30 07:12 UTC, ijs1103 commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    }
맞습니다~ 충분히 하나의 메서드로 만들 수 있었는데 미처 생각하지 못하였네요. 수정하겠습니다 !!

2023-11-30 07:30 UTC, andyanappdev commented on RockPaperScissors/RockPaperScissors/Game.swift
>                  }
구조체의 경우 프로퍼티에 접근해서 그 값을 새롭게 할당하는 행위를 하는 메서드 앞에 붙이는 키워드로 알고 있습니다.
구조체는 Data model로 사용되는데 immutable 객체인데 그 속성의 값을 변경하려고 하기 때문에 값을 변경한다는것을 개발자가 인지 및 의도해서 하는것을 다시한번더 체크 하기 위해서 붙이지 않으면 컴파일러가 컴파일 에러를 발생시킵니다.

2023-11-30 07:32 UTC, andyanappdev commented on RockPaperScissors/RockPaperScissors/Prompt.swift
> +    }
넵 수정해서 commit 하도록 하겠습니다.

2023-11-30 07:49 UTC, ijs1103 commented on RockPaperScissors/RockPaperScissors/Game.swift
> +        while true {
가위바위보처럼 `loopState`와 같은 조건을 사용하지 않은 이유는 맨밑의 코드와 같이 기존에 재귀함수를 사용하던것을
재귀호출을 피하기 위해서 `while true {}`로 변경하다보니 일관된 기준을 설정하지 못하게 되었네요 ..ㅠ

가위바위보에서 `while`문의 조건을 준 이유는 `while`문 내의 nested된 스코프에서 탈출하기 위함이었습니다.
그래서 `playMookZziBba()`는 다른 이유로 `while`문을 사용하였으니, 같은 기준을 줄 필요는 없다고 판단하였습니다.

만약 기준이 같다면 기존의 `loopState`변수이름은 `outerLoopState`로 변경, `playMookZziBba()`에서의 `while`문의 조건문 변수이름은 `mookZziBBaLoopState`와 같이 최대한 일관되게 이름을 지을것 같습니다.

`같은 프로퍼티가 아니더라도 같은 설계 방식을 유지하는게 좋을까요?`에 대해서는 가독성과 일관성을 지키기 위한 방향으로 가는게 맞다고 대답드릴 수 있을것  같습니다.

```
private func playMookZziBba() {
            print(Prompt.MookZziBbaChoice(currentPlayerTurn), terminator: " ")
            
            receiveUserInput() {
                if self.currentPlayerTurn == .human {
                    self.changePlayerTurn()
                }
                print(Prompt.badInput)
                print(self.isPlayingMookZziBba ? Prompt.MookZziBbaChoice(self.currentPlayerTurn) : Prompt.rockScissorsPaperChoice, terminator: " ")
            }
            
            switch userInput {
            case 1, 2, 3:
                calculateMookZziBbaResult(with: userInput)
                return
            case 0:
                shutDown()
                return
            default:
                print(Prompt.badInput)
                if currentPlayerTurn == .human {
                    changePlayerTurn()
                }
                playMookZziBba()
            }
    }
```

2023-11-30 08:07 UTC, ijs1103 commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    private let MookZziBbaDictionary: [Int: String] = [1: "묵", 2: "찌", 3: "빠"]
넵 소문자로 수정하겠습니다.

사실 `MookZziBbaDictionary`를 통해 Int를 묵찌빠에 매칭시켜서 화면에 출력하는 기능은 

요구사항과는 번외로 묵찌빠를 했을때 컴퓨터와 유저가 무엇을 냈는지 알 수 있으면 좋겠다고 생각을 해서 넣은 일종의 보너스 기능이라서

가위바위보와 묵찌빠의 차이에 대해서는 생각해보지 않은것 같습니다 ;;ㅎ

데이터를 앱내에서 좀더 안전하게 사용하는 방법으로는 데이터를 Modeling 하여 정의해서 사용해야 합니다.

Model이 되는 데이터의 이름도 헷갈리지 않게 명시적으로 지어서 `Struct MookZziBbaResponseModel: Codable {}`과 같이 작성할 수 있을것 같습니다.

2023-12-01 03:28 UTC, keeplo commented on RockPaperScissors/RockPaperScissors/Game.swift
>                  }
키워드를 두 분 모두 알고 계시군요! 역시 Swfit 를 잘파악하고 계십니다 👍

`class` 와 달리 `struct` 에서 `mutating` 키워드를 강조하는 이유는 뭘까요?
두 타입의 특징과 관계가 있을것 같은데 어떤 특징 때문일지 고민해보면 좋을것 같아요!

2023-12-01 03:37 UTC, keeplo commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    private let MookZziBbaDictionary: [Int: String] = [1: "묵", 2: "찌", 3: "빠"]
enum case 로 가위(찌) 바위(묵) 보(빠) 를 동일하게 구성해보는 아이디어는 어떠세요?

2023-12-01 04:44 UTC, ijs1103 commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    private let MookZziBbaDictionary: [Int: String] = [1: "묵", 2: "찌", 3: "빠"]
동일한 방식으로 관리되는게 맞는것 같습니다. 
CLI 형태로 구현하다보니 고려하지 못했네요.
앱에서 애니메이션이 나오도록 구현한다면 숫자를 매칭시키는것 보다 
손모양과 숫자를 1대1 매칭 시키는게 맞다고 생각합니다. 
아래와 같이 작성할 수 있을것 같습니다. 

```
enum  HandFigure: UIImage {
  case mook = UIImage(named: "묵")
  case jji = UIImage(named: "찌")
  case bba = UIImage(named: "빠")
}
```

2023-12-01 04:50 UTC, andyanappdev commented on RockPaperScissors/RockPaperScissors/Game.swift
>                  }
다른 언어에서는 불변 객체를 사용하기 위해 sealed class로 만들어 불변객채로 사용합니다.
Swift는 불변의 Custom Data model에 사용할수 있도록 struct를 제공해 주고 있습니다.
class & struct의 공통점은 커스텀 모델 타입으로 인스턴스화 할수 있다는 점이 가장 큰것 같습니다.
두 타입의 차이점으로는
**class** 
Reference Type
인스턴스 데이터는 Heap에 저장, 해당 Heap을 가르키는 변수는 stack에 저장
메모리 주소값이 Hepa을 가르킴
복사시 저장된 주소를 복사(전달)
ARC 시스템을 통해 해제가 관리 되고 있기 때문에 메모리 관리에 주의 필요
**struct**
Value Type
인스턴스 데이터를 모두 Stack에 저장
복사시 복사본을 생성해서 전달 (다른 메모리공간 생성)
Stack의 공간에 저장됨에 따라 Stack프레임 종료시, 메모리에서 자동 해제

저의 생각에는 struct는 태생적으로 immutable한 Custom Data Model을 위함이라고 생각 합니다.
즉 해당 인스턴스에 값을 막 변경하지 않으려고 struct를 사용 한것인데
개발자가 그 값을 변경하려는 시도를 하기 때문에 일종의 한번더 질문을 던지는 (너 이거 값 바꾸는 행위야 그런데도 할거야?) 의도를 다시 한번더 확인하는 안전장치 같은 역할을 한다고 저는 생각 합니다.

2023-12-01 05:10 UTC, keeplo commented on RockPaperScissors/RockPaperScissors/Game.swift
>                  }
답변해주신 것처럼 제 생각에도 Swift 언어에서 `struct` 불변개체로써 사용되기를 기대한 것 같습니다. 

그런면에서 `inout` 키워드와 동작에 대해서 알고 계신가요?  
[In-Out Parameters](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/declarations/#In-Out-Parameters)
이 부분의 동작 원리를 공부해보시면 좋을 것 같습니다.

저는 이 부분처럼 값 타입의 내부 프로퍼티 변경은 값 복사를 기반으로 수정되는 동작이기 때문에
`mutating` 은 암시적인 오류가 아니라 강제하고 있다고 판단했습니다.

2023-12-01 05:25 UTC, keeplo commented on RockPaperScissors/RockPaperScissors/Game.swift
> +    private let MookZziBbaDictionary: [Int: String] = [1: "묵", 2: "찌", 3: "빠"]
음... 저는 지금처럼 작은 규모에 프로젝트에서도 명확한 기준이 정해지면 좋을거라고 생각했습니다.
제가 그런 판단하게 되는 부분이 `HandFigure` 에 있다고 생각됩니다.

UIImage는 이미지라서 다른 인스턴스에 비해 큰 용량을 차지하는데
enum 의 rawValue 로 들고 있을 필요가 있을까요?

이 전에 출력될 문자열을 raw 값으로 가지기보다 
분리하는걸 추천드린 것처럼 아래 코드처럼 작성하면 좋을것 같아요.
`enum` 은 `case` 라는 이름처럼 분류의 목적만 가지면 좋을것 같습니다.

데이터의 캡슐링의 의도로 enum과 rawValue 묶이게 된다면, 
C언어부터 전통적인 구조체 개념의 `struct` 타입으로 처리하는 쪽이 좋을 것같아요!

```swift
// userInputNumber 가위 (1) 찌 (2) 입력
// 가위 입력 let hand = Hand(rawValue: userInputNumber)
// 찌 입력 let hand = Hand(rawValue: userInputNumber - 1)

enum Hand: Int {
   case rock = 1
   case paper = 2
   case scissors = 3

   var imageName: String {
      switch self {
         case .rock:      return "묵"
         case .paper:     return "찌"
         case .scissors:  return "빠"
   }
}
```
---

이번 프로젝트를 계기로 코드 레벨에 논리 수준을 넘어서 
인스턴스의 종류와 크기, 함수의 동작 등에서 메모리 수준 이후엔 쓰레드 수준까지
CS 이해를 조금씩 찾아가면서 설계 또는 구현을 하는걸 조언드리고 싶습니다!

2023-12-01 05:25 UTC, merged

2023-12-01 05:32 UTC, keeplo commented
첫 프로젝트 임에도 프로젝트 기한이나 설계나 구현 모두 잘 해내셨다고 생각합니다!
프로젝트 진행하시느라 고생하셨습니다!

다음 프로젝트가 지금 프로젝트보다 로직이 복잡해질 수 있지만,
이번 프로젝트에서 언급되었던 모든 부분은 default로 유지되고 반복됩니다.

조금 놓쳤더라도 다시 인지하면 되고 만약 미루게된다면 틈틈히 TODO로 쌓인 것부터 공부해나가는걸 추천드려요!
다음 프로젝트에서 이번 프로젝트 내용을 미뤄두고 진행하면 6개월 뒤에나 돌아볼 수 있게 되더라구요..

제가 이번 프로젝트에서 강조하고 싶었던 부분은 이 [Commit](https://github.com/tasty-code/ios-rock-scissor-paper/pull/58#discussion_r1411625210) 으로 함축된다고 생각합니다.
나만의 기준 또는 팀의 기준, 대새의 기준을 명확히 알고 따라가는 것도 중요하고,
코드의 논리만 가지고 구현하기보다 내면에 동작원리나 CS 구조를 연결지으면서 구현하는것도 중요하다고 생각합니다!

처음부터 잘하는 사람은 절대 없고 조금씩 조금씩 의식하기만 해도 엄청난 성장을 하실 수 있다고 확신합니다!

고생많으셨고 즐거운 주말 보내시며 조금 충전하시길 바라요! 🙌 🙌