묵찌빠 [STEP2] llama, Harry
tasty-code/ios-rock-scissor-paper pull request #60
Opened 2023-11-29 08:43 UTC by hemil0102

안녕하세요 두두! 묵찌빠 Step2 PR을 드립니다. 
기능 구현은 완료하였고, 리팩토링도 수행하였는데 작업할 것이 더 있어 보입니다.
그러나 PR 제출 마감기한이 내일 오후 5시까지여서 검토를 받으면서 방향을 잡아 가는게 좋다고 생각하였습니다.
코멘트를 주시면 가이드를 참고하여서 추가 작업하겠습니다. 
감사합니다.

1. PlayerTurn(b8daa3d696619265570235a83725afaa2340c754)
PlayerTurn 열거형을 활용하여서 묵찌빠 수행 단계에서 플레이어의 턴을 관리합니다. 
none은 플레이어의 턴이 지정되지 않은 가위바위보 게임 구분을 위해 활용했습니다. 

```swift
enum PlayerTurn: CustomStringConvertible {
    case user, computer, none
    
    var description: String {
        switch self {
        case .user:
            return "사용자"
        case .computer:
            return "컴퓨터"
        case .none:
            return "none"
        }
    }
}
```

2. 가위바위보(RPS)와 묵찌빠(MJP) 중복 로직의 재활용 (7251ac22339a2a7cfd2717411cc0b1cbeee80703), (f2f7c79c87722f9b4731c16db65313ae641e89ff)
    처음에는 RPS와 MJP를 별도로 놓고 코드를 생각의 흐름에 따라 방대하게 작성하였습니다.
    그 이후 기능 구현이 완료되었을 때 리팩토링을 수행하다보니, 가위바위보와 묵찌빠의 공통 로직이 보여 중복을 제거하여 하나의 로직으로 합쳐줬습니다. 
    
    사용자와 컴퓨터가 묵(바위), 찌(가위), 빠(보)고르는 행위 자체는  두 게임에서 동일하며, 
    `processInvalidOrExitBy` 내부에서 가위바위보와 묵찌빠 여부에 따라 분기를 두어 책임을 달리 가져갔습니다. 
    
    ```swift
    let userOption = user.chooseOption()
    let computerOption = computer.chooseOption()
            
    guard let userChoice = Option.getRockPaperScissors(from: userOption),
          let computerChoice = Option.getRockPaperScissors(from: computerOption) else {
              processInvalidOrExitBy(userOption, computerOption)
           return
    }
            
    let outcome = referee.determineRPSOutcome(between: userChoice, and: computerChoice)
    ```
    
2. 가독성을 위한 isRSP와 is MJP (ae4f8e838cb4962821cb25890bb66941c6e8db11)
    ```swift
    private func isRPS() -> Bool {
         return playerTurn == .none
    }
        
    private func isMJP() -> Bool {
         return playerTurn != .none
    }
    ```
   
3. GameManager 구조체의 `getRockPaperScissors` 메서드를 Option 열거형으로 옮겼습니다. (1a55f03ce8aa85b8b0805b8414b9a3fc69d0e631)

```swift
enum Option: Equatable {
    case valid(RockPaperScissors)
    case exit
    case invalid
    
    static func getRockPaperScissors(from option: Option) -> RockPaperScissors? {
        switch option {
        case .valid(let choice):
            return choice
        case .exit, .invalid:
            return nil
        }
    }
}
```

질문1) 아래 부분이 묵찌빠에서 승자를 판단하는 부분인데, else와 endGameIfWinnerDetermined의 조합으로 판단이 됩니다. 이 경우 승자 판단이라는 인지나 가독성 적인 측면이 좋지 않다고 생각되는데, 어떻게 수정해보면 좋을까요?
```swift
        guard let determinedTurn = determinePlayerTurn(from: rpsOutcome) else {
            endGameIfWinnerDetermined()
            return
        }
```

2023-11-30 00:51 UTC, FirstDo requested changes
두분 고생하셨습니다!
PR 본문에, 상세한 설명과 커밋 링크를 남겨둬서 보기가 편했습니다

코맨트 간단히 남겼으니 확인한 후 말씀해주세요~

추가로 conflict이 났는데 (아마 저번 그 이슈?)
한번 해결해 보시겠어요??

간단히 설명하면
현재 destination <- llama/Harry PR을 보낸 상황인데,
1. llama/Harry Branch에 Destination Branch를 Pull
2. Conflict을 해결
3. llama/Harry를 다시 Push

과정을 거치시면 될것 같네요!

2023-11-30 00:51 UTC, FirstDo commented on RockPaperScissors/RockPaperScissors/Enum/PlayerTurn.swift
> +}
가위바위보와 달리 묵찌빠 게임은 턴이 존재하죠!
PlayerTurn이라는 enum을 만드신건 좋아보입니다.

두분 혹시 옵셔널이 어떤식으로 구현되어 있는지 아시나요?

```swift
enum Optional<Wrapped> {
  case none // nil
  case some(Wrapped) // optional value
}
```

Swift 옵셔널은 열거형으로 구현되어 있습니다. 그리고 값이 없을때는 `none` 이에요.
따라서 아래와 같은 구현도 가능합니다!
수정사항이아닌, 그냥 그런것도 있다 라고만 알고계시면 좋을것 같네요 :)

```swift
enum PlayerTurn {
   case user, computer
}

var turn: PlayerTurn?

switch turn {
case .user:
case .computer:
case .none:
}
```

2023-11-30 00:51 UTC, FirstDo commented on RockPaperScissors/RockPaperScissors/Handler/PrintingHandler.swift
> +enum PrintingHandler {
출력을 한곳에서 담당하니 깔끔한것 같네요 :)

2023-11-30 00:51 UTC, FirstDo commented on RockPaperScissors/RockPaperScissors/Role/GameManager.swift
> +    }
저는 단순히 ~인지 여부를 판단하는
isXX?, shouldXX? 등의 프로퍼티는 
가능하다면 매서드보다는 연산프로퍼티로 만드는 편입니다.

두분이 매서드와 연산프로퍼티를 사용하는 나름의 기준을 세워보시는게 좋을것같네요!
수정사항은 아닙니다

```swift
func isRPS() -> Bool

->

var isRPS: Bool
```

2023-11-30 00:51 UTC, FirstDo commented on RockPaperScissors/RockPaperScissors/Role/Referee.swift
> +                              and computerChoice: RockPaperScissors) -> RPSOutcome {
Referee 객체가 하는일이 좀 애매한것 같습니다.
가위바위보 결과만 결정하는게아니라
묵찌빠 결과, 묵찌빠 턴을 결정해주는것도 모두 심판이 해야하는일이 아닌가? 라는 생각이 드네요.

어디까지가 GameManager의 역할이고, Referee의 역할인지 명확한 구분이 필요해 보입니다

수정사항은 아닙니다! 구현은 자유니까요

2023-11-30 00:51 UTC, FirstDo commented on RockPaperScissors/RockPaperScissors/Role/GameManager.swift
> +            endGameIfWinnerDetermined()
어떤점때문에 어색하다고 생각했는지를 잘 모르겠어요..!

문제 없다고 생각하고 가독성이라면 차라리 밑에 코드가 더 문제되지 않나 생가합니다
(수정하라는건 아닙니다..!)

```swift
    private mutating func processInvalidOrExitBy(_ userOption: Option, _ computerOption: Option) {
        guard shouldEndGameEarlyBy(userOption, computerOption) else {
            PrintingHandler.notifyInvalidOption()
            if playerTurn == .user {
                playerTurn = .computer
            }
            return
        }

        PrintingHandler.notifyGameOver()
        endGame()
    }
```

2023-11-30 07:37 UTC, llamang commented on RockPaperScissors/RockPaperScissors/Enum/PlayerTurn.swift
> +}
네 해당 정보 감사합니다! 
이번에는 시간 관계상 사용하지 않았지만, 다음에 활용해 보겠습니다.

2023-11-30 07:39 UTC, llamang commented on RockPaperScissors/RockPaperScissors/Role/GameManager.swift
> +    }
알려주신 연산 프로퍼티를 활용했습니다. 
매개변수가 필요한 것은 메서드로 구현했습니다.
591c0be3aec5e0fe2326ead699485640ea29c1d1

2023-11-30 07:41 UTC, llamang commented on RockPaperScissors/RockPaperScissors/Role/Referee.swift
> +                              and computerChoice: RockPaperScissors) -> RPSOutcome {
determineNextPlayerTurn() 메서드를 GameManager에서 Referee로 옮겼습니다. 
해당 책임은 심판의 역할인데, 저희가 놓쳤던 것 같아요, 감사합니다~
3b93cbd77c2445cc186d20c6f2a6628891caa12d

2023-11-30 07:44 UTC, llamang commented on RockPaperScissors/RockPaperScissors/Role/GameManager.swift
> +            endGameIfWinnerDetermined()
해당 부분은 guard 문 대신에 if 문으로 변경하니, 저희가 봤을 때 가독성이 나아졌습니다. 
더 좋은 표현/방법이 있다면 알려주시면 감사합니다. 🙏🏼
cda02f8dd2210c4496096e3775b5df6f7064ab59

2023-11-30 10:00 UTC, llamang commented on RockPaperScissors/RockPaperScissors/Role/GameManager.swift
> +        determineMJPOutcome(basedOn: nextPlayerTurn)
메서드 이름이 `determineSOMETHING()`으로 되어 있는 것 중에 반환값이 있는 것과 없는 것이 있습니다. 
이 부분을 다른 동사를 사용했으면 혼동이 없었을 것 같은데, 최종 코드의 commit 후에 봐서 별도의 comment로 남깁니다.

```swift
func determineRPSOutcome(between userChoice: RockPaperScissors,
                         and computerChoice: RockPaperScissors) -> RPSOutcome
```

```swift
func determineNextPlayerTurn(basedOn rpsOutcome: RPSOutcome) -> PlayerTurn
```

```swift
private mutating func determineMJPOutcome(basedOn nextPlayerTurn: PlayerTurn)
```

2023-11-30 10:13 UTC, llamang commented on RockPaperScissors/RockPaperScissors/Role/GameManager.swift
> +        currentPlayerTurn = nextPlayerTurn
현재 `currentPlayerTurn = nextPlayerTurn`은 `processGameOutcome` 메서드 내부의 마지막에 있습니다.

```swift
private mutating func processGameOutcome(between userOption: Option, and computerOption: Option)

```

이 `currentPlayerTurn = nextPlayerTurn`를 `determineMJPOutcome` 메서드 내부의 마지막에 넣어야 할지 고민했습니다.

```swift
private mutating func determineMJPOutcome(basedOn nextPlayerTurn: PlayerTurn)

```

하지만 요구 사항의 동작은 동일하고 의미상으로도 큰 차이를 느끼지 못했습니다.
고민했던 부분이라 comment를 남깁니다.

2023-11-30 10:34 UTC, llamang commented on RockPaperScissors/RockPaperScissors/Role/GameManager.swift
> +        if isMJP && nextPlayerTurn != .none {
`nextPlayerTurn != .none`은 다음의 `isNextPlayerTurn` 연산 프로퍼티를 활용하지 않았습니다. 

```swift
    private var isNextPlayerTurn: Bool {
        nextPlayerTurn != .none
    }
```

가독성에 큰 차이가 없다고 느꼈습니다. 
하지만 통일성면에서는 아쉬운 부분이에요.

2023-12-01 03:59 UTC, hemil0102 commented on RockPaperScissors/RockPaperScissors/Role/Referee.swift
> +        } else if (userChoice.value + 1) % RockPaperScissors.count == computerChoice.value % RockPaperScissors.count {
가위바위보 승부 판단 오류 부분입니다. 사용자가 묵을 냈을 때 값(userChoice.value)이 2로 로직에서 +1 되어 3이 되고 %를 통해서 값이 0이 되는데, computer가 보자기를 냈을 경우 값이(computerChoice.value) 3으로 결과적으로 0 == 3은 false가 되어 원래 원했던 0 == 0 으로 true를 반환하지 않아 승패를 잘못 판단하고 있었습니다. 원하는 결과를 위해 컴퓨터도 %3 (RockPaperScissors.count) 으로 나누어 주어 의도한 로직으로 구현했습니다.

2023-12-01 04:11 UTC, FirstDo approved these changes
안녕하세요! 2주동안 정말 고생많으셨습니다.
저도 두분의 잘 짜여진 코드를 보면서 많이 배웠습니다 :)

### 질문에 대한 답변입니다

1. 위의 5번 상황에서, isDraw(nextPlayerTurn)도 연산프로퍼티로 만들어 줄 방법이 있을까요?

현재 구조에선 없어보입니다.
currentPlayerTurn, nextPlayerTurn을 구분해야 하는 이유가 있나요?
코드를 작성하는 과정에서 분명 
턴을 구분하는 변수가 두개나 필요하게 된 이유가 있을텐데, 궁금합니다

3. 위에 반영된 currentPlayerTurn과 nextPlayerTurn을 willset으로 구현해보는 것도 괜찮을 것 같은데, 아직 익숙치 않아서 반영하지 않았습니다. 프로퍼티 옵저버를 사용하는 것에 대해 어떻게 생각하시나요?

저는 프로퍼티 옵져버 정말 좋아합니다!
코드만 잘 작성해 놓으면 프로그래머가 신경쓸 게 더 줄어듭니다..!
리액티브하게 프로그램을 작성하기도 쉽고요

2023-12-01 04:11 UTC, FirstDo commented on RockPaperScissors/RockPaperScissors/Role/GameManager.swift
> +        : PrintingHandler.showMJPOptions(for: referee.currentTurn)
3항 연산자를 활용해 주신부분이 좋습니다!
자칫 가독성이 안좋을 수 있는데, 이런식으로 내려쓰는걸 저도 선호하는 편입니다 :)

2023-12-01 04:11 UTC, FirstDo commented on RockPaperScissors/RockPaperScissors/Role/Referee.swift
> +            : (computerChoice == .rock ? .scissors : .paper)
위에서 3항연산자의 가독성을 이야기했는데,
특히 이런식으로 중첩해서 사용할 경우 가독성이 떨어질 수 있습니다.

지금은 로직이 깔끔하고 개행을 잘 해주셔서 문제 없어보여요!

또 개인적으로는 이런경우는 guard문을 선호합니다
```swift
if isMJP {
    // logic
}

guard isMJP else { return }
// logic
```

가장 큰 차이는 코드 뎁스가 들어가냐 안들어가냐의 차이가 있겠네요!
{}가 중첩될 수록 코드 파악이 어려워지니 뎁스는 최대한 얕게 유지하는게 좋습니다
(물론 이경우는 큰 상관이없고 수정사항이 아닙니다)

2023-12-01 08:22 UTC, llamang commented on RockPaperScissors/RockPaperScissors/Role/Referee.swift
> +            : (computerChoice == .rock ? .scissors : .paper)
알려주신 대로 guard 문을 활용했습니다. 
감사합니다~
600e4797d22d4fbd9311f5bb54005266d6a20314

2023-12-01 08:53 UTC, llamang commented on RockPaperScissors/RockPaperScissors/Role/Referee.swift
> -    private func mapIfMJP(_ userChoice: inout RockPaperScissors, _ computerChoice: inout RockPaperScissors) {
이 메서드는 Option 타입으로 옮겼습니다(`mapToMJP`). 
df15ab8d8b36d103746c618ddd0d04b269a17f9f

2023-12-02 14:09 UTC, merged