묵찌빠 [STEP2] Loffy, Hoi
tasty-code/ios-rock-scissor-paper pull request #61
Opened 2023-11-30 06:40 UTC by happykwon

2023-11-30 06:43 UTC, kimdj1102 commented
## 시작전에...

담당 리뷰어 : @junbangg (알라딘)
팀원: @kimdj1102 (loffy), @happykwon (hoi)

### 인사말
- loffy : 안녕하세요 알라딘! 인생 첫 PR이라 정말 떨리네요🤣 부족하지만 잘 부탁드립니다. 피드백으로 최대한 많은 정보를 얻어가서 성장하고 싶습니다!
- hoi: 안녕하세요 Hoi입니다. 잘부탁드립니다. 감사합니다.

## 코드에 관하여 

### 순서도 
<img width="400" alt="codeFlow" src="https://github.com/tasty-code/ios-rock-scissor-paper/assets/12614929/b4e93250-de4b-42c8-b02b-4cd68e7b30bf">

---
### 코드 구성 요소

> ### enum 
#### 1. ChoiceMenu
- 사용자가 입력하는 값을 분류하는 열거형 타입
- Int변환 하는 과정을 생략하기 위해 String타입으로 선언
- 가위, 바위, 보, 종료는 rawValue값 설정
- 그 외의 값은 other케이스에 해당

#### 2. Result
- 결과를 출력하는 값을 분류하는 열거형 타입
- 이김, 짐, 비김 각각의 case에 rawValue값 설정
 
> ### method
#### 1. startMessage()
- 일은 코드에게 시켜라"라는 야곰의 말을 듣고 최대한 method를 사용해서 동작하게 하고 싶어서 추가

#### 2. action()
- 유저와 컴퓨터 입력값에 대한 처리를 위한 method

#### 3. startGame()
- 이번 프로젝트의 가위바위보 각각에 대한 분기처리를 위한 method

#### 4. endGame() 
- 중복되는 부분이 많아서 함수로 따로 선언
- 게임종료 안내 출력 후 'isWorking'값 반전 (while문 종료를 위함)

> ### etc
#### 1. isWorking
- while문 실행여부를 결정하는 Bool값 변수
- 기본값은 true로 할당

#### 2. rps
- 컴퓨터가 선택할 수 있는 선택지를 담은 String타입 배열
- randomElement()를 사용해 선택지 중 한개를 랜덤으로 추출 (기본값 : "") 

#### 3. while문
- isWorking이 참일때 계속 실행
- if let을 사용해 사용자 입력값(readLine()) Optional Wrapping
- 그 후 action함수 호출
    - ChoiceMenu Enum타입의 rawValue값을 매개변수로 받음
    - comChoice의 기본값 : .scissor(가위) (임의로 설정)
    - userChoice의 기본값 : .ohter (0~3이외의 값을 입력받을 시 처리해주기 위함)
    
---
### 고민했던 점
#### loffi
1. 최대한 순서도에 작성한대로 로직을 짜려고 고민해보았습니다. 그 결과 한 함수당 한 개의 기능씩 최소 단위로 구현을 하려고 해보았습니다.

2. print출력값들을 enum타입으로 선언해서 사용해 보았습니다.
    - 이겼습니다! 문구 출력 시 `print("이겼습니다!")` 에서`print("Result.win.rawValue")`로 변경 
3. action 함수에서 사용자의 입력값을 받을 때 나올 수 있는 모든 경우의 수 (3가지)를 다 처리해보려고 시도했습니다. 
    - 그 결과 ChoiceMenu enum에 other를 선언
    - action함수로 모든 경우의 수 처리가능하게 됨

4. 가위바위보를 enum으로 설정해 보다 직관적으로 게임 결과를 연산하도록 함
   `comPick == 1 && userPick == 2`에서 `comPick == .scissor && userPick == .rock`로 변경

#### hoi
1. 더 줄일 방법을 고민해봤지만 떠오르는 방법이 없어서 포기했습니다.
```Swift =
 else if (comPick == .scissor && userPick == .rock) ||
                (comPick == .rock && userPick == .paper) ||
                (comPick == .paper && userPick == .scissor)
```

2. enum / struct중 써야할지 고민을 했고, 명확한 기준이 있고 구분이 가능하기 때문에 enum타입을 채택하였습니다. 
```Swift=
enum ChoiceMenu: String {
    case scissor = "1" , rock = "2", paper = "3", exit = "0"
    case other
```

```Swift=
enum Result: String {
    case win = "이겼습니다!"
    case lose = "졌습니다!"
    case draw = "비겼습니다!"
}
```

3. 최대한 단일 책임 원칙(SRP)를 해보려고 노력하였습니다.

---
### 조언을 얻고 싶은 부분
#### loffi
```
enum Result: String {
    case start = "가위(1), 바위(2), 보(3)! <종료: 0> : "
    case win = "이겼습니다!"
    case lose = "졌습니다!"
    case draw = "비겼습니다!"
    case exit = "게임 종료"
    case error = "잘못된 입력입니다. 다시 시도해주세요."
}

func printMessage(a: Result) {
    switch a {
    case .start:
        print(Result.start.rawValue, terminator: "")
    case .win:
        print(Result.win.rawValue)
    case .lose:
        print(Result.lose.rawValue)
    case .draw:
        print(Result.draw.rawValue)
    case .exit:
        print(Result.exit.rawValue)
    case .error:
        print(Result.error.rawValue)
    }
}
```
-  message를 출력하는 함수를 따로 만들어서 모든 메세지를 출력하게 끔하는 코드를 짜보았습니다.
    - enum타입으로 모든 경우의 수를 선언하고
    - 메세지 출력함수로 enum타입을 매개변수로 받아 rawValue를 출력
    - 코드가 조금 많이 길어질 것 같아서 반영하지는 않았는데, `효율적인 코드인지 궁금합니다!`
    
- while문을 사용해서 계속 실행이 되도록 했는데, 혹시 다른 방법이 있을지 궁금합니다. 재귀함수를 사용하는 방법은 알긴하는데, 이 while문을 재귀함수로 변경하려고 하니 잘 되지 않았습니다 😭 혹시 while문과 재귀함수 중 '어떤 방법이 더 효율적이다' 이런 경우가 있을까요? 제가 알기로는 이정도로 알고있습니다.
    - 재귀함수를 사용하면 코드의 가독성 향상
    - 반복문보다 더 단순함
    - 하지만 재귀의 깊이가 깊어지면 속도가 느려지고 과정이 복잡해짐

#### hoi
```Swift=
while isWorking {
    
    startMessage()
    
    func getUserChoice() -> ChoiceMenu? {
        
        guard let userChoice = readLine(), ["0","1", "2", "3"].contains(userChoice) else {
            return .other
        }
        return ChoiceMenu(rawValue:userChoice )
    }
    
    guard let userChoice = getUserChoice() else { continue }
    
    let comChoice = ChoiceMenu(rawValue: ["1", "2", "3"].randomElement() ?? "") ?? .other
    
    action(com: comChoice, user: userChoice)
    
}
```
- 위코드는 while isWorking절을 if let 에서 guard let으로 변경한 코드입니다.
if let 보다는 guard let을 의식적으로 사용하는게 좋다고 들었는데 이거에 어떤 코드가 더 좋은 코드인지 그리고 그 이유는 무엇인지 궁금합니다.

2023-11-30 16:09 UTC, junbangg requested changes
수고하셨습니다! 
객체를 사용하기 위해 고민하신 부분들이 느껴지네요!
가독성도 이전 PR보다 향성된 느낌이 확 들었습니다~

고민하셨던 부분들에 대해서 코멘트 남기겠습니다~

> 1. 파일을 어떻게 나눌지 🤔

파일 나누는 기준은 정말 정하기 나름인데요..! 
지금 나누신 기준이 어떤건지 궁금하네요! 
타입별로 파일을 나눈 것으로 보이는데 맞을까요???

> 2. while반복문 두번이 들어가도 괜찮을까요?

말씀하신대로 이중 반복문은 **복잡성** 이 증가되고 **성능 문제** 가 있는것이 맞습니다~ 
하지만! 왜 성능 문제가 발생할까요?
지금 적어주신 이유가 
`루프의 반복 횟수가 늘어날수록 성능에 영향을 미칠 수 있음` 인데
루프의 반복 횟수가 늘어날수록 왜 성능이 나빠질까요??
단순히 나쁘다, 성능이 좀 안좋아진다 라는 것은 개발자마다 기준이 다르면 안되겠지요!
저희는 이렇게 특정 알고리즘이나 코드의 성능에 대한 이야기를 나눌때 시간/복잡도에 대한 이야기를 나누는데
반복문 하나랑 중첩 반복문이 왜 성능적 차이가 있는지 이론적으로 알면 정말 좋을것 같습니다! 시간되시면 한번 시간 복잡도에 대해서 알아보시면 좋을것 같아요!

알아보시면 이게 괜찮은 접근 방법인지, 너무 비효율적인건지에 대한 새로운 인사이트도 얻으실 수도 있을것 같네요! 

> 전에 말씀해주신 가위바위보 결과 연산 함수에서 switch문을 좀 더 간단히 하는 방법에 대해 고민해보았습니다.

좋아보이는데요?!👍 
코드에 대해서 계속 개선하시려는 모습 아주 좋습니다~~~

> 4. 내용이 있어서 적게 반복되는 코드들은 왠만하면 함수로 묶지 않고 코드에 그대로 내용을 치는 쪽으로 고민해보았습니다.

함수를 어떤 기준으로 나누시는지 궁금하네요! 
반복되는 코드에 대해서만 메서드로 묶으신걸까요?!

2023-11-30 16:09 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/Enum/GameMenuPrompt.swift
> +}
이름이 바뀌었군요!👍

2023-11-30 16:09 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/Enum/MuckChiPpaGameTurn.swift
> +
불필요한 줄바꿈이 있네요!

2023-11-30 16:09 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/Enum/MukChiPpaUserOption.swift
> +
위에 있는 enum 에서는 여기 줄바꿈이 없었던거 같네요!

2023-11-30 16:09 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/Enum/MukChiPpaUserOption.swift
> +
여기 의도된 줄바꿈일까요??

2023-11-30 16:09 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/Enum/RockScissorPaperUserOption.swift
> +    case paper = "3"
저번 pr 에서 말씀드린 내용이긴한데
Case 랑 rawValue 가 매칭 안되는 느낌이 조금 있지 않나요??🙃( 위에도 마찬가지!)

2023-11-30 16:09 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/GameIOmanager.swift
> +struct GameIOmanager {
Manager 이 소뮨자로 시작하네요!?

2023-11-30 16:09 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/GameIOmanager.swift
> +    func handleUserInput(computerPick: RockScissorPaperUserOption, userChoice: RockScissorPaperUserOption) {
computer 는 pick, user 는 choice 로 네이밍을 정하신 이유가 있나요??

2023-11-30 16:09 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/GameIOmanager.swift
> +            let result: GameMenuPrompt = rockSicssorPaperGameManager().determineGameResult(computerPick: computerPick, userChoice: userChoice)
메서드에 오타가 있어보이네요!

2023-11-30 16:09 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/GameIOmanager.swift
> +                let iswon = result == .win
didWin 도 가능할것 같네요.!
그리고 w는 대문자 처리가 필요해보입니다!
그리고 타입 명시를 해주면 더 좋을것 같아요😉

2023-11-30 16:09 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/GameIOmanager.swift
> +    static func showGameMenu(for situation: GameMenuPrompt) {
밑에 있는 메서드랑 이 메서드는 왜 스태틱 으로 하셨나요???
다른 메서들과 다르게 스태틱으로 설정하신 이유가 궁금해요!

2023-11-30 16:09 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let result =  GameIOmanager()
중간에 불필요한 space 가 있어보입니당

근데 변수명을 result 로 지어쥬신 이유가 궁금합니다! 타입은 매니저로 되어있어서 약간 어색해보이네요!

2023-11-30 16:09 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/main.swift
> +    guard let randomComputerPick = RockScissorPaperUserOption.allCases.filter({ $0 != .exit }).randomElement() else { continue }
. 이 굉장히 많네요🫢
적절히 쥴바꿈 처리 해쥬는건 어떨까요??

2023-11-30 16:09 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/mukChiPpaGameManager.swift
> +
불필요한 줄바꿉 있어보여요!

2023-11-30 16:09 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/mukChiPpaGameManager.swift
> +struct mukChiPpaGameManager {
타입명이 소문자네요!

2023-11-30 16:09 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/mukChiPpaGameManager.swift
> +        while true {
오.. 요것만 봤을때는 
언제까지 도는 반복문인지 한눈에 안보인다는 생각이 드네요 개인적으로!

2023-11-30 16:09 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/mukChiPpaGameManager.swift
> +            guard let randomComputerPick = MukChiPpaUserOption.allCases.filter({ $0 != .exit }).randomElement()
이정도로 길면 그냥 메서드로 빼는건 어떨까요??

2023-11-30 16:09 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/mukChiPpaGameManager.swift
> +            }
위 아래는 가드문 사용하셨는데 
여긴 if로 처리하신 이유가 궁금합니다!

2023-11-30 16:09 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/rockSicssorPaperManager.swift
> +struct rockSicssorPaperGameManager {
워에서도 말씀드렸는데 타입명은 대문자가 되어야 합니다!
그리고 가위에 오타가 보이네요ㅎㅎ

2023-11-30 16:09 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/rockSicssorPaperManager.swift
> +//        }
오 어떤 주석일까요?!

2023-11-30 16:09 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/rockSicssorPaperManager.swift
> +    func determineGameResult(computerPick: RockScissorPaperUserOption, userChoice: RockScissorPaperUserOption) -> GameMenuPrompt {
여기도 콤퓨타 네이밍이랑 유저 네이밍이 좀 다르네요?!

2023-11-30 16:09 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/rockSicssorPaperManager.swift
> +            return.draw
오.. 빌드가 안됐을것 같은데😬 이거 컴파일 에러 없었나요??

2023-11-30 16:09 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/Enum/MuckChiPpaGameTurn.swift
> +    mutating func toggle() {
오! 이 메서드 탄생 스토리가 궁금합니다🙋‍♂️

2023-12-01 01:26 UTC, happykwon commented on RockPaperScissors/RockPaperScissors/Enum/MuckChiPpaGameTurn.swift
> +
133141f6c304ac2d58d996cb89d3be847a8b8304 줄바꿈 및 타입명 대문자로 수정  완료했습니다     😀

2023-12-01 01:27 UTC, happykwon commented on RockPaperScissors/RockPaperScissors/Enum/MukChiPpaUserOption.swift
> +
의도된 줄바꿈은 아니였습니다. 습관적으로 enter를 치는 습관이 있는데.. 컨벤션에 맞춰 의식적으로 살피는 습관을 갖겠습니다 😅

2023-12-01 01:53 UTC, happykwon commented on RockPaperScissors/RockPaperScissors/Enum/RockScissorPaperUserOption.swift
> +    case paper = "3"
ca6e80ca0eb51aaa39b1f18ef479be9b52e9e6de

어색한 것 같아,  좀 더 통일감을 줄 수 있는 Int로 타입 변경 후 그에따른 오류 수정했습니다 😄

2023-12-01 01:59 UTC, happykwon commented on RockPaperScissors/RockPaperScissors/rockSicssorPaperManager.swift
> +//        }
```
        switch (computerPick, userChoice) {
        case (let computerPick, let userChoice) where computerPick == userChoice:
            return.draw
        case (.scissor, .rock), (.rock, .paper), (.paper, .scissor):
            return .win
        default:
            return .lose
        }

```
에서 if문과 switch문 둘중에 무엇이 나을까 생각해봤습니다. 
switch문을 쓴 이유는 if문의 경우 줄바꿈이 많아져 코드가 길어지고 가독성이 떨어진다고 생각해 switch문을 채택했습니다. 
알리딘은 어떻게 생각하시나요 ?🤔

2023-12-01 02:03 UTC, happykwon commented on RockPaperScissors/RockPaperScissors/rockSicssorPaperManager.swift
> +    func determineGameResult(computerPick: RockScissorPaperUserOption, userChoice: RockScissorPaperUserOption) -> GameMenuPrompt {
컴퓨터가 동작하는 것은 Pick으로 , 유저가 동작하는 것은 Choice로 통일했습니다. 
코드를 보는 사람이 헷갈리지 하나로 통일하는 것이 더 좋은 방법을까요 ??

2023-12-01 02:04 UTC, happykwon commented on RockPaperScissors/RockPaperScissors/rockSicssorPaperManager.swift
> +            return.draw
네 다행히도 에러는 없었습니다 !! 🥳

2023-12-01 02:39 UTC, happykwon commented on RockPaperScissors/RockPaperScissors/Enum/MuckChiPpaGameTurn.swift
> +    mutating func toggle() {
Step2 프로젝트에서는 결과에따라 턴이 바뀌는 코드가 필요했습니다. 
MukChiPpaGameManager파일에서 묵찌빠로직을 코딩하고 있는중에 
turn이 바뀌는 것을 어떻게 처리할지 고민했고, 처음에는 하드코딩 스타일로 하려고 했습니다.

```
var computerTurn: String = "[컴퓨터 턴] 묵(1), 찌(2), 빠(3)! <종료 : 0> :"
var userTurn: String = "[사용자 턴] 묵(1), 찌(2), 빠(3)! <종료 : 0> :"
```
이런식으로.... 😅

좀 더 생각해보니 `toggle()`을 사용해보면 어떨까 싶었고, 코드내에서 불러오기 편하고 가독성이 좋은 
`enum`타입으로 설계를하고 `swtich`문으로 경우에따라 `toggle()`이되는 코드로 작성했습니다. 


Step2 조건 
---

>Step 1의 게임 중 가위, 바위, 보 후에 결과에 따라 게임을 이어갑니다.
>가위, 바위, 보를 비긴 경우 : 다시 가위, 바위, 보 게임 진행
>가위, 바위, 보 게임에서 승패가 갈린 경우 : 묵찌빠로 이어서 게임 진행

---
>실행 시 출력
>[*** 턴] 묵(1), 찌(2), 빠(3)! <종료 : 0> :
>[*** 턴] 위치에는 현재 누구의 턴인지 표시합니다.
>가위, 바위, 보 게임 혹은 지난 턴에서 이긴 사람이 턴을 쥡니다.
>잘못된 입력을 한 경우 컴퓨터에게 턴을 넘깁니다.
>사용자에게 0, 1, 2, 3 중 한 가지를 입력받아 결과를 출력합니다.
>사용자의 패와 컴퓨터의 패가 동일한 경우 : 턴을 쥐고 있는 쪽이 승리합니다.
>“***의 승리!” 출력 후 게임 종료
>사용자의 패와 컴퓨터의 패가 다른 경우 : 이긴 쪽이 턴을 쥡니다.
>“***의 턴입니다” 출력 후 묵, 찌, 빠 계속 실행
>0을 입력받은 경우 : 게임 종료

2023-12-01 04:26 UTC, happykwon commented
## 질문에 대한 답변입니다 .

1. 파일 나누는 기준은 정말 정하기 나름인데요..!
지금 나누신 기준이 어떤건지 궁금하네요!
타입별로 파일을 나눈 것으로 보이는데 맞을까요???
> 네 맞습니다 ! 최대한 코드를 쪼개보려했지만, 이미 구축되어있는 것들을 모두 엎고 하는게 시간상 오래걸릴 것 같아 타입별로만 나눴습니다.
여기서 얻게된 교훈 처음 코드를 작성할 때 러프하게 밑그림? 작업을 먼저 하고 들어가는게 단일책임 원칙 등 객체지향 프로그래밍을 하기 위해 유리할 것 같았습니다, 다음 프로젝트를 진행한다면 처음에 먼저 그림을 그려볼 것 같습니다 이번 프로젝트로 예를 들어보면

```
struct RPS  {
    //가위바위보 로직 구현
}

struct MuckCciPpa{
    //묵찌빠 로직구현
}


struct GameIOmaneger {
    //유저 인풋값 , 컴퓨터 인풋값을 받아 처리하는 로직 구현
    //RPS , MuckCciPpa 에서 값을 받아와 처리하는 로직을 구현함
}
```
이런식으로 대략적인 밑그림 작업을 하고 시작을 할 것 같습니다. 
조금 더 알아보니 이런것들은 아키텍처의 영역인 것 같아 추가로 공부를 더 해볼 예정입니다 !! 
혹시 괜찮은 책?이나 강의가 있다면 추천 부탁드립니다 😃

---

2. while반복문 두번이 들어가도 괜찮을까요?
>말씀하신대로 이중 반복문은 복잡성 이 증가되고 성능 문제 가 있는것이 맞습니다~
하지만! 왜 성능 문제가 발생할까요?
지금 적어주신 이유가
루프의 반복 횟수가 늘어날수록 성능에 영향을 미칠 수 있음 인데
루프의 반복 횟수가 늘어날수록 왜 성능이 나빠질까요??
단순히 나쁘다, 성능이 좀 안좋아진다 라는 것은 개발자마다 기준이 다르면 안되겠지요!
저희는 이렇게 특정 알고리즘이나 코드의 성능에 대한 이야기를 나눌때 시간/복잡도에 대한 이야기를 나누는데
반복문 하나랑 중첩 반복문이 왜 성능적 차이가 있는지 이론적으로 알면 정말 좋을것 같습니다! 시간되시면 한번 시간 복잡도에 대해서 알아보시면 좋>을것 같아요!

시간복잡도라는 개념을 처음 접하게 되어 얕게나마 공부해봤고,
다음 프로젝트에서는 시간복잡도의 개념을 적용해서 코드에 녹여보고 싶다는 생각을 했습니다 :)
### 공부한 내용 정리 
시간복잡도의 개념은 얼마나 빠르게 실행이 되고 끝마치는가에 대한 것!
간단히 말해서, 어떤 작업이나 알고리즘이 얼마나 많은 시간이 걸리는지를 표현하고,
입력이 커질수록 작업에 필요한 시간이 어떻게 변하는지를 나타내며, 이를 통해 알고리즘의 효율성을 평가 할 수 있는 개념
예를 들어, 입력 크기가 10인 경우보다 100인 경우에 같은 작업이 얼마나 더 오래 걸리는지를 나타내는 것이며
이를 통해 알고리즘의 성능을 예측하고, 효율적인 알고리즘을 선택할 수 있게 도와줍니다.
이를 통해 개발자들은 어떤 코드에 대해 정량적인 시간복잡도를 파악 할 수 있고 개선과 개선을 위한 커뮤니케이션을 진행 가능함

### 반복문에서의 시간복잡도
1. 중첩된 반복문은 루프의 수행 횟수를 제곱 또는 세제곱으로 증가시켜 시간 복잡도를 높임
2. 외부 루프의 반복마다 내부 루프가 실행되므로 반복 횟수가 증가할수록 전체 반복 횟수는 기하급수적으로 늘어남
3. 많은 반복 횟수는 하드웨어 리소스를 많이 사용하므로, 효율적인 알고리즘 선택이 중요하고 이는 실행 속도와 시스템 리소스 효율성에 영향을 줌.
4. 중첩된 반복문은 일반적으로 O(n^2), O(n^3)과 같은 제곱, 세제곱의 시간 복잡도를 가질 수 있음.

처음 봤을때는 잘 이해가 안되서 코드로 직접 짜봤습니다. 
중첩된 while문은 100배넘게 많은 시간이 걸렸다는걸 감안하면 
시간 복잡도의 개념이 정말 중요하구나라는 것을 직접적으로 눈으로 볼 수 있었습니다 ! 
[시간복잡도](https://github.com/happykwon/-while_-Time-Complexity-) 
![스크린샷 2023-12-01 오후 1 13 51](https://github.com/tasty-code/ios-rock-scissor-paper/assets/149054154/e056332a-9089-4838-bddd-2a522e8ad1a3)

2023-12-01 04:43 UTC, happykwon commented on RockPaperScissors/RockPaperScissors/GameIOmanager.swift
> +    func handleUserInput(computerPick: RockScissorPaperUserOption, userChoice: RockScissorPaperUserOption) {
네 있습니다. 
1. 유저와 컴퓨터의 값이란 것을 확실하게 구분짓기 위해 
2. 컴퓨터는 내부적으로 숫자를 선택하고 유저값은 외부적으로 선택되기 때문에 

이렇게 기준을 정했습니다 !

2023-12-01 04:49 UTC, happykwon commented on RockPaperScissors/RockPaperScissors/GameIOmanager.swift
> +struct GameIOmanager {
168b0d6e2315a1649ccd9b5f27c1026e002febbe
수정완료했습니다 !

2023-12-01 04:49 UTC, happykwon commented on RockPaperScissors/RockPaperScissors/GameIOmanager.swift
> +            let result: GameMenuPrompt = rockSicssorPaperGameManager().determineGameResult(computerPick: computerPick, userChoice: userChoice)
168b0d6e2315a1649ccd9b5f27c1026e002febbe
수정완료했습니다 !

2023-12-01 04:52 UTC, happykwon commented on RockPaperScissors/RockPaperScissors/GameIOmanager.swift
> +                let iswon = result == .win
1a293c1c93871c5b8cafe451e372c07c4ff17265
수정 완료했습니다 😁

2023-12-01 05:14 UTC, happykwon commented on RockPaperScissors/RockPaperScissors/GameIOmanager.swift
> +    static func showGameMenu(for situation: GameMenuPrompt) {
showGameMenu 게임의 description을 보여주기 위한 메소드로서, 게임 description은 모두 
enum 타입인 GameMenuPrompt에 작성했고, 때문에 타입메서드로 바꿔주는 키워드 `static`을 사용했습니다

2023-12-01 05:21 UTC, happykwon commented on RockPaperScissors/RockPaperScissors/main.swift
> +    let result =  GameIOmanager()
1a293c1c93871c5b8cafe451e372c07c4ff17265
최종적인 결과를 담는다는 의미에서 result로 사용했었습니다.
상수명 변경완료했습니다.

2023-12-01 05:25 UTC, happykwon commented on RockPaperScissors/RockPaperScissors/main.swift
> +    guard let randomComputerPick = RockScissorPaperUserOption.allCases.filter({ $0 != .exit }).randomElement() else { continue }
6e151666de471172b795f39f45516b3ad1bbfafd

줄바꿈 처리 완료했습니다 😀

2023-12-01 05:28 UTC, happykwon commented on RockPaperScissors/RockPaperScissors/mukChiPpaGameManager.swift
> +
3fb6b4ef4b9465f0f4a6458c82bd578b0742c65d

수정완료했습니다 !

2023-12-01 06:47 UTC, happykwon commented on RockPaperScissors/RockPaperScissors/mukChiPpaGameManager.swift
> +            }
다시 한번 더 생각해본 결과. 분기처리의 경우가 1가지 밖에 없어 guard문이 깔끔할 것 같아 guard문으로 코드 변경했습니다.
e42a97846a42c4e21f62e9ef8ac3bc6581f11d9e

2023-12-01 08:28 UTC, happykwon commented on RockPaperScissors/RockPaperScissors/mukChiPpaGameManager.swift
> +        while true {
b353feb92568bf03f9ccd62574982c4d05776599
동작 시기를 추가했습니다. !

2023-12-01 12:15 UTC, kimdj1102 commented on RockPaperScissors/RockPaperScissors/mukChiPpaGameManager.swift
> +struct mukChiPpaGameManager {
수정완료 했습니다!

2023-12-01 12:16 UTC, kimdj1102 commented on RockPaperScissors/RockPaperScissors/rockSicssorPaperManager.swift
> +struct rockSicssorPaperGameManager {
수정완료 했습니다😅

2023-12-01 12:29 UTC, kimdj1102 commented on RockPaperScissors/RockPaperScissors/mukChiPpaGameManager.swift
> +            guard let randomComputerPick = MukChiPpaUserOption.allCases.filter({ $0 != .exit }).randomElement()
```
func getRandomComputerPick() -> MukChiPpaUserOption? {
    return MukChiPpaUserOption.allCases.filter({ $0 != .exit}).randomElement()
}
```

getRandomComputerPick() 메서드를 사용해서 MukChiPpaUserOption을 Optional타입으로 리턴하게 한 후, 

```
 guard let randomComputerPick = getRandomComputerPick() else {
    continue
}
```

guard let으로 Optional Wrapping 처리를 해주는 방법으로 고민해보았습니다.
괜찮은 방법일까요?

2023-12-01 12:31 UTC, kimdj1102 commented on RockPaperScissors/RockPaperScissors/rockSicssorPaperManager.swift
> +            return.draw
혹시 어떤 부분에서 컴파일 에러가 의심됬는지 여쭤봐도 될까요? 해당 방법은
```
case (let x, let y) where x = y:
    return .draw
```
이렇게 case에 조건을 넣어 처리하는 방법이 있어서 사용해 보았습니다!

2023-12-01 15:38 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/Enum/RockScissorPaperUserOption.swift
> +    case paper = "3"
아하 제가 이야기 드리고싶었던것은 enum에 computed property 추가하는 방향이었어요! :)

2023-12-01 15:39 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/rockSicssorPaperManager.swift
> +            return.draw
엇 18번째줄에 
`return.draw` 이렇게 되어있어서요~! 


<img width="708" alt="Screenshot 2023-12-02 at 12 39 28 AM" src="https://github.com/tasty-code/ios-rock-scissor-paper/assets/33091784/72609a08-41f9-46ba-9462-e3e6a25bfd57">

2023-12-01 15:43 UTC, junbangg commented on RockPaperScissors/RockPaperScissors/rockSicssorPaperManager.swift
> +    func determineGameResult(computerPick: RockScissorPaperUserOption, userChoice: RockScissorPaperUserOption) -> GameMenuPrompt {
흠 넵 지금 보면 두 파라미터의 타입은 동일한데 
computer는 pick, user 는 choice 인게 조금 어색한것 같아요,,!
의미적으로는 차이가 없어보이는데 굳이 다르게 할 필요가 있나 싶네요 개인적으로는

두분이서 논의 후에 일부러 어떤 의미를 부여하신거라던지, 구분을 두신 이유가 있다면 넘어가셔도 좋습니다~

2023-12-03 12:44 UTC, kimdj1102 commented on RockPaperScissors/RockPaperScissors/rockSicssorPaperManager.swift
> +            return.draw
엇...띄어쓰기를 안했네요 주의하겠습니다...😅

2023-12-03 12:52 UTC, kimdj1102 commented on RockPaperScissors/RockPaperScissors/Enum/RockScissorPaperUserOption.swift
> +    case paper = "3"
```
enum Step1UserInputInfo: String, CustomStringConvertible {
    case scissor
    case rock
    case paper
    case exit
    
    var description: String {
        switch self {
        case .scissor:
            return "1"
        case .rock:
            return "2"
        case .paper:
            return "3"
        case .exit:
            return "0"
        }
    }
}
```

computed property 추가한 후, `CustomStringConvertible`프로토콜 사용해서 더 간단히 호출할 수 있도록 해보겠습니다!

2024-01-02 01:32 UTC, Tacocat-tastycode commented
프로젝트 진행 기간 종료로 PR Close

2024-01-02 01:32 UTC, closed without merging