묵찌빠 프로그램 [Step 2] Paul, Hong
tasty-code/ios-rock-scissor-paper pull request #65
Opened 2023-11-30 07:54 UTC by earths-voluble

안녕하세요 코든! 묵찌빠 프로젝트 Step2의 PR입니다.

객체지향적인 구조로 구현해보고자 해서 많은 리팩터를 거쳤습니다.

그 과정에서 시행착오가 있었고 무엇보다 일정이 많이 늦어진 점 거듭 죄송합니다.

늦어지고 git 실수를 연발해도 친절하게 도와주신 코든에게 먼저 감사 인사를 올립니다!

다음은 Step2의 PR을 하는 지금 시점에서 프로젝트를 진행하며 느낀 여러 가지 점들에 대해 말씀드리고자 합니다.

## 배운 것들

- 재귀함수를 쓸 때는 탈출조건에 유의할 것
- 명세를 확실히 체크할 것과 `git` 사용에 유의할 것
- 함수의 인자는 상수이다.
- `enum`에 `caseIterable` 프로토콜을 적용하면 열거형을 배열처럼 다룰 수 있다.
- 등등등…

## 아쉬운 점들

- `refree`의 메서드 `runRockScissorsPaper`는 인자로 `Player`의 변수인 `rockScissorsPaperHand`를 받는데, `runMukJiPa`는 로직상 인자로 `mukJiPaHand`가 아닌 `Player` 자체를 받아야 하는 한계가 있었고 아직까지 해결하지 못했습니다.
- 함수의 인수는 상수라 함수의 동작으로 인수의 프로퍼티를 변경하는 것은 불가능합니다. 때문에 `runMukJiPa`를 구현할 때, 인자로 받아온 `user`와 `computer`를 내부에서 복사한 shadow객체들을 생성했습니다만, 코드가 난잡해짐과 동시에 성능 면에서도 손실이 있지 않을까 하는 의문이 있습니다.
- 종료 구현을 위해 enum마다 `.exit`가 있는데 이것도 분리하고 싶었지만 아직 구현하지 못했습니다.
- startGame() 함수가 너무 방대해진 듯 해서 나눌 필요성을 느꼈습니다.
- 전체적으로 객체지향이라는 컨셉을 고수하려다 보니 잃은 것도 많고, 제대로 구현되지 못한 것도 많아서 아쉬운 마음이 큽니다.

## 궁금한 점들

- 게임의 시작 부분을 `while`구문으로 전역적으로 선언했는데, 구조체나 클래스 변수를 만들어서 내부에 있는 함수를 실행시키는 쪽이 좀 더 안전한 코드일까요?
- 객체지향적인 코드를 지향하며 쓴 프로그램이라 보았을 때 부족한 점, 보완할 점들은 어떤 것이 있을까요?
- 더 확장성 있는 코드를 위한 추천사항이 있으실까요?

2023-11-30 19:45 UTC, ictechgy requested changes
안녕하세요 @earths-voluble , @ujhong7 ! STEP2도 정말 고생 많으셨습니다.    
`배운 것들`을 보니 정말 많은 것을 공부해주신 것 같아요~ 👍 재귀함수도 알아보고 쓰신점! 좋습니다.

### 적어주신 아쉬운 점들에 대해 이야기 하기 전에 한번 여쭤보고 싶은 것이 있는데요!   
- 두분은 객체지향 프로그래밍이란 무엇이라 생각하시나요?
- shadow 객체를 만든 것 -> 어떤 점에서 성능상 손실이 있다고 생각하시나요?
- exit은 꼭 가위바위보 / 묵찌빠의 열거형에 같이 포함시켜야 할까요?

위와 같은 부분들에 대해 먼저 답변해주시면, 제 관점을 전달드리는게 훨씬 수월할 것 같아요!

### 궁금한 점들에 대하여
- 객체지향의 관점으로 본다면 게임의 시작도 특정 객체가 해줘야 하는 역할이지 않을까 싶은데요! 이 부분에 대해서는 '명령형 프로그래밍과 객체지향형 프로그래밍의 차이'에 대해 알아봐주시면 좋을 것 같아요!
- 부족한 점, 보완할 점 -> 이 부분은 위에 제가 적어드린 질문에 먼저 답해주시면 더 자세히 말씀드릴 수 있을 것 같아요! 
- 확장성 있는 코드를 위한 추천사항 -> 이 부분은 SOLID 원칙에 대해 한번 공부해보시면 좋을 것 같아요! 그리고 프로토콜에 대해 이어서 공부해보시면 좋을 것 같은데요! 확장성 있는 코드는 무엇인지 두분의 의견도 한번 들어보고 싶네요!

아무쪼록 묵찌빠 프로젝트 진행하시느라 고생 많으셨습니다!   
제가 질문드린 사항에 답변해주시면 저도 제 의견을 정리해서 말씀드릴게요~!   
어려운 부분은 DM 꼭 주세요!

2023-11-30 19:45 UTC, ictechgy commented on RockPaperScissors/.gitignore
> +.DS_Store
gitignore가 바깥쪽에도 하나, 이쪽에도 하나가 있네요. 꼭 두 곳에 다 있을 필요가 있을까요??

2023-11-30 19:45 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +//
`import Foundation`은 지워주셨네요!   
어떠한 이유로 지워두신 것인지 설명 부탁드릴게요!

2023-11-30 19:45 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +var power: Bool = true
전역으로 상수나 변수를 선언해두는 것은 권장되지 않는 방법이에요.    
`namespace pollution` 또는 `전역변수 사용 자제`에 대해 검색해보시면 좋을 것 같습니다!

2023-11-30 19:45 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +var power: Bool = true
또, power라는 이름은 어떤 의미의 변수인 것인지 감이 잘 오지 않아요. 더 좋은 이름은 없을까요?

2023-11-30 19:45 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +func startGame() {
`startGame`이라는 이름은 잘 지어주신 것 같아요! 👍

2023-11-30 19:45 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +    print("가위(1), 바위(2), 보(3)! <종료 : 0> : ", terminator: "")
요구사항을 맞추기 위해 terminator 인자를 쓰셨군요!! 좋습니다!

2023-11-30 19:45 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +    var computer = Player()
새 변수의 이름도 정말 잘 지어주신 것 같아요~    
다만 user와 compute 인스턴스는 var로 선언해주셨는데 mutating function 때문이겠죠?   

let과 var의 차이는 무엇인가요??

2023-11-30 19:45 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +func shutDown() {
shutDown이라는 이름 잘 와닿네요 😆

2023-11-30 19:45 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +enum Result: String {
`Result`라는 이름은 조금 더 구체적으로 가져가면 좋을 것 같아요.   
`MukJiPaResult`와 같은 네이밍으로요!   

`Result`라는 타입은 이미 존재하는 타입이기도 한데요. 시간 되실 때 살펴봐주세요! (정말 중요한 녀석중에 하나랍니다)

2023-11-30 19:45 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +    case pa = "3"
가위바위보와 묵찌빠가 거의 비슷한 열거형들처럼 보이는데요. 꼭 두개로 분리되어있어야 할까요?

2023-11-30 19:45 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +    mutating func choiceRockScissorsPaperHand() {
mutating 함수를 선택하신 이유는 무엇인가요??

2023-11-30 19:45 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +           let select = RockScissorsPaper(rawValue: input) {
이 함수는 컴퓨터가 호출할수도, 사용자가 호출할 수도 있는 함수인데요. (잘못 호출할 수도 있음)    
사용자 입력은 객체 바깥에서 받는건 어떨까요?

2023-11-30 19:45 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +            let playerHand = select
이 변수는 꼭 있어야 할까요??

2023-11-30 19:45 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +            choiceRockScissorsPaperHand()
재귀함수를 쓰셨군요~~!!! 👏👏👏🔥    
아주 좋습니다!!!   

반복문이 아닌 재귀함수를 쓰신 이유가 있을까요?   
그리고 재귀함수의 장단점에는 어떤게 있을까요? 두분 다 말씀해주세요!

2023-11-30 19:45 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +            return
요 return문은 꼭 있어야 할까요? 👀

2023-11-30 19:45 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +    mutating func randomRockScissorsPaperHand() {
함수의 네이밍은 조금 더 고민해봐주시면 좋을 것 같습니다!   

`selectRockPaperScissorsRandomly` 이런 네이밍은 어떨까요?

2023-11-30 19:45 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +    case pa = "3"
묵찌빠라는 열거형에 종료라는 case가 있는 것은 조금 어색한 것 같습니다!   
종료 케이스는 따로 처리해주시는게 좋을 것 같아요

2023-11-30 19:45 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +        let exceptExitCase = RockScissorsPaper.allCases.filter { $0.rawValue != "0" }
종료를 제외한 가위, 바위, 보를 추출하기 위해 filter를 쓰신 것으로 보이는데요   
해당 타입에 대한 네이밍을 'Exit을 제외한 케이스이다' 라고 하기보단 직관적으로 'RockScissorsPaperCase`처럼 지어주시는게 좋을 것 같아요.    

이 코멘트는 위쪽 가위바위보 / 묵찌빠 enum에 작성해드린 코멘트와 함께 봐주시면 좋을 것 같습니다.

2023-11-30 19:45 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +        self.rockScissorsPaperHand = exceptExitCase.randomElement()
randomElement를 쓰신 것은 정말 좋습니다!

2023-11-30 19:45 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +        }
이 함수도 위쪽 choiceRockScissorsPaperHand 함수에 달아드린 코멘트와 동일한 말씀을 드릴 수 있을 것 같네요!

2023-11-30 19:45 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +        self.mukJiPaHand = exceptExitCase.randomElement()
randomRockScissorsPaperHand 함수에 달아드린 코멘트를 같이 참고해주세요!

2023-11-30 19:45 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +                              computerHand: RockScissorsPaper?) -> Result {
가위바위보를 실행한다기보다 사용자의 패와 컴퓨터의 패를 비교하여 결과를 만들어준다는 관점에서   
judge-같은 prefix등을 고민해보시면 어떨까요?

2023-11-30 19:45 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +            return Result.lose
모든 상황에 대해 열거형으로 비교하고 열거형을 돌려주도록 구현하셨군요!   

열거형을 썼을 때의 장점은 무엇이 있을까요??

2023-11-30 19:45 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +        }
notice라는 함수명 잘 지어주신 것 같습니다. 결과들을 switch 구문으로 구분해주신 것들도요!       

아래에 있는 error들은 어떤 의미인걸까요??

2023-11-30 19:45 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +        return
여기도 재귀함수를 쓰셨군요! 👏   
다만 아래의 return은 꼭 필요한 걸까요?

2023-11-30 19:45 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +        shutDown()
종료 로직이 명확해져서 좋네요!

2023-11-30 19:45 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +    func runMukJiPa(rockScissorsPaperResult: Result, user: Player, computer: Player) {
묵찌빠를 진행한다는 네이밍도, 재귀함수를 써주신 것도 잘 해주셨습니다!! 🙌

2023-11-30 19:45 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +            exit(0)
이 부분은 요구사항에는 해당하지 않는 것 같은데 이렇게 작성해주신 이유가 있을까요??

2023-11-30 19:45 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +        func judgeMukJiPa(_ : Result) {
judge라는 prefix를 써주신 것 좋습니다.
다만 parameter부분은 쓰지 않는 것 같은데 만들어두신 이유가 있을까요?

2023-11-30 19:45 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +            shutDown()
여기가 동작하는 경우는 어떤 경우가 있을까요?

2023-11-30 19:45 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +                       computer: shadowComputer)
누구에게 턴이있는지, 그 결과를 같이 넘기면서 재귀를 써주신 점 좋네요~~ 😁🙌

2023-12-01 10:05 UTC, earths-voluble commented on RockPaperScissors/.gitignore
> +.DS_Store
실수로 추가된 것 같습니다 🥲 삭제해보도록 하겠습니다

2023-12-01 10:09 UTC, earths-voluble commented on RockPaperScissors/RockPaperScissors/main.swift
> +    var computer = Player()
refree같은 경우는, 보유하고 있는 프로퍼티가 없이 메서드만 실행하는 구조체라 변수로 선언할 필요가 없다고 생각했고
user와 computer는 말씀하신 대로 mutating function을 사용해 스스로 프로퍼티를 변경해야 하기 때문에 변수로 선언했습니다!

2023-12-01 10:10 UTC, earths-voluble commented on RockPaperScissors/RockPaperScissors/main.swift
> +enum Result: String {
`GameResult`로 변경하고 `exit`를 제외했습니다. 감사합니다!

2023-12-01 10:11 UTC, ujhong7 commented on RockPaperScissors/RockPaperScissors/main.swift
> +//
기본 Swift 표준 라이브러리만으로 충분한 경우 Foundation을 직접적으로 사용하지 않아도 된다고 해서 지워봤습니다!

2023-12-01 10:12 UTC, earths-voluble commented on RockPaperScissors/RockPaperScissors/main.swift
> +    case pa = "3"
가위바위보와 묵찌빠의 순서가 달라 일단 두 열거형으로 정리해놨었는데, 말씀하신 대로 하나로 통일하고 싶어서 입력받을 때 가위 -> 묵, 바위 -> 찌로 치환하는 방식으로 통일했습니다! 그리고 `exit`도 제거했습니다~

2023-12-01 10:13 UTC, earths-voluble commented on RockPaperScissors/RockPaperScissors/main.swift
> +    mutating func choiceRockScissorsPaperHand() {
`Player`구조체로 생성된 인스턴스가 스스로 `hand`프로퍼티를 바꿀 수 있도록 하기 위해 `mutating function`을 사용했습니다!

2023-12-01 10:15 UTC, earths-voluble commented on RockPaperScissors/RockPaperScissors/main.swift
> +           let select = RockScissorsPaper(rawValue: input) {
이 부분도 고민됐는데 여기까진 아직 손보지 못하고 일단 랜덤으로 패를 내는 함수만 통일했습니다! 좀 더 생각해 보겠습니다🤔

2023-12-01 10:15 UTC, earths-voluble commented on RockPaperScissors/RockPaperScissors/main.swift
> +            let playerHand = select
삭제했습니다!

2023-12-01 10:18 UTC, earths-voluble commented on RockPaperScissors/RockPaperScissors/main.swift
> +        let exceptExitCase = RockScissorsPaper.allCases.filter { $0.rawValue != "0" }
`exit`가 삭제되어서 `filter`함수는 사용하지 않게 되었습니다. 감사합니다!

2023-12-01 10:18 UTC, earths-voluble commented on RockPaperScissors/RockPaperScissors/main.swift
> +    mutating func randomRockScissorsPaperHand() {
비슷한 컨벤션으로 수정해보았습니다!

2023-12-01 10:20 UTC, ujhong7 commented on RockPaperScissors/RockPaperScissors/main.swift
> +var power: Bool = true
power 를 onGame 으로 변경해서 게임의 on/off 를 의미하도록 만들어봤습니다! 그리고 전역으로 선언된 변수들은 전체적인 코드 구조를 더 다듬어서 클래스 혹은 구조체 내부에 선언할수있도록 변경하겠습니다!

2023-12-01 10:40 UTC, ujhong7 commented on RockPaperScissors/RockPaperScissors/main.swift
> +            return Result.lose
Switch문과 함께 사용해 열거형의 각 케이스에 대한 처리를 명시적으로 할 수 있습니다.

2023-12-01 10:42 UTC, ujhong7 commented on RockPaperScissors/RockPaperScissors/main.swift
> +        return
삭제했습니다!

2023-12-01 11:11 UTC, ujhong7 commented on RockPaperScissors/RockPaperScissors/main.swift
> +            choiceRockScissorsPaperHand()
재귀 함수를 사용하면 문제 해결의 자연스러운 모델링, 코드의 간결성, 알고리즘의 효율성의 장점을 갖지만 스택 프레임이 쌓여 메모리 사용량이 늘어나는 스택 오버플로우 현상을 단점을 갖습니다.

2023-12-01 11:12 UTC, ujhong7 commented on RockPaperScissors/RockPaperScissors/main.swift
> +            return
삭제했습니다!

2023-12-02 16:03 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +var power: Bool = true
onGame도 좋지만 타입이 Bool이니 '~해야하는가' 라는 뜻으로 다가오도록 다음과 같은 이름은 어떨까요?    
- `needGameContinue`
- `isInPlayingGame` 등

2023-12-02 16:06 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +           let select = RockScissorsPaper(rawValue: input) {
아하 그렇군요~ 넵!

2023-12-02 16:16 UTC, ictechgy commented on RockPaperScissors/RockPaperScissors/main.swift
> +            choiceRockScissorsPaperHand()
알고리즘의 효율성은 구체적으로 무얼 말씀하시는걸까요??

2023-12-02 16:59 UTC, ictechgy commented
@earths-voluble , @ujhong7  프로젝트 진행하시느라 고생하셨습니다~   
간단하게 재귀함수에 대한 피드백만 드려볼게요!

현재 재귀함수가 외부 프로퍼티인 `OnGame`에 의존하여 종료하는 형태인데요! 인자로 받아서 함수가 종료될 수 있도록 해보면 좋을 것 같습니다. (이를면 다음과 같이요)
```swift
func runMukJiPa(previousGameResult: GameResult, currentGameResult: GameResult) {
    if currentGameResult == .draw {
        // previousGameResult를 이용해 승자 출력
        return
    }

    let userHand = user.showHand()
    let computerHand = computer.showHand()
    let newGameResult = judgeGameResult(userHand: userHand, computerHand: computerHand)
    
    runMukJiPa(previousGameWinner: currentGameResult, currentGameResult: newGameResult)
}
```

묵찌빠 진행하시느라 정말 고생 많으셨고 다음 프로젝트도 화이팅 하세요!!

2023-12-02 17:19 UTC, ictechgy commented
아 PR 코멘트 중 질문하신 내용들 답변해드리겠습니다!

- 꼭 Player가 Hand 프로퍼티를 가지고 있어야 할까요? 저는 그럴 필요는 없다고 생각합니다. 사용자의 패는 사용자가 한번 내면 끝이고 해당 패가 뭐였는지는 심판인 Refree가 알고있어도 충분하다고 봐요
- startGame이 방대해진 것같다고 하신 부분 ➡️ 함수는 하나의 역할만 할 수 있도록 단위를 더 고민해보시면 좋을 것 같아요
  - 함수의 네이밍이 명시적으로 한 문장으로 만들어질 수 있도록요!
- 보완할 점 ➡️ Player 타입을 선언했을 때 내부 메서드는 user이든 computer이든 접근 가능한 상태에요. (교차하여 사용해버릴 수 있음)
  - 이 부분은 패를 내는 함수는 하나만 만들고 패를 어떻게 만들지는 외부에서 주입해보면 어떨까요? (의존성 주입)
- 확장성 있는 코드 ➡️ 프로토콜을 나중에 공부해보시면 좋을 것 같습니다

더불어 객체지향 프로그래밍과 명령형 프로그래밍의 차이, SOLID가 무엇인지 꼭 찾아보시길 바랄게요!

2024-01-02 01:32 UTC, Tacocat-tastycode commented
프로젝트 진행 기간 종료로 PR Close

2024-01-02 01:32 UTC, closed without merging